### ISSUE TITLE
AKS Pod update removed accidentally "dns name label" on the static Azure IP

### ISSUE THREAD

**Issue by SergeBerwert** [Azure/AKS#1376] opened 2020-01-08 13:41 UTC
I Started last night the Kubernetes update to version 1.15.7. after updating our app was not longer available on the internet because front door could not find the IP anymore. After searching I while we figured out the AKS removed the "dns name label" on the static IP that was associated with the Kubernetes Service Object. In the Activity log, we could see that it was removed by the cluster for whatever reason.

Activity log shows SP-Cluster01 removed the lable. SP-Cluster01 is the service principal the cluster runs under
![activitylog1](https://user-images.githubusercontent.com/7489837/71981991-e4acde80-3223-11ea-989d-0e0e57acb99d.jpg)

Shows that the cluster removed the dns label
![activitylog2](https://user-images.githubusercontent.com/7489837/71982000-e9719280-3223-11ea-9b2c-0e6311301fe3.jpg)

**Comment by curtdept** [comment] 2020-01-08 18:24
Confirmed, happened to me as well. So much for no outage upgrade!

**Comment by edalferes** [comment] 2020-01-09 13:55
Problem happened to me too, using regions eastus2 region

**Comment by palma21** [comment] 2020-01-09 17:21
I'm guessing you added the DNS label manually to the IP? That was not AKS it was kubernetes reconciling the state it has internally. That IP is controlled by kubernetes

To give it a DNS label you need to do it in kubernetes via `service.beta.kubernetes.io/azure-dns-label-name` on the spec.

With this, the DNS label will persist.

**Comment by curtdept** [comment] 2020-01-09 17:36
LOL so you make us create and generally manage the public IP manually, but then obliterate its state via k8s reconciliation.

That's really inconsistent design and implementation.

**Comment by SergeBerwert** [comment] 2020-01-09 17:42
Is there more documentation about that topic? a quick research indicates that there is not a single word about that feature mention in the official documentation.

**Comment by palma21** [comment] 2020-01-10 19:15
@curtdept could you clarify what you mean by forcing to create and manually manage? If you just expose a service of type LB with the label. The IP will automatically be created, and its lifecycle managed for you.

@SergeBerwert thanks, we can get that added to the AKS documentation too. 

I think you might have benefited from a bug in upstream k8s where the label was not being correctly reconciled in some k8s versions.

**Comment by SergeBerwert** [comment] 2020-01-10 19:24
@palma21 I opened already an issue in the documentation github project https://github.com/MicrosoftDocs/azure-docs/issues/45878

**Comment by alonisser** [comment] 2020-01-11 15:43
@palma21 This also happend to us, a night of outages because of this issue
1. Because our clients need preknown ip addresses we need to create it outside and aks resource group (and this is being allowed with the annotation of `service.beta.kubernetes.io/azure-load-balancer-resource-group` I also would expect in this case that aks won't try to override stuff there
2. The actual [bug report](https://github.com/kubernetes/kubernetes/issues/67813) that triggered this "fix" is from August 24, 2018! So most of us never experienced this behavior from aks. Changing this in a minor update seems a bit questionable. 
3. The "fix" merged in the [pr](https://github.com/kubernetes/kubernetes/pull/85318) seems to introduce an unexpected behavior (At least for me) 
While the bug was about "changes in the dns zone annotation not propagated to public ip" the actual change is
1. Reconciling the existing service annotation state on the existing public ip even if there was no change in the service - so very hard to track
2. Forcing a "null"   annotation (no annotation existing, not an existing annotation with a null value) as state for the public ip - I would understand "no annotation" as "no manual changes on the public IP" 
So I think this is actually a bug in the implementation of the fix . Please reopen this issue

**Comment by AdamGlass** [comment] 2020-01-12 05:20
This broke our workflow/automation.  We relied on being able to set the dns name for the ip address as we have standardized pre-created CNAME records   This worked in the past.  Now, our DNS names is cleared off.

adamg@microsoft.com

**Comment by palma21** [comment] 2020-01-13 23:46
Re-opening for discussion of the implementation of https://github.com/kubernetes/kubernetes/pull/85318 

Adding @feiskyer and @nilo19 as owners of the discussion. I think that is the behavior intended from the original proposal, but will let the folks chime in. If most folks feel the behavior should be different it might warrant a new proposal for this upstream.

**Comment by nilo19** [comment] 2020-01-14 08:07
Is this issue only in 1.15?

**Comment by edwa001** [comment] 2020-01-14 19:12
Is there any instructions on how to set it with service.beta.kubernetes.io/azure-dns-label-name? I am trying to get our environments back online.

**Comment by curtdept** [comment] 2020-01-14 20:20
It goes in the annotation section with the dns prefix you had before.

**Comment by curtdept** [comment] 2020-01-14 20:21
The IPs you have to manage that get overwritten by this are Public Static ones.

**Comment by AdamGlass** [comment] 2020-01-14 20:40
We hit this doing new test installs of aks and the bits we run inside.  Wouldn’t folks doing an upgrade of their cluster hit this and have their dns names cleared?

________________________________

**Comment by curtdept** [comment] 2020-01-14 20:44
Definelty, at least 3 of us on this thread got wiped out haha.

**Comment by edwa001** [comment] 2020-01-14 21:52
> It goes in the annotation section with the dns prefix you had before. @edwa001
> 
> Example
> 
> kind: Service
> apiVersion: v1
> metadata:
> name: gateway
> annotations:
> service.beta.kubernetes.io/azure-load-balancer-resource-group:
> service.beta.kubernetes.io/azure-dns-label-name:
> namespace: gateway
> spec:
> loadBalancerIP: <your static up, if you have one>
> type: LoadBalancer
> selector:
> app: gateway
> ports:
> - name: http
> port: 80
> targetPort: 8080

Hey @curtdept  i am unable to add it back as i had it. Its giving me a regex error and will not allow the '.' which is how i had it on my public IP Address resource

![image](https://user-images.githubusercontent.com/34496517/72385810-136bfe80-36d5-11ea-9fe6-0faebbda7d90.png)


Original Error: Code="InvalidDomainNameLabel" Message="The domain name label prod-silver.eastus.cloudapp.azure.com is invalid. It must conform to the following regular expression: ^[a-z][a-z0-9-]{1,61}[a-z0-9]$."

**Comment by curtdept** [comment] 2020-01-14 21:54
@edwa001 not the full dns name, just the first part (<whatever>-prod-silver), the rest is predetermined by the region you are in.

**Comment by feiskyer** [comment] 2020-01-15 01:05
refer https://github.com/kubernetes/kubernetes/issues/87127, would improve this and won't remove the PIP dns if there's no service annotations.

**Comment by nilo19** [comment] 2020-01-15 04:58
Thank you @palma21, @SergeBerwert. I'll fix this.

**Comment by luddskunk** [comment] 2020-01-20 13:18
Hi,

I ran into this issue in my cluster which caused a lot of environment crashing. I must join into the choir and express my dissatisfaction regarding this undocumented change. However, I am grateful to the fact that there was a swift act of fixing this as well as an active community who helps to resolve the issue at hand.

A fast workaround if you do not have time to go into your service yamls and changing this is to set an Azure Read Lock on the Public IP resource (Can be done from the Azure Portal), which will prevent the service principal to actually updating (erasing) the DNS value.

**Comment by bramvdklinkenberg** [comment] 2020-01-20 13:40
Any idea on when a new version with the fix from 87246 will be available for AKS?

**Comment by edalferes** [comment] 2020-01-20 19:50
As recommended, we now use the annotation service.beta.kubernetes.io/azure-dns-label-name

The change in CRD Voyager had an effect on the service and consequently on the public.

Then we made an attempt to change the dns using Helm, we saw that the annotation changes, but we did not have the change in the DNS of the Public IP.

Is this condition expected?

Regards

**Comment by kyschouv** [comment] 2020-01-21 21:00
We experienced this last night as well, and it took a lot of effort to discover the issue. I've seen it before, and locking the public IP was the only way to prevent Kubernetes from changing it. I expected that since I had set up the IP address manually, Kubernetes would not need to change it to set up Load Balancing rules with it (and it hadn't in the past).

The [documentation](https://docs.microsoft.com/en-us/azure/aks/static-ip) says to set `spec.loadBalancerIP` to the public ip address, but doesn't mention `service.beta.kubernetes.io/azure-dns-label-name`. The only time we've ever used the latter is when we want Kubernetes to create and manage ip address for us. In this case, we don't want that, since we may want to remove the cluster and use the ip address to set up a new cluster (we've had to do this before for disaster recovery).

As we pre-provision these IP Addresses and DNS names, I'd expect Kubernetes to not change them when used as a static IP.

**Comment by bramvdklinkenberg** [comment] 2020-01-22 09:50
@edalferes are you using an ingress controller or do you expose your services via type loadbalancer?

if you use an ingress controller with ingrerss resources then you need to set the annotation in the service of the ingress controller.

**Comment by bramvdklinkenberg** [comment] 2020-01-22 09:55
@kyschouv see [87246](https://github.com/kubernetes/kubernetes/pull/87246)

**Comment by luddskunk** [comment] 2020-01-22 11:53
I tried setting `service.beta.kubernetes.io/azure-dns-label-name` in the edit mode of my service, however this caused me to lose this endpoint?

Do I need to redeploy the service in full? Right now I just Locked the IP resource.

**Comment by bramvdklinkenberg** [comment] 2020-01-22 11:55
Hi @luddskunk , do you expose your service via type loadbalancer or do you use an ingress and ingress controller?
if you use an ingress controller with ingrerss resources then you need to set the annotation in the service of the ingress controller.

**Comment by mikegoatly** [comment] 2020-01-22 14:39
So unless I've got the wrong end of the stick, PR [87246](https://github.com/kubernetes/kubernetes/pull/87246) that @bramvdklinkenberg mentions would suggest that this is going to be fixed in an upcoming release. What is the normal sort of timeframe for these releases to make their way to AKS as a supported release? (Not looking for an exact date, just an order of magnitude)

**Comment by bramvdklinkenberg** [comment] 2020-01-22 14:51
@mikegoatly around february 11th.

**Comment by bramvdklinkenberg** [comment] 2020-01-22 14:52
As a workaround you have to set the dns label in the service annotation.

**Comment by edalferes** [comment] 2020-01-22 19:24
Hello @bramvdklinkenberg, I'm using Ingress Voyager

**Comment by luddskunk** [comment] 2020-01-22 19:28
> Hi @luddskunk , do you expose your service via type loadbalancer or do you use an ingress and ingress controller?
> if you use an ingress controller with ingrerss resources then you need to set the annotation in the service of the ingress controller.

Hi, I'm using an nginx ingress controller and service. However, editing (not redeploying it) did not seem to work. Did you do a fresh re-deploy with a .yaml file or did edit the live configuration work for you?

Thanks

**Comment by bramvdklinkenberg** [comment] 2020-01-22 19:35
Hi @luddskunk , we use an azure devops pipeline so the pipeline applied the new changes. So I didn't edit the svc live.

**Comment by feiskyer** [comment] 2020-01-23 01:25
Update: https://github.com/kubernetes/kubernetes/pull/87246 has merged and cherry-picked to 1.15-1.17.

**Comment by nilo19** [comment] 2020-02-02 02:25
The bug has been fixed and corresponding docs have been added.

**Comment by AMoghrabi** [comment] 2020-02-06 22:35
Hey @nilo19 , can you elaborate a bit more on the bug being fixed? We are running 1.15.7 and I don't see an option to upgrade further than that. When do we expect to see this bug fixed on AKS? I assume we'll be able to receive the fix when 1.15.8 is released. Is that correct?

Thanks!

**Comment by nilo19** [comment] 2020-02-07 01:11
@AMoghrabi actually we're waiting for the release of k8s. We will add support to the new version on AKS after the release being rolled out.

**Comment by feiskyer** [comment] 2020-02-07 01:12
refer https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#timelines for k8s patch release timelines.

**Comment by thisispaulsmith** [comment] 2020-02-11 01:41
We recently upgraded to 1.15.7 and this same issue has wiped out our production cluster. Scaling up the node count wipes out the DNS label. This needs a pretty urgent fix? Adding the label to services isn't an really a viable option for us.

**Comment by davidmw** [comment] 2020-02-11 02:55
Our DNS label has been erased four times today, at random without any scaling activity or other known action triggering it.

**Comment by fstugren** [comment] 2020-02-11 22:42
Will version 1.15.7 be patched or will it be retired and excluded from the options available when creating a cluster? Some of our clusters are on 1.15.5 and do not experience this DNS name wipeout issue. However we spent most of the day today figuring out what could have gone wrong when we deployed a new cluster on 1.15.7

**Comment by bramvdklinkenberg** [comment] 2020-02-12 07:01
I think you will have to wait for 1.15.8 to be available for AKS. I think that will be available somewhere this month. Till then either don't use 1.15.7 or just set that annotation in your nginx svc or your application svc when using type loadbalancer.

**Comment by Daleck7** [comment] 2020-02-13 15:01
I put a lock on the IP resource just the time to deploy the yaml with the annotation, then I removed the lock after a couple of minutes. Now working since 2 weeks without any interruptions.
I add the following annotation in my traefik-ingress-service configuration :

```
annotations: 
    service.beta.kubernetes.io/azure-dns-label-name: <dnslabelname>
```

**Comment by Aray47** [comment] 2020-02-13 16:45
This happened to us as well. We had to add the dns name label back into the public IP address as the upgrade process got rid of them, and then add the endpoints back into the traffic manager profile.

**Comment by feiskyer** [comment] 2020-02-14 04:22
Update: 1.15.10, 1.16.7 and 1.17.3 are released. Since it's just released yesterday, it would need some time to have them in AKS. Before that, please use the annotation "service.beta.kubernetes.io/azure-dns-label-name" as a workaround.

**Comment by thisispaulsmith** [comment] 2020-02-24 10:39
@feiskyer How long does it normally take to hit AKS?

**Comment by feiskyer** [comment] 2020-02-24 10:58
@thisispaulsmith those versions would be available in next 2~3 weeks

**Comment by AMoghrabi** [comment] 2020-03-18 16:26
Hey team. Do we have an update on the release date? We're on the third week from @feiskyer's message. 

Can anyone confirm that 1.15.5 does not have the bug that 1.15.7 introduced? If that's the case we can upgrade to 1.15.5 in the meantime.

Thanks!

**Comment by fstugren** [comment] 2020-03-18 16:30
Yes, I can confirm that 1.15.5 does not have this “DNS label disappearance” issue, we’ve been using it for a while and I just deployed a cluster from scratch yesterday.
Today I am deploying another cluster on 1.15.10, which is available in a different region; I guess I’ll see if the problem was resolved in that version.

**Comment by AMoghrabi** [comment] 2020-03-18 16:32
Perfect, thanks for your quick response @fstugren  😄

**Comment by fstugren** [comment] 2020-03-18 17:56
@AMoghrabi - I can also confirm that version 1.15.10 does not have this issue either. I just deployed a new cluster and all application pods in West Europe using this version. I did not have to use the azure-dns-label-name workaround.

**Comment by AMoghrabi** [comment] 2020-03-18 18:22
@fstugren -- Curious, do you know of a way to replicate the issue on-demand? When we set up 1.15.7 it usually took a full day for the issue to occur by itself.

**Comment by fstugren** [comment] 2020-03-18 18:28
@AMoghrabi - no, we didn't try to come up with a consistent way to make that happed - when we noticed the issue, some clusters that were already using 1.15.7 were patched with the yaml fix, for the others we just kept using 1.15.5. Moving ahead we'll probably just skip to 1.15.10 or higher. I will keep an eye for the next couple of days on the cluster I deployed earlier today with 1.15.10, just in case the issue appears with a delay.

**Comment by Aray47** [comment] 2020-03-19 13:35
The error for us was very inconsistent as we updated 3-4 different endpoints all to 1.15.7 and only a select few DNS labels were removed - at random.

**Comment by amarlot2** [comment] 2020-03-26 20:18
Hello,
Can someone from Microsoft confirm in which version this issue is fixed !
In the changelog of AKS there is nothing about it.
We used to have a support ticket opened for this case since more than 2 month. The ticket has been closed this morning without any explaination. Just closed.
Thanks,
Alex

**Comment by AnujSehgall** [comment] 2020-05-07 03:18
@fstugren - Can you confirm that v1.15.10 doesn't have this issue?

**Comment by AMoghrabi** [comment] 2020-05-07 03:21
@AnujSehgall I can confirm 1.15.10 does not have the bug. We have been running it for three weeks now.

**Comment by palma21** [comment] 2020-07-21 04:58
Closing as per confirmation

**Closed by palma21** 2020-07-21 04:58 UTC
Labels: action-required
