### ISSUE TITLE
Failed to save container service '<name>'. Error: The VM size of Agent is not allowed in your subscription in location 'westeurope'.

### ISSUE THREAD

**Issue by Zimmergren** [Azure/AKS#279] opened 2018-03-29 06:28 UTC
I've been running AKS for a few months and have always used West Europe as a location for my resources and cluster. I've been running A4-sized clusters for a couple of things, and starting today we're seeing the below message when trying to scale out from N to Y nodes. 

**Current cluster config** 
- Size: Standard_A4
- Location: West Europe

**Expected results**
This has worked for a long time, so I would naively expect it to continue working.

**Actual results**
Failed with the below message.

```
Failed to save container service 'cloudcluster2'. Error: The VM size of Agent is not allowed in your subscription in location 'westeurope'. Agent VM size 'Standard_A4' is available in locations: centraluseuap,eastus,eastus2euap,southcentralus,westcentralus,westus2.
```

Is this a glitch in the matrix right now, or are the locations available to different VM sizes changing? If so, where is this being communicated so I can keep up with those changes?

**Comment by Zimmergren** [comment] 2018-03-29 07:40
Update: 
Trying to create a new cluster using the same setup, trying with different node sizes in West Europe specifically, we still get the error: 

```
az aks create -g rg-weu-aks-a4mv2 -n cloudcluster-a4mv2 --location westeurope --node-vm-size Standard_A4m_v2
```

Yields this result:
```
Operation failed with status: 'Bad Request'. Details: The VM size of Agent is not allowed in your subscription in location 'westeurope'. Agent VM size 'Standard_A4m_v2' is available in locations: centraluseuap,eastus,eastus2euap,southcentralus,westcentralus,westus2.
```

**Expected results**
- I expect to be able to continue to create a cluster in West Europe

**Actual Results**
- I can not create a cluster in West Europe
- Triggering a creation of a new cluster in `eastus` works, but this is not what we desire.

**Comment by lehtiton** [comment] 2018-03-29 11:52
I have the same issue. Using another region is not an option. Someone from Microsoft, please comment on this! What is the reason for this? This is not a first time I'm running this issue. I cannot do anything with AKS now!!!

**Comment by Zimmergren** [comment] 2018-03-29 12:01
I've been in touch with MS support who's looking into this now. Might be a data center issue rather than AKS but they are working on it.

I will follow up here once I receive more info.



Sent from my Samsung Galaxy smartphone.

**Comment by LoungeFlyZ** [comment] 2018-03-29 22:54
related? #280

**Comment by chryswoods** [comment] 2018-03-30 14:36
I have the same issue. Deleted an existing westeurope AKS cluster so that I could create a new one with a different VM size and now get 'Bad Request' for every VM size I try. A2_v2, A4_v2,, A4m_v2 D4_v3 etc. all give the same errors. Also raised a service ticket with MS support. Cannot do anything with AKS at the moment. Have to run servers in Europe, and since northeurope doesn't support managed clusters, am pretty stuck now.

**Comment by chryswoods** [comment] 2018-03-31 09:17
Support confirmed that this is related to issue #280. Suggested I try a different VM size (Av1, Av2, H, GS or LS) or another region.

**Comment by slack** [comment] 2018-04-03 03:27
This is related to #280 closing this issue.

**Closed by slack** 2018-04-03 03:27 UTC
Labels: capacity, question

**Comment by linocatucci** [comment] 2018-04-03 11:59
hi, 
any updates on this issue?

Br,
Lino

**Comment by Zimmergren** [comment] 2018-04-03 12:01
@linocatucci please see #280 which is describing the issue and reason. No solution as of writing this though.

**Comment by linocatucci** [comment] 2018-04-03 12:03
great thank you for your quick response!


-- 
Lino Catucci

Op 3 april 2018 bij 14:01:57, Tobias Zimmergren (notifications@github.com)
schreef:

@linocatucci <https://github.com/linocatucci> please see #280
<https://github.com/Azure/AKS/issues/280> which is describing the issue and
reason. No solution as of writing this though.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/AKS/issues/279#issuecomment-378225654>, or mute
the thread
