### ISSUE TITLE
Network policies are incorrectly merged

### ISSUE THREAD

**Issue by ball-hayden** [Azure/AKS#1138] opened 2019-08-06 12:15 UTC
Searched for existing default-deny network policy issues, but couldn't find anything.

**What happened**:

Define the following resources:

<details>
<summary>Resources</summary>

<pre>
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: console-netpol
spec:
  podSelector:
    matchLabels:
      console: "console"
  policyTypes:
  - Egress
  - Ingress
  egress:
    - {}
  ingress:
    - {}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector: {}
  policyTypes:
  - Egress
  - Ingress

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test-deployment
spec:
  template:
    metadata:
      labels:
        name: test-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            limits:
              cpu: '200m'
              memory: 512Mi

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-netpol
spec:
  podSelector:
    matchLabels:
      name: test-deployment
  policyTypes:
  - Egress
  - Ingress
  ingress:
    - ports:
      - port: 80
        protocol: TCP
</pre>
</details>

Create a console pod using the following command:

```sh
kubectl run --rm -i --tty --image nginx:latest --labels="console=console" --generator=run-pod/v1 "$@" "console-$(date +%s)" /bin/sh
```

Attempt to connect to the NGINX pod:

```sh
# apt-get install -y curl
# curl http://<test-deployment-pod-ip>
curl: (7) Failed to connect to <test-deployment-pod-ip> port 80: Connection timed out
```

**What you expected to happen**:

The `default-deny` and `test-netpol` network policies should be merged, allowing access to the `test-deployment` pod.

**How to reproduce it (as minimally and precisely as possible)**:

Order of creation appears to be important. Creating the default-deny policy, then adding the `test-netpol` works as expected. Creating them the other way round causes the pod to be inaccessible.

**Anything else we need to know?**:

Default deny taken from here:
https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-ingress-and-all-egress-traffic

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:27:12Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?): 3

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

Test cluster running only the above workload.

**Comment by sauryadas** [comment] 2019-08-06 20:20
@song-jiang This is expected behavior right ?

Order of creation appears to be important. Creating the default-deny policy, then adding the test-netpol works as expected. Creating them the other way round causes the pod to be inaccessible.

**Comment by ball-hayden** [comment] 2019-08-06 20:42
I'll see if I can find a better reference, but I'd argue this is not expected behaviour.

https://serverfault.com/a/952221

**Comment by ball-hayden** [comment] 2019-08-06 20:52
From the K8s API reference (my bold):

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#networkpolicyspec-v1beta1-extensions

> Outgoing traffic is allowed ... if the traffic matches **at least one** egress rule across all of the NetworkPolicy objects whose podSelector matches the pod

> Traffic is allowed to a pod ... if the traffic matches **at least one** ingress rule across all of the NetworkPolicy objects whose podSelector matches the pod

In the case above both network policies' podSelector matches `test-deployment` pods. When attempting to access the pod, at least one of the ingress rules matches so traffic should be allowed (regardless of order of creation of the network policies).

**Comment by ams0** [comment] 2019-08-08 06:28
Tried to repro, it works. Deleting and recreating the `test-netpol` policy has the desired effect (deny/allow traffic). Using Kubenet+calico on 1.14.3.

**Comment by ball-hayden** [comment] 2019-08-08 06:32
Interesting. I was using CNI and Azure backed network policies.

**Comment by sauryadas** [comment] 2019-08-08 21:33
thanks for confirming.

@aanandr Can you please take a look at this?

**Comment by bergerx** [comment] 2019-08-11 22:12
Could #1135 be related to this?

**Comment by song-jiang** [comment] 2019-08-12 09:42
@sauryadas Sorry for the late response. Just back from vacation. Calico implements kubernetes network policies by converting them to calico network policies with priorities where default-deny will be made as least priority. The order of how user creating those policies does not affect policy priorities.

**Comment by NillsF** [comment] 2019-08-19 01:07
I ran into the same today, and I compared Azure Networkpolicies and Calico Networkpolicies. My conclusion is the following:

Calico: follows kubernetes docs and allows traffic if it matches at least one rule.
Azure: doesn't follow docs, and if deny-all is deployed after a specific allow it denies traffic. 

Let it be up for debate whose interpretation is correct - but there is at least a huge inconsistency.
I hit a related but distinct inconsistency between Azure and Calico as well #1158

**Comment by aanandr** [comment] 2019-08-20 00:26
We dont support overlapping policies of this type - where you define a deny all for all pods and then selectively allow for certain pods (both these policies overlap for the pods that you want to allow traffic for). However, support for this is coming very soon.

**Comment by sauryadas** [comment] 2019-08-20 03:14
Duplicate of #1135 will track 1135

**Closed by sauryadas** 2019-08-20 03:14 UTC
Labels: network-policies
