### ISSUE TITLE
Pods on Virtual Node keep restarting

### ISSUE THREAD

**Issue by relferreira** [Azure/AKS#1040] opened 2019-06-05 10:44 UTC
**What happened**:
Pods deployed on virtual node keep restarting frequently.

**What you expected to happen**:
We intend to deploy an API using the ACI connector, but even the simple example described on the following tutorial 
https://docs.microsoft.com/pt-br/azure/aks/virtual-nodes-portal 
keep restarting from time to time. 

Based on this tutorial:
https://docs.microsoft.com/bs-latn-ba/azure/container-instances/container-instances-restart-policy#container-restart-policy
one solution might be changing the `restart policy` of the container, but in Kubernetes we can't change this property on deployments.

**How to reproduce it (as minimally and precisely as possible)**:
I think we followed an older version of this tutorial:
https://docs.microsoft.com/pt-br/azure/aks/virtual-nodes-portal

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.3
- Size of cluster (how many worker nodes are in the cluster?): 25 VMs and 1 virtual node
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Java and Machine Learning

Thanks in advance

**Comment by Senai-T** [comment] 2019-06-05 18:55
I recreated the issue and you're completely right, the container terminates after about two seconds of running, I even tried it with the restart policy set to Never and it still terminated with a status code of 0 meaning that the termination signal is most likely coming from the container. I ran the same scenario using a different image  (mcr.microsoft.com/azure-functions/python:2.0) just to be sure the problem isn't with ACI and it ran as expected, even attached to it to confirm. In conclusion a container should run without a problem so long as the container isn't sending a success signal (status code 0) initiating a shutdown.
on a side note: if you have a whole bunch of stuff on Kubernates, have a look at [batch jobs](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/)  you can even go fancy by customizing how parallel starts..etc.

**Comment by jnoller** [comment] 2019-06-06 20:28
@srrengar Virtual Node issue

**Comment by srrengar** [comment] 2019-06-06 22:04
@mostafaez can you take a look

**Comment by relferreira** [comment] 2019-06-19 13:10
Hello @jnoller, any news about this issue?

**Comment by jnoller** [comment] 2019-06-19 15:19
@relferreira Virtual Nodes/VK/ACI are outside of my scope, we're waiting on followup from @srrengar and @mostafaez

**Comment by srrengar** [comment] 2019-06-19 16:02
@relferreira have you opened a support case on this - is it still occurring? this is odd that it would occur with the image in the sample

**Comment by relferreira** [comment] 2019-06-19 16:47
Hello @srrengar, the ticket ID is 119050923001565

**Comment by jluk** [comment] 2019-08-09 04:12
@srrengar or @relferreira was this incident ever closed?

**Comment by mostafaez** [comment] 2019-08-09 17:15
The ticket was resolved long ago. The container was succeeding and had deployed with restart policy always.

**Comment by jluk** [comment] 2019-08-09 17:57
Thanks @mostafaez for confirm, closing this issue as a result.

**Closed by jluk** 2019-08-09 17:57 UTC
Labels: azure/aci, virtual-nodes
