### ISSUE TITLE
VMSS create in CLI 2.0.74 not returning a scale set cluster

### ISSUE THREAD

**Issue by redliu312** [Azure/AKS#1237] opened 2019-09-27 02:08 UTC
**What happened**:
the "Release Notes 2019-09-09 " mentioned the VMSS backed AKS cluster
feature is in GA. We tried to use the az (version: 2.0.74) to creatre the VMSS backed aks cluster 
the command is:

```
az aks create \                                                                               1 ↵  6416  10:18:09
    --resource-group cliRgVmss \
    --name cliVmssAks \
    --vm-set-type VirtualMachineScaleSets \
    --node-count 2 \
    --generate-ssh-keys \
    --kubernetes-version 1.13.10 \
    --load-balancer-sku standard
```

but still got a non-VMSS cluster. Then we found we still need to follow the preview 
[tutorial](https://docs.microsoft.com/zh-tw/azure/aks/use-multiple-node-pools#before-you-begin) to make a VMSS backed cluster which indicates that we need to do two things before
creating VMSS cluster:
- az feature register --name MultiAgentpoolPreview --namespace Microsoft.ContainerService
- az provider register --namespace Microsoft.ContainerService

**What you expected to happen**:
Because this feature is in GA, we should not need to register the preview feature.

**How to reproduce it (as minimally and precisely as possible)**:
try to create a VMSS backed cluster with az 2.0.74

**Anything else we need to know?**:

**Environment**:
- az cli : 2.0.74
- the subscription is created before the GA announcement

**Comment by jluk** [comment] 2019-09-27 18:22
@redliu312 we were not able to reproduce that issue when deploying a VMSS cluster from a new subscription without feature registration, could you please double check the compute type of that created cluster?

**Comment by redliu312** [comment] 2019-09-27 18:51
Thanks @jluk , do you mean for the old subscription we still need to follow the preview vmss backed cluster guide?

**Comment by jluk** [comment] 2019-09-27 19:18
@redliu312 re-reading your original post I think there is confusion about the features. VMSS back clusters are separate from using multiple node pools, which is the doc you linked.

VMSS backed clusters can be used without any additional registration. Multiple node pools still need registration of the multiplenodepools feature.

The document states you need to register the multiagentpool feature flag.
az feature register --name MultiAgentpoolPreview --namespace Microsoft.ContainerService

**Comment by jluk** [comment] 2019-09-27 23:47
Closing this as the original report of VMSS enabled clusters deploy properly, but feel free to comment if it's not clear and I'll revisit.

**Comment by redliu312** [comment] 2019-10-01 09:23
@jluk 
The way I asked the question may confuse you. Let me redefine the question:
for the old subscription (created before the GA announcement), we noticed that  the vmss backed cluster can not be enabled on the portal or via the az cli even we enabled the vmss feature on portal or pass the parameter via az cli. The only way we found to resolve it is  to register the multiAgentPoolPreview feature through az cli command line , then we can create a vmss cluster.

we are also sure the MicrosoftContainerService resource provider has been registered on that subscription.

is our observation correct for the old subscription? if so, do we have another way to make it can be done to create a vmss backed cluster without register the MultiAgentPoolPreview feature for all the old subscriptions?

**Comment by jluk** [comment] 2019-10-01 15:50
Thanks for clarifying @redliu312 that is definitely not expected behavior, you should be able to deploy a scale set cluster without any feature flag registration. Could you please open a support ticket so we can take a hands-on look at your subscription? Feel free to share the ticket # here and I'll chase it too.

**Comment by redliu312** [comment] 2019-10-02 02:52
opened a  support ticket and finally knowing what happened here:
-  event if we create the VMSS backed cluster , but in the Node Pool(preview) page in the aks resource, it  shows it is not a vmss backed cluster
![image](https://user-images.githubusercontent.com/6196351/66014505-bd969080-e501-11e9-9b45-81535437044e.png)
- we can check the cluster is vmss enabled via check the VMSS  agent pool resource in the MC(managed cluster) resource group.
-  it seemed it is frontend displaying information issue here. maybe it will better to show "please use az cli to regiter the multi agent pool preview feature " instead showing "this is not a VMSS backed cluster "

**Comment by jluk** [comment] 2019-10-02 16:34
Thanks for follow-up @redliu312 I will re-open to close discussion.

@jenetlan can you please review this page?

**Comment by jenetlan** [comment] 2019-10-04 02:49
Thanks for bringing this up! We're working on a wording change so that the message accurately reflects the cluster. I'll update once it goes live.

**Comment by jenetlan** [comment] 2019-10-14 21:39
Update - should be live everywhere now :) Thanks again for reporting!

**Comment by jluk** [comment] 2019-10-14 22:09
Closing thanks everyone

**Closed by jluk** 2019-10-14 22:09 UTC
Labels: azure/portal
