### ISSUE TITLE
AKS cluster AutoScaling stopped working

### ISSUE THREAD

**Issue by brudnyhenry** [Azure/AKS#1259] opened 2019-10-08 07:07 UTC
**What happened**: 
AKS cluster autoscaler was working fine till yesterday- all clusters created with below options were able to be scaled-up automatically
```bash
--enable-cluster-autoscaler 
-vm-set-type VirtualMachineScaleSets
```
However since yesterday the same cluster configuration does not provide cluster auto-scaling feature even though that enableAutoScaling option is set to true in cluster definition.

```json
    "agentPoolProfiles": [
      {
        "availabilityZones": null,
        "count": 1,
        "enableAutoScaling": true,
        "enableNodePublicIp": null,
        "maxCount": 2,
        "maxPods": 110,
        "minCount": 1,
        "name": "nodepool1",
        "nodeTaints": null,
        "orchestratorVersion": "1.13.10",
        "osDiskSizeGb": 100,
        "osType": "Linux",
        "provisioningState": "Succeeded",
        "scaleSetEvictionPolicy": null,
        "scaleSetPriority": null,
        "type": "VirtualMachineScaleSets",
        "vmSize": "Standard_DS2_v2"
      }

```

**What you expected to happen**:
In case of situation when there are no resources available in the cluster to schedule a pod:
```
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  2m45s (x29 over 24m)  default-scheduler  0/1 nodes are available: 1 Insufficient memory.

```
There should be event from **cluster-autoscaler** informing that pod triggered scale-up action
```
kubectl describe pod erstwhile-cardinal-mysql-7676987ccf-skk2d | grep autoscaler                                                                                    
                                 
  Normal   TriggeredScaleUp   19s                cluster-autoscaler  pod triggered scale-up: [{aks-nodepool1-28583763-vmss 1->2 (max: 2)}]                                                    

```
It is not happening since yesterday (or could have started over the weekend because it was working on friday 4.10.2019)

Problem is present in all regions.
**How to reproduce it (as minimally and precisely as possible)**:
```sh
az aks create --vm-set-type VirtualMachineScaleSets -g WestEurope  -n MojAutoAKS --node-count 1 --enable-cluster-autoscaler --min-count 1 --max-count 2

helm init
helm install stable/mysql --set resources.requests.memory=2048Mi 
helm install stable/mysql --set resources.requests.memory=2048Mi 
helm install stable/mysql --set resources.requests.memory=2048Mi 
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
1 worker. Max number of nodes is 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
HELM chart stable/mySQL
- Others:

**Comment by sauryadas** [comment] 2019-10-08 17:35
@palma21 PTAL

**Comment by palma21** [comment] 2019-10-09 19:42
From above it looks like CA is enabled but the scaling events are not being triggered, can you check the CA logs and confirm you have quota?
https://docs.microsoft.com/en-us/azure/aks/view-master-logs

**Comment by hallgeirl** [comment] 2019-10-10 07:36
We see a similar issue. Scale-up was triggered, but we don't get a new node. 

For the record - The node count in the Azure portal for the node pool shows 2 nodes, but only 1 node is actually present when checking "kubectl nodes". Also, the VM scale set for the node pool also only had one instance.

I disabled autoscaling, and then scaled it back to 1 node through the Azure portal (since it was showing 2, even though there were actually only 1). Then I tried scaling it manually up to 2 nodes. Then I get this monstrosity:

Failed to scale node pool 'winpol' in Kubernetes service 'DevFarm3808'. Error: VMSSAgentPoolReconciler retry failed: Code="AllocationFailed" Message="Allocation failed. If you are trying to add a new VM to a Virtual Machine Scale Set with a single placement group or update/resize an existing VM in a Virtual Machine Scale Set with a single placement group, please note that such allocation is scoped to a single cluster, and it is possible that the cluster is out of capacity. Please read more about improving likelihood of allocation success at http://aka.ms/allocation-guidance."

Interestingly, again the node count in the portal was increased to 2, even though the scaling operation failed. This must be a bug(?).

For the record the nods we run are standard D2s_v3.

**Comment by hallgeirl** [comment] 2019-10-10 13:38
Seems autoscaling started working for us again at some point during the day...

**Comment by palma21** [comment] 2019-10-10 19:55
@hallgeirl that is what I suspected above that is an allocation failure, CA was trying to scale but not being able such as you manual step. For those cases I'd recommend opening a support ticket.

**Comment by palma21** [comment] 2019-10-10 20:00
@brudnyhenry all subscription have quotas. You can check them by navigating the the subscription in the portal and clicking quotas and limits
When you say there are not logs you mean you don't see any logs in Log Analytics from CA? 

can you disable CA and try to do a manual scale to confirm?

**Comment by brudnyhenry** [comment] 2019-10-11 06:28
Hi,
Sorry I meant no quotas are being exceeded. 
I enabled Log Analytics for CA but did not get any result with below query:

```
AzureDiagnostics
| where Category == "cluster-autoscaler" 
```

Next I disabled autoscaling and tried to scale up manually and it worked:
Before:
```
az aks show -g FTS_SRE_K8_AUTOSCALING -n FTS_SRE_K8_AUTOSCALING_AKS  --query agentPoolProfiles
The behavior of this command has been altered by the following extension: aks-preview
[
  {
    "availabilityZones": null,
    "count": 1,
    "enableAutoScaling": true,
    "enableNodePublicIp": null,
```
After:

```sh
az aks scale -g FTS_SRE_K8_AUTOSCALING -n FTS_SRE_K8_AUTOSCALING_AKS  --node-count 2 --nodepool-name default
The behavior of this command has been altered by the following extension: aks-preview
{
  "aadProfile": null,
  "addonProfiles": null,
  "agentPoolProfiles": [
    {
      "availabilityZones": null,
      "count": 2,
      "enableAutoScaling": false,
```

Like I wrote before- everything was working till this week, our deployment did not change.
Last week every time a pod was scheduled we could see at least below information form CA- if it triggered scale-up or not. 
```
  Normal   NotTriggerScaleUp  30s                cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added):                                                    
  Normal   TriggeredScaleUp   19s                cluster-autoscaler  pod triggered scale-up: [{aks-nodepool1-28583763-vmss 1->2 (max: 2)}]  
```
Currently we don't even see above events when we describe a pod, as if CA was not enabled, even though it's marked as enabled.

**Comment by palma21** [comment] 2019-10-11 19:44
Thanks for the investigation @brudnyhenry and glad it's back working.

Not sure I understood the last bit, you mean that on any new cluster you create you can't get autoscaler to work? (only after disabling and enabling again?)

**Comment by brudnyhenry** [comment] 2019-10-12 07:21
Hi,
that is correct. It does not work until I disable it and enable again.

**Comment by hallgeirl** [comment] 2019-10-14 07:51
Hi, 
Been following the thread here since we also had the same issue. Our cluster were also a new one. After my initial post I did switch autoscaling on again. I later mentioned that autoscaling started working again. 

This seems consistent with @brudnyhenry observations - although I can't 100% confirm that the switching it off and on again was the exact thing that solved this.

We also use Azure CLI to create the cluster and node pools (version 2.0.72).

**Comment by Blackbaud-TimMcVicker** [comment] 2019-10-14 21:27
We also saw this behavior today:

1. Created a new cluster with ```--enable-cluster-autoscaler --min-count 3 --max-count 13``` and an initial node count of 3
2. Scaled a deployment to 15 replicas (to force an autoscale), with 5 pods failing to get scheduled. This *did not* trigger a scale out at all. The ```cluster-autoscaler-status``` configmap was not created.
3. Turned the cluster autoscaler off.
4. Turned it back on again with the same parameters. Once it was turned back on, it immediately triggered a scale out event to 4 nodes. The ```cluster-autoscaler-status``` was now created.

We are using version `2.0.74` of the Azure CLI and Kubernetes version ```1.14.6```

**Comment by brianxieseattle** [comment] 2019-10-16 20:59
Hi, we saw the similar behavior. 
When we pass the autoscaler parameter to provision a new cluster, autoscaler does not work. There is no log for "cluster autoscaler"
We changed to manual scale and changed back to auto scaler in Portal UI. The autoscaler immediately worked. We can also see the cluster autoscaler master logs.  
We tried three clusters and saw the same behaviors. 

Is it a bug?

**Comment by DavidZisky** [comment] 2019-10-22 13:40
Same happened for our client. Autoscaler configured properly, everything should work. But it didn't. We disabled autoscaler and enabled it again and it started working immediately.

**Comment by palma21** [comment] 2019-10-22 22:53
Could  you folks open some support tickets so I can take a look at your specific clusters? We've not been able to repro and that would allows to find out what happened. 

Also, I'm guessing in all your non-working cases, the CA config map has not been created?

**Comment by Blackbaud-TimMcVicker** [comment] 2019-10-23 00:11
I've created support ticket 119102321000006 for our cluster, if that helps.

When this was originally not working, the configmap was not created. Once I turned it off/back on again, it was created.

**Comment by marwanad** [comment] 2019-10-23 00:19
@Blackbaud-TimMcVicker are you able to repro this behaviour consistently? I've managed to get to this state once out of 8 tries. - just trying to get to the root cause here.

**Comment by DavidZisky** [comment] 2019-10-23 10:26
@palma21 I've created 119102324001064, but in our case ConfigMap was there. Just the ScaleUp wasn't triggered at all (even tho all the nodes had almost 100% mem usage). We disabled and enabled autoscaler (with the same min/max nodes numbers), configmap was recreated and ScaleUp action got triggered immediately.

**Comment by Blackbaud-TimMcVicker** [comment] 2019-10-23 16:31
@marwanad I'm able to reproduce it, but not consistently. It happened 2/2 times last week, but only 1/4 times this week (using the same versions).

**Comment by palma21** [comment] 2019-10-29 16:38
Hi all, apologies on the delay for update but we were working on it. We identified the race condition at create and this was shipped on last week's release. We don't expect you to encounter this problem again during create. Please let us know otherwise. 

Closed as fixed.

**Closed by palma21** 2019-10-29 16:38 UTC

**Comment by PSanetra** [comment] 2019-12-02 09:44
@palma21 This (or at least a very similar issue) happened today in our AKS, too.
A scale-up was triggered, but the new VM in the VMSS was too slow to start up (it was stuck in the ProvisioningState/creating state for a while). After some time the autoscaler deleted that VM again.

**Comment by dewnull** [comment] 2019-12-06 00:21
disabling and reenabling it worked for me. I recently upgraded one of our clusters to 1.14.8
```az aks nodepool update --resource-group <>  --cluster-name <> --name nodepool --disable-cluster-autoscaler```

``` az aks nodepool update --resource-group <> --cluster-name <> --name nodepool --enable-cluster-autoscaler --min-count 4 --max-count 40```

**Comment by ShamSV** [comment] 2020-03-23 14:59
The issue seems to persits in version 1.15.7.
I face the same issue and disabling and enabling auto trigger also doesn't fix the issue.

**Comment by rlees85** [comment] 2020-04-27 15:14
Facing same issue. Autoscaling is totally broken on multiple clusters, back to scaling ye olde way

**Comment by marwanad** [comment] 2020-04-27 16:39
@ShamSV @rlees85 can you share your region and more info on the issue you're facing?

Are you able to see the autoscaler configmap?

`kubectl describe configmap --namespace kube-system cluster-autoscaler-status`

**Comment by ShamSV** [comment] 2020-04-27 19:06
Hi Marwan and Rich,

I could get the issue sorted. We have AKS in South India and Central India.

If you are creating AKS cluster, though SPN, it should have explicit “network contributor” access.

Once we ensured it has that access, the issue got sorted.

Regards,
Sham SV

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
