### ISSUE TITLE
Scaling a MI-enabled cluster fails

### ISSUE THREAD

**Issue by ams0** [Azure/AKS#1324] opened 2019-11-19 01:28 UTC
**What happened**:

Scaling of a cluster deployed with `--enable-managed-identity` fails.

**What you expected to happen**:

Correctly scaling up and down of the cluster.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy a cluster with:
```
$ az aks create -k 1.15.5   --load-balancer-sku Standard --network-plugin kubenet --network-policy calico -x -c 2 -s Standard_B4ms --node-zones 1 2 3 --nodepool-name base  -g k8s -n aksmi --enable-managed-identity --no-wait
```

Scaling up fails with:
```
$ az aks nodepool scale -g k8s --cluster-name aksmi -n base -c 4

Operation failed with status: 'Bad Request'. Details: Provisioning of resource(s) for Agent Pool base failed. Error: {
  "code": "InvalidTemplateDeployment",
  "message": "Deployment failed with multiple errors: 'Authorization failed for template resource 'aksmi-agentpool' of type 'Microsoft.ManagedIdentity/userAssignedIdentities'. The client '49facfd4-19c2-4b38-91af-6263b285ca29' with object id '49facfd4-19c2-4b38-91af-6263b285ca29' does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/write' at scope '/subscriptions/12c7e9d6-967e-40c8-8b3e-4659a4ada3ef/resourceGroups/k8s/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aksmi-agentpool'.:Authorization failed for template resource '02195548-517e-5307-a600-c550d11f8edd' of type 'Microsoft.Authorization/roleAssignments'. The client '49facfd4-19c2-4b38-91af-6263b285ca29' with object id '49facfd4-19c2-4b38-91af-6263b285ca29' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/12c7e9d6-967e-40c8-8b3e-4659a4ada3ef/resourceGroups/k8s/providers/Microsoft.Authorization/roleAssignments/02195548-517e-5307-a600-c550d11f8edd'.'"
```

The funny part is that the objectID `49facfd4-19c2-4b38-91af-6263b285ca29` is nowhere to be found in my subscription. It's not the SP (the one I store in `~/.azure/aksServicePrincipal.json` and that is used by the cluster), neither the MI created in the `MC_` group. And even stranger, scalind *down* works!

```
$ az aks nodepool scale -g k8s --cluster-name aksmi -n base -c 1

AgentPoolType            Count    MaxPods    Name    OrchestratorVersion    OsDiskSizeGb    OsType    ProvisioningState    ResourceGroup    VmSize
-----------------------  -------  ---------  ------  ---------------------  --------------  --------  -------------------  ---------------  -------------
VirtualMachineScaleSets  1        110        base    1.15.5                 100             Linux     Succeeded            k8s              Standard_B4ms
```

Seems related to #1315 .

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.5
- Size of cluster (how many worker nodes are in the cluster?) 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) testing
- Others:
Calico, AZs, kubenet, SLB

**Comment by norshtein** [comment] 2019-11-19 06:14
Thanks for reporting, we found the root cause, the issue will be fixed soon.

**Comment by jluk** [comment] 2020-04-22 21:54
Closing as this should be fixed now.

**Closed by jluk** 2020-04-22 21:54 UTC
Labels: Managed Identity, known-issue
