### ISSUE TITLE
Unable to SSH to AKS Nodes via Azure Bastion (other SSH ways works)

### ISSUE THREAD

**Issue by sprab** [Azure/AKS#1854] opened 2020-09-11 05:15 UTC
**What happened**:
Unable to SSH to AKS nodes via Azure Bastion. 
SSH to non-AKS Linux VMSS instances works just fine.

**What you expected to happen**:
Successful SSH to AKS agent nodes via Azure Bastion.

**How to reproduce it (as minimally and precisely as possible)**:
Create AzureBastionSubnet in the same VNET where the AKS worker nodes are running.
Create AzureBastion service on that subnet.
Generate ssh keys (id_rsa and id_rsa.pub)
Push the public key into the VMSS instances either from portal or via CLI.
Go the the nodepool VMSS >> select one of the instances >> Bastion
Use the SSH private key (id_rsa) that was generated using ssh-keygen.

![image](https://user-images.githubusercontent.com/17014671/92864969-1de7bf00-f441-11ea-8748-9e267f4a4d40.png)

SSH to AKS nodes via a pod in the same cluster works fine.
https://docs.microsoft.com/en-us/azure/aks/ssh#create-the-ssh-connection

Referred the articles:
https://docs.microsoft.com/en-gb/azure/bastion/bastion-overview
https://docs.microsoft.com/en-us/azure/bastion/bastion-nsg

**Anything else we need to know?**:
SSH to other nodes in the same VNETs works just fine.

**Environment**:
- Kubernetes version (use `kubectl version`):
1.16.10
- Size of cluster (how many worker nodes are in the cluster?)
One nodepool >> 2 instances
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
NA
- Others:
SSH to AKS nodes via a pod in the same cluster works fine.
https://docs.microsoft.com/en-us/azure/aks/ssh#create-the-ssh-connection

**Comment by blame19** [comment] 2020-09-14 09:12
Following

**Comment by yangl900** [comment] 2020-09-15 05:48
@sprab it should work too for Bastion, what error did you get?

**Comment by sprab** [comment] 2020-09-15 05:54
![image](https://user-images.githubusercontent.com/17014671/93171009-a0d38700-f76b-11ea-9b3e-403da4257288.png)

This is the error i am getting.

**Comment by palma21** [comment] 2020-09-15 06:24
Are you trying with password? With private key? Bastion has a few limitations in these areas.
That error is basically SSH was rejected by the target VM which is normally credentials and not connectivity.

**Comment by sprab** [comment] 2020-09-15 06:27
I am trying with SSH keys.  The same keys work when I use it in a jump box VM to connect to the worker nodes.  So the SSH to the nodes work with the public and private keys.  When I use it in Bastion, it is not working.

**Comment by pradeepbohra** [comment] 2020-09-24 15:16
Exactly the same issue I was facing and I got a response from Azure support telling its a known error. Now here I am seeing it is reported as an issue. Can Azure Bastion team explain this.

**Comment by TomGeske** [comment] 2020-11-24 14:26
Did you add required NSG for Bastion? https://docs.microsoft.com/en-us/azure/bastion/bastion-nsg

**Comment by weinong** [comment] 2020-11-24 18:48
the problem is in Bastion which doesn't support newer SSH protocols like ED25519 which is default on AKS nodes.

**Comment by TomGeske** [comment] 2020-11-25 16:21
Just tried it and sshd log reports:

`Unable to negotiate with $node_ip port 48826: no matching key exchange method found. Their offer: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha1 [preauth]`

**Comment by TomGeske** [comment] 2020-11-26 08:38
+@msabansal for visibility.

**Comment by msabansal** [comment] 2020-11-26 08:48
Getting this unblocked is one of our top priorities. I will report back here once this issue is fully resolved.

**Comment by sanath230** [comment] 2020-11-29 14:52
Any updates here? I am also hitting with the same issue.

**Comment by alexeldeib** [comment] 2020-12-10 23:53
if the issue is ed25519, wouldn't using a different ssh key type for the cluster be a simple workaround?

**Comment by msabansal** [comment] 2020-12-11 19:57
ED25519 is more secure algorithm. Bastion currently only supports RSA/DSA keys.

**Comment by msabansal** [comment] 2020-12-11 20:12
using RSA/DSA is a workaround but personally, i would not recommend it.

**Comment by msabansal** [comment] 2020-12-11 20:13
@sanath230 Which region are your resources in?

**Comment by msabansal** [comment] 2020-12-19 00:17
I tried this scenario today and am unable to reproduce. Kubernetes version was 1.18.10. Can you please check on your side if it works?

**Comment by sanath230** [comment] 2020-12-19 06:15
> @sanath230 Which region are your resources in?

They are in East US

**Comment by sanath230** [comment] 2020-12-19 06:34
> > @sanath230 Which region are your resources in?
> 
> They are in East US

I'm able to connect to aks nodes through bastion now, with kubernetes version 1.17.13

**Comment by msabansal** [comment] 2020-12-19 06:47
@sanath320 thanks for the update. 

@sprab can you please check aswell.  We can then close the issue

**Comment by sprab** [comment] 2020-12-23 00:03
Thanks @msabansal , It is now working for me.  This can be closed.

**Closed** 2020-12-23 00:17 UTC
Labels: question
