### ISSUE TITLE
AKS nodes do not self heal

### ISSUE THREAD

**Issue by twsouthwick** [Azure/AKS#135] opened 2018-01-17 18:15 UTC
I recently hit the monthly quota on my Azure subscription and had my resources all deactivated. Last night, the next billing cycle started and the resources were activated. When I ran `kubectl get node`, the node was listed as "not ready". I'm not a Kubernetes expert, and have found that deleting pods would self heal and new ones would be created. I tried this with the nodes, but no node was created. After running `az aks scale -c 2`, a single node showed up with `kubectl`. If I scaled it back down to 1, then no nodes were available. It appears that now aks believe there to be a node available that kubernetes does not know about.

**Comment by seanmck** [comment] 2018-06-09 05:20
Duplicate of #131

**Closed by seanmck** 2018-06-09 05:20 UTC
