### ISSUE TITLE
How to keep kubernetes dashboard running

### ISSUE THREAD

**Issue by mouradmourafiq** [Azure/AKS#779] opened 2019-01-10 23:06 UTC
**What happened**:

In order to access the k8s dashboard, the user must run:
```
aks browse --resource-group <VALUE> --name <VALUE>
```

But the dashboard timesout after a couple of minutes.

**What you expected to happen**:

I expect the dashboard to keep running until I stop the command.

**How to reproduce it (as minimally and precisely as possible)**:

Just start the dashboard using the command above.

**Environment**:

 - Kubernetes version (use kubectl version):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
 - Size of cluster: 8 nodes
 - General description of workloads in the cluster: machine learning

**Comment by DovAmir** [comment] 2019-01-14 15:16
+1

**Comment by dennisameling** [comment] 2019-01-15 11:21
+1

**Comment by devkws** [comment] 2019-01-15 15:38
Same issue as [#68](https://github.com/Azure/AKS/issues/68) and [#313](https://github.com/Azure/AKS/issues/313)

**Comment by alexsandro-xpt** [comment] 2019-01-16 12:06
+1

**Comment by EvgenyKhaliper** [comment] 2019-01-20 14:39
+1

**Comment by IvanJosipovic** [comment] 2019-01-20 18:52
+1

**Comment by benc-uk** [comment] 2019-01-21 16:10
You can create your own service for the dashboard, rather than go through a proxy tunnel
I wrote a script that only opened it up for a single IP (your current public IP) to make it more secure, **but it's still pretty risky**

https://gist.github.com/benc-uk/58ac45d05d00ea2db2bf86f6953fd225#file-dash-external-sh

**Comment by jnoller** [comment] 2019-04-04 22:10
closing as duplicate of https://github.com/Azure/AKS/issues/68

**Closed by jnoller** 2019-04-04 22:10 UTC
