### ISSUE TITLE
Missing control over resource naming

### ISSUE THREAD

**Issue by amoorthaemer** [Azure/AKS#246] opened 2018-03-15 14:34 UTC
Hi,

I really like AKS, but I'm really missing control over resource naming. In fact, there is almost nothing customizable at all. I'v read through some threads here and I think I can conclude I'm not the only one here that feels like this. Most ARM templates allow detailed customization and it would be greatly contribute to wide adoption of AKS in the near future.

Cheers
Bert

**Comment by slack** [comment] 2018-03-15 20:02
We are unlikely to allow for fine-grained control over resource names, as we are generating resources through acs-engine. Is there a specific use-case that you are after?

**Comment by amoorthaemer** [comment] 2018-03-16 10:35
Well ... If there were a possibility to at the least specify a naming prefix per resource type that would be a great help already.

**Comment by murraypete** [comment] 2018-03-19 08:30
...or if renaming isn't possible (and I can kinda see why), then propagation of tags should work. Haven't really dug into AKS from a billing/resource tracking perspective yet, but imagine tagging will be useful.

i.e. an AKS cluster tagged with billing/created-by/etc information should apply the same to all taggable objects created in the AKS resource group.

**Comment by ultimateboy** [comment] 2018-03-27 19:54
Related: https://github.com/Azure/AKS/issues/207

**Comment by theheatDK** [comment] 2018-06-15 16:49
When you create a cluster like this:
`az aks create --resource-group myResourceGroup ....`

The cluster is created in myResourceGroup but everything else is created in a new resource group. (VMs, scale sets etc.)

Is this a bug or intentional? :-)

I do not care so much for the naming of the resources them self, but I really would like everything in the same resource group.

**Comment by amanohar** [comment] 2018-06-15 17:09
This is by design. All AKS cluster resources are in a resource group starting with `MC_*`

**Comment by jnoller** [comment] 2019-04-03 20:33
Closing as duplicate issue, this functionality is not supported, but on our roadmap to support

**Closed by jnoller** 2019-04-03 20:33 UTC
Labels: resource-groups
