### ISSUE TITLE
[Feature] Support for Azure Linux 3.0

### ISSUE THREAD

**Issue by suhuruli** [Azure/AKS#4372] opened 2024-06-28 05:13 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Support Azure Linux 3.0 in AKS. Planned approximately same time as #4314.

**Comment by allyford** [comment] 2024-12-11 16:55
Closing as duplicate of #4535

**Closed by allyford** 2024-12-11 16:55 UTC
Labels: feature-request
