### ISSUE TITLE
AKS with no nodes, just ACI

### ISSUE THREAD

**Issue by dpen2000** [Azure/AKS#406] opened 2018-06-04 19:15 UTC
Is it possible to have AKS with 0 real nodes and just use Azure Container Instance for requested containers?

**Comment by JackQuincy** [comment] 2018-06-06 22:36
Not today. The ACI virtual kubelet requires some pods to be ran outside of it. so you'll need at least one node to install those pods as well as the ACI virtual kubelet executable. There is active work on this I believe. You will probably get better info on this if you ask the question in the Virtual Kubelet github repo

**Comment by seanmck** [comment] 2018-06-09 05:32
Duplicate of #52

**Closed by seanmck** 2018-06-09 05:32 UTC
