### ISSUE TITLE
AKS Cluster update fails when both the OSMAgent feature is disabled and the Azure AAD secret gets updated 

### ISSUE THREAD

**Issue by djsly** [Azure/AKS#1636] opened 2020-05-28 04:20 UTC
**What happened**:
Cluster update failed
**What you expected to happen**:
Cluster update to succeed
**How to reproduce it (as minimally and precisely as possible)**:
'update at the same time your AAD Client Secret as well as disable OSMAgent feature and deleting the log Analytic Workspace`

note that the operation were done with terraform

1) LAW was deleted
2) AKS resource was updated with two change
 -- the addon_profile / oms_agent --> enabled = false
 -- the Aad profile sp secret was updated 

**Anything else we need to know?**:
```
 Error: waiting for update of RBAC AAD profile of Managed Cluster "cd4-k8s" (Resource Group "cd4-aks-rg"):, Code="GetLogAnalyticsWorkspaceError" Message="Unable to get log analytics workspace info. Resource ID: /subscriptions/<>/resourcegroups/<>/providers/microsoft.operationalinsights/workspaces/<>. Details: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.OperationalInsights/workspaces<>' under resource group 'cd4-aks-rg' was not found.\". For more details about how to create and use log analytics workspace,  please refer to: https://aka.ms/new-log-analytics"
**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:
```

**Comment by djsly** [comment] 2020-05-28 05:04
Turns out that the issue might be in Terraform + your SKD… terraform will run https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/containers/kubernetes_cluster_resource.go#L757
 
clusterClient.ResetAADProfile(ctx, id.ResourceGroup, id.Name, *props.AadProfile)
 
and this call to the cluster will return the missing LogAnalyticsWorkspaceNotFound error when the LAW gets deleted before.
 
The second call to the API to disable OMS_Agent would have been done after…
 
I’m not sure why there was a decision made to process the Azure AAD reset FIRST


`// RBAC profile updates need to be handled atomically before any call to createUpdate as a diff there will create a PropertyChangeNotAllowed error`

**Comment by palma21** [comment] 2020-08-06 18:40
Closing as per terraform root cause. Let us know if we would need to re-open.

**Closed by palma21** 2020-08-06 18:40 UTC
Labels: Needs Attention :wave:, Terraform, action-required
