### ISSUE TITLE
kubectl get nodes fails on new cluster with "TLS handshake timeout"

### ISSUE THREAD

**Issue by mkjsix** [Azure/AKS#124] opened 2018-01-15 17:26 UTC
_Note: this could correlate with issue #123 and there's an open Azure support request (n. 118010817421407) since 8th of January, but without any interesting answer to this problem._

We have built 3 AKS Kubernetes resource groups (k8s-nemo-dev-rg, k8s-nemo-staging-rg, k8s-nemo-test-rg) with 1 cluster each.

When we issue the command:

`$ az aks get-credentials --resource-group 'k8s-nemo-dev-rg' --name 'nemo-dev-cluster'`

and then:
`$ kubectl get nodes`
`Unable to connect to the server: net/http: TLS handshake timeout`

While if we do:
```
$ kubectl config use-context nemo-staging-cluster
$ kubectl get nodes
NAME                       STATUS    ROLES     AGE       VERSION
aks-nodepool1-23195585-0   Ready     agent     10h       v1.7.7
aks-nodepool1-23195585-1   Ready     agent     10h       v1.7.7
aks-nodepool1-23195585-2   Ready     agent     10h       v1.7.7
```
So it seems there is something broken when connecting to the nemo-dev-cluster. We tried deleting and recreating it several times without any success. Also nemo-test-cluster works without any problem.

**Comment by mkjsix** [comment] 2018-01-15 17:27
BTW, location is always `westeurope`

**Comment by Karreg** [comment] 2018-01-18 09:22
Same here. Is there someone managing the westeurope instance? The issue is pending for a month without resolution, where it seems other regions have been fixed.

**Comment by ternel** [comment] 2018-01-23 18:42
Same here. I've tried with K8s 1.7 and 1.8.
Create new resource on the *westeurope* zone -> create new cluster -> install-cli -> get-credentials -> launch `kubectl get nodes`
Result : TLS handshake timeout.

I'm trying to have fix with a tweet to @AzureSupport :
https://twitter.com/ternel/status/955871839305261057

**Comment by mkjsix** [comment] 2018-01-25 09:42
I deleted the RG yesterday and re-created it this morning, now kubectl is able to connect to cluster.

**Comment by necevil** [comment] 2018-06-06 18:10
@mkjsix @ternel @Karreg  I am starting to collect info on this issue in a question over on StackOverflow:
https://stackoverflow.com/questions/50726534/why-cant-kubectl-connect-to-the-azure-aks-server-managing-my-cluster-net-http

If you guys could answer a couple of these (here or above on SOF)
-------------

1. Have you had the TLS issue impact your Clusters more than once?
2. How long did it take before your Cluster was back up and could be connected to (what was the outage duration)?
3. Did it 'heal' itself / resolve / come back to life on it's own or did you have to post a support ticket — and wait for MS to fix it?
4. If support, how long was that ticket posted for before the problem was solved on your Cluster?
5. Did you notice anything weird with your CPU / Network IO dropping but your disk usage jumping higher? (see my metrics on stackoverflow)
6. Would you be in favor of allowing AKS preview customers to create higher Severity Help Tickets (For this specific issue only) regardless of their support plan in order to achieve a more timely solution?

Feel free to respond here or (as mentioned) hit StackOverflow and I will collect the responses.

**Comment by ternel** [comment] 2018-06-15 09:41
I needed a quick hosting, so I've used another provider to do something quick...
The MS support team responded quickly to my tweet, and they fixed the problem less than 24 hours after the creaation of the support ticket. (💛 the support!)
My project has been paused quickly after that, so I didn't try it more... 
Sorry, I havn't much more info :)

**Comment by necevil** [comment] 2018-06-15 17:58
@ternel if you were able to escalate your issue severity related to this issue free of charge would you have considered keeping your infrastructure on the Azure cloud?  

Put another way:
If MS committed to supporting AKS issues relating to the TLS handshake problem as if customers had paid for a high tier support would you have kept your infrastructure on Azure?

**Comment by ternel** [comment] 2018-06-18 12:45
@necevil AzureSupport on Twitter gave me a free token to create an issue, the MS team replied quickly (on Twitter, and quite quickly on the issue). The only problem was that I hadn't 24 hours for the project... and I've used another provider to deploy this time. I would have transfer everything back to Azure after, but the project has been paused.

**Comment by seanknox** [comment] 2018-08-07 15:12
Believe this has been fixed; please reopen if still an issue.

**Closed by seanknox** 2018-08-07 15:12 UTC
