### ISSUE TITLE
New way of accessing AKS dashboard after upgrade to 1.16.7

### ISSUE THREAD

**Issue by Karolwww** [Azure/AKS#1609] opened 2020-05-15 10:10 UTC
**What happened**: I made upgrade of Kubernetes cluster to 1.16.7 and now I cannot access dashboard using this command az aks browse --resource-group name--name name
directly. AKS is asking to provide Kubeconfig file or token.
![image](https://user-images.githubusercontent.com/31865101/82039264-04a65000-96a5-11ea-93d3-ccbc377ee54b.png)

 Previously it logged me automatically. Please advice me what is the best practise to access dashboard now?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"e2d9f8479783020904aba3de7499a49be6c75ebd", GitTreeState:"clean", BuildDate:"2020-04-09T02:31:15Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster (how many worker nodes are in the cluster?) 2 node cluster
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) 
- Others:

**Comment by tomkerkhove** [comment] 2020-05-15 11:47
Can be related to #1193 where it's not possible if it's RBAC enabled

**Comment by Karolwww** [comment] 2020-05-15 12:08
I have RBAC enable. So this is normal behaviour right?

**Comment by tomkerkhove** [comment] 2020-05-15 12:11
Yes, see #1193

**Comment by zodraz** [comment] 2020-05-19 20:15
The same issue is happening for me:

Anyway is the same issue than [1534](https://github.com/Azure/AKS/issues/1534).

We must wait for the AKS team to solve it...

**Comment by jluk** [comment] 2020-05-22 17:44
Thanks for this report, it seems this is a dupe so closing this as a dupe of #1534 which we are investigating at the moment. We'll share updates there.

**Closed by jluk** 2020-05-22 17:44 UTC
Labels: triage
