### ISSUE TITLE
AKS Auto healing cluster

### ISSUE THREAD

**Issue by sukrit007** [Azure/AKS#395] opened 2018-05-29 07:03 UTC
What is the process of recovering and replacing a bad node in the cluster?   

Also isn't AKS responsible to detect bad nodes and replace them?

In addition,  can we manually delete the node and expect AKS to replace it ?

*Context*: 
On quite a few occasions our node went bad in the cluster,  however, AKS did not replace it. Instead ,  AKS allowed scheduling on this node and none of the containers ever got provisioned.  In some instances, restart of node fixed the problem, while on others killing the node and changing capacity to desired value replaced the node.

**Comment by mactr0n** [comment] 2018-05-31 05:44
I'm pretty sure right now that there is no such thing as "auto healing".  AKS is more pre-alpha than preview. After a lot of broken clusters as a result of scaling and randomly failing nodes **I can just advice anyone reading this to stay away from AKS and use gke instead!!**
If you don't want to believe me search for "scale" or "NotReady" in the issues.

**Comment by kvolkovich-sc** [comment] 2018-06-08 15:46
@mactr0n, sad, but true. 😢

**Comment by seanmck** [comment] 2018-06-09 05:33
Duplicate of #131

**Closed by seanmck** 2018-06-09 05:33 UTC
