### ISSUE TITLE
Kubernetes 1.9.6 fails installing nginx using helm

### ISSUE THREAD

**Issue by andtii** [Azure/AKS#370] opened 2018-05-14 14:58 UTC
Created new Kubernetes cluster and then followed this guide to install nginx: https://docs.microsoft.com/en-us/azure/aks/ingress

But got the following errors

Error: release zooming-chipmunk failed: clusterroles.rbac.authorization.k8s.io "zooming-chipmunk-nginx-ingress" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["ingresses"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["ingresses"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["ingresses"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["events"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["events"], APIGroups:[""], Verbs:["patch"]} PolicyRule{Resources:["ingresses/status"], APIGroups:["extensions"], Verbs:["update"]}] user=&{system:serviceaccount:kube-system:default d562b0ed-5771-11e8-a6d4-361ad4a6bb3a [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]

**Comment by slack** [comment] 2018-05-14 16:11
Looks like the RBAC default changed upstream a few days ago. Until AKS supports RBAC (soon), install the chart with `--set rbac.create=false`.

**Comment by andtii** [comment] 2018-05-14 19:20
So i tested installing using this
`helm install stable/nginx-ingress --namespace kube-system --set rbac.create=false`
but still i got the issue

**Comment by stevebelton** [comment] 2018-05-15 10:07
Same issue for me, either fix works - however other helm charts work fine, only nginx has this issue/fix requirement.

**Comment by sauryadas** [comment] 2018-08-07 20:30
AKS clusters are secure by default by design. you can disable by using the disable rbac flag if needed. closing this issue as i believe folks know how to get this to work.
1) either disable rbac when creating a cluster OR 
2) deploy tiller with a default service account ...
kubectl delete deployment tiller-deploy --namespace kube-system
helm init --upgrade --service-account default
helm install stable/nginx-ingress --set rbac.create=false --set rbac.createRole=false --set rbac.createClusterRole=false

**Closed by sauryadas** 2018-08-07 20:30 UTC
Labels: docs
