### ISSUE TITLE
ImagePullBackoff error when creating a kubernetes cluster using yaml file #AzureContainerRegistry #ACR

### ISSUE THREAD

**Issue by badarosama** [Azure/AKS#476] opened 2018-06-25 08:18 UTC
I am using the following tutorial but using my own project and not the example code used in the tutorial.
https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-deploy-cluster

I created a yaml file and replaced the image source to following image: listingssdfregistry.azurecr.io/listingsdevfrontend:v1

Ran the following command to see the image in my azure registry:
**az acr repository list --name ListingsSDFRegistry --output table**
and it returns:
Result:
listingsdevfrontend

The image is uploaded to ACR. I did the "Configure ACR authentication" step.
When I run **kubectl apply -f listingsfrontend.yaml**
it successfully creates a deployment and a service as i specified in yaml file.

when i run: kubectl get pods:
it shows the **ImagePullBackOff** Status.

**Environment summary**
Using Windows, Powershell, ACR, AKS.

**Comment by aspnet4you** [comment] 2018-06-25 16:11
Is your image in Windows Container? If so, it would not work because Kubernetes nodes in Azure supports Linux cluster! See my post here-
https://stackoverflow.com/questions/50899387/failed-to-pull-image-myapidemodocker-azurecr-io-apidemov4-0-rpc-error-code/51016334#51016334

**Comment by badarosama** [comment] 2018-06-25 19:43
@aspnet4you thanks for the response. Can someone at Azure confirm that windows containers are not supported on kubernetes.

**Comment by andyzhangx** [comment] 2018-06-26 16:03
this issue should be duplicate of https://github.com/Azure/AKS/issues/442

**Comment by sauryadas** [comment] 2018-07-02 23:09
Windows containers are not supported on AKS yet. Please use acs-engine or ACI

**Comment by sauryadas** [comment] 2018-07-02 23:10
Closing this . Windows support is in the roadmap but no ETA

**Closed by sauryadas** 2018-07-02 23:10 UTC
Labels: roadmap
