### ISSUE TITLE
[Feature] AKS allows creation of NodePools in different Subnets (Azure CNI)

### ISSUE THREAD

**Issue by rhummelmose** [Azure/AKS#1338] opened 2019-11-28 09:45 UTC
As stated under limitations in the documentation, all node pools have to reside within the samee subnet.

The ask is to support assignment of a unique subnet per node pool in a cluster, but all shared from the same VNET.

**Comment by ferantivero** [comment] 2019-12-09 17:56
If I am not wrong this issue is more to start validating requests since users could specify multiple subnets when it isn't currently supported. 

But please let me mention that I love if this actually work instead of being a limitation. Already voted up for it in user voice 😸

**Comment by palma21** [comment] 2020-01-08 07:36
Do you have any details on around how networking breaks? 

What plugin are you using?

**Comment by jluk** [comment] 2020-01-14 18:29
@rhummelmose any details you can share on Jorge's question above?

**Comment by bhicks329** [comment] 2020-01-15 19:18
I’ve experimented with this today and I was able to create a 1.17 (SLB, Azure CNI)  AKS cluster with multiple node pools in different subnets with Istio over the top utilising Egress Gateways to control the flow of traffic. I haven’t attempted to place any UDRs on the subnets yet, but will do soon. I’m interested to know if this is going to be a supported scenario in the future and also what @rhummelmose has experienced in terms of breaking things.

**Comment by rhummelmose** [comment] 2020-01-15 22:13
Sorry guys I will have to stand up a cluster again and see if I can make it break. I will close the issue if I can't reproduce it.

**Comment by jluk** [comment] 2020-01-15 22:15
I've set this issue to track this open feature ask, so let's keep this one open but update prev comments to remove the issue mentioned if its been resolved and can't be reproduced.

@bhicks329 this is actively being worked on to be a supported scenario.

**Comment by marcostrullato** [comment] 2020-01-16 06:54
Hi @jluk I was with @rhummelmose when we experienced the issue. 
If Rasmus can't help, I will: I'm sure I can reproduce the issue.

**Comment by jluk** [comment] 2020-01-16 18:15
That would be great @marcostrullato if you have any repro steps we can investigate

**Comment by marcostrullato** [comment] 2020-01-17 08:22
Ok I will restore the cluster with the IaC I had, and I'll check if I can make it available to you. I'll come back early next week.

**Comment by marcostrullato** [comment] 2020-01-29 07:42
Apologize, I'm late. It's in our tasks list and will be done soon.

**Comment by marcostrullato** [comment] 2020-01-31 07:26
Hi everyone, so we have replicated the situation once again.
You can find the IaC code here: https://github.com/marcostrullato/aksiac
Off course I've cleaned it from any reference, so be aware it might be hard to run.

The source of this IaC is the akscommander code from @rhummelmose.

Is there anything else I can do?

Cheers

**Comment by jluk** [comment] 2020-01-31 16:18
Thanks @marcostrullato for the pointer to repro - to help us diagnose can you explain what the situation is that is not working? Is it a failure of communication between agent pools, failure during setup/provision, or something else?

**Comment by marcostrullato** [comment] 2020-02-03 08:44
Hi @jluk what is happening is a failure in communications. It's possible to reach one of the agent pool, where the other is inaccessible.  

Let me drive you through the IaC code.

This is the code to define the vnets (https://github.com/marcostrullato/aksiac/blob/master/aks-commander/terraform/base/main.tf)

```
resource "azurerm_virtual_network" "vnet" {
  name                = "${var.prefix}-vnet-${terraform.workspace}"
  location            = "${var.region}"
  resource_group_name = data.terraform_remote_state.remote_state_core.outputs.resource_group_name
  address_space       = ["${var.aks_vnet_address_space}"]
}

resource "azurerm_subnet" "subnet1" {
  name                 = "subnet1"
  resource_group_name  = "${azurerm_virtual_network.vnet.resource_group_name}"
  address_prefix       = "${var.aks_subnet_gpu_address_prefix}"
  virtual_network_name = "${azurerm_virtual_network.vnet.name}"
  service_endpoints    = ["Microsoft.ContainerRegistry","Microsoft.AzureCosmosDB","Microsoft.Storage","Microsoft.KeyVault"]
}

resource "azurerm_subnet" "subnet2" {
  name                 = "subnet2"
  resource_group_name  = "${azurerm_virtual_network.vnet.resource_group_name}"
  address_prefix       = "${var.aks_subnet_address_prefix}"
  virtual_network_name = "${azurerm_virtual_network.vnet.name}"
  service_endpoints    = ["Microsoft.ContainerRegistry","Microsoft.AzureCosmosDB","Microsoft.Storage","Microsoft.KeyVault"]
}
```

This is the code for the agentpools (https://github.com/marcostrullato/aksiac/blob/master/aks-commander/terraform/aks/main.tf) Bear in mind I've masked/hidden names and references.

```
  agent_pool_profile {
    name                = "cpupool"
    count               = 1
    min_count           = 1
    max_count           = 4
    vm_size             = "Standard_DS3_v2"
    os_type             = "Linux"
    os_disk_size_gb     = 30
    type                = "VirtualMachineScaleSets"
    availability_zones  = [ "1", "2", "3"]
    enable_auto_scaling = true
    vnet_subnet_id      = data.terraform_remote_state.remote_state_base.outputs.aks_cluster_subnet_id
  }

  agent_pool_profile {
    name                = "gpupool"
    count               = 1
    min_count           = 1
    max_count           = 10
    vm_size             = "Standard_NC6s_v2"
    os_type             = "Linux"
    os_disk_size_gb     = 30
    type                = "VirtualMachineScaleSets"
    availability_zones  = [ "1", "2", "3"]
    enable_auto_scaling = true
    vnet_subnet_id      =""
  }
```

With this configuration in our environment networking does not completely work.

@rhummelmose anything else to add?

Regards

**Comment by ams0** [comment] 2020-02-13 14:50
Able to reproduce: adding a second pool in another subnet works:
```
$> kg node
NAME                                STATUS   ROLES   AGE   VERSION
aks-base-15062426-vmss000000        Ready    agent   9h    v1.17.0
aks-base-15062426-vmss000001        Ready    agent   9h    v1.17.0
aks-extrapool-15062426-vmss000000   Ready    agent   8h    v1.17.0
aks-extrapool-15062426-vmss000001   Ready    agent   8h    v1.17.0
```

However:

AzureCNI:
Pods can talk to each other across nodepools, services work with pods both pools.

Kubernet:
Services can route traffic to pods sitting on any pool, however, pods on the non-default pool have no connectivity to the internet, and no connectivity to other pods in other pools or service IPs. However, by manually associating the RT in the MC_ group to the subnet of the extra nodepool makes it work.

So I think it just needs to be either documented or the `az aks nodepool` command should associate the RT automatically.

**Comment by ams0** [comment] 2020-02-13 15:07
Also, RT association survives scaling operations and adding another nodepool (but the latter requires additional association of course).

**Comment by jluk** [comment] 2020-02-13 18:31
Thanks for the input @ams0 this is in-line with what we're working on. The likely rollout is Azure CNI coverage first, Kubenet following that a bit later.

The general improvement for BYO RT for Kubenet is being worked on right now.

**Comment by scivm** [comment] 2020-02-17 17:18
@jluk will the improvements work with current GA 1.15.7 or only 1.17?

**Comment by djsly** [comment] 2020-02-17 21:59
@scivm  hopefully this is an AKS release that won't be required to be tied to an K8S version since it seems only Azure specific resources are required to be properly configured.

**Comment by jluk** [comment] 2020-02-18 17:23
Azure CNI subnet per pool should work for all the supported AKS k8s versions.

**Comment by scivm** [comment] 2020-02-18 18:40
Ok. We are using kubenet.

**Comment by jluk** [comment] 2020-02-18 22:20
No k8s dependency for Kubenet if the network and route table are created by AKS.

If you plan to BYO network & route table with Kubenet, this requires cloud provider changes in 1.15 or greater. This BYO RT proper support is going to land in AKS and is in-flight (https://github.com/Azure/AKS/issues/1424).

If you're on at least 1.15 you should be fine either way.

**Comment by ams0** [comment] 2020-02-19 08:39
I found a workaround using terraform, as shown here: https://github.com/ams0/terraform-templates/tree/master/aks-kubenet-multipool-multisubnet

The template create 2 pools in 2 subnets (kubenet+calico+custom vnet) and associate the default RT with the subnets.

**Comment by scivm** [comment] 2020-02-19 08:58
We also use Terraform. Their docs say only one subnet allowed [https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster_node_pool.html] for node pools so when https://github.com/Azure/AKS/issues/1424 goes out I want to get that fixed there.  NOTE: At this time the vnet_subnet_id must be the same for all node pools in the cluster

**Comment by ams0** [comment] 2020-02-19 09:01
Yeah well, there's no check enforcing the same `vnet_subnet_id`, as my script works just fine.

**Comment by mkosieradzki** [comment] 2020-02-21 16:01
I am using Azure CNI and private clusters and I am facing issues with omsagents on all nodes in one of the pools not beeing able to run correctly, is this a known issue?

**Comment by jluk** [comment] 2020-02-21 17:48
@mkosieradzki please open a support request so both AKS and OMS on-call can take a look at your cluster.

**Comment by mkosieradzki** [comment] 2020-02-24 14:36
@jluk done - SR: 120022426003546

**Comment by mkosieradzki** [comment] 2020-02-28 13:03
Hi @jluk 

Amit, who is the support engineer working at the case, has identified the problem and apparently calico is incompatible with multiple node pools (when using Azure CNI).

**Comment by jluk** [comment] 2020-02-28 17:03
Thanks @mkosieradzki I see engineering is engaged, will reach out to them to capture the latest.

**Comment by rhummelmose** [comment] 2020-03-02 09:29
We were also leveraging Calico when encountering the issue.

**Comment by jluk** [comment] 2020-03-11 15:49
Splitting this issue to be about subnet support for Azure CNI specifically. 

Please bring Kubenet issues to this separate issue regarding subnet per pool.
#1500

**Comment by antoniaklja** [comment] 2020-03-16 10:19
Is it possible to create an additional node pool in a separate VNet?

**Comment by asubmani** [comment] 2020-04-25 03:52
@mkosieradzkiand @jluk , would this issue with Calico occur even in a single subnet scenario. Today we have 1 (default) node pool. We plan to add more nodepools. We will use a single subnet for now (Azure CNI). Would this cause the Calico issue?

**Comment by asubmani** [comment] 2020-04-25 03:55
> Also, RT association survives scaling operations and adding another nodepool (but the latter requires additional association of course).

with `outgoingType =userdefinedRoutes` being almost ready for Azure CNI. Is the plan to leverage route tables applied to each subnet to make this feature (dedicated subnets per node pool) work?

**Comment by lestaat** [comment] 2020-07-27 16:22
> Is it possible or planned in the near future to create an additional node pool in a separate VNet?
> This might be a valid usecase for hub-spoke topology with async routing (network appliance).

I think it's valid use cause for nodepools on different address spaces. Any update on this inquiry?

**Comment by jluk** [comment] 2020-07-27 16:59
Dedicating a unique VNET per node pool is not on the roadmap today, but your input is valuable. For others with this need please share the scenarios!

**Comment by mkosieradzki** [comment] 2020-07-27 17:01
Istio egress gateways on a dedicated node pool to control egress traffic.

Workloads on a subnet with blocked outbound connectivity (NSG level).

**Comment by mkosieradzki** [comment] 2020-07-27 17:02
Vnet or subnet?

**Comment by bhicks329** [comment] 2020-07-27 19:00
We are running two address spaces on a vnet with different subnets for node pools (/22 for compute and istio-egress on a /24) and it works fine. The only thing to bear in mind is that when traffic is leaving the vnet address space it masquerades the traffic out of the node ip address and not the ip address of the egress gateway pod which is a real PITA.

**Comment by mkosieradzki** [comment] 2020-07-27 19:08
It's worth emphasizing the value added of istio-egress in separate subnet:
subnet with node pool with istio-egress can have very permissive NSG, while workload subnet with rest of the workers can have very restrictive NSG.

This way the only way out is trough the egress gateway which provides full control over outbound traffic, with layer 7 traffic filtering and micro-segmentation.

**Comment by palma21** [comment] 2020-07-27 20:35
@bhicks329 you can configure the IP Masq agent to suite your needs if you want. We'll be publishing a doc on that this week or the next.

To clarify, as per the state of this issue. Creating a nodepool per subnet with Azure CNI is already supported in preview today

**Comment by mkosieradzki** [comment] 2020-07-27 20:39
@palma21 but it doesn't work with calico... and Azure NPM is a sad joke :-( . I wish it worked... But every time I try to use it, it still is non-conformant with k8s Network Policy and swamped with bugs. To be clear, terrible quality of Azure NPM is the only reason I want to use Calico.

**Comment by ezYakaEagle442** [comment] 2020-11-11 16:42
Hi  @palma21  any update on this issue please ?

**Comment by paulgmiller** [comment] 2020-11-11 17:47
Seems like the main concern here is calico? We think we'll be taking a new version of calico  in the next couple of months. Let me see if we can test multiple node pools at that time.

**Comment by san360** [comment] 2020-11-11 20:50
Any plans on implementing this?

**Comment by djsly** [comment] 2020-11-27 18:40
FYI, I was able to get multi subnets working with Azure CNI + Calico + Window/Linux Node pools. 

The only missing piece was one IPPool resource per extra subnets that you introduce.

**Comment by NickLarsenNZ** [comment] 2021-02-01 03:24
> FYI, I was able to get multi subnets working with Azure CNI + Calico + Window/Linux Node pools. 
> 
> The only missing piece was one [IPPool](https://docs.projectcalico.org/reference/resources/ippool) resource per extra subnets that you introduce. 

Are you able to describe how you did it? We're looking at AKS (I'm familiar with EKS) and I'd like to have worker pools on different subnets for identifying traffic sources on legacy firewalls.

I was hoping to use Terraform but the provider doesn't suggest multiple subnets are supported yet (I assume because of that being a preview feature)

**Comment by paulgmiller** [comment] 2021-02-02 19:28
Sharing a preview of the updated limitations that wer're changing [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Faks%2Fuse-multiple-node-pools%23add-a-node-pool-with-a-unique-subnet-preview&data=04%7C01%7CPaul.Miller%40microsoft.com%7Cfa007e6406f2455687f608d8c703be24%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637478166210844637%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Aw3U7FW93vqqhiJSSh9pEhMkCJSNPDXXI%2Fd0O2mV99Y%3D&reserved=0)

* All subnets assigned to nodepools must belong to the same virtual network.
( System pods must have access to all nodes/pods in the cluster to provide critical functionality such as DNS resolution and tunneling kubectl logs/exec/port-forward proxy.
* If you expand your VNET after creating the cluster you must reconcile your cluster (perform any managed clster operation but agentpool operations don't count) before adding a subnet outside the original cidr. AKS will error out on this now though we originally allowed it. If you don't know how to reconcile your cluster file a support ticket.
* Calico Network Policy has not been thoroughly tested and is not supported. At the very least in azure cni with calico 3.8 it does not create a IPPool per agent pool.
* Azure Network Policy has not been thoroughly tested. Plase file issues if you encounter them.
* Kube-proxy expects a single contiguous cidr and uses it this for three optmizations. See this K.E.P. and --cluster-cidr here for details. In azure cni your first agentpool's subnet will be given to kube-proxy.

**Comment by jyee021** [comment] 2021-03-09 23:15
Is there an anticipate GA date for this feature?

**Comment by ondrejhlavacek** [comment] 2021-03-15 14:41
I have found out that Kubernetes Network Policies do not work between node pools in different subnets. We're running AKS with  Azure CNI and Azure networking policy. Is this related to this issue or should I create a support ticket?

**Comment by paulgmiller** [comment] 2021-04-05 21:46
Our guess is that this is related because of kube-proxy --cluster-cidr: 
    "When configured, traffic sent to a Service cluster IP from outside this range will be masqueraded"
    
    We're still looking for this KEP to fix this and might try and get more involved.  https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2450-Remove-knowledge-of-pod-cluster-CIDR-from-iptables-rules

**Comment by jack4it** [comment] 2021-05-03 18:59
Pods in a pool with a unique subnet (outside `--cluster-cidr`) can't reach the internet but can reach other pods in other pools. Pods with `hostNetowrk: true` work fine. Does anyone see this behavior? It's consistent across multi clusters in my test.

**Comment by noahbirrer-8451** [comment] 2021-06-28 18:19
> Dedicating a unique VNET per node pool is not on the roadmap today, but your input is valuable. For others with this need please share the scenarios!

@jluk We are in need of this feature. Our scenario is described below.

This feature would allow us to better allocate and plan IP space that is shared with our on-prem network via VNET peering.  We use Azure CNI and our current cluster strategy is to use a shared cluster for all workloads (those that require on-prem connectivity and those that do not). We would like to move the distinction of whether or not a workload can reach on-prem from a peered VNET from the cluster level to the node pool level. 

Today, we are limited to using one VNET per cluster since nodepools cannot be created on separate VNETs. One app that requires on-prem connectivity dictates that all workloads then unnecessarily consume peered IP space, which can be costly with CNI. Ideally, workloads that do not require on-prem connectivity could be run separately on subnets on private/unpeered nodepools, which would reduce the amount of on-prem network space that is consumed.

**Comment by mapdegree** [comment] 2021-07-05 06:29
We need to be able to scale out AKS deployment with the ability to add additional VNETs and subnets after initial deployment. Many organisations are just not 'buying' that migration to a larger VNET / subnet is the only option.
Could you please let us know when it will become GA?

**Comment by ArgonQQ** [comment] 2021-07-05 06:55
I totally agree with @mapdegree . From the start of a project you already have defined your limitations in terms of pod count per Subnet. By default its relatively easy to scale a VNET (or add a CIDR range) but its currently not possible to extend a subnet if any resources are attached to it. 

Therefore if you run out of IP-Addresses it is required to completely remove the subnet and create a bigger one (if the VNET is properly sized).  

From my POV this is not how Microsoft describes Azure because currently there is no "infinite scale" available because you always have CIDR limitations except you have reserved all private CIDR ranges and you're not peering anywhere.

**Comment by paulgmiller** [comment] 2021-07-14 23:57
To give an update here. Kube-proxy currently expects one cluster-cidr and nats and does other things if you're not inside it.

This is a known issue
https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2450-Remove-knowledge-of-pod-cluster-CIDR-from-iptables-rules 

But there is already support to use the nodes pod cidr isntead of cluster 
https://github.com/kubernetes/kubernetes/pull/88935 

So our current thought is to use the update the node's podcidr with a deamonset or controller. I have a prototype but we're still a month or more from delivering it. So this is all just a proposal for now and may change. 

You will still have to all be in the same vnet.

**Comment by ElkRom** [comment] 2021-11-09 20:50
Hi guys, do you have any updates regarding this issue?

**Comment by asubmani** [comment] 2021-12-17 15:49
Wouldn't this introduce more problems?
### CURRENT SCENARIO:
1) Multiple user node pools (no taints tolerations). AKS/k8s schedules pods
2) Should be easy to lock pod to pod communication by NS using calico/cilium etc.
3) control all intra AKS using network policies and Ingress/Egress from the cluster using 3rd party NVA's.

### FUTURE SCENARIO (if each nodepol has it's own subnet)
1) K8s reschedules a pod from Node in NP-A to another node in NP-B

> now the pod will have a different IP range, which might make k8s network policies hard to manage)
> each time this happens the NVA needs updating (assuming you control which subnets egress out)
> If above is true then each NP/Subnet may need some mechanism to **guarantee only certain pods  get scheduled on a specific NP** to guarantee network access.

2) Overall k8's ability to schedule pods to node pools will be restricted.

**Comment by swgriffith** [comment] 2022-01-25 14:43
>

**Comment by swgriffith** [comment] 2022-01-26 18:51
Any update on this? It seems that the kube-proxy pod cidr issue has been addressed in upstream Kubernetes.

https://github.com/kubernetes/enhancements/issues/2450

**Comment by andriktr** [comment] 2022-03-02 12:09
Hey,
When this feature will become GA?
Thanks.

**Comment by IvanJosipovic** [comment] 2022-03-30 18:11
My company is also interested in this feature. Will Azure Network Policy be supported when this goes GA?

**Comment by danielalvesleandro** [comment] 2022-04-04 15:16
Hi guys, any news regarding GA for this feature? Will it support Azure Network Policies when GA? Thanks.

**Comment by wedaly** [comment] 2022-05-16 19:57
> To give an update here. Kube-proxy currently expects one cluster-cidr and nats and does other things if you're not inside it.
> 
> This is a known issue https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2450-Remove-knowledge-of-pod-cluster-CIDR-from-iptables-rules
> 

> Any update on this? It seems that the kube-proxy pod cidr issue has been addressed in upstream Kubernetes.
> 
> [kubernetes/enhancements#2450](https://github.com/kubernetes/enhancements/issues/2450)

Hi all, wanted to give a quick update on the kube-proxy cluster CIDR issue. As of [AKS release 2022-05-01](https://github.com/Azure/AKS/releases/tag/2022-05-01), AKS now configures kube-proxy to detect local traffic using the network interface name prefix instead of cluster CIDR. This should preserve the IP addresses of traffic from secondary subnets so that network policies are applied correctly. Please note that the change applies only to Kubernetes versions 1.23.3 and later.

**Comment by ondrejhlavacek** [comment] 2022-05-17 08:51
Does this mean that Network Policies will start working across node pools in different subnets?

**Comment by wedaly** [comment] 2022-05-17 16:19
> Does this mean that Network Policies will start working across node pools in different subnets?

Yes, network policies will work across different subnets.

**Closed** 2022-06-03 06:00 UTC
Labels: enhancement, feature-request, networking/azcni, resolution/shipped
