### ISSUE TITLE
run-kube-svc-redirect.sh crashes due to shell script syntax error

### ISSUE THREAD

**Issue by azureissues** [Azure/AKS#1179] opened 2019-08-29 19:34 UTC
**What happened**:

once upgraded to AKS v1.13.10, `run-kube-svc-redirect.sh` crashes with a bash error: `/lib/redirector/run-kube-svc-redirect.sh: line 166: //: Is a directory` on certain node of the cluster.

Notice line 166 below. Bash comments should start with `#` rather than `//`
```bash
156 function placeCustomChainInChain()
157 {
158    local chainName="$1"
159    local existingRules=""
160
161    existingRules="$(iptables -w -t nat -S "$chainName" | grep "$gCustomChainName" || echo -n "" )"
162    if [ -z "$existingRules" ]; then
163       log_inf "Rule did not pre exist in $chainName"
164    else
165       while read -r currentRule; do
166           // Example: -A prerouting -p tcp -m tcp --dport 8080 -j aks-custom-hcp
167           truncRule=$(echo $currentRule | cut -d ' ' -f2-)
168           delCmd=$(expr "iptables -w -t nat -D $truncRule")
169           log_inf "Found invalid rule:$currentRule. it will be deleted"
170           resp=$($delCmd)
171       done <<< "$existingRules"
172    fi
173
174    log_inf "Adding jump rule (at position 1) for $gCustomChainName in chain:$chainName"
175    iptables -w -t nat -I "$chainName" 1 -j "$gCustomChainName"
176
177    log_inf "Current rules in chain:$chainName"
178    printChain "$chainName"
179 }

```

This shell script is ran by `redirector` container from the `kube-svc-redirect` pod in the `kube-system` namespace. 

Once this is observed, pods running on that particular node is no longer able to communicate with the API server.

**What you expected to happen**:
I expect things to not crash

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade to AKS v1.13.10

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jnoller** [comment] 2019-08-29 19:39
duplicate of #1176

**Closed by jnoller** 2019-08-29 19:39 UTC
Labels: triage

**Comment by slynickel** [comment] 2019-08-29 19:40
@jnoller how so? It would appear this error message is different. Or is it just another known issue with the kube-svc-redirect changes?

**Comment by jnoller** [comment] 2019-08-29 19:43
The errors/crash were / are caused by a regression on our side we are repairing @slynickel
