### ISSUE TITLE
Viewing an AKS Deployment 'Changelogs' in the Azure Portal requires listClusterAdmin credential

### ISSUE THREAD

**Issue by jimmyjamesbaldwin** [Azure/AKS#2166] opened 2021-03-08 10:31 UTC
**What happened**:

In the Azure Portal in the AKS resource viewer, attempting to use view the Deployment "Changelog" without listerClusterAdmin permissions fails for any namespaces, throwing the error in the screenshot below:

_'Changelogs' option fails wanting listClusterAdmin_
![changelogs option fails wanting listClusterAdmin](https://github.com/jimmyjamesbaldwin/Kind-k8s-cluster-YACMT/blob/main/screenshots/denied.PNG?raw=true)
_Other options work fine with just read permissions_
![other options work fine with just read permissions](https://github.com/jimmyjamesbaldwin/Kind-k8s-cluster-YACMT/blob/main/screenshots/deploymentyaml.PNG?raw=true)

Our users typically have readonly permissions to anything but Dev and all the other options in the AKS resource view work correctly (viewing namespaces, looking at deployment yaml) with readonly permissions, but the Changelog option seems to want admin rights which feels over-scoped and this feature could be implemented with just read permissions. 

**What you expected to happen**:
I expect the Changelogs option to work without requiring listClusterAdmin. This feature should work with just Azure Kubernetes Service Cluster User Role.

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to view the 'Changelogs' option without listClusterAdmin/AKS Cluster Admin Role

**Anything else we need to know?**:
A support case with MS has been raised and this has been acknowledged as a bug: 2102190050005914. Support rep recommended opening a ticket here to engage the product engineering team.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.11

**Comment by ammohant** [comment] 2021-03-30 01:19
@rachitb777  -  Can you pls help close this one ?

**Comment by abarqawi** [comment] 2021-04-07 15:08
@ammohant  @rachitb777  can you help please ?

**Comment by rachitb777** [comment] 2021-04-21 11:32
The changelog view needs to read annotations from deployments to find out the git commit SHA and other pertaining details. Without listClusterAdmin credentials we are not able to get the deployment data to read the annotations.

**Comment by abarqawi** [comment] 2021-04-21 11:44
thanks @rachitb777  so its by design , @jimmyjamesbaldwin  are you ok with this ?

**Comment by jimmyjamesbaldwin** [comment] 2021-04-22 15:48
Thanks @rachitb777 and @abarqawi - I'm still slightly confused, are these just the annotations in the annotations block of the Deployment yaml spec that need to be read for the Change Logs feature to work? If so I'm still unclear why this can't be done with the listClusterUserCredential API call rather than listerClusterAdminCredential?

**Comment by palma21** [comment] 2021-09-15 16:40
It should use listClusterUserCredential if it's an AAD enabled cluster (non AAD ones just have admin). Is that the case here?

**Comment by jimmyjamesbaldwin** [comment] 2021-09-15 21:43
@palma21 thats correct - IMO shouldn't be any need for the admin api credential call 🙂

**Comment by phealy** [comment] 2021-09-29 16:19
Tagging @jenetlan @chandraneel again. Will also forward offline.

**Comment by chandraneel** [comment] 2021-09-29 16:34
Taking a look

**Comment by jimmyjamesbaldwin** [comment] 2021-11-28 20:02
Not stale...

**Comment by jimmyjamesbaldwin** [comment] 2022-01-28 09:33
Not stale...

**Comment by jimmyjamesbaldwin** [comment] 2022-03-29 14:01
Not stale...

**Comment by jimmyjamesbaldwin** [comment] 2022-07-05 14:58
Not stale.....................................................

**Comment by raghulmsft** [comment] 2022-08-30 19:31
Thanks for bring it to our attention. I am a PM with the AKS portal team and have passed it on to our team. Will share updates as we have them.

**Comment by jimmyjamesbaldwin** [comment] 2022-11-29 15:28
Hi @raghulmsft , is there any update on this issue or can it be closed if remediated?

Thanks!

**Comment by raghulmsft** [comment] 2022-12-14 18:27
@jimmyjamesbaldwin, we are deprecating the "changelogs" blade because the underlying "deployment center" experience that was populating this view is also getting deprecated. I agree with you on the credentials side of things and our plan right now is to remove the blade by early next year in favor of the new experience "automated deployment" which will not have a "changelogs" companian.

**Closed by raghulmsft** 2022-12-14 18:27 UTC
Labels: azure/portal, feature-request, Feedback
