### ISSUE TITLE
container to container communication through service

### ISSUE THREAD

**Issue by elkh510** [Azure/AKS#2056] opened 2021-01-13 16:08 UTC
**What happened**:
if we have a pod that has two containers (like a client and a server) and the client tries to connect to the server through the service, the client will get an error and won't be able to connect. if the client tries to connect to the server via localhost, everything works as expected.
the bug has been reproduced on aks v1.19.3.
on aks  v1.18.10 the error is not reproducible

**What you expected to happen**:
if we have a pod that has two containers (like a client and a server) and the client tries to connect to the server through the service, the client can success connect to server.

**How to reproduce it (as minimally and precisely as possible)**:
deploy test deployment. can be found at this [link](https://github.com/elkh510/examples/blob/main/test_deployment.yaml)
from client try to curl(telnet) server  via service

**Anything else we need to know?**:
maybe related to
https://github.com/kubernetes/kubernetes/issues/94754
https://github.com/kubernetes/kubernetes/issues/95409
https://bugs.launchpad.net/ubuntu/+source/linux-meta-hwe-5.4/+bug/1899690
**Environment**:
- Kubernetes version v1.19.3:
- Size of cluster 10

**Comment by joaguas** [comment] 2021-02-04 17:42
Hi @elkh510 ,
Is this issue still happening? I'm unable to reproduce it either with azure cni or kubenet.

![image](https://user-images.githubusercontent.com/62766211/106932614-d9223480-670f-11eb-8c1c-c14c3fb0418a.png)

If this is still happening can you confirm that name resolution is working for the service (assuming you're not using svc ip) and that iptables rules are correctly translating service to pod?

`IP=zzz.zzz.zzz.zzz`
`ID=$(iptables-save | grep $IP | grep SVC | awk -F '-' '{print $NF}')`
`for SEP in $(iptables-save | grep $ID | grep SEP | awk -F '-' '{print $NF}'); do iptables-save | grep "/32"| grep $SEP; done`

**Comment by elkh510** [comment] 2021-02-09 10:20
hi @joaguas 
>Is this issue still happening?

yes

>can you confirm that name resolution is working for the service

yes(screen below)
![image](https://user-images.githubusercontent.com/60512579/107349445-e608a480-6ad0-11eb-97c3-4686f5465153.png)

>iptables rules are correctly translating service to pod?

yes, as i understand
![image](https://user-images.githubusercontent.com/60512579/107349681-2bc56d00-6ad1-11eb-8f8a-84eed2a57ab0.png)

**Comment by eriksywu** [comment] 2021-02-12 18:18
Hi @elkh510

Based on your pod ip I assume this is a kubenet cluster? Do you know how old the cluster is? There was a typo we fixed and rolled out in early Jan that was preventing proper network hairpinning.
https://github.com/Azure/AgentBaker/pull/503/files

Check /etc/cni/net.d/10-containerd.conflist. If the typo is there (promisMode, should be promiscMode) then you can do a node image upgrade to pick up the latest image with the fix.

**Comment by elkh510** [comment] 2021-02-15 08:34
hi @eriksywu 
yes, update to 1.19.7 fixed the problem.

**Comment by xuto2** [comment] 2021-02-17 00:20
closing since the fix is rolled out

**Closed** 2021-02-17 00:20 UTC
Labels: networking/kubenet

**Comment by xuto2** [comment] 2021-02-17 02:23
to clarify - this is not related to kubernetes/kubernetes#94754
