### ISSUE TITLE
Helm deploy fails on pre-install hooks (AKS only)

### ISSUE THREAD

**Issue by msiegenthaler** [Azure/AKS#455] opened 2018-06-20 14:46 UTC
Our helm deployments fail to install on the AKS cluster. The same charts work fine on other clusters including the ACS cluster.

Reproduction:
```
[ms@ ~] helm install --name notebook stable/tensorflow-notebook
Error: watch closed before Until timeout
```
(I chose the tensorflow-notebook chart for the reproduction because it's not huge and easily available. The same thing also happens with other charts)

Tiller log:
```
+ tiller-deploy-7ccf99cd64-5745j › tiller
tiller-deploy-7ccf99cd64-5745j tiller [main] 2018/06/20 14:35:43 Starting Tiller v2.9.1 (tls=false)
tiller-deploy-7ccf99cd64-5745j tiller [main] 2018/06/20 14:35:43 GRPC listening on :44134
tiller-deploy-7ccf99cd64-5745j tiller [main] 2018/06/20 14:35:43 Probes listening on :44135
tiller-deploy-7ccf99cd64-5745j tiller [main] 2018/06/20 14:35:43 Storage driver is ConfigMap
tiller-deploy-7ccf99cd64-5745j tiller [main] 2018/06/20 14:35:43 Max history per release is 0
tiller-deploy-7ccf99cd64-5745j tiller [tiller] 2018/06/20 14:35:53 preparing install for notebook
tiller-deploy-7ccf99cd64-5745j tiller [storage] 2018/06/20 14:35:53 getting release history for "notebook"
tiller-deploy-7ccf99cd64-5745j tiller [tiller] 2018/06/20 14:35:53 rendering tensorflow-notebook chart using values
tiller-deploy-7ccf99cd64-5745j tiller [tiller] 2018/06/20 14:35:54 performing install for notebook
tiller-deploy-7ccf99cd64-5745j tiller [tiller] 2018/06/20 14:35:54 executing 1 pre-install hooks for notebook
tiller-deploy-7ccf99cd64-5745j tiller [kube] 2018/06/20 14:35:54 building resources from manifest
tiller-deploy-7ccf99cd64-5745j tiller [kube] 2018/06/20 14:35:54 creating 1 resource(s)
tiller-deploy-7ccf99cd64-5745j tiller [kube] 2018/06/20 14:36:54 Watching for changes to Secret notebook-tensorflow-notebook with timeout of 5m0s
tiller-deploy-7ccf99cd64-5745j tiller [tiller] 2018/06/20 14:36:54 warning: Release notebook pre-install tensorflow-notebook/templates/secrets.yaml could not complete: watch closed before Until timeout
tiller-deploy-7ccf99cd64-5745j tiller [tiller] 2018/06/20 14:36:54 failed install perform step: watch closed before Until timeout
```

The secret did get created during this:
```
[ms@ ~] kubectl get secret
NAME                           TYPE                                  DATA      AGE
default-token-vvtqq            kubernetes.io/service-account-token   3         3h
notebook-tensorflow-notebook   Opaque                                1         6m
```

We reproduced the issue on three separate AKS clusters, all on kubernetes 1.9.6 in west and north europe. We tested with helm 2.7.0, 2.9.0, 2.9.1.
As said above, the same works without issues in our ACS cluster and on multiple terraform based ones (Kubernetes versions 1.7.7 (ACS), 1.8.5, 1.8.4).

Charts without a pre-install hook (or maybe other hooks, didn't isolate that) deploy without any issue on the AKS cluster. The cluster appears to be fine, calls via kubectl work, kubectl port-forward also works, helm list works.

**Comment by andrew-dinunzio** [comment] 2018-06-20 17:27
Same issue (linked above) while `helm install`ing Istio. In my case it was failing on post-install hooks. Could this be related to AdmissionControllers?

**Comment by twendt** [comment] 2018-06-21 12:05
This is related to #408 

We had our clusters patched yesterday and now helm pre-install hooks are working again.

**Comment by andrew-dinunzio** [comment] 2018-06-21 14:12
Just tried on centralus cluster and it still fails

**Comment by rite2nikhil** [comment] 2018-06-22 04:49
All (in all regions) new cluster creates should be patched with the fix. thanks for your patience, please report if you still see issues. Existing clusters will eventually get patched.

**Comment by ChingizMard** [comment] 2018-06-22 14:56
I happen to have the similar issue on AKS with post-install hooks but while installing `cockroachdb`. Seems like an exactly same issue as @andrew-dinunzio  is having. Here are the logs:
```
[tiller] 2018/06/22 14:50:34 executing 2 post-install hooks for cockroachdb
[kube] 2018/06/22 14:50:34 building resources from manifest
[kube] 2018/06/22 14:50:34 creating 1 resource(s)
[kube] 2018/06/22 14:50:34 Watching for changes to Job cockroachdb-cockroachdb-init with timeout of 5m0s
[kube] 2018/06/22 14:50:34 Add/Modify event for cockroachdb-cockroachdb-init: ADDED
[kube] 2018/06/22 14:50:34 cockroachdb-cockroachdb-init: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
[kube] 2018/06/22 14:50:34 Add/Modify event for cockroachdb-cockroachdb-init: MODIFIED
[kube] 2018/06/22 14:50:34 cockroachdb-cockroachdb-init: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
[tiller] 2018/06/22 14:51:34 warning: Release cockroachdb post-install cockroachdb/templates/cluster-init.yaml could not complete: watch closed before Until timeout
[tiller] 2018/06/22 14:51:34 warning: Release "cockroachdb" failed post-install: watch closed before Until timeout
[storage] 2018/06/22 14:51:34 updating release "cockroachdb.v1"
[tiller] 2018/06/22 14:51:34 failed install perform step: watch closed before Until timeout
```

**Comment by rite2nikhil** [comment] 2018-06-22 16:13
This is caused by the idle timeout on watches, currently this is expected to be ~60s, aware of this issue, partial fix rolling out next week, working at high priority on a full fix.

Thanks for reporting the issue.

**Comment by msiegenthaler** [comment] 2018-06-22 16:19
Works for me now after upgrading the cluster to 1.10.3

**Comment by rlucioni** [comment] 2018-06-22 18:23
The 60-second idle timeout on watches is also preventing our post-install hooks from succeeding. Our cluster is running 1.9.6, will attempt to reproduce with a 1.10.3 cluster.

**Comment by andrew-dinunzio** [comment] 2018-06-22 18:28
We tested with 1.10.3 and it still fails. It's a configuration (--min-request-timeout I think) of the api-server that's responsible for fixing this. It defaults to 30 minutes but is 1 minute on AKS it seems.

**Comment by andrew-dinunzio** [comment] 2018-06-25 13:49
There's another issue with Istio that might be related to this watch timeout issue. Looking at the logs for the mixer with `kubectl logs -n istio-system istio-telemetry-54b5bf4847-l9qqt mixer`, I see the following logs:
```
2018-06-25T10:17:50.439694Z     error   istio.io/istio/mixer/pkg/config/crd/store.go:169: Failed to watch *unstructured.Unstructured: the server was unable to return a response in the time allotted, but may still be processing the request (get kuberneteses.config.istio.io)
```

The container never crashes - it just repeats this error repeatedly. Does not happen on minikube.

**Comment by rite2nikhil** [comment] 2018-07-05 02:02
We have rolled out fixes, please provide feedback if there are issues with new cluster creates

**Comment by StianOvrevage** [comment] 2018-07-05 11:03
We had problems with 1.10.3 and the prometheus-operator chart. Will try again today on a new cluster.

https://github.com/coreos/prometheus-operator/issues/1514#issuecomment-402685553

**Comment by andrew-dinunzio** [comment] 2018-07-05 13:01
Is this fix only for 1.10.3 clusters? We still have the watch timeout issue on 1.9.6 for a default installation of Istio (rbac enabled in AKS)

**Comment by StianOvrevage** [comment] 2018-07-05 13:06
Created a new AKS cluster now and try to install prometheus-operator:

```
$ helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

$ helm install coreos/prometheus-operator --name prometheus-operator --set serviceMonitorsSelector="{}" --debug
[debug] Created tunnel using local port: '4917'

[debug] SERVER: "127.0.0.1:4917"

[debug] Original chart version: ""
[debug] Fetched coreos/prometheus-operator to /root/.helm/cache/archive/prometheus-operator-0.0.27.tgz

[debug] CHART PATH: /root/.helm/cache/archive/prometheus-operator-0.0.27.tgz

Error: watch closed before Until timeout
```

**Comment by blackbaud-brandonstirnaman** [comment] 2018-07-08 16:29
Can confirm @StianOvrevage's comment. Cluster created yesterday (1.10.3) fails the same.

```⟩ helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring --debug
[debug] Created tunnel using local port: '59464'

[debug] SERVER: "localhost:59464"

[debug] Original chart version: ""
[debug] Fetched coreos/prometheus-operator to /Users/brandon.stirnaman/.helm/cache/archive/prometheus-operator-0.0.27.tgz

[debug] CHART PATH: /Users/brandon.stirnaman/.helm/cache/archive/prometheus-operator-0.0.27.tgz

Error: watch closed before Until timeout
```

**Comment by StianOvrevage** [comment] 2018-07-16 09:53
Looks like this might be working on 1.10.5:

```
$ helm install coreos/prometheus-operator --name prometheus-operator
NAME:   prometheus-operator
LAST DEPLOYED: Mon Jul 16 11:48:55 2018
NAMESPACE: default
STATUS: DEPLOYED
```

**Comment by necevil** [comment] 2018-07-18 16:48
I can confirm that (as of today) in my case upgrading to 1.10.5 via the docs over here (https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster) fixed my issue and I was able to install prometheus via helm.

**Comment by StianOvrevage** [comment] 2018-07-30 12:17
This is now failing again on 1.10.5:

```
helm install coreos/prometheus-operator --name prometheus-operator
Error: watch closed before Until timeout
```

:(

**Comment by rite2nikhil** [comment] 2018-07-30 14:16
The fix has not rolled out yet as it did not make it to the realease last week. apologies for the delay, I expect it to start rollout today and rollout to all production regions by end. To expedite patch mailto:aks-gh-feedback@service.microsoft.com
with sub id, resource group and resource id(cluster name)

**Comment by yanivoliver** [comment] 2018-08-05 12:59
@rite2nikhil - The issue is still occurring in a newly created AKS cluster.

```
[kube] 2018/08/05 12:55:05 Starting delete for "cpanel" Job
[kube] 2018/08/05 12:55:05 Using reaper for deleting "cpanel"
[kube] 2018/08/05 12:55:05 jobs.batch "cpanel" not found
[kube] 2018/08/05 12:55:05 building resources from manifest
[kube] 2018/08/05 12:55:05 creating 1 resource(s)
[kube] 2018/08/05 12:55:05 Watching for changes to Job cpanel with timeout of 0s
[kube] 2018/08/05 12:55:05 Add/Modify event for cpanel: ADDED
[kube] 2018/08/05 12:55:05 cpanel: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
[tiller] 2018/08/05 12:56:05 warning: Release excited-panther post-install data-bootstrap/charts/deployment/cpanel-bootstrap.yaml could not complete: watch closed before Until timeout
[tiller] 2018/08/05 12:56:05 warning: Release "excited-panther" failed post-install: watch closed before Until timeout
[storage] 2018/08/05 12:56:05 updating release "excited-panther.v1"
[tiller] 2018/08/05 12:56:05 failed install perform step: watch closed before Until timeout
```

**Comment by yarinm** [comment] 2018-08-05 13:03
This happens to me as well with a a newly created cluster.

**Comment by ckanljung** [comment] 2018-08-06 11:05
This still happens for me with the post-install stage of prometheus-operator on a newly created cluster. I've tested with both version 1.9.6 and 1.10.6.  Worked on a newly created cluster last week though.

**Comment by rite2nikhil** [comment] 2018-08-07 20:47
The fix for helm/tiller will get rolled out by end of next week, so if this is urgent Please send your cluster info @ aks-gh-feedback@service.microsoft.com

**Comment by StianOvrevage** [comment] 2018-08-20 09:43
This still fails on 1.11.1 on a newly created cluster today @rite2nikhil . Does this mean the fix is not fixing it or that this is several different problems or that it does not apply to new clusters yet?

Also agree with @twendt . Being able to see which version gets deployed and maybe a changelog and/or status of known bugs would be nice.

**Comment by tkaepp** [comment] 2018-08-22 12:52
@StianOvrevage I had the same problem with prometheus-operator. I was able to deploy it successfully with the --debug parameter. Without the parameter it failed after 60s. With the parameter it completed after ~10-15s

Cluster was created yesterday with K8s Version 1.11.1

**Comment by andrew-dinunzio** [comment] 2018-08-22 13:03
@tkaepp is it possible that t succeeded the second time because the image was already cached on the nodes? If kubernetes does not have to pull the images, some helm installs work (because they're able to complete before the 1 minute timeout). This is actually the basis of a workaround I had to helm install Istio, where I deploy a DaemonSet with the hyperkube image before installing - that way the postinstall jobs can complete much more quickly (and within the 1 minute timeout period)

**Comment by plc402** [comment] 2018-08-22 14:18
Totaly agree with you @StianOvrevage .
I just updated my cluster to 1.11.1 and did a test, and I'm still not able to do my helm upgrade because of 
"Error: UPGRADE FAILED: watch closed before Until timeout"

**Comment by plc402** [comment] 2018-08-23 15:09
@jskulavik 
Thank, I did that yesterday, but right now, they answered me the following : 
"With Helm being a 3rd party product I am not sure of it’s behavior, but my best guess is that the watch has a timeout of 1m or 60s and it timed out before the operation completed on the Azure side, but the error it gives is misleading as the upgrade did continue and complete on the Azure side."

**Comment by jskulavik** [comment] 2018-08-24 22:38
Hi @plc402,

Please reply to support requesting that they assign the case to me and we will look at your cluster.  Thank you.

**Comment by andrew-dinunzio** [comment] 2018-09-06 18:58
Tested with a new cluster today on Kubernetes 1.11.2, Helm 2.10.0 and Istio 1.0.1, and the helm install worked (without the DaemonSet workaround)!

Still having issues with watches and listing resources (interacting with the apiserver in general), but this issue in particular (helm installing with postinstall jobs) seems fixed for me.

**Comment by nphmuller** [comment] 2018-09-13 08:51
Can also confirmed this is fixed. Upgrading to 1.11.2 wasn't enough, I had to redeploy the cluster.

**Comment by nemzes** [comment] 2018-09-18 08:13
Just created a cluster with 1.11.2; it worked this time. 🤷‍♂️

**Comment by StianOvrevage** [comment] 2018-10-09 08:43
Fails:

```
Installing helm chart for prometheus-operator
helm install coreos/prometheus-operator --name prometheus-operator
Error: watch closed before Until timeout
```

**Comment by jskulavik** [comment] 2018-10-09 15:19
Please see issue #676 which we are actively working to address.

**Comment by StianOvrevage** [comment] 2018-10-09 19:19
Thanks @jskulavik . Any idea on how to implement the workaround with setting the KUBERNETES_* env vars on Helm? Add them to the `tiller` Deployment maybe?

**Comment by f4tq** [comment] 2018-10-16 00:48
I was hitting this `watch closed before Until timeout` with aks 1.11.3, tiller 2.11 when I created the cluster with `az aks create --node-name xxx . ...`.
The moment I removed `--node-name`, istio 1.0.1 installed cleanly.  I had been installing cleanly for a while but got sick of all my cluster worker nodes named `aks-nodepool1-xxx`  (i.e. the nodepool default ) otherwise I got watch timeout...
I hope provides a clue (and workaround for others) .

**Comment by nphmuller** [comment] 2018-10-29 10:40
This seems to be fixed by: https://github.com/Azure/AKS/issues/676 (opt-in preview atm)

**Comment by jnoller** [comment] 2019-04-03 21:50
Closing this issue as old/stale/resolved.

Note: 
If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.

**Closed by jnoller** 2019-04-03 21:50 UTC
