### ISSUE TITLE
OMS Agent doesn't work on AKS with Kubernetes version 1.18.8

### ISSUE THREAD

**Issue by franz-net** [Azure/AKS#1924] opened 2020-10-27 18:41 UTC
**What happened**:
When creating AKS cluster using kubernetes 1.18.8 and enabling OMS integration, the OMS Agent pods fail with the following errors:

```
2020-10-27T18:04:22.961657075Z 2020-10-27T18:04:22Z E! [agent] Failed to connect to output socket_writer, retrying in 15s, error was 'dial tcp 0.0.0.0:25228: getsockopt: connection refused' 
2020-10-27T18:04:23.059574037Z Telegraf unknown (git: fork 50cd124)
2020-10-27T18:04:23.159866813Z td-agent-bit 1.4.2
2020-10-27T18:04:37.962108508Z 2020-10-27T18:04:37Z E! [telegraf] Error running agent: dial tcp 0.0.0.0:25228: getsockopt: connection refused
```

**What you expected to happen**:
OMS Agent should be collecting logs and metric information

**How to reproduce it (as minimally and precisely as possible)**:
Create AKS Cluster and enable OMS agent integration, sample below:
```
{    
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "clusterName": {
            "metadata": {
                "description": "Cluster Name"
            },
            "type": "string",
            "defaultValue": "aks-test"
        },
        "primaryLocation": {
            "type": "string",
            "defaultValue": "eastus"
        }
    },
    "variables": {},
    "resources": [
        {
            "comments": "------------------- Log Analytics Workspace for AKS -------------------",
            "type": "Microsoft.OperationalInsights/workspaces",
            "apiVersion": "2020-03-01-preview",
            "name": "[concat(parameters('clusterName'),'-workspace')]",
            "location": "[parameters('primaryLocation')]",
            "properties":{
                "sku": {
                    "name": "Free"
                }
            }
        },
        {
            "comments": "------------------- AKS Cluster Resource -------------------",
            "apiVersion": "2020-03-01",
            "type": "Microsoft.ContainerService/managedClusters",
            "location": "[parameters('primaryLocation')]",
            "name": "[concat(parameters('clusterName'),'-aks')]",
            "dependsOn": [
                "[concat(parameters('clusterName'),'-workspace')]"
            ],
            "identity": {
                "type": "SystemAssigned"
            },
            "properties": {
                "nodeResourceGroup": "[concat(parameters('clusterName'),'-infra-rg')]",
                "kubernetesVersion": "1.18.8",
                "dnsPrefix": "[concat(parameters('clusterName'),'-dns')]",
                "agentPoolProfiles": [
                    {
                        "name": "[substring(uniqueString(resourceGroup().id),0,11)]",
                        "osType": "Linux",
                        "vmSize": "Standard_E8s_v3",
                        "count": 1,
                        "enableAutoScaling": true,
                        "maxCount": 2,
                        "minCount": 1,
                        "type": "VirtualMachineScaleSets",
                        "mode": "System",
                        "nodeTaints": [],
                        "nodeLabels": {
                            "app/pool": "infra"
                        }
                    }
                ],
                "addonProfiles": {
                    "omsagent": {
                        "enabled": true,
                        "config": {
                            "logAnalyticsWorkspaceResourceID": "[resourceId('Microsoft.OperationalInsights/workspaces', concat(parameters('clusterName'),'-workspace'))]"
                        }
                    }
                },
                "networkProfile": {
                    "networkPlugin": "kubenet",
                    "loadBalancerSku": "standard"
                }
            },
            "resources": []
        },
        
        {
            "type": "Microsoft.ContainerService/managedClusters/providers/diagnosticSettings",
            "name": "[concat(concat(parameters('clusterName'),'-aks'), '/Microsoft.Insights/diagnostics')]",
            "apiVersion": "2017-05-01-preview",
            "dependsOn": [
                "[concat('Microsoft.ContainerService/managedClusters/',concat(parameters('clusterName'),'-aks'))]"
            ],
            "properties": {
                "workspaceId": "[resourceId('Microsoft.OperationalInsights/workspaces', concat(parameters('clusterName'),'-workspace'))]",
                "metrics": [
                    {
                        "category": "AllMetrics",
                        "enabled": true,
                        "retentionPolicy": {
                            "enabled": false,
                            "days": 0
                        }
                    }
                ],
                "logs": [
                    {
                        "category": "guard",
                        "enabled": true
                    },
                    {
                        "category": "kube-apiserver",
                        "enabled": true
                    },
                    {
                        "category": "kube-controller-manager",
                        "enabled": true
                    },
                    {
                        "category": "kube-scheduler",
                        "enabled": true
                    }
                ]
            }
        }
    ],
    "outputs": {}
}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"73ec19bdfc6008cd3ce6de96c663f70a69e2b8fc", GitTreeState:"clean", BuildDate:"2020-09-17T04:17:08Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?)
2 Node Cluster
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Only OMS Agent at this moment

**Comment by vishiy** [comment] 2020-11-19 07:00
Looks agent fails to start due to probably incorrect workspace ? Can u share the full log for the pod?

**Comment by awalford16** [comment] 2020-11-26 11:16
Has there been any progress with this @franz-net ? I am having the same issues with a cluster running on 1.14. These are the logs that I get:

`10:58:35.187 2020-11-26T10:58:35Z I! Starting Telegraf
10:58:35.187  Telegraf unknown (git: fork 50cd124)
10:58:35.288 2020-11-26T10:58:35Z E! [agent] Failed to connect to output socket_writer, retrying in 15s, error was 'dial tcp 0.0.0.0:25226: getsockopt: connection refused'
10:58:35.389 td-agent-bit 1.4.2
10:58:35.389 stopping rsyslog...
10:58:35.486 * Stopping enhanced syslogd rsyslogd
10:58:36.586 ...done.
10:58:36.586 getting rsyslog status...
10:58:36.596 * rsyslogd is not running `

This is from installing the OmsAgentForLinux to a VMSS using `az vmss extension set`. 

I have confirmed the workspace is correct from within the portal

**Comment by vishiy** [comment] 2020-11-26 15:57
@awalford16 please share the full pod log

**Comment by awalford16** [comment] 2020-11-27 09:37
```
09:24:58.135 INFO: Configuring OMS agent service 104045af-c467-445f-8ced-7bd5af32699e ...

09:24:58.247 invoke-rc.d: could not determine current runlevel

09:24:58.331 * Starting Operations Management Suite agent (104045af-c467-445f-8ced-7bd5af32699e):

09:25:03.033 ...done.

09:25:03.128 -e erroru0009MetaConfig generation script not available at /opt/microsoft/omsconfig/Scripts/OMS_MetaConfigHelper.py 

09:25:03.227 * Starting periodic command scheduler cron

09:25:03.230 ...done.

09:25:03.433 Primary Workspace: 104045af-c467-445f-8ced-7bd5af32699e Status: Onboarded(OMSAgent Running)

09:25:03.537 omsagent 1.10.0.1

09:25:03.627 docker-cimprov 11.0.0.0

09:25:03.732 DOCKER_CIMPROV_VERSION=11.0.0.0

09:25:03.732 ************start oneagent log routing checks************

09:25:03.826 oneagent regions: koreacentral,norwayeast 

09:25:03.829 current region: eastus2

09:25:03.923 oneagent region is false for current region:eastus2

09:25:03.923 ************end oneagent log routing checks************

09:25:03.925 nodename: aks-blue-37462504-vmss00008j

09:25:03.925 replacing nodename in telegraf config 

09:25:04.923 File Doesnt Exist. Creating file...

09:25:04.923 u001b[1mFluent Bit v1.4.2u001b[0m

09:25:04.923 * u001b[1mu001b[93mCopyright (C) 2019-2020 The Fluent Bit Authorsu001b[0m

09:25:04.923 * u001b[1mu001b[93mCopyright (C) 2015-2018 Treasure Datau001b[0m

09:25:04.923
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
37fcde25-24c7-11eb-926d-9aa765fbeb53
09:25:04.923
* https://fluentbit.io `

**Comment by sudharsanomprakash** [comment] 2021-01-04 19:04
Having same issue. Anyone found solution?


Fluent Bit v1.4.2
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

Telegraf unknown (git: fork 50cd124)
td-agent-bit 1.4.2
stopping rsyslog...
2021-01-04T18:55:49Z I! Starting Telegraf
2021-01-04T18:55:49Z E! [agent] Failed to connect to output socket_writer, retrying in 15s, error was 'dial tcp 0.0.0.0:25228: getsockopt: connection refused'
 * Stopping enhanced syslogd rsyslogd
   ...done.
getting rsyslog status...
 * rsyslogd is not running
2021-01-04T18:56:04Z E! [telegraf] Error running agent: dial tcp 0.0.0.0:25228: getsockopt: connection refused
2021/01/04 18:56:49 Error Reading omsadmin configuration open /etc/opt/microsoft/omsagent/conf/omsadmin.conf: no such file or directory

**Comment by vishiy** [comment] 2021-01-04 19:10
@sudharsanomprakash - Those are generic errors. Whats the pod status? Is it constantly restarting? If so, its most likely connectivy to log analytics end points need to be opened up from your side - https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic#required-fqdn--application-rules-2

If you need further help, please open a support ticket.

**Comment by sudharsanomprakash** [comment] 2021-01-04 19:17
@vishiy Thank you for your response. Yes, the pods are restarting constantly and goes to Crashloopback state. I will check the firewall rule and keep this thread updated. thanks again.

**Comment by sudharsanomprakash** [comment] 2021-01-04 20:54
@vishiy I have validate the firewall rules and aks cluster is able to communicate with below destinations. The pods are in CrashLoopBackOff State with below logs. I am not sure why omsadmin.conf is missing. Any idea?

dc.services.visualstudio.com | HTTPS:443 
*.ods.opinsights.azure.com | HTTPS:443 
*.oms.opinsights.azure.com | HTTPS:443
*.monitoring.azure.com | HTTPS:443

Logs:

2021-01-04T20:45:59Z E! [agent] Failed to connect to output socket_writer, retrying in 15s, error was 'dial tcp 0.0.0.0:25228: getsockopt: connection refused'
2021-01-04T20:46:14Z E! [telegraf] Error running agent: dial tcp 0.0.0.0:25228: getsockopt: connection refused
**2021/01/04 20:46:44 Error Reading omsadmin configuration open /etc/opt/microsoft/omsagent/conf/omsadmin.conf: no such file or directory**

**/opt/microsoft/omsagent/bin/service_control: line 159: /etc/opt/microsoft/omsagent/<workspace-id>/conf/omsadmin.conf: No such file or directory**
**ERROR:  stop_omsagent failed with result '1' on workspace <workspace-id>.
open /etc/opt/microsoft/omsagent/conf/omsadmin.conf: no such file or directory**

**Comment by vishiy** [comment] 2021-01-04 21:08
@sudharsanomprakash - That file will be missing only if onboarding to a log analytics workspace fails. If you see the earlier parts of the log, you will see some curl requests failing. Are your workspace id & key correct? Workspace not deleted etc... ?
How did you enable monitoring ?

**Comment by sudharsanomprakash** [comment] 2021-01-04 21:21
@vishiy - Below is the full logs. Based on the log events, OMS agent is On-boarded Successfully. The Workspace ID and Key is correct. I tried onboarding in both ways - Azure Portal and Command line (az aks enable-addons -a monitoring -n AKSCluster -g rg-aks --workspace-resource-id "/subscriptions/<subscription-id>/resourceGroups/rg-aks/providers/Microsoft.OperationalInsights/workspaces/<workspace-name>")

##kubectl logs pod/omsagent-hcc9y -n kube-system

customResourceId:/subscriptions/<subscription-id>/resourceGroups/rg-aks/providers/Microsoft.ContainerService/managedClusters/AKSCluster
**Making curl request to oms endpint with domain: opinsights.azure.com**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
**curl request to oms endpoint succeeded.**
****************Start Config Processing********************
Both stdout & stderr log collection are turned off for namespaces: '*_kube-system_*.log'
****************End Config Processing********************
****************Start Config Processing********************
****************Start NPM Config Processing********************
config::npm::Successfully substituted the NPM placeholders into /etc/opt/microsoft/docker-cimprov/telegraf.conf file for DaemonSet
config::Starting to substitute the placeholders in td-agent-bit.conf file for log collection
config::Successfully substituted the placeholders in td-agent-bit.conf file
****************Start Prometheus Config Processing********************
config::No configmap mounted for prometheus custom config, using defaults
****************End Prometheus Config Processing********************
****************Start MDM Metrics Config Processing********************
****************End MDM Metrics Config Processing********************
****************Start Metric Collection Settings Processing********************
****************End Metric Collection Settings Processing********************
Making wget request to cadvisor endpoint with port 10250
Wget request using port 10250 succeeded. Using 10250
Making curl request to cadvisor endpoint /pods with port 10250 to get the configured container runtime on kubelet
configured container runtime on kubelet is : docker
getting gid for docker.sock
creating a local docker group
adding omsagent user to local docker group
set caps for ruby process to read container env from proc
aks-nodepool1
**Workspace <workspace-id> already onboarded and agent is running.**
Symbolic links have not been created; re-onboarding to create them
info    Generating certificate ...
-e info Agent GUID is XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
-e error        Error onboarding. HTTP code 403, Reason: . Check the Workspace ID, Workspace Key and that the time of the system is correct.
 * Starting periodic command scheduler cron
   ...done.
/opt/microsoft/omsagent/bin/service_control: line 159: /etc/opt/microsoft/omsagent/<workspace-id>/conf/omsadmin.conf: No such file or directory
**Workspace: <workspace-id>    Status: Onboarded(OMSAgent Running)**
omsagent 1.10.0.1
docker-cimprov 11.0.0.1
DOCKER_CIMPROV_VERSION=11.0.0.1
************start oneagent log routing checks************
oneagent regions: koreacentral,norwayeast
current region: eastus
oneagent region is false for current region:eastus
************end oneagent log routing checks************
nodename: aks-nodepool1
replacing nodename in telegraf config
File Doesnt Exist. Creating file...
Fluent Bit v1.4.2
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

Telegraf unknown (git: fork 50cd124)
2021-01-04T20:45:44Z I! Starting Telegraf
2021-01-04T20:45:44Z E! [agent] Failed to connect to output socket_writer, retrying in 15s, error was 'dial tcp 0.0.0.0:25226: getsockopt: connection refused'
td-agent-bit 1.4.2
stopping rsyslog...
 * Stopping enhanced syslogd rsyslogd
   ...done.
getting rsyslog status...
 * rsyslogd is not running
2021-01-04T20:45:59Z E! [agent] Failed to connect to output socket_writer, retrying in 15s, error was 'dial tcp 0.0.0.0:25228: getsockopt: connection refused'
2021-01-04T20:46:14Z E! [telegraf] Error running agent: dial tcp 0.0.0.0:25228: getsockopt: connection refused
2021/01/04 20:46:44 Error Reading omsadmin configuration open /etc/opt/microsoft/omsagent/conf/omsadmin.conf: no such file or directory

/opt/microsoft/omsagent/bin/service_control: line 159: /etc/opt/microsoft/omsagent/<workspace-id>/conf/omsadmin.conf: No such file or directory
ERROR:  stop_omsagent failed with result '1' on workspace <workspace-id>.
open /etc/opt/microsoft/omsagent/conf/omsadmin.conf: no such file or directory

**Comment by vishiy** [comment] 2021-01-04 21:23
-e error Error onboarding. HTTP code 403, Reason: . Check the Workspace ID, Workspace Key and that the time of the system is correct.

**Comment by vishiy** [comment] 2021-01-04 21:29
@sudharsanomprakash to further troubleshoot from my side, i need cluster resourceid. Can you create a support ticket ?

**Comment by sudharsanomprakash** [comment] 2021-01-06 22:17
@vishiy Thank you for your support and guidance for resolving this issue. Much appreciated. 

This problem and resolution is for Private Cluster.

LAW - Log Analytics Worspace
AMPLS - Azure Monitor Private Link Scope

**Problems:**

- AMPLS was not created
- "Allow public network access for queries" was set to NO in LAW Network Isolation.
- Log Analytics Contributor access was missing in the LAW for my userid.

**Resolution:**

- AMPLS was created to link the Virtual network/Subnet and the Monitoring Resources(LAW). This is required for Private Cluster to ingest to Azure Monitor workspace.
- "Allow public network access for queries" was set to YES in LAW Network Isolation. This is required to query data from portal
- Log Analytics Contributor access was granted to my userid in the LAW - I had to re-enable the monitoring add-ons

**Comment by genpattonmd** [comment] 2021-01-20 17:05
This still seems to be an issue.  I got the below output from Terraform. However, after logging into the portal and checking it seems like OMS did install and is monitoring.  Any response from Microsoft on this being addressed?

`Error: 
The Kubernetes/Orchestrator Version "1.18.8" is not available for Node Pool "clusternodes".

Please confirm that this version is supported by the Kubernetes Cluster "ClusterTestName"
(Resource Group "TestRG") - which may need to be upgraded first.

The Kubernetes Cluster is running version "1.18.8".

The supported Orchestrator Versions for this Node Pool/supported by this Kubernetes Cluster are:
 * 1.17.13
 * 1.17.16
 * 1.16.15
 * 1.16.13

Node Pools cannot use a version of Kubernetes that is not supported on the Control Plane. More
details can be found at https://aka.ms/version-skew-policy.


  on .terraform/modules/mse_kubernetes/module/azurekubernetes.tf line 1, in resource "azurerm_kubernetes_cluster" "kubernetes_cluster":
   1: resource "azurerm_kubernetes_cluster" "kubernetes_cluster" {`

**Comment by miwithro** [comment] 2021-03-22 14:27
@vishiy

**Comment by cforce** [comment] 2021-03-30 06:55
same here

**Comment by vishiy** [comment] 2021-03-30 15:39
All - this original issue is due to misconfiguration for private clusters, which @sudharsanomprakash posted back with a solution.

@genpattonmd - this terraform issue is unrelated to this. Please open an issue for that and reference here and AKS team will look into it.

@cforce - Please share the issue you are seeing.

**Comment by saaror** [comment] 2021-07-09 16:47
The issues are fixed. Please re-open if you still find these issues.

**Closed by saaror** 2021-07-09 16:47 UTC
Labels: Needs Attention :wave:, action-required, addon/container-insights
