### ISSUE TITLE
Pod-Identity management bug

### ISSUE THREAD

**Issue by ekhaydarov** [Azure/AKS#2203] opened 2021-03-19 09:26 UTC
**What happened**: Pod identity is in a state where it cannot do anything to a managed identity role. it is stuck and getting mixed up between different roles. 

The command to delete an identity named `aks-ns-data-core` references `aks-ns-data-mlp` in the error. ive granted  the cluster managed identity, the mc-xx resource group, everything possible to assign a `Managed Identity Contributor` has been assigned and yet the error below occurs. What sacrifices need to be made to simply delete a resource?

```
az aks pod-identity delete --cluster-name ${CLUSTER_NAME} --namespace ${NAMESPACE} --name aks-ns-data-core -g ${RESOURCE_GROUP}
Operation failed with status: 'Bad Request'. Details: Cluster identity has no assignment permission over identity 'resourceId: /subscriptions/x/resourcegroups/x/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-ns-data-mlp - clientId: x - objectId: x'. Please grant at least 'Managed Identity Operator' permission before assigning pod identity.
```

**What you expected to happen**: to simply delete a pod-identity binding

**How to reproduce it (as minimally and precisely as possible)**: 
* create aks with system assigned managed identity. 
* create a user assigned identity 
* run `az aks pod-idenity create` on the new user assigned identity
* try to delete

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20 preview
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): nothing apart from your broken OS implementations of gatekeeper and 
- Others:

**Comment by miwithro** [comment] 2021-03-19 17:04
@bcho

**Comment by bcho** [comment] 2021-03-22 01:44
@ekhaydarov thanks for reporting this issue! I have a question for the managed identity `aks-ns-data-mlp` we are checking: did you delete this identity, **before** running the pod identity delete command?  If so, we suspect there is a bug that cause the cluster's pod identity reference are in a wrong state.

I will try repro in my end with following steps as well: 1. assign managed identity to the cluster; 2. delete the managed identity resource; 3. unassign the pod identity from cluster

**Comment by ekhaydarov** [comment] 2021-03-22 03:14
Hi @bcho 
Pretty sure that delete was run only an the user assigned identity and the pod identity delete was missed altogether for a few days. This is because the identity was deleted through terraform. Pod identity is not available in terraform so was missed out. It was in a null resource but destroying that resource doesn't actually run pod identity delete

However, your colleague @aramase has already repro deleting of identity before deleting of pod identity and he did not get a bug. There must have been something we did in-between deleting identity and creating new ones to cause this issue. Right now nothing in `az aks pod-identity` runs for that specific RG

A security concern was that those identity bindings in aks still worked for new identities even though they were bound to old ones to access azure key vault.

**Comment by bcho** [comment] 2021-03-22 03:21
@ekhaydarov thanks for the info! One more thing to confirm, did all your delete attempts send from terraform?

**Comment by ekhaydarov** [comment] 2021-03-22 03:35
Delete attempts were az cli commands from the same container that runs terraform. I did attempt with my own user a few times. The subscription owner tried once too and still couldn't delete

**Comment by bcho** [comment] 2021-03-22 04:12
@ekhaydarov I think I can reproduce this issue now, I tried following setup:

1. create two managed identities and assign to an AKS cluster with `aks pod-identity add`
2. delete both identities from portal
3. run `aks pod-identity delete` for to remove any one of above identities, we should see the command failed with complaining it cannot check the permission for another identity.

This usage trigger a bug in AKS side.

In your case, I guess it's because both managed identities `aks-ns-data-core` and `aks-ns-data-mlp` were removed by terraform. @ekhaydarov could you help confirm if the managed identity `aks-ns-data-mlp` still presents? If it has been deleted, I can manually to remove the reference for your cluster for now. What do you think?

Also, if possible, I suggest to open a support ticket for your cluster from Azure portal, so that we can share more details with this case.

**Comment by ekhaydarov** [comment] 2021-03-22 04:20
There are more identities that are stuck. And one more cluster in the same RG that had the same thing applied to it so pretty sure has stuck identities. I am not at my terminal but will post a full list of all pod identities to delete

Also would you be able to share the docs or steps to where I can open up a support case in the portal? I have not done it before

Thanks for your help

**Comment by bcho** [comment] 2021-03-22 04:26
<img width="276" alt="Screen Shot 2021-03-22 at 12 24 38 PM" src="https://user-images.githubusercontent.com/1975118/111940409-a12d5000-8b09-11eb-9f09-5ab44e9fe4c6.png">

@ekarafezov we can open a support ticket in the AKS cluster resource page, from the sidebar. Please provide the full list of managed identities you want to remove in the support ticket, then I can remove them today, thanks!

**Comment by ekhaydarov** [comment] 2021-03-22 11:51
@bcho i cannot open a support ticket right now.
here are the pod-identities that need to be deleted
```
az aks show --name we1-dev-data-core-services --query 'podIdentityProfile.userAssignedIdentities[].{name:name, state:provisioningState}'

[
  {
    "name": "aks-ns-data-core",
    "state": "Failed"
  },
  {
    "name": "aks-ns-data-monitoring",
    "state": "Failed"
  },
  {
    "name": "aks-ns-user-erkin",
    "state": "Failed"
  },
  {
    "name": "aks-ns-data-mlp",
    "state": "Failed"
  },
  {
    "name": "aks-ns-data-featurestore",
    "state": "Failed"
  },
  {
    "name": "aks-ns-airflow-core",
    "state": "Failed"
  }
]

az aks show --name we1-dev-data-core-workloads --query 'podIdentityProfile.userAssignedIdentities[].{name:name, state:provisioningState}'

[
  {
    "name": "aks-ns-data-monitoring",
    "state": "Failed"
  },
  {
    "name": "aks-ns-data-core",
    "state": "Failed"
  }
]
```

**Comment by bcho** [comment] 2021-03-22 13:09
@ekhaydarov I had manually updated both clusters, PTAL.

While we are working on the fix in AKS end, I would suggest we avoid deleting the managed identities before removing from the cluster; i.e. run `aks pod-identity delete` then `identity delete`. Sorry for the inconvenience!

**Comment by ekhaydarov** [comment] 2021-03-22 13:12
Thank you, I managed to submit the support request for both the clusters and referencing this issue in the comments. Hope that is OK.

**Comment by bcho** [comment] 2021-03-22 13:16
That's fine! I can handle the ticket. Yes I had removed these failed identities. We should be able to assign new pod identities to the cluster now.

**Comment by jotavar** [comment] 2021-03-22 13:24
@bcho I was assigned this case, can you please reach out to me over Teams to discuss next steps?

**Comment by ekhaydarov** [comment] 2021-03-22 18:50
so we have a very bad workaround in terraform that looks something like this. We do not want this to be a long term solution.

```
resource "azurerm_user_assigned_identity" "namespace" {
  for_each            = var.enable_pod_identity ? toset(list("1")) : []
  resource_group_name = var.resource_group.name
  location            = var.resource_group.location
  name                = local.identity.identity_name
  tags                = local.identity

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = "${self.tags["az_login"]} && az aks pod-identity add ...
  }

  provisioner "local-exec" {
    when        = destroy
    interpreter = ["/bin/bash", "-c"]
    command     = "${self.tags["az_login"]} && az aks pod-identity delete ...
  }
}
```

The ideal solution is this terraform-providers/terraform-provider-azurerm#10206. However, what seemed like scheduled for imminent release has now been untouched for over a month with no sign of progress. Would it be possible to get any info on when we would be able to perform pod identity actions through terraform?

**Comment by bcho** [comment] 2021-03-29 08:51
> Would it be possible to get any info on when we would be able to perform pod identity actions through terraform?

Hey @ekhaydarov , currently we are focusing on the v2 version of this addon, therefore, we will keep the terraform implementation as-is.

**Closed** 2021-04-07 18:02 UTC
Labels: resolution/answer-provided
