### ISSUE TITLE
az aks create without --service-principal arg picks some SP from the ones I own, uses it for multiple clusters

### ISSUE THREAD

**Issue by wasker** [Azure/AKS#1425] opened 2020-02-05 04:09 UTC
**What happened**:
aks-preview 0.4.27 uses some SP from the ones I own when creating a cluster w/o --service-principal arg. When I'm creating multiple clusters in various locations, the same SP is being used. I.e., if I run az aks show on 2 different clusters, I get the same SP block:

```
  "servicePrincipalProfile": {
    "clientId": "8e82e4cc-ccbf-4358-9d60-xxx"
  }
```

After looking through AAD / App registrations - this is the SP that I've created more than 2 months ago. I do not use --service-principal arg to pass this SP to aks create command.

**What you expected to happen**:
AKS would create a brand new SP for each cluster I'm creating, if --service-principal is not specified.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create several SPs using az ad sp create-for-rbac
1. Use basic az aks create command, do not use --service-principal arg.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.0

**Comment by wasker** [comment] 2020-02-06 00:20
OK, that explains how the SP gets assigned, but it's completely non-intuitive! There's no mention anywhere that if `--service-principal` was not specified, something from the local system will be used. This doesn't make any sense. :-\

**Comment by wasker** [comment] 2020-02-06 00:36
[Not here though](https://docs.microsoft.com/en-us/cli/azure/ext/aks-preview/aks?view=azure-cli-latest#ext-aks-preview-az-aks-create)

**Comment by jluk** [comment] 2020-02-10 18:38
We'll revisit why the additional help isn't in the rest reference. Explained a bit more in the additional considerations section. https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal#additional-considerations

Closing as this behavior is by design, but we have action to improve the cli ref. Thanks for the feedback.

FYI @mlearned @zr-msft for us to get these caught up.

**Closed by jluk** 2020-02-10 18:38 UTC
Labels: triage

**Comment by ams0** [comment] 2020-02-10 19:59
Out of curiosity, I made the `aksServicePrincipal.json` file non-readable by my user and `az aks create` failed; perhaps, it could gracefully continue without saving the local SP credentials. Why we need it locally after all? As long as the AppId can be retrieved as part of the cluster properties, I really don't need the SP password stored locally.
