### ISSUE TITLE
Source IP Not available within Cluster using Nginx Ingress

### ISSUE THREAD

**Issue by moomzni** [Azure/AKS#607] opened 2018-08-16 07:26 UTC
**What happened**:
Our scenario is that we have deployed an AKS cluster using advanced networking and nginx ingress and we've noticed that the SourceIP address for requests originating from the internet is not visible on the ingress controller.

We have tried setting `controller.service.externalTrafficPolicy=Local` which didn't resolve the issue.

The IP addresses reported to nginx vary between pods/nodes connected to the VNET in which AKS is resident and the Azure LB's internal IP.

**What you expected to happen**:
Upon setting `controller.service.externalTrafficPolicy=Local` the source IP address should have been reported in nginx.

**How to reproduce it (as minimally and precisely as possible)**:
1. Build a new AKS cluster (v1.10.5) using advanced networking
2. Deploy nginx-ingress using Helm (v.0.23.0)
3. Enable `controller.service.externalTrafficPolicy=Local` annotation in ingress controller
4. Try accessing your cluster and observing the IP addresses nginx is reporting; they will all be local

**Anything else we need to know?**:
This is a pretty significant gap as short of a fix we have no idea which public IP addresses are making requests of our AKS hosted services.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Internet facing www and api endpoints

**Comment by blackentropy** [comment] 2018-08-22 22:08
I've reached out to Azure support and they have confirmed that a fix is being deployed and will be available in about a week

**Comment by JunSun17** [comment] 2018-08-23 16:46
Many thanks to @marrobi for providing a temporary fix for this issue. Please save the following contents to yaml files, and deploy the config map and daemon set to mitigate this issue.

daemonset.yaml
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: source-ip-fix
  labels:
    app: source-ip-fix
spec:
  template:
    metadata:
      labels:
        name: source-ip-fix
    spec:
      hostNetwork: true
      containers:
        - name: source-ip-fix
          securityContext:
            privileged: true
          image: alpine
          imagePullPolicy: Always
          command:
          - /bin/sh
          - -c
          - |
            echo "copy scripts to /tmp"
            cp /scripts/*.sh /tmp
            echo "chmod"
            chmod +x /tmp/run.sh
            echo "execute"
            /tmp/run.sh
          resources:
            requests:
              cpu: 5m
              memory: 50Mi
          volumeMounts:
          - mountPath: /scripts
            name: scripts
      volumes:
      - name: scripts
        configMap:
          name: source-ip-fix
```

configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name:  source-ip-fix
data:
  run.sh: |
    #!/bin/sh

    echo "adding iptables"

    apk add iptables
    while true; do
      echo $(iptables -t nat -L POSTROUTING )

      # check if exists
      iptables -t nat -C POSTROUTING -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d 10.0.0.0/8 -j MASQUERADE
      EXISTS=$?

      # delete rule if exists        
      if [ $EXISTS  -eq 0 ]
      then
        echo "Bad rule exists"

        iptables -t nat -D POSTROUTING  -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d 10.0.0.0/8 -j MASQUERADE

        echo "Deleted Rule"
      else 
        echo "Bad rule does not exist"
      
      fi
    

      # Get subnet of azure nic, sufficient as source traffic comes from same subnet in our instance
      SUBNET_CIDR=$(ip -o -f inet addr show | awk '/azure0/ {print $4}')

      echo "Subnet is " ${SUBNET_CIDR}

      # check if exists
      iptables -t nat -C POSTROUTING -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d $SUBNET_CIDR -j MASQUERADE
      EXISTS=$?

      if [  $EXISTS  -eq 0  ]
      then
        
        echo "Rule already exists"

      else 
          
        iptables -t nat -A POSTROUTING -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d $SUBNET_CIDR -j MASQUERADE

        echo "Added rule"

      fi

      sleep 60
    
    done

    exit 0
```

**Comment by marrobi** [comment] 2018-10-02 11:37
@JunSun17 as per @serbrech comment need to ensure specify ```--wait``` in the iptables commands above.

**Comment by denniszielke** [comment] 2018-10-25 16:42
It works the `x-forwarded-from` header gets set with the source-ip with the following configuration.
The wait needs to be set and the lock file needs to be mounted into the daemonset.
configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name:  source-ip-fix
data:
  run.sh: |
    #!/bin/sh

    echo "adding iptables"

    apk add iptables
    while true; do
      echo $(iptables -t nat -L POSTROUTING)

      # check if exists
      iptables -t nat -C POSTROUTING -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d 10.0.0.0/8 -j MASQUERADE -w
      EXISTS=$?

      # delete rule if exists        
      if [ $EXISTS  -eq 0 ]
      then
        echo "Bad rule exists"

        iptables -t nat -D POSTROUTING  -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d 10.0.0.0/8 -j MASQUERADE -w

        echo "Deleted Rule"
      else 
        echo "Bad rule does not exist"
      
      fi
    

      # Get subnet of azure nic, sufficient as source traffic comes from same subnet in our instance
      SUBNET_CIDR=$(ip -o -f inet addr show | awk '/azure0/ {print $4}')

      echo "Subnet is " ${SUBNET_CIDR}

      # check if exists
      iptables -t nat -C POSTROUTING -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d $SUBNET_CIDR -j MASQUERADE -w
      EXISTS=$?

      if [  $EXISTS  -eq 0  ]
      then
        
        echo "Rule already exists"

      else 
          
        iptables -t nat -A POSTROUTING -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d $SUBNET_CIDR -j MASQUERADE -w

        echo "Added rule"

      fi

      sleep 60
    
    done

    exit 0
```

daemonset
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: source-ip-fix
  labels:
    app: source-ip-fix
spec:
  template:
    metadata:
      labels:
        name: source-ip-fix
    spec:
      hostNetwork: true
      containers:
        - name: source-ip-fix
          securityContext:
            privileged: true
          image: alpine
          imagePullPolicy: Always
          command:
          - /bin/sh
          - -c
          - |
            echo "copy scripts to /tmp"
            cp /scripts/*.sh /tmp
            echo "chmod"
            chmod +x /tmp/run.sh
            echo "execute"
            /tmp/run.sh
          resources:
            requests:
              cpu: 5m
              memory: 50Mi
          volumeMounts:
          - mountPath: /scripts
            name: scripts
          - mountPath: /var/run/xtables.lock
            name: xtables
      volumes:
      - name: scripts
        configMap:
          name: source-ip-fix
      - name: xtables
        hostPath:
          path: /run/xtables.lock
```

**Comment by toutougabi** [comment] 2018-11-06 19:44
Any news on this, should we wait for MSFT rollout or use the fix ?

**Comment by JunSun17** [comment] 2018-11-06 20:23
Please use this mitigation for now. The fix is pending for more testing before roll out.

**Comment by hermesian** [comment] 2019-01-15 06:36
Any update?

**Comment by huydinhle** [comment] 2019-01-16 23:05
any updates on this?

**Comment by JunSun17** [comment] 2019-01-16 23:08
Hi All, the fix is being tested and currently in the phase of rolling out. ETA for WW deployment is end of Jan.

**Comment by Zenlil** [comment] 2019-01-18 17:43
Just a sidenote: We are running with externalTrafficPolicy=Local and when we access our services from within Azure we usually get a 127.0.0.1 as source. But when we access from the real outside (i.e not Azure) we do get the proper source IP.

**Comment by niemyjski** [comment] 2019-01-24 15:11
Will setting the `externalTrafficPolicy` to `Local` be required when this rolls out? I've read a few GitHub issues of stating that setting this to local is not a great idea.

**Comment by JunSun17** [comment] 2019-01-24 23:08
Yes, it will be required by nigix-ingress to preserve IP from incoming requests.

**Comment by ejsmith** [comment] 2019-01-25 17:20
@JunSun17 we are having the issue of the X-ForwardedFor header not properly being flowed through the Azure Load Balancer and through our NGINX ingress controller to our apps. I'm a little confused, is that what this issue is about?

**Comment by sylus** [comment] 2019-01-26 19:41
Would be great to see this rolled out, I thought it was fixed a while back but glad to know fix is def on the way.

**Comment by chiefzor** [comment] 2019-01-28 22:33
We are also waiting for that thing, we are using a multi cluster environment, and while trying to route the traffic from the external cluster into our internal cluster, the source ip is omitted and replaced by the pod ip from the external cluster in the X-Forwarded-For header

**Comment by chiefzor** [comment] 2019-01-29 09:54
Found a workaround that work well for us:
Use the externalTrafficPolicy to **Local** and then you will have the header name **X-Original-Forwarded-For** with the source IP.
The only thing that we needed to add in our code is to check if that header exists -> use this IP, else -> use X-Forwarded-For (so we will not have any issue on another non-kubernetes environment that we have our application implemented.
Hope that it works for you as well
![image](https://user-images.githubusercontent.com/20601896/51899669-31552c00-23bc-11e9-9701-c19b42767287.png)

**Comment by JunSun17** [comment] 2019-01-31 23:01
The fix has been released WW and ready for try out :)

**Comment by ejsmith** [comment] 2019-02-04 16:54
@JunSun17 can I please get a response and at least point me in the right direction?? This seems like the kind of thing that should just work out of the box.

**Comment by NitroAMD** [comment] 2019-02-04 21:54
Try with changing the TrafficPolicy:

helm install stable/nginx-ingress --namespace kube-system --set controller.replicaCount=2,controller.service.externalTrafficPolicy=Local

or

helm list
NAME            REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE
worn-billygoat  1               Mon Feb  4 17:31:56 2019        DEPLOYED        nginx-ingress-1.0.2     0.21.0          kube-system
helm upgrade worn-billygoat stable/nginx-ingress --set controller.service.externalTrafficPolicy=Local

**Comment by ejsmith** [comment] 2019-02-04 22:48
It’s my understanding that setting controls the actual request IP and not just the X-Forwarded-For header value. I don’t want to fake the request IP, I just want the header value to get flowed through.

**Comment by JunSun17** [comment] 2019-02-05 18:09
@ejsmith from the nginx doc (https://github.com/helm/charts/tree/master/stable/nginx-ingress), you need to set controller.service.externalTrafficPolicy=Local to preserve source IP. I do not think it is faking a request IP, from my understanding, it is passing the source IP as asked.

**Comment by JunSun17** [comment] 2019-02-19 17:46
This issue should be resolved now.

**Closed by JunSun17** 2019-02-19 17:46 UTC

**Comment by JamesBewley** [comment] 2019-03-12 15:39
Hi @JunSun17 , this doesn't appear to be working for TCP forwarding.  Is this possible? Does this need a separate ticket?

https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/

**Comment by niemyjski** [comment] 2019-03-12 23:04
We've been unable to get x-forward-for headers to be created correctly as
well. Do you have any guidance on this?
Thanks
-Blake Niemyjski

**Comment by mikebridge** [comment] 2019-03-22 17:00
I was able to set the value via `helm upgrade [release] stable/nginx-ingress --set controller.service.externalTrafficPolicy=Local` as per @NitroAMD and it appears to be set correctly:

```
$ helm get values example-nginx-ingress
controller:
  service:
    externalTrafficPolicy: Local
controller:
  replicaCount: 2
  ...
```
But this doesn't seem to propagate automatically.  Do I need to delete and recreate the pods or is there a better way?

**Comment by jjrdev** [comment] 2019-03-22 23:27
i was scratching my head over this for a bit. you need to setcontroller.service.externalTrafficPolicy="Local" 

```
helm install stable/nginx-ingress \
    --namespace ${KUBE_SERVICES_NAMESPACE} \
    --name nginx-ingress \
    --set controller.service.type="LoadBalancer" \
    --set controller.service.loadBalancerIP="${AKS_PUBLIC_IP}"  \
    --set controller.service.externalTrafficPolicy="Local" \
    --set controller.replicaCount=2
```
it does say above in another post, but to point it out again... checking the logs on the nginx-ingress pod showed the correct external ipaddress as $remote_addr in nginx-ingress log (the start of the line). i was then expecting to see the same ipaddress in my pod nginx service as $remote_addr but it was 10.x.x.x from the kube. however note that the real ip is in the nginx log file at the end as $http_x_forwarded_for as its set by X-Forwarded-For header. you can prove this further by deploying an image like brndnmtthws/nginx-echo-headers in your pod

**Comment by RehanSaeed** [comment] 2019-04-04 08:23
Also, what are the downsides of using `externalTrafficPolicy=Local`?

**Comment by xRoker** [comment] 2019-05-07 06:13
@JunSun17 for some reason X-Forwarded-For header contains the IP of the `kube-svc-redirect` pods and not the source IP. What can be the reason of such behaviour?

**Comment by niemyjski** [comment] 2019-05-07 11:11
Maybe this is what we are seeing too?
Thanks
-Blake Niemyjski

**Comment by jnoller** [comment] 2019-05-10 20:57
Just to recap what works, and limitation:

- Source IP for normal services exposed via type loadBalancer works.
  - Users must set externalTrafficPolicy=Local
  - If the user is not using an Ingress Controller, SSL works and the source IP is available
- Source IP for services using ingress controllers (all):
  - SSL pass-through with ingress controllers will not work, this would be a man in the middle attack and break SSL
- If the user is using ingress controllers but not attempting SSL pass through, source IP preservation will work
  - Users should set use-proxy-protocol: "true"
  - Users must use the “X-Forwarded-For” header as the source of truth to get information about the client IP address
- Source IP preservation at the Kubernetes API server level
  - Not supported currently, source IP preservation for the API server is dependent on Single IP per CCP on track for 1H 2019

**Comment by jnoller** [comment] 2019-05-10 20:58
I've pinged @JunSun17 to help look at the kube-svc-redirect issue mentioned too.

**Comment by rubbish** [comment] 2019-05-14 14:18
I'm also still seeing the issue after removing the source-ip-fix daemonset and then upgrading an older cluster from 1.12.6 to 1.13.5 to roll all nodes without the `source-ip-fix` pod. I'm using the `echoserver` (https://github.com/kubernetes-retired/contrib/blob/master/ingress/echoheaders/echo-app.yaml) with a `LoadBalancer` service with `externalTrafficPolicy: Local` to verify that the client address is not the node IP, but should be the actual client address. However, it's not working for this cluster. I haven't yet tried bringing up a new AKS cluster to find out if it's just an issue with existing clusters.

**Comment by rubbish** [comment] 2019-05-14 14:54
So when I brought up a new AKS cluster on version 1.13.5 also using advanced networking, but only in a different subnet, I didn't have the source ip issue and didn't need to deploy the source-ip-fix daemonset.

**Comment by rubbish** [comment] 2019-05-14 15:06
So one big difference that I've found is that the new cluster has an `azure-ip-masq-agent` daemonset (which seems to be https://github.com/kubernetes-incubator/ip-masq-agent). However, when I tried to take that same daemonset and apply it to my older cluster, it was deleteed by something.

**Comment by toutougabi** [comment] 2019-05-14 15:23
In AKS maintains an expected value for system pods. As this is probably now a system pod, your cluster must be set to expect not to have that container so the AKS API automatically detects it, you could try with a different name to see if you can trick the system into not looking at it.

**Comment by JunSun17** [comment] 2019-05-15 21:49
@xRoker I checked your cluster, and it is created before the fix is released. Unfortunately this fix can not be received automatically when doing upgrade/scale. You can try the mitigation in a previous post: https://github.com/Azure/AKS/issues/607#issuecomment-415486715

As for the kube-svc-redirect IP, it is actually the node IP, kube-svc-redirect pod is created by a daemon set and therefore it gets the node IP. However, due to the fact that the above fix is in your cluster, the source IP is not preserved and is SNAT to node IP.

**Comment by Vandersteen** [comment] 2019-08-09 07:34
> If the user is using ingress controllers but not attempting SSL pass through, source IP preservation will work
> * Users should set use-proxy-protocol: "true"
> * Users must use the “X-Forwarded-For” header as the source of truth to get information about the client IP address

When I turn this on in the configmap nginx stops working and throws errors like:

```
2019/08/09 07:27:40 [error] 14486#14486: *12897003 broken header: "" while reading PROXY protocol, client: 10.130.2.96, server: 0.0.0.0:443
2019/08/09 07:27:41 [error] 14485#14485: *12897013 broken header: "" while reading PROXY protocol, client: 10.130.0.155, server: 0.0.0.0:443
2019/08/09 07:27:43 [error] 14486#14486: *12897066 broken header: "���Ft}[���5�ɩK]�Љ�~�IҎʰ(Q�ܚ9b�0�,�2�.�/�+�1�-�������(�$��
�*�&��kih976�'�#�" while reading PROXY protocol, client: 10.130.0.4, server: 0.0.0.0:443
2019/08/09 07:27:44 [error] 14485#14485: *12897033 broken header: "" while reading PROXY protocol, client: 10.130.0.4, server: 0.0.0.0:443
2019/08/09 07:27:45 [error] 14485#14485: *12897037 broken header: "" while reading PROXY protocol, client: 10.130.2.96, server: 0.0.0.0:443
```

I turned this on by setting [use-proxy-protocol](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-proxy-protocol) in the configmap to true.

k8s: 1.13.5
nginx: nginx-ingress-1.3.1 (helm chart)

**Comment by zffocussss** [comment] 2019-08-27 11:50
> > If the user is using ingress controllers but not attempting SSL pass through, source IP preservation will work
> > 
> > * Users should set use-proxy-protocol: "true"
> > * Users must use the “X-Forwarded-For” header as the source of truth to get information about the client IP address
> 
> When I turn this on in the configmap nginx stops working and throws errors like:
> 
> ```
> 2019/08/09 07:27:40 [error] 14486#14486: *12897003 broken header: "" while reading PROXY protocol, client: 10.130.2.96, server: 0.0.0.0:443
> 2019/08/09 07:27:41 [error] 14485#14485: *12897013 broken header: "" while reading PROXY protocol, client: 10.130.0.155, server: 0.0.0.0:443
> 2019/08/09 07:27:43 [error] 14486#14486: *12897066 broken header: "���Ft}[���5�ɩK]�Љ�~�IҎʰ(Q�ܚ9b�0�,�2�.�/�+�1�-�������(�$��
> �*�&��kih976�'�#�" while reading PROXY protocol, client: 10.130.0.4, server: 0.0.0.0:443
> 2019/08/09 07:27:44 [error] 14485#14485: *12897033 broken header: "" while reading PROXY protocol, client: 10.130.0.4, server: 0.0.0.0:443
> 2019/08/09 07:27:45 [error] 14485#14485: *12897037 broken header: "" while reading PROXY protocol, client: 10.130.2.96, server: 0.0.0.0:443
> ```
> 
> I turned this on by setting [use-proxy-protocol](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-proxy-protocol) in the configmap to true.
> 
> k8s: 1.13.5
> nginx: nginx-ingress-1.3.1 (helm chart)

me too

**Comment by zffocussss** [comment] 2019-08-27 12:00
> Just to recap what works, and limitation:
> 
> * Source IP for normal services exposed via type loadBalancer works.
>   
>   * Users must set externalTrafficPolicy=Local
>   * If the user is not using an Ingress Controller, SSL works and the source IP is available
> * Source IP for services using ingress controllers (all):
>   
>   * SSL pass-through with ingress controllers will not work, this would be a man in the middle attack and break SSL
> * If the user is using ingress controllers but not attempting SSL pass through, source IP preservation will work
>   
>   * Users should set use-proxy-protocol: "true"
>   * Users must use the “X-Forwarded-For” header as the source of truth to get information about the client IP address
> * Source IP preservation at the Kubernetes API server level
>   
>   * Not supported currently, source IP preservation for the API server is dependent on Single IP per CCP on track for 1H 2019

I can get my local remote IP in the ingress-nginx-controller pod. when I set controller.service.externalTrafficPolicy="Local".
but we I curl inside my pod which is the same cluster as ingress-nginx-controller,internal IP 10.244.0.1 shows.is it normal

**Comment by cristiklein** [comment] 2019-09-26 12:48
> Hi @JunSun17 , this doesn't appear to be working for TCP forwarding. Is this possible? Does this need a separate ticket?
> 
> https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/

@JamesBewley Did you find a way to preserve the source IP when exposing TCP or UDP services behind the ingress controller?
