### ISSUE TITLE
AKS nodepool for ManagedCluster doesn't get upgraded even though control panel is upgraded

### ISSUE THREAD

**Issue by rehan2908** [Azure/AKS#3289] opened 2022-10-24 18:40 UTC
AKS nodepool for ManagedCluster doesn't get upgraded even though the control panel is upgraded
-->

**What happened**:  when using ARM template, we are upgrading from 1.22.6 to 1.23.8 , AKS node pool for ManagedCluster doesn't get upgraded even though the control panel is upgraded

**What you expected to happen**: upgrade of AKS version of NodePool to 1.23.8 

**How to reproduce it (as minimally and precisely as possible)**: ARM Template.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version 1.22.6 to 1.23.8
- Size of cluster 3 Node Pool, (Linux and Windows)

**Comment by rehan2908** [comment] 2022-10-27 21:45
https://github.com/hashicorp/terraform-provider-azurerm/issues/17839#issue-1325408901

**Comment by rehan2908** [comment] 2022-10-27 21:45
Well this issue isn't fixed though Azure claims it is resolved, could we get some attention on this please

**Comment by carvido1** [comment] 2022-11-07 16:46
Hello @rehan2908 .

Are you upgrading the control-plane as well as the different nodepools on your cluster? You need to specify it for both, control-plane and nodepools in your arm template.

There is a similar issue here [3087](https://github.com/Azure/AKS/issues/3087)

Best regrads.

**Comment by shashankbarsin** [comment] 2023-02-03 19:32
Closing this issue as it's a duplicate of #3087

**Closed by shashankbarsin** 2023-02-03 19:32 UTC
Labels: triage, action-required, Needs Attention :wave:
