### ISSUE TITLE
Cannot add new Windows pool - error: The Admin Username specified is not allowed

### ISSUE THREAD

**Issue by dineshsharmads** [Azure/AKS#1578] opened 2020-04-24 13:17 UTC
az aks create allows "admin" as a valid value for --windows-admin-username.
The cluster is created successfully. But later when adding a Windows Node pool it fails as "admin" is not allowed as username when creating the node.

Is there a way to update this value without recreating the cluster?

**Comment by nidiculageorge** [comment] 2020-04-25 06:32
@dineshsharmads From my understanding the windows username and password can be passed only when creating the cluster

**Comment by jluk** [comment] 2020-05-06 16:15
@nidiculageorge is correct, it should be the case that all new clusters created today have the admin/username defaulted so cluster recreates are not needed. But if this is an older cluster it is the case a recreate is needed to specify the uname/pw.

Closing as by design, but cc @MikkelHegn to correct me on anything.

**Closed by jluk** 2020-05-06 16:15 UTC
Labels: question, windows
