### ISSUE TITLE
AKS ingress controller 404 for .net core API project

### ISSUE THREAD

**Issue by praveenkadimi** [Azure/AKS#965] opened 2019-05-13 18:08 UTC
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jnoller** [comment] 2019-05-13 18:10
No information, closing

**Comment by praveenkadimi** [comment] 2019-05-13 18:10
I have an API service which is working as expected when I use path as "/". but when I mention path as "/test/" or "/test" which is not working site not reachable 404. can you help to resolve the issue

**Closed by jnoller** 2019-05-13 18:10 UTC
Labels: triage

**Comment by jnoller** [comment] 2019-05-13 18:13
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse
