### ISSUE TITLE
AKS rotate certificates feature result in missing worker nodes and failed state of nodepool

### ISSUE THREAD

**Issue by zuehlke-dea** [Azure/AKS#1455] opened 2020-02-19 09:29 UTC
Hi, regarding the new feature mentioned in https://github.com/Azure/AKS/issues/756

We tried out this feature again after it has worked in December 2019

We could reproduce the following behaviour with a current cluster (kubernetes version 1.14.x) with active nodepools:

* Certificates were replaced
* Worker nodes left the cluster (for some time kubectl access was still working)
* Nodepool is now in Failed state. 
* Kube API is back again
* Still no worker nodes visible and Ingress is not working anymore

**Comment by sauryadas** [comment] 2020-02-19 16:27
@andyzhangx PTAL

**Comment by jluk** [comment] 2020-02-20 21:32
This has been investigated by AKS on-call and a root cause has been discovered in certain clusters causing cert rotation failure. A hotfix is being rolled out globally to resolve this issue. 

The AKS team will close this issue when the fix is global.

**Comment by zuehlke-dea** [comment] 2020-02-24 08:46
Thx for the fast research!

**Comment by andyzhangx** [comment] 2020-02-29 13:55
this issue has been fixed on all Azure regions, if you already hit this issue, pls try rotate-certs again, thanks.

**Closed by andyzhangx** 2020-02-29 13:55 UTC
Labels: cert-rotation, known-issue
