### ISSUE TITLE
Operational Threshold errors returned on AKS create in WestEurope

### ISSUE THREAD

**Issue by MourIdri** [Azure/AKS#1189] opened 2019-09-04 13:17 UTC
hi there 

we cannot deploy a k8s cluster with the following error :

`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"UnderlayNotFound\",\r\n \"message\": \"Azure Container Service is unable to provision an AKS cluster in westeurope, due to an operational threshold. Please try again later or use an alternate location. For more details please refer to: https://github.com/Azure/AKS/blob/master/preview_regions.md.\"\r\n }\r\n ]\r\n }\r\n}"}]}`

We are deploying from the portal and using F2s series associated with CNI with existing VNet ( specifying this info if this has an impact...  )

please advise

**Comment by bramvdklinkenberg** [comment] 2019-09-05 06:53
Same issue here just a minute ago:

$ az aks create --resource-group bram-aqua-poc --name aqua-master --kubernetes-version 1.14.6 --node-vm-size Standard_DS3_v2 --ssh-key-value ~/.ssh/fullstaq.pub

The behavior of this command has been altered by the following extension: aks-preview
Deployment failed. Correlation ID: dce3fa22-a7ea-458c-8b65-1849331260dc. Azure Container Service is unable to provision an AKS cluster in westeurope, due to an operational threshold. Please try again later or use an alternate location. For more details please refer to: https://github.com/Azure/AKS/blob/master/preview_regions.md.

**Comment by janschumann** [comment] 2019-09-05 07:11
Same issue here,  (since yesterday)

Error: Error waiting for completion of Managed Kubernetes Cluster "APWEDEVAKS001" (Resource Group "APWEDEVRGPAKS001"): Code="UnderlayNotFound" Message="Azure Container Service is unable to provision an AKS cluster in westeurope, due to an operational threshold. Please try again later or use an alternate location. For more details please refer to: https://github.com/Azure/AKS/blob/master/preview_regions.md."

  on .terraform/modules/aks-cluster/cluster.tf line 3, in resource "azurerm_kubernetes_cluster" "cluster":
   3: resource "azurerm_kubernetes_cluster" "cluster" {

**Comment by bramvdklinkenberg** [comment] 2019-09-05 07:13
Mine worked after removing the failed aks resources and redeploying it.... don't know if I was lucky or not

**Comment by hkailantzis** [comment] 2019-09-05 07:51
same here since yesterday. Although got same error also on Tuesday. please advise.

**Comment by theres** [comment] 2019-09-05 08:52
yep, the same here.

**Comment by matsisak** [comment] 2019-09-05 08:54
Same issue here thursday September 5th. I'm using the aks-preview for custom name on node resource group.

**Comment by smed1na** [comment] 2019-09-05 09:05
By default, AKS cluster is created with 3 nodes. That error might be caused by a subscription quota limit. Try:
a) increasing the limits
b) delete some VMs
c) create the AKS cluster just with 1 node (az aks create --node-count 1)

**Comment by bramvdklinkenberg** [comment] 2019-09-05 10:55
I deployed it with 3 nodes, it failed. Then I deleted the AKS failed resource and redeployed it again with 3 nodes and it worked. Like I said, maybe I was lucky

**Comment by mihaimircea** [comment] 2019-09-05 11:39
After retrying the AKS (2 nodes) was created successfully in my case.

**Comment by hkailantzis** [comment] 2019-09-05 12:13
2 nodes as before, but problem still persists.

**Comment by hkailantzis** [comment] 2019-09-05 14:35
after several attempts looks OK for now...

**Comment by tommydejong** [comment] 2019-09-05 14:43
Still receiving errors, even with only 2 nodes...

**Comment by jluk** [comment] 2019-09-05 15:33
Hey folks, the AKS engineering team is aware of this issue and is working on deploying a fix. In the interim please try to utilize a different region while we resolve this, we will provide more details and ETA as soon as possible.

**Comment by vbrinza** [comment] 2019-09-06 08:07
Adding the cluster with only one node does not address the problem and it should not as the response is more about the Azure API reaching its limits.
I opened a ticket in Azure support too.
Let's see what the fix will be.

**Comment by jluk** [comment] 2019-09-06 16:02
The issue, which was a regional capacity issue, should now be mitigated and you should be able to create clusters in-region again. Closing for now, but please re-open or ping me if it is still repeatedly failing with this error. Thank you!

**Closed by jluk** 2019-09-06 16:02 UTC
Labels: capacity, known-issue

**Comment by Michael-Coetzee** [comment] 2019-09-17 17:40
Can we reopen this issue, it's still happening
https://github.com/Azure/AKS/issues/1214

**Comment by jluk** [comment] 2019-09-17 18:50
@Michael-Coetzee since you already opened a new issue, let's follow-up there and leave this one to avoid dupes.

**Comment by vbrinza** [comment] 2019-09-18 10:06
It is happening again in West Europe.

  echo "${RESOURCES_LOCATION}: Create the Kubernetes cluster"
  az aks create --resource-group ${RESOURCES_GROUP_NAME}_${RESOURCES_LOCATION} \
  --name ${K8S_CLUSTER_NAME}-${RESOURCES_LOCATION} \
  --location ${RESOURCES_LOCATION} \
  --node-count ${K8S_NODE_COUNT} \
  --node-vm-size ${K8S_NODE_SIZE} \
  --vnet-subnet-id ${backend_subnet_id} \
  --kubernetes-version ${K8S_VERSION} \
  --enable-addons monitoring \
  --dns-name-prefix ${K8S_CLUSTER_NAME}-${RESOURCES_LOCATION} \
  --dns-service-ip 10.0.0.10 \
  --docker-bridge-address 172.17.0.1/16 \
  --network-plugin azure \
  --service-cidr 10.0.0.0/16 \
  --no-ssh-key

**Comment by rverschuur** [comment] 2019-09-18 10:10
I can confirm that it doesnt work in west europe:

`PS D:\git\innotractor\docker> az aks create `
>>     -g $name `
>>     --name $name `
>>     --node-resource-group $nodeResourceGroup `
>>     --service-principal $appId `
>>     --client-secret $password `
>>     --network-plugin azure `
>>     --vnet-subnet-id $subnetId `
>>     --node-count 3 `
>>     --node-vm-size Standard_B2s `
>>     --location westeurope `
>>     --generate-ssh-keys `
>>     --kubernetes-version 1.14.6 `
>>     --service-cidr 192.168.0.0/16 `
>>     --dns-service-ip 192.168.0.10
The behavior of this command has been altered by the following extension: aks-preview

Deployment failed. Correlation ID: abc35493-d2ee-4012-a1f5-ef6946c8175d. Azure Container Service is unable to provision an AKS cluster in westeurope, due to an operational threshold. Please try again later or use an alternate location. For more details please refer to: https://github.com/Azure/AKS/blob/master/preview_regions.md.`

**Comment by nbarrasson** [comment] 2019-09-18 10:21
Same here:
az aks create --resource-group aks_lab_1809 --name aks-lab-cluster-1809 --location westeurope --kubernetes-version 1.15.3 --generate-ssh-keys
Deployment failed. Correlation ID: cfbd7493-e9ce-4b3d-ad4b-b5dcc9cffb2e. Azure Container Service is unable to provision an AKS cluster in westeurope, due to an operational threshold. Please try again later or use an alternate location. For more details please refer to: https://github.com/Azure/AKS/blob/master/preview_regions.md.

**Comment by mihaimircea** [comment] 2019-09-18 15:45
I'm getting this in West Europe:
` Code="ControlPlaneProvisioningInternalError" Message="Internal server error"`
```
kubernetes_version = "1.13.10"
os_type = "Linux"
agents_size = "Standard_A4"
agents_count = 2
```

**Comment by MrMCake** [comment] 2019-09-18 16:01
Same here. 3 Nodes in WestEurope and via ARM-Deployment

**Comment by jluk** [comment] 2019-09-18 16:18
@mihaimircea and @MrMCake are you trying to deploy with the IP whitelisting feature turned on? If so please follow issue #1214. 

If not please let me know and we'll take a look at it.

**Comment by MrMCake** [comment] 2019-09-18 17:12
Hey @jluk, no we are not whiteling any IPs in the context of our ARM deployment.

**Comment by jluk** [comment] 2019-09-18 17:20
@mrmcake thanks ive updated issue #1214 to reflect the current state which is a capacity constraint for any cluster in west eu. Please direct comments into that issue our on-call is working on this to increase capacity.

**Comment by ghelyar** [comment] 2019-09-20 07:58
I'm still getting `Code="ControlPlaneProvisioningInternalError" Message="Internal server error"` from a terraform deployment in West Europe.

**Comment by ronaldmiranda** [comment] 2019-09-26 04:07
Im getting the same message above on westus2

Code="ControlPlaneProvisioningInternalError" Message="Internal server error"

**Comment by kevinwedwards** [comment] 2020-04-30 13:42
We started getting this issue yesterday.  We deployed on Friday with no issues.  Now we can't run az aks update, nor can we reprovision via ARM template.
