### ISSUE TITLE
Azure CNI Overlay

### ISSUE THREAD

**Issue by seanmck** [Azure/AKS#3208] opened 2022-09-14 15:27 UTC
Tracking item for delivery of the Azure CNI Overlay solution:

https://docs.microsoft.com/en-us/azure/aks/azure-cni-overlay

**Comment by saswatmohanty01** [comment] 2022-09-19 14:19
When can we expect for Windows as it is highly demanded feature for Windows where customers use AKS for Windows as Azure CNI only support Windows customers.

**Comment by aysabzevar** [comment] 2022-10-25 06:53
At the moment *Azure CNI Overlay is currently only available in US West Central region.*

Could you let me know when Azure CNI Overlay will be available for other regions, i.e. West Europe?

**Comment by galibozek** [comment] 2022-10-31 18:02
+1 for Europe/West Europe

**Comment by weisdd** [comment] 2022-11-04 14:52
Also, would be great to know what's the current ETA for making it GA.
Thanks!

**Comment by divim** [comment] 2022-11-09 15:12
+1 for Europe/West Europe

**Comment by illrill** [comment] 2022-12-01 12:19
Is there any restriction on which IP range we can use for the pod CIDR (as there is with the traditional Azure CNI that [bans certain IP ranges](https://learn.microsoft.com/en-us/azure/aks/configure-azure-cni#prerequisites))?

> AKS clusters may not use 169.254.0.0/16, 172.30.0.0/16, 172.31.0.0/16, or 192.0.2.0/24 for the Kubernetes service address range, pod address range, or cluster virtual network address range.

**Comment by vinvli** [comment] 2022-12-14 17:35
+ 1 for (West) Europe

**Comment by palma21** [comment] 2022-12-26 15:03
Windows support is now available, look for the next release notes. 

Keep in mind Azure CNI Overlay is much better than kubenet, it has no limitations on cluster size and not performance impact, while still delivering non routable IPs for pods.

You can use any range for the private range with the exception of the ranges reserved by the service. The IP ranges not allowed are common to both CNI and kubenet and any other network options. They are reserved by the service, we are actually working on reducing/removing them which will be common to all options as well.

**Comment by slawekww** [comment] 2022-12-27 08:30
@palma21 Thank you for information and guidance. 

I wait for new AKS release notes 👍 
Now official MS docs state that Azure CNI Overlay is not supported by Windows: https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay#limitations-with-azure-cni-overlay
There is no information what IP ranges are not allowed for Azure CNI Overlay, at least reference to common not-allowed IP ranges.

I look for this feature supported in regions: East US 2, West Europe and SEA.

**Comment by hsunwenfang** [comment] 2023-01-12 00:16
Hi @palma21 

As documented,
https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay
Azure CNI Overlay networking in Azure Kubernetes Service (AKS) is already GA in 
- North Central US
- West Central US
- East US ASK
Is there an estimation GA date for **Australia** as well?
Thanks!!

**Comment by Garnaalkroket** [comment] 2023-01-17 07:49
Any ETA on when this would be available in West Europe? Would love to start using this.

**Comment by karthikmannem1991** [comment] 2023-02-01 17:31
Hi, is there any timeline for making the Azure CNI Overlay feature GA?

**Comment by yamansama** [comment] 2023-02-04 13:53
Any ETA for France central / west Europe ?

Could be really cool to know when I'll be able to use cilium on my Linux nodes without pod using IP from vnet

**Comment by Aldjinn** [comment] 2023-02-07 09:10
The feature should soon be available as preview in uksouth and australiaeast.

Source: https://github.com/Azure/AKS/releases/tag/2023-01-29

**Comment by JoeRistine** [comment] 2023-02-24 14:29
Will CNI overlay support separate worker node subnets for node pools (#1338)?

**Comment by jkroepke** [comment] 2023-03-05 13:57
https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay

> Azure CNI Overlay is currently unavailable in the West US region. All other public regions are supported.

It seems like the CNI Overlay is now available in a lot region, however:

> You can't use Application Gateway as an Ingress Controller (AGIC) for an overlay cluster.

I'm interest into the support for AGIC, there are any plans for it?

**Comment by BzSpi** [comment] 2023-03-06 07:50
Just saw that all regions except West US are now supported. Awesome :+1:
But, is it possible to have this ticket updated when new regions are supported ? Otherwise, there's no way to stay tuned.

@jkroepke I think you're looking for Azure CNI powered by Cilium which is approximately the same thing as CNI Overlay but with AGIC supported.

**Comment by jkroepke** [comment] 2023-03-06 10:18
> the same thing as CNI Overlay but with AGIC supported.

I hope thats true (and not just not documented) :D

**Comment by Flasheh** [comment] 2023-03-06 15:37
> @BzSpi do you have an idea, whats the Use Case of Azure CNI Overlay, if Cilium co-exists?

Cilium is not an alternative to CNI Overlay. It is a network plugin like kubenet or azure cni which can optionally also be deployed in cni overlay mode just like the azure cni.  
I have not tested this personally but I would assume it has the same limitations as the azure cni in overlay but I can't find any documentation to confirm this.

**Comment by jkroepke** [comment] 2023-03-06 16:32
Not sure, for me Cilium feels like an Network Policy only implement and uses Azure CNI and Azure CNI Overlay as Base (the same Feature toggle is required). I assume, the limitations are the same.

**Comment by michalgozdowski** [comment] 2023-03-17 12:15
I've just been testing Azure CNI Overlay in Private AKS Cluster and as it is not well described in documentation: is this expected behaviour that system pods in kube-system namespace got assigned IP addresses same as nodes, while the "non-system" pods are assigned IPs from provided CIDR?

**Comment by jkroepke** [comment] 2023-03-19 17:32
> I've just been testing Azure CNI Overlay in Private AKS Cluster and as it is not well described in documentation: is this expected behaviour that system pods in kube-system namespace got assigned IP addresses same as nodes, while the "non-system" pods are assigned IPs from provided CIDR?

Can't confirm this. Some pods are have `hostNetwork: true` enabled but most of them getting an CNI overlay. Make sense that not all system pods have a dependency against CNI.

**Comment by kevinharing** [comment] 2023-03-22 21:12
Will this be supported for existing clusters as well or only for newly created clusters?

**Comment by kevinharing** [comment] 2023-04-18 08:22
Now [GA](https://azure.microsoft.com/en-us/updates/azurecnioverlay/)! Upgrading existing clusters is [still in preview](https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay#upgrade-an-existing-cluster-to-cni-overlay---preview).

**Comment by jkroepke** [comment] 2023-04-18 09:42
From https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay

> You can't use Application Gateway as an Ingress Controller (AGIC) for an Overlay cluster.

I would like to now, if this is persistent limitation or will this fixed soon? Does have AGIC no priority?

Additionaly, can someone clarify this typo?

> Virtual Machine Scale Sets (VMAS) are not supported for Overlay

Are Virtual Machine Scale Sets not supported OR Are VM Availability Set not supported?

**Comment by bplasmeijer** [comment] 2023-04-18 12:46
Hi @palma21 

We use [Calico network policy](https://learn.microsoft.com/en-us/azure/aks/use-network-policies).
![image](https://user-images.githubusercontent.com/116467/232780747-42ff23f4-bf43-45d2-9a7d-9f9d363ed68b.png)

Anything on the roadmap that will unblock this CNI update/upgrade?

**Comment by kevinharing** [comment] 2023-04-18 13:01
> Hi @palma21
> 
> We use [Calico network policy](https://learn.microsoft.com/en-us/azure/aks/use-network-policies). ![image](https://user-images.githubusercontent.com/116467/232780747-42ff23f4-bf43-45d2-9a7d-9f9d363ed68b.png)
> 
> Anything on the roadmap that will unblock this CNI update/upgrade?

I think it only needs to be disabled during the upgrade.

**Comment by bplasmeijer** [comment] 2023-04-25 21:34
> > Hi @palma21
> > We use [Calico network policy](https://learn.microsoft.com/en-us/azure/aks/use-network-policies). ![image](https://user-images.githubusercontent.com/116467/232780747-42ff23f4-bf43-45d2-9a7d-9f9d363ed68b.png)
> > Anything on the roadmap that will unblock this CNI update/upgrade?
> 
> I think it only needs to be disabled during the upgrade.

Disable on PROD cluster, and then enable again sounds not good to me.

**Comment by jkroepke** [comment] 2023-04-25 21:52
You could scale to zero to prevent security breaches.

**Comment by satrox28** [comment] 2023-05-07 10:27
Hi,

Can we able to use Azure CNI Overlay with AGIC, if its not supported today, any plans to make it available on the near future.

**Comment by satrox28** [comment] 2023-05-17 09:34
> Now [GA](https://azure.microsoft.com/en-us/updates/azurecnioverlay/)! Upgrading existing clusters is [still in preview](https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay#upgrade-an-existing-cluster-to-cni-overlay---preview).

Any instructions on using Azure CNI Overlay on the existing cluster and nodepools?.

**Comment by rgarcia89** [comment] 2023-05-22 06:32
Seems like the Upgrade an existing cluster section is online again https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay#upgrade-an-existing-cluster-to-cni-overlay-preview

Has anyone tried it out already?
![image](https://github.com/Azure/AKS/assets/4134730/e858f636-64ed-4790-8101-02beacce970a)

**Comment by satrox28** [comment] 2023-05-22 08:45
> Seems like the Upgrade an existing cluster section is online again https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay#upgrade-an-existing-cluster-to-cni-overlay-preview
> 
> Has anyone tried it out already? ![image](https://user-images.githubusercontent.com/4134730/239821685-e858f636-64ed-4790-8101-02beacce970a.png)

I tried it last week and didn't work as expected.

It's under preview, for upgrade.

**Comment by satrox28** [comment] 2023-06-18 23:44
> > > Seems like the Upgrade an existing cluster section is online again https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay#upgrade-an-existing-cluster-to-cni-overlay-preview
> > > Has anyone tried it out already? ![image](https://user-images.githubusercontent.com/4134730/239821685-e858f636-64ed-4790-8101-02beacce970a.png)
> > 
> > 
> > I tried it last week and didn't work as expected, will be retrying shortly.
> > It's under preview by Microsoft for upgrade.
> 
> what version of the cli was this on? CNI Overlay migrations require 2.38.0+. We're updating the docs to reflect that shortly.

I am not sure about the version used, right now I have 2.48.1

I am noticing in the doc that if we have network policies enabled then unable to use the Azure CNI Overlay is it still true for new instance and upgrade?.

**Comment by rgarcia89** [comment] 2023-06-21 07:40
Upgrade is not working for me. Cluster was initially deployed with kubenet network-plugin and calico for network-polcy.

```
az aks update --name k8s-calico-lab --resource-group LAB --network-plugin-mode overlay --pod-cidr 10.244.0.0/16

The behavior of this command has been altered by the following extension: aks-preview
(PropertyChangeNotAllowed) Changing property 'networkProfile.networkPluginMode' is not allowed.
Code: PropertyChangeNotAllowed
Message: Changing property 'networkProfile.networkPluginMode' is not allowed.
Target: networkProfile.networkPluginMode
```

**Comment by jkroepke** [comment] 2023-06-21 07:58
@rgarcia89

You have to read the documentation more precisely. 

> You can update an **existing Azure CNI cluster** to Overlay if the cluster meets the following criteria

Which mean, you can upgrade to CNI overlay, if you already stay on Azure CNI

**Comment by slawekww** [comment] 2023-06-23 07:51
When GA for Windows support is planned for Azure CNI Overlay?
Note: no issues observed for Windows part, plan to use this feature on production clusters

**Comment by satrox28** [comment] 2023-06-23 18:50
> > > > Seems like the Upgrade an existing cluster section is online again https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay#upgrade-an-existing-cluster-to-cni-overlay-preview
> > > > Has anyone tried it out already? ![image](https://user-images.githubusercontent.com/4134730/239821685-e858f636-64ed-4790-8101-02beacce970a.png)
> > > 
> > > 
> > > I tried it last week and didn't work as expected, will be retrying shortly.
> > > It's under preview by Microsoft for upgrade.
> > 
> > 
> > what version of the cli was this on? CNI Overlay migrations require 2.38.0+. We're updating the docs to reflect that shortly.
> 
> I am not sure about the version used, right now I have 2.48.1
> 
> I am noticing in the doc that if we have network policies enabled then unable to use the Azure CNI Overlay is it still true for new instance and upgrade?.

I was able to update aks cluster to use Azure CNI Overlay successfully.

**Comment by jmp601** [comment] 2023-06-26 21:01
@satrox28 Is that an AGIC enabled cluster?

**Comment by satrox28** [comment] 2023-06-26 21:57
No,

I don't have AGIC enabled on the cluster.

Based on the doc, it's not supported.

**Comment by tyler-lloyd** [comment] 2023-06-28 14:19
> Thanks for the hint - I somehow missed the part where they mentioned that this works only for Azure CNI... Someone knows if there will be an upgrade path from kubenet to Azure CNI Overlay?

yes, kubenet -> CNI overlay work is in progress. Should be available in the next couple of months.

**Comment by palma21** [comment] 2023-08-11 18:44
Closing this since all issues here are about migration. Here's the 2 open issues on migration:

CNI Vnet to Overlay: https://github.com/Azure/AKS/issues/3720
Kubenet to Overlay: https://github.com/Azure/AKS/issues/3848

**Closed by palma21** 2023-08-11 18:44 UTC
Labels: feature-request, networking/azcni
