### ISSUE TITLE
Ubuntu 22.04

### ISSUE THREAD

**Issue by miwithro** [Azure/AKS#2897] opened 2022-04-13 15:25 UTC
Adding support for Ubuntu 20.04 on AKS.

**Comment by PixelRobots** [comment] 2022-04-14 10:40
https://github.com/Azure/AKS/issues/2883

**Comment by alexeldeib** [comment] 2022-04-21 16:23
@miwithro we've got a few existing issues for this, how about we close this as dupe? already closed a few others. 

2883 is tagged as a feature request.

**Comment by miwithro** [comment] 2022-04-21 16:28
closing duplicate to #2883

**Comment by jabbera** [comment] 2022-04-26 22:36
This looks like it will fix the issue I'm fighting with daily: https://github.com/Azure/AKS/issues/2911. Is this going into preview any time soon? Any way I can get in a private preview?

**Comment by miwithro** [comment] 2022-04-26 22:51
@jabbera we are working on a Public Preview date.  Follow this issue for updates.

**Comment by jabbera** [comment] 2022-04-26 22:52
Thanks!

**Comment by joejulian** [comment] 2022-05-04 17:38
This ticket was on the project board before it was closed as a duplicate of #2883, but #2883 is not. Should it be?

**Comment by jabbera** [comment] 2022-05-18 14:53
@miwithro Any way you can provide me a preview date? I'm currently struggling with support to get out of order UDP delivery enabled on my network so I can use NFS 3 instead but nothing seems to be easy:-)

**Comment by miwithro** [comment] 2022-05-18 17:06
@jabbera we are looking at Sept as the release date corresponding with the Release of 1.25

cc @justindavies

**Comment by jabbera** [comment] 2022-05-18 17:07
Oof. Thanks for the info!

**Comment by miwithro** [comment] 2022-06-03 17:23
@cpressland correct we decided to go with 22.04 instead of 20.04.  We are targeting AKS 1.25 for the release of 22.04.

**Comment by EppO** [comment] 2022-06-21 17:41
> @cpressland correct we decided to go with 22.04 instead of 20.04. We are targeting AKS 1.25 for the release of 22.04.

that means AKS 1.25 will use cgroups v2, right?

**Comment by alexeldeib** [comment] 2022-07-29 21:01
^yes!

**Comment by alexeldeib** [comment] 2022-07-29 21:02
gah I keep forgetting there's a dupe because one's 20.04 and 22.04 -_-

**Closed by alexeldeib** 2022-07-29 21:02 UTC
Labels: feature-request

**Comment by alexeldeib** [comment] 2022-07-29 21:04
for posterity updated https://github.com/Azure/AKS/issues/2897 to clarify we will move directly to 22.04
