### ISSUE TITLE
Enable adding managed identities to an aks cluster as an option rather than service principals

### ISSUE THREAD

**Issue by hectoralicea** [Azure/AKS#803] opened 2019-02-01 13:42 UTC
Right now it appears I need both managed identities and service principals to manage my kubernetes cluster. It would be nice if I can merge everything to use just managed identities since these show up in the resource group and not in the AAD.

The enhancement request is to allow managed identities object ids as inputs for the `--service-principal` or provide a second parameter `--assign-identity` to the `az aks create` command

To go along with this also provide a new command `az aks identity` to assign or remove manage identities from a cluster.

**Comment by jluk** [comment] 2019-08-29 20:45
We absolutely agree @hectoralicea thanks for the feedback! I'm going to close this ticket as a dupe of #993 which Jesse linked so everyone can track the latest info there. Thank you!

**Closed by jluk** 2019-08-29 20:45 UTC
Labels: triage
