### ISSUE TITLE
AKS shows internal source IP for request.

### ISSUE THREAD

**Issue by mcs-endk** [Azure/AKS#402] opened 2018-06-01 08:59 UTC
Hi, i was referred here by the Azure support team.

We have been developing a system based to move files internaly and externaly based on the bittorrent platform.

But we have discovered an issue. We have a docker image itdi/tracker:0.1 containing a tracker service which has a open UDP port on 6969.

The issue is that when we host the container in AKS. Then the tracker will return internal IPs for the peers instead of external IPs. But we don't have this issue when we run the tracker in docker on a virtual machine in Azure.

We use a second virtual machine for torrent test client in both cases.
External ip is '168.20.30.210'

**The Linux setup:**
We have set up a default docker VM and added the firewall rule to open port 6969.

Then we run the following command to start the instance:
docker run -d -p 6969:6969/udp itdi/tracker:0.1

When we then use our test program, and external ip shows: '168.20.30.210'

**The AKS setup:**
We start the container istance with the same container image: itdi/tracker:0.1
And configure it to open on port 6969 and on udp

When we now try to test the system, it will return an internal ip: '10.244.0.1'

![diagram](https://user-images.githubusercontent.com/35594045/40831649-dcb494a6-6589-11e8-95b5-33912982c9fe.jpg)

I have included a file containing the test files we use. It is a libtorrent based test program.

[test.zip](https://github.com/Azure/AKS/files/2061997/test.zip)

The IP Adresses are not the actual ones.

**Comment by JackQuincy** [comment] 2018-06-06 22:51
This is a by product of how KUBERNETES does network routing in the standard setup. There is a network plugin for azure called azure cni which would fix this issue. Sadly the cli doesn't support setting this up yet. this pr will add it. https://github.com/Azure/azure-cli/pull/6497 the change would be to add `--network-plugin azure` onto the create command and then the cluster should behave more how you want. The plugin gives every pod it's own ip address. I'm not 100% this will fix it but it seems likely as you shouldn't need to use iptables/kubeproxy to route things to the correct node/pod anymore.

**Comment by mcs-endk** [comment] 2018-06-20 10:44
Hi Jack,

We have tried using the network plugin. And we have also tried using node-port without success.

Do you have any other suggestions?

**Comment by JackQuincy** [comment] 2018-06-20 21:35
Sorry I've been busy today and was on phone which didn't have all the features I needed.
I don't have any other ideas. @khenidak  any ideas why this would happen?

**Comment by feiskyer** [comment] 2018-06-21 03:16
@mcs-endk  Have you set service.spec.externalTrafficPolicy=Local?  externalTrafficPolicy=Local is required for preserving source IPs.

**Comment by nunojsferreira** [comment] 2018-07-04 14:09
I am experiencing the same problem with an app that serves as HTTP hook which would then keep track of client IP. With this limitation the container no longer has visibility on the client IP.

We've also tried change the service spec to 
`externalTrafficPolicy=Local`
 
and even recreating the SVC with that configuration. But without success so far...

**Comment by lastcoolnameleft** [comment] 2018-11-06 16:07
I'm working with another partner that is experiencing a similar issue.  `externalTrafficPolicy=Local` did not resolve the issue for them either.  Any thoughts @khenidak ?

**Comment by TiagoJMartins** [comment] 2018-11-12 14:47
@lastcoolnameleft Take a look at https://github.com/Azure/AKS/issues/607

**Comment by lastcoolnameleft** [comment] 2018-11-12 17:19
Thanks @TiagoJMartins .  I'll look into this!

**Comment by RehanSaeed** [comment] 2019-02-22 11:23
Does Azure AKS support `externalTrafficPolicy=Local`?

**Comment by JunSun17** [comment] 2019-04-03 17:00
This is dupe of #607, it has been fixed now.

**Closed by JunSun17** 2019-04-03 17:00 UTC
