### ISSUE TITLE
Cluster networking gone intermittent

### ISSUE THREAD

**Issue by marekr** [Azure/AKS#554] opened 2018-07-24 22:34 UTC
I was mucking about with kubectl proxy earlier on a cluster that otherwise worked just fine. And I don't think it would be related but I went from a perfectly healthy cluster to one now having very intermittent networking.   It did somehow break the dashboard pod and it went into a restart crash loop with log messages about not being able to talk to the api server even though I could access just fine via the proxy. After killing the dashboard pod, and svc-redirect pods and heapster, the dashboard finally works. But now networking is poorly functioning with the symptons:

1. Pods intermittently no longer connect to Azure databases
2. Major slow downs in networking going outbound

CPU, memory usage, et al on nodes looks ok and theres nothing any of them do thats particularly heavy.
So I really don't understand how the cluster could fail on a kubectl proxy call unless theres something wrong with West Europe networking.

Edit: kube-dns has now gone rouge on me

```
E0724 23:12:09.581152       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Get https://XXXXX-ebd1ea44.hcp.westeurope.azmk8s.io:443/api/v1/services?resourceVersion=0: dial tcp: lookup XXXXX-ebd1ea44.hcp.westeurope.azmk8s.io on XXXXXX:53: read udp 10.1.0.50:55553-&gt;1XXXXXXX:53: i/o timeout
I0724 23:12:10.061612       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:10.558088       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:11.059996       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:11.554741       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:12.058721       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:12.555253       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:13.055115       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:13.558692       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:14.055892       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:14.556283       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:15.056161       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:15.556457       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:16.055665       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:16.558274       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:17.059528       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:17.558834       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:18.055038       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:18.558044       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...

I0724 23:12:18.558044       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:19.056042       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:19.556028       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:20.065416       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:20.555011       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:21.058159       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:21.557085       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:22.055449       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:22.554869       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:23.056413       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:23.558734       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:24.058835       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:24.555482       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:25.054575       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:25.559749       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:26.062075       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:26.555126       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:27.061087       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:27.555585       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0724 23:12:28.055991       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
F0724 23:12:28.554703       1 dns.go:167] Timeout waiting for initialization
```

Edit2: Over the last 8 hours since (9AM on July 25th EST), one of the nodes seems to have been the cause of networking failure with pods rapidly crashing out due to networking loss the entire night or just using stupid amounts of CPU due to networking loss. I cordoned and drained the pods off the node. Now everything is back to normal.

But the bad node is sitting at 20% CPU.

I don't like that a node's networking failed like this....

**Comment by marekr** [comment] 2018-07-25 13:58
Ok, the new node I spawned to replace the failing node has now started failing networking as well :(((((((((((((((((

```
Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "XXXXX-7dd6c69f8f-5c2gd_prod" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
```

This is absolutely a disaster.

**Comment by AaronFriel** [comment] 2018-07-30 16:36
Are you seeing symptoms like #568?

**Comment by marekr** [comment] 2018-07-30 16:54
That was one of the symptons. And every now and then a job will fail because it can't connect to a managed sql database on azure itself (lol)

**Comment by marekr** [comment] 2018-08-01 13:09
@AaronFriel A support guy is claiming it was due to OOM on one node in my case. (Which is true due to node logs). Though I do recall explicitly checking for OOM but only in the kubernetes dashboard. Its possible the node had something go bad and eat the memory outside kubernetes. I did have the issue that even after draining the node of pods, it was still eating 20% cpu that only went away once the node was restarted. Kubernetes was also unable to see that 20% cpu usage, only the azure portal could see it. (But at the time, I forgot you could still SSH into the nodes managed by AKS)

**Comment by rite2nikhil** [comment] 2018-08-07 20:39
Please perform a update operation (upgrade to same k8s or scale to same number of nodes) and bounce the kube-system/azureproxy pod, this would fix the issue you are seing, closing the incident, if this does not fix send your cluster info to aks-gh-feedback@service.microsoft.com with (subid, resource group and cluster name) and feel free to reopen the issue

**Closed by rite2nikhil** 2018-08-07 20:39 UTC

**Comment by marekr** [comment] 2018-08-08 13:09
@rite2nikhil I did upgrade to 1.10.6 about 10 hours before you posted, would it have any of the latest fixes?

I tried az upgrade (to the same version) in the command line since the portal won't let you issue a change that but it just returns the cluster config json after some delay. So I'm not sure what that means.

**Comment by rite2nikhil** [comment] 2018-08-08 15:05
@marekr did you follow the upgrade with bouncing (delete) the kube-system/azureproxy pod ? That should apply the patches. And they you can check if the problem is fixed, if not send your cluster info with reference to this github issue @ aks-help@services.microsoft.com

**Comment by marekr** [comment] 2018-08-10 14:15
@rite2nikhil Yea, I think it actually restarted the pods when I updated to 1.10.6. But almost all is well now (aks browse is still wonky).

Huge improvement by whatever was done behind the scenes. 


Here's a pretty graph where you can clearly see the change ;)
![image](https://user-images.githubusercontent.com/1838013/43962551-fe41d592-9c85-11e8-93fc-dca5aa8d1b34.png)

![image](https://user-images.githubusercontent.com/1838013/43962588-1e626846-9c86-11e8-81ef-c499c1700846.png)


I couldn't get those graphs before because of all the screwyness but Prometheus/Grafana were running.

**Comment by marekr** [comment] 2018-08-10 14:16
![image](https://user-images.githubusercontent.com/1838013/43962749-7bbf8f3c-9c86-11e8-872f-fb0c3767e060.png)


Lol, just wow. That was quite a bug fixed...
