### ISSUE TITLE
LoadBalancer still linked to a VMSS after all ingresses removed

### ISSUE THREAD

**Issue by stevehipwell** [Azure/AKS#2878] opened 2022-03-31 13:54 UTC
**What happened**:
When trying to uninstall a [Nginx Ingress](https://kubernetes.github.io/ingress-nginx/) Helm chart the service cannot be deleted due to the load balancer still being attached to a VMSS. We get the following error and the service still has the `service.kubernetes.io/load-balancer-cleanup` finalizer.

> Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: { "error": { "code": "LoadBalancerInUseByVirtualMachineScaleSet", "message": "Cannot delete load balancer /subscriptions/dfc7f929-6df6-4d6c-bf41-febd7f6dbd09/resourceGroups/mc_iob-aks-3/providers/Microsoft.Network/loadBalancers/kubernetes-internal since its child resources kubernetes are in use by virtual machine scale set /subscriptions/dfc7f929-6df6-4d6c-bf41-febd7f6dbd09/resourceGroups/mc_iob-aks-3/providers/Microsoft.Compute/virtualMachineScaleSets/aks-workers2-23049841-vmss.", "details": [] } }

**What you expected to happen**:
The service finalizer should be handled by the AKS code (in-tree cloud controller?) and the Helm chart should uninstall correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Install the [ingress-nginx](https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx) Helm chart and use the following values.

```yaml
controller:
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"

    type: LoadBalancer
    externalTrafficPolicy: Local
```

**Anything else we need to know?**:
n/a

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.9
- Size of cluster (how many worker nodes are in the cluster?): 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): n/a
- Others: n/a

**Comment by CocoWang-wql** [comment] 2022-04-02 18:13
Maybe it's caused by the LB reference still exists. You could refer to below doc and delete the LB reference to have a try.
https://docs.microsoft.com/en-us/azure/load-balancer/update-load-balancer-with-vm-scale-set#delete-a-load-balancer-used-by-a-virtual-machine-scale-set

**Comment by stevehipwell** [comment] 2022-04-02 18:17
@CocoWang-wql I know how to manually clean up, but that doesn't help me. The creation of the load balancer is automated and so should the deletion be.

**Comment by stevehipwell** [comment] 2022-04-22 14:22
It looks like this issue is potentially being caused by something that persists after a cluster has been destroyed, once this issue happens it always occurs each time I rebuild and destroy a cluster with the same name in the same subscription.

**Comment by Robert-Stam** [comment] 2022-06-24 15:14
Seems we have the same issue. Xref MS ticket: 2206130050000712

Resulting in a call and the result:
```
We have discussed about the issue from start and how it got fixed and how to avoid it in future over the call, also as we discussed please create a dummy load balancer on the cluster and do not delete it to avoid issues in future.

**Comment by stevehipwell** [comment] 2022-06-24 17:50
@Robert-Stam that doesn't sound like usable advice. These options work for IaC where clusters are treated as cattle. Suggesting not using internal LBs is completely missing the point.

**Comment by Robert-Stam** [comment] 2022-06-24 17:56
> @Robert-Stam that doesn't sound like usable advice. These options work for IaC where clusters are treated as cattle. Suggesting not using internal LBs is completely missing the point.

I fully agree, these options are from Microsoft (support) and only wants to share them here. We opted for 3 now.

**Comment by stevehipwell** [comment] 2022-06-24 19:09
@Robert-Stam not being able to delete your cluster seems like the ultimate cloud lock in!

**Comment by feiskyer** [comment] 2022-08-10 03:36
The issue has been fixed in https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2029 and would be included in AKS soon (ETA two weeks since this Monday).

Please upgrade the cluster to v1.22+ to have the fix.

**Closed by feiskyer** 2022-08-10 03:36 UTC
Labels: triage, action-required, Needs Attention :wave:
