### ISSUE TITLE
Cluster Internal Communication Failing

### ISSUE THREAD

**Issue by illfang** [Azure/AKS#646] opened 2018-09-13 01:04 UTC
**What happened**:
We are creating the same AKS cluster every day. Within 10 days, two AKS clusters have been reported as created but the cluster internal communication is not possible.

### 2018/09/13
[aks-default-15891270-0.txt](https://github.com/Azure/AKS/files/2377297/aks-default-15891270-0.txt)

```
--- 07:10 ---
$ kubectl exec .....

Error from server: error dialing backend: dial tcp 10.1.0.4:10250: i/o timeout

--- 07:27 ---
$ kubectl exec ...
Error from server: error dialing backend: dial tcp 10.1.0.4:10250: i/o timeout


---- 8:52 ----
$ az aks browse --resource-group xxxxxxx --name AKSCluster30e62a
Merged "AKSCluster30e62a" as current context in /var/folders/nm/1vhkrbl10778_z0sb103y1b80000gp/T/tmpxj1zq533
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
error: error upgrading connection: error dialing backend: dial tcp 10.1.0.66:10250: i/o timeout


$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

### 2018/09/04

[2018-09-04_kube-proxy.log](https://github.com/Azure/AKS/files/2377292/2018-09-04_kube-proxy.log)
[2018-09-04_netcat.log](https://github.com/Azure/AKS/files/2377293/2018-09-04_netcat.log)
[2018-09-04_pods.log](https://github.com/Azure/AKS/files/2377294/2018-09-04_pods.log)
[2018-09-04_tunnel-front.log](https://github.com/Azure/AKS/files/2377296/2018-09-04_tunnel-front.log)

```
$ az aks browse --resource-group xxxxxx --name AKSCluster6690b7
Merged 'AKSCluster6690b7' as current context in /var/folders/nm/1vhkrbl10778_z0sb103y1b80000gp/T/tmphdd4xwcy
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
error: error upgrading connection: error dialing backend: dial tcp 10.1.0.66:10250: i/o timeout 

$ kubectl exec .....
Error from server: error dialing backend: dial tcp 10.1.0.35:10250: i/o timeout

$ kubectl version
Client Version: version.Info{Major:'1', Minor:'11', GitVersion:'v1.11.2', GitCommit:'bb9ffb1654d4a729bb4cec18ff088eacc153c239', GitTreeState:'clean', BuildDate:'2018-08-07T23:17:28Z', GoVersion:'go1.10.3', Compiler:'gc', Platform:'linux/amd64'}
Server Version: version.Info{Major:'1', Minor:'11', GitVersion:'v1.11.2', GitCommit:'bb9ffb1654d4a729bb4cec18ff088eacc153c239', GitTreeState:'clean', BuildDate:'2018-08-07T23:08:19Z', GoVersion:'go1.10.3', Compiler:'gc', Platform:'linux/amd64'}
```

### Common:
In both cases kubectl apply deployed pods.
In both cases the tunnelfront service is failing because the tunnel dns could not be resolved.

```
{"log":"Resolving aks-cluster-30e62a-7ac5d971.tun.eastus.azmk8s.io (aks-cluster-30e62a-7ac5d971.tun.eastus.azmk8s.io)... failed: Name or service not known.\n","stream":"stderr","time":"2018-09-13T00:04:22.8530404Z"}
{"log":"Resolving aks-cluster-6690b7-889381e9.tun.eastus.azmk8s.io (aks-cluster-6690b7-889381e9.tun.eastus.azmk8s.io)... failed: Name or service not known.\n","stream":"stderr","time":"2018-09-04T05:51:27.638930904Z"}
```

**What you expected to happen**:
The communication within the cluster should reliably be possible.

**How to reproduce it (as minimally and precisely as possible)**:
```
	{
            "comments": "Generalized from resource: ....",
            "type": "Microsoft.ContainerService/managedClusters",
            "name": "[parameters('managedClusters_AKSCluster30e62a_name')]",
            "apiVersion": "2018-03-31",
            "location": "eastus",
            "scale": null,
            "properties": {
                "kubernetesVersion": "1.11.2",
                "dnsPrefix": "aks-cluster-30e62a",
                "agentPoolProfiles": [
                    {
                        "name": "default",
                        "count": 3,
                        "vmSize": "Standard_D2_v3",
                        "storageProfile": "ManagedDisks",
                        "vnetSubnetID": "[concat(resourceId('Microsoft.Network/virtualNetworks', parameters('virtualNetworks_WebVNET30e62a_name')), '/subnets/WebVNET-AppSubnet30e62a')]",
                        "maxPods": 30,
                        "osType": "Linux"
                    }
                ],
                "linuxProfile": {
                    "adminUsername": "xxxxxxxxxx",
                    "ssh": {
                        "publicKeys": [
                            {
                                "keyData": "ssh-rsa....."
                            }
                        ]
                    }
                },
                "servicePrincipalProfile": {
                    "clientId": "xxxxxxxxxxx"
                },
                "enableRBAC": false,
                "networkProfile": {
                    "networkPlugin": "azure",
                    "serviceCidr": "10.1.128.0/18",
                    "dnsServiceIP": "10.1.128.10",
                    "dockerBridgeCidr": "172.17.0.1/16"
                }
            },
            "dependsOn": [
                "[resourceId('Microsoft.Network/virtualNetworks', parameters('virtualNetworks_WebVNET30e62a_name'))]"
            ]
        },
```

**Anything else we need to know?**:
Support Request 2018/09/04: 118090418918581
Support Request 2018/09/13: 118091318996365

**Environment**:
- Kubernetes version (use `kubectl version`):
see above
- Size of cluster (how many worker nodes are in the cluster?)
3 agents - Standard D2 v3 (2 vcpus, 8 GB memory)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
simple web application
- Others:

**Comment by tomasr** [comment] 2018-09-14 14:35
Ran into the same thing on my own one-node test cluster a couple of days ago. Several issues have been reported in the last few months on this, without much clear response as to what is going on.

For me, the thing that worked (as suggested in one of the older threads) was to delete the `kube-dns`, `kube-proxy`, `kube-svc-redirect`, `omsagent`, and `tunnelfront`, and let them be recreated, and a few minutes after that, it suddenly started working again.

Definitely annoying; but I'm more concerned about the lack of a clear response from the AKS team as to what triggers this condition, to be honest.

**Comment by Turil** [comment] 2019-01-31 08:45
@tomasr - Could you solve this issue? Experiencing exactly the same error message (i/o timeout) when trying to run commands like "kubectl logs" etc.
Recreated the entire cluster twice, upgraded to latest version, no solution yet.

**Comment by dmiyamasu** [comment] 2019-02-06 20:53
We also are experiencing this issue.

**Comment by liambarnett** [comment] 2019-02-15 09:45
+1 also having this issue. Unfortunately, @tomasr workaround didn't work for us.

**Comment by amity0** [comment] 2019-02-17 19:35
also have the same issue after upgrading to 1.12.5

**Comment by jnoller** [comment] 2019-02-18 15:46
Please - everyone hitting this please file tech support requests in the azure portal with all subscription and cluster information, short description of symptoms and link to this issue. There’s a lot of variability here (kubenet vs azure CNI vs other issues) and we want to ensure we chase down all permutations

**Comment by rajeev1982** [comment] 2019-02-28 14:23
+1. Having this issue

**Comment by matthewhartstonge** [comment] 2019-04-18 00:11
@jnoller is there a way to do this without hitting the support paywall?
Being a managed service, if critical managed components break, I would expect there to be a way to access support :/

![Capture](https://user-images.githubusercontent.com/6119549/56327864-6c534880-61d0-11e9-9bc6-82ed428e62e9.PNG)
![Capture](https://user-images.githubusercontent.com/6119549/56327902-9a388d00-61d0-11e9-9622-8f6c524f5441.PNG)

We just had a 30 minute outage and very slow network performance due to either a tunnelfront upgrade/failure or the kube-api-server dying.

```
Name:               tunnelfront-668c7975c5-htpqv
Namespace:          kube-system
Priority:           1000000
PriorityClassName:  high-priority
Node:               aks-agentpool-18115853-0/10.240.0.4
Start Time:         Thu, 18 Apr 2019 10:41:32 +1200
Labels:             component=tunnel
                    pod-template-hash=668c7975c5
Annotations:        <none>
Status:             Running
IP:                 10.244.1.105
Controlled By:      ReplicaSet/tunnelfront-668c7975c5
Containers:
  tunnel-front:
    Container ID:   docker://fec6cbaf9fd0810d3e1b24b948ea11b85f0d3cca760ec6a89888cb0c3f092a50
    Image:          docker.io/deis/hcp-tunnel-front:v1.9.2-v4.0.6
    Image ID:       docker-pullable://deis/hcp-tunnel-front@sha256:4e40e3ac4064190682af1dd87d13b14ad7db1cf4fc21973e10852e30738a7de1
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 18 Apr 2019 10:54:01 +1200
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:     10m
      memory:  64Mi
    Liveness:  exec [/lib/tunnel-front/check-tunnel-connection.sh] delay=10s timeout=1s period=60s #success=1 #failure=12
    Environment:
      OVERRIDE_TUNNEL_SERVER_NAME:   t_REDACTED.hcp.australiaeast.azmk8s.io
      TUNNEL_CLUSTERUSER_NAME:       28819842
      TUNNELGATEWAY_SERVER_NAME:     REDACTED.tun.australiaeast.azmk8s.io
      TUNNELGATEWAY_SSH_PORT:        22
      TUNNELGATEWAY_TLS_PORT:        443
      KUBE_CONFIG:                   /etc/kubernetes/kubeconfig/kubeconfig
      KUBERNETES_PORT_443_TCP_ADDR:  REDACTED.hcp.australiaeast.azmk8s.io
      KUBERNETES_PORT:               tcp://REDACTED.hcp.australiaeast.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://REDACTED.hcp.australiaeast.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       REDACTED.hcp.australiaeast.azmk8s.io
    Mounts:
      /etc/kubernetes/certs from certificates (ro)
      /etc/kubernetes/kubeconfig from kubeconfig (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-kqzqt (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kubeconfig:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet
    HostPathType:
  certificates:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/certs
    HostPathType:
  default-token-kqzqt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-kqzqt
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age                From                               Message
  ----     ------       ----               ----                               -------
  Normal   Scheduled    34m                default-scheduler                  Successfully assigned kube-system/tunnelfront-668c7975c5-htpqv to aks-agentpool-18115853-0
  Warning  FailedMount  33m                kubelet, aks-agentpool-18115853-0  MountVolume.SetUp failed for volume "default-token-kqzqt" : Get https://REDACTED.hcp.australiaeast.azmk8s.io:443/api/v1/namespaces/kube-system/secrets/default-token-kqzqt: read tcp 10.240.0.4:43690->REDACTED (kube-api-server public IP)>:443: use of closed network connection
  Warning  FailedMount  33m                kubelet, aks-agentpool-18115853-0  MountVolume.SetUp failed for volume "default-token-kqzqt" : Get https://REDACTED.hcp.australiaeast.azmk8s.io:443/api/v1/namespaces/kube-system/secrets/default-token-kqzqt: read tcp 10.240.0.4:43900->REDACTED>:443: use of closed network connection
  Warning  FailedMount  32m                kubelet, aks-agentpool-18115853-0  MountVolume.SetUp failed for volume "default-token-kqzqt" : Get https://REDACTED.hcp.australiaeast.azmk8s.io:443/api/v1/namespaces/kube-system/secrets/default-token-kqzqt: read tcp 10.240.0.4:44426->REDACTED>:443: use of closed network connection
  Warning  FailedMount  31m                kubelet, aks-agentpool-18115853-0  MountVolume.SetUp failed for volume "default-token-kqzqt" : Get https://REDACTED.hcp.australiaeast.azmk8s.io:443/api/v1/namespaces/kube-system/secrets/default-token-kqzqt: read tcp 10.240.0.4:44976->REDACTED>:443: use of closed network connection
  Warning  FailedMount  30m                kubelet, aks-agentpool-18115853-0  MountVolume.SetUp failed for volume "default-token-kqzqt" : Get https://REDACTED.hcp.australiaeast.azmk8s.io:443/api/v1/namespaces/kube-system/secrets/default-token-kqzqt: read tcp 10.240.0.4:45614->REDACTED>:443: use of closed network connection
  Warning  FailedMount  29m                kubelet, aks-agentpool-18115853-0  MountVolume.SetUp failed for volume "default-token-kqzqt" : Get https://REDACTED.hcp.australiaeast.azmk8s.io:443/api/v1/namespaces/kube-system/secrets/default-token-kqzqt: read tcp 10.240.0.4:46332->REDACTED>:443: use of closed network connection
  Warning  FailedMount  26m (x4 over 34m)  kubelet, aks-agentpool-18115853-0  MountVolume.SetUp failed for volume "default-token-kqzqt" : Get https://REDACTED.hcp.australiaeast.azmk8s.io:443/api/v1/namespaces/kube-system/secrets/default-token-kqzqt: net/http: TLS handshake timeout
  Warning  FailedMount  23m                kubelet, aks-agentpool-18115853-0  MountVolume.SetUp failed for volume "default-token-kqzqt" : Get https://REDACTED.hcp.australiaeast.azmk8s.io:443/api/v1/namespaces/kube-system/secrets/default-token-kqzqt: read tcp 10.240.0.4:50276-><REDACTED>:443: use of closed network connection
  Warning  FailedMount  23m (x5 over 32m)  kubelet, aks-agentpool-18115853-0  Unable to mount volumes for pod "tunnelfront-668c7975c5-htpqv_kube-system(f227fed8-6161-11e9-b6ee-72156c8f919f)": timeout expired waiting for volumes to attach or mount for pod "kube-system"/"tunnelfront-668c7975c5-htpqv". list of unmounted volumes=[default-token-kqzqt]. list of unattached volumes=[kubeconfig certificates default-token-kqzqt]
  Normal   Pulled       21m                kubelet, aks-agentpool-18115853-0  Container image "docker.io/deis/hcp-tunnel-front:v1.9.2-v4.0.6" already present on machine
  Normal   Created      21m                kubelet, aks-agentpool-18115853-0  Created container
  Normal   Started      21m                kubelet, aks-agentpool-18115853-0  Started container
  Warning  Unhealthy    12m (x2 over 13m)  kubelet, aks-agentpool-18115853-0  Liveness probe failed:
```

**Comment by masonb81** [comment] 2019-05-09 05:35
+1 Same issue with a 3 node cluster, tried restarting & redeploying the nodes with no success.

**Comment by t0meck** [comment] 2019-05-29 05:39
> +1 Same issue with a 3 node cluster, tried restarting & redeploying the nodes with no success.

We had same case. Connection between nodes and master couldn't be correctly established. Restarting tunnelfront pod did not solve anything. Relocating it too.
What in our case helped analysis somehow was to check if our firewall wasn't blocking anything or malfunctioning. It turns out that although it shouldn't it was blocking connections. Sometimes "basic" license do have limitations on number of concurrent connections which are handled by the firewall. So check your case. If you have firewall before your cluster try to reroute cluster traffic so it will have direct access to the Internet for test purposes. You'll see that this will help. Moreover sometimes not everything is logged in firewall UI. Some firewalls do expose shell interface to debug connections. It's far more explaining than tcp_dump/wireshark analysis. Then you'll be able to see which input interface of firewall was used and which output one. How firewall searched for the route to direct packet to and other stuff. I encourage you to look on that. Shell isn't your enemy. On the contrary. It's your greatest friend. Right now we're in the middle of process of solving the case with our firewall vendor. Hope this will help you and others having similar case.

**Comment by poochwashere** [comment] 2019-06-18 23:54
+2 Same issue with a 3 node cluster...

I tried deleting/recreating the pods in `kube-system` and that did nothing. I also rebooted the node that was hosting `tunnelfront` and same same. 

I deployed a brand new cluster from scratch and I do not get the dialup error on those pods. 

*shrugs*

I opened a ticket with support several hours ago but have yet to receive a response.

**Comment by ball-hayden** [comment] 2019-07-16 16:06
I've seen this on a cluster with CNI and azure netpols enabled.
I've a ticket open with support, and we're trying to reproduce this in the agent's subscription.
So far, it's looking like the issue doesn't occur on the agent's subscription despite it repeatably occurring on mine (same commands to create the cluster, same workload in the cluster, same vnet config used, etc...).
I'll report back if we get anywhere.

**Comment by nwbt** [comment] 2019-08-06 19:27
@poochwashere any update worth sharing? 

I see this happening in a cluster with tunnelfront on version v1.9.2-v3.0.6, but not occurring on a cluster with version v1.9.2-v4.0.7. Is there a way to have the AKS cluster update to the v4.0.7 version?

**Comment by palma21** [comment] 2019-08-08 23:32
@nwbt please run `az aks upgrade `to a newer version

@ball-hayden that looks like the np could be blocking the needed api-agent comm. 
no np applied should just work. 
If you have a cluster without network policies that sees this please check firewall, proxy or nsg stopping traffic. If nothing is stopping traffic and you have no np, please open a ticket and feel free to report back. Ask for an escalation if your problem persists as we will need to investigate your specific clusters if that's the case.


I am closing this ticket now since the OP issues have been solved and at this point AKS has evolved and the proposed solutions throughout the issue are misleading or not recommended at this point.
Please do open a new support ticket or issue as necessary following https://github.com/Azure/AKS#bug-reports-


@matthewhartstonge those are the current support options but do follow up with an issue if necessary and can try to help here

**Closed by palma21** 2019-08-08 23:32 UTC
Labels: triage
