### ISSUE TITLE
Propagate custom user assigned tags to every dependent resource used by AKS cluster

### ISSUE THREAD

**Issue by mlushpenko** [Azure/AKS#1200] opened 2019-09-11 13:13 UTC
**What happened**: 
Specified tags are not used for all resources created during cluster provisioning. We have a policy that all resources should have a set of standard tags and it blocks creation of the cluster even though I specify needed tags.

**What you expected to happen**:
Cluster is created successfully and all resources have specified tags

**How to reproduce it (as minimally and precisely as possible)**:
Create policy that all resources need some tag. Try creating a cluster with that tag 

**Anything else we need to know?**:
So far looks like network security group and vnet are not receiving tags:
```
az aks create --resource-group rancher-prod-02 --name node-pools --enable-vmss --node-count 2 --generate-ssh-keys  --kubernetes-version 1.13.10 --tags environment=development
The behavior of this command has been altered by the following extension: aks-preview
Operation failed with status: 'Bad Request'. Details: Provisioning of resource(s) for container service node-pools in resource group rancher-prod-02 failed. Message: The template deployment failed with multiple errors. Please see details for more information.. Details: [{"code":"RequestDisallowedByPolicy","message":"Resource 'aks-vnet-19831696' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"Require a set of standard tags on the resource\",\"id\":\"/subscriptions/627cfc66-7737-474e-96ba-9b49fa86e1fd/providers/Microsoft.Authorization/policyAssignments/resource_tags_assignment\"},\"policyDefinition\":{\"name\":\"Audit tags for specific resources\",\"id\":\"/subscriptions/627cfc66-7737-474e-96ba-9b49fa86e1fd/providers/Microsoft.Authorization/policyDefinitions/tags_for_resources\"},\"policySetDefinition\":{\"name\":\"Require a set of standard tags on the resource\",\"id\":\"/subscriptions/627cfc66-7737-474e-96ba-9b49fa86e1fd/providers/Microsoft.Authorization/policySetDefinitions/resource_tags\"}}]'.","target":"aks-vnet-19831696"},{"code":"RequestDisallowedByPolicy","message":"Resource 'aks-agentpool-19831696-nsg' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"Require a set of standard tags on the resource\",\"id\":\"/subscriptions/627cfc66-7737-474e-96ba-9b49fa86e1fd/providers/Microsoft.Authorization/policyAssignments/resource_tags_assignment\"},\"policyDefinition\":{\"name\":\"Audit tags for specific resources\",\"id\":\"/subscriptions/627cfc66-7737-474e-96ba-9b49fa86e1fd/providers/Microsoft.Authorization/policyDefinitions/tags_for_resources\"},\"policySetDefinition\":{\"name\":\"Require a set of standard tags on the resource\",\"id\":\"/subscriptions/627cfc66-7737-474e-96ba-9b49fa86e1fd/providers/Microsoft.Authorization/policySetDefinitions/resource_tags\"}}]'.","target":"aks-agentpool-19831696-nsg"}]


az aks create --resource-group aks --name node-pools --enable-vmss --node-count 2 --generate-ssh-keys  --kubernetes-version 1.13.10 --tags environment=development --vnet-subnet-id /subscriptions/627cfc66-7737-474e-96ba-9b49fa86e1fd/resourceGroups/aks/providers/Microsoft.Network/virtualNetworks/aks/subnets/test-cluster
The behavior of this command has been altered by the following extension: aks-preview
Operation failed with status: 'Bad Request'. Details: Provisioning of resource(s) for container service node-pools in resource group aks failed. Message: Resource 'aks-agentpool-30157047-nsg' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"Require a set of standard tags on the resource","id":"/subscriptions/627cfc66-7737-474e-96ba-9b49fa86e1fd/providers/Microsoft.Authorization/policyAssignments/resource_tags_assignment"},"policyDefinition":{"name":"Audit tags for specific resources","id":"/subscriptions/627cfc66-7737-474e-96ba-9b49fa86e1fd/providers/Microsoft.Authorization/policyDefinitions/tags_for_resources"},"policySetDefinition":{"name":"Require a set of standard tags on the resource","id":"/subscriptions/627cfc66-7737-474e-96ba-9b49fa86e1fd/providers/Microsoft.Authorization/policySetDefinitions/resource_tags"}}]'.. Details:
```

**Comment by mlushpenko** [comment] 2019-09-16 08:55
I am not alone here :) https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/37248499-mc-resource-group-should-have-option-to-inherit-a

**Comment by jluk** [comment] 2019-09-16 19:52
Hey @mlushpenko

We're aware of this and it's in the backlog for now, but the provided functionality today only goes as far as propagating custom tags you set on your cluster's resource group to the MC resource group object. You can see more on this issue: https://github.com/Azure/AKS/issues/970

The underlying resources in there such as networking as you mentioned will not receive the tags propagated today. This is net new functionality so updating the title and adding tags for tracking.

**Comment by mlushpenko** [comment] 2019-09-16 21:08
Thanks @jluk. Could you explain why you consider this as a new functionality? To me this looks like an oversight or a bug. If I provide some tags to virtual machine, I expect network interface card or whatever direct children resources to get the tags as well, same for the cluster. Using policies is a best practice and now with this bug/feature the best practice can't be used easily (I've found one workaround though). So, to me it clearly looks like an issue with existing functionality rather than a feature request. I could be missing something, please correct me if I am wrong.

**Comment by mlushpenko** [comment] 2019-09-16 21:17
Also, I was writing some code recently using Azure API and providing tags to new resources, and from my limited knowledge, it's as simple as providing one extra parameter to each children resource. So, I am wondering how much work is it to fix this considering you already creating MC_* resource groups with proper tags. Don't know code complexity, but perhaps I could help?

**Comment by FilipeCoutinhoSantos** [comment] 2019-10-14 14:13
I agree with @mlushpenko this looks like a bug and not a new feature.
Is there any estimate to when it will be available?
Persisting the tags only at the MC_ resource group and not the child itens don´t make sense for a billing purpose.

**Comment by mlushpenko** [comment] 2019-10-14 14:43
We are using a workaround for now - a policy that targets MC_* resource groups and appends resource group tags to all children. And to me seems like a bug-proof solution as Azure guys can forget something similar in the future but our resources will still be tagged properly, so not even sure we will move away from it after the bug is fixed.

**Comment by bhicks329** [comment] 2019-10-14 19:15
Changing the tags on child objects is not supported and causes your cluster to not be supported. 

https://docs.microsoft.com/en-us/azure/aks/faq#can-i-modify-tags-and-other-properties-of-the-aks-resources-in-the-node-resource-group

**Comment by mlushpenko** [comment] 2019-10-14 19:28
hm...I wonder if that is related to the resource group where you create a cluster or auto-generated one. But we are only appending our tags, so perhaps it's not the same as changing and so far haven't noticed any problems

![image](https://user-images.githubusercontent.com/2006610/66777406-3fef5f00-eec9-11e9-892d-7a582ac1be29.png)

And here is a policy if you'd like to test it as well:

```
{
  "properties": {
    "displayName": "Append tag from resource group for aks clusters",
    "policyType": "Custom",
    "mode": "Indexed",
    "description": "Append tag from MC* resource groups to all child resources",
    "parameters": {
      "tagName": {
        "type": "String",
        "metadata": {
          "description": "Name of the tag, such as 'environment'",
          "displayName": "Tag Name"
        }
      }
    },
    "policyRule": {
      "if": {
        "allOf": [
          {
            "exists": "false",
            "field": "[concat('tags[', parameters('tagName'), ']')]"
          },
          {
            "notEquals": "",
            "value": "[resourceGroup().tags[parameters('tagName')]]"
          },
          {
            "like": "MC*",
            "value": "[resourceGroup().name]"
          }
        ]
      },
      "then": {
        "details": [
          {
            "field": "[concat('tags[', parameters('tagName'), ']')]",
            "value": "[resourceGroup().tags[parameters('tagName')]]"
          }
        ],
        "effect": "append"
      }
    }
  },
  "id": "/subscriptions/627cfca-9b49fa86e1fd/providers/Microsoft.Authorization/policyDefinitions/append_rg_tag",
  "type": "Microsoft.Authorization/policyDefinitions",
  "name": "append_rg_tag"
}
```

**Comment by jluk** [comment] 2019-11-13 16:45
Revisiting - apologies for delay.

@mlushpenko if that work around covers your scenario that's great since it would be locked to the MC RG and it fits your deployment style. Mentioned previously placing custom action on managed iaas by AKS isn't a directly supported scenario so if certain resources or edge cases are not caught by that solution it is at your own discretion.

We are going to deliver the ability to define tags within a nodepool to cover the tagging of compute resources for your cluster, this is driven by the scenario of a multi-tenant cluster with each team requiring their own unique tag for their node pool usage.

This leaves only the networking and storage resources untagged from AKS itself, given it covers many BYO scenarios and it isn't clear which owning team would need to tag those. If you have this requirement please share the interface and billing structure that fits your automation/deployment pipelines and we can discuss possible paths.

**Comment by mlushpenko** [comment] 2019-11-14 10:01
Thank for the reply @jluk. This policy has been working great so far for us. We just want all resources to be tagged per `environment`, `instance` and `tenant`, so that would include storage and networking as well. Those tags define our billing structure if I understood you correctly. The policy I shared does exactly what we need and what I put in issue description - propagates tags to every dependent resource, including networking and disks.

But in general, I would be happy if I didn't have to come with and maintain that policy :) By maintaining, I mean that we may change tags in the future and then I have to update policy as well. Maybe from a technical point of view, you could just do the same on your side when creating an MC resource group. You are adding some k8s specific tags anyway, so you could just merge them with user-defined ones I guess.

**Comment by jsmartt** [comment] 2020-02-01 00:13
The [release notes from 2020-01-27](https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-2020-01-27) say that now setting tags on the nodepool is allowed, and those will propagate automatically to all nodes in the nodepool. I haven't tried it yet, since that version isn't in the SDK I'm using, but it looks promising.

**Comment by jluk** [comment] 2020-02-01 01:27
@jsmartt to clarify, that feature captures this: https://github.com/Azure/AKS/issues/1344

This one is referencing not just the VMs in a nodepool, but all of the dependent resources in a cluster like storage/networking as well.

**Comment by julienym** [comment] 2020-06-01 12:41
As well as the cloud provider created ressources (disk, storage account, LB)

**Comment by sikovatc** [comment] 2020-11-03 15:13
any updates on this feature request?

**Comment by capusta** [comment] 2020-12-03 08:56
can we also throw in VMSS in there too ?  As of now any [terraform-assigned tags](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#tags) get propagated to the Azure AKS resource and further onto the MC-* group.  However, those tags do NOT end up being propagated to the VMSS and the VMs themselves, which is what actually gets counted in the cost report.

**Comment by jacqueskang** [comment] 2021-01-22 09:29
We have some Azure policies assigned to the subscription requiring some mandatory tags.
Due to this issue we are unable to create any AKS cluster.

Why exactly this is so difficult to implement? And no update since more than 1 year?

If we have already accepted to add custom tags to the MC resource group, why it becomes debatable when talking about individual resources inside the MC resource group?

**Comment by jacqueskang** [comment] 2021-01-22 09:53
What is more frustrating is we have even modified our tagging policies to exclude resources under "MC_*" resource groups, but it's till working.
Somehow when azure validates the ARM template it doesn't consider those MC resources be placed under MC_ resource group.

**Comment by jacqueskang** [comment] 2021-01-22 10:58
I would appreciate if anybody could provide a walkaround to deploy an AKS cluster without disabling custom tagging policy enforcement.

**Comment by jacqueskang** [comment] 2021-01-22 13:50
So we finished by modifying our tagging policy in the following (dirty) way: 

```json
 {
    "if": {
        "not": {
            "anyOf": [
                {
                    "value": "[resourceGroup().name]",
                    "like": "MC_*"
                },
                {
                    "field": "name",
                    "like": "aks-vnet-*"
                },
                {
                    "field": "name",
                    "like": "aks-agentpool-*"
                },
                {
                    "field": "tags[env]",
                    "in": [
                        "dev",
                        "test",
                        "verif",
                        "preprod",
                        "prod"
                    ]
                }
            ]
        }
    },
    "then": {
        "effect": "deny"
    }
}
```

**Comment by brkifle** [comment] 2021-05-18 14:17
Support for propagating custom user assigned tags to every dependent resource is currently in development. You can track the progress of this feature here: https://github.com/Azure/AKS/projects/1

**Comment by PixelRobots** [comment] 2021-06-09 08:09
As this is now in public preview, do we have any docs to look at? Or will it just work?

**Comment by wangyira** [comment] 2021-07-20 18:18
@palma21 Do you know if there's documentation on this?

**Comment by dentad** [comment] 2021-09-20 09:07
We have an issue where a custom tag with a value containing commas is migrated, but the dependent resource gets the value truncated just before the first comma. For multiple tags, each tag value get truncated the same way.

Not an issue with k8s 1.19.11, but an issue after upgrading the control plane only to 1.20.9.

**Comment by aristosvo** [comment] 2021-09-20 10:26
Can we expect to also propagate to i.e. the ContainerInsights add-on? That would be really awesome!

**Comment by dentad** [comment] 2021-09-20 23:45
We have an issue where a custom tag with a value containing commas is migrated, but the dependent resource gets the value truncated just before the first comma. For multiple tags, each tag value get truncated the same way.

Not an issue with k8s 1.19.11, but an issue after upgrading the control plane only to 1.20.9.

**Comment by mattruma** [comment] 2021-11-19 16:50
What is the status of this? Seems like it is no long in public preview?

**Comment by annerajb** [comment] 2021-12-09 17:22
> So we ended up by modifying our tagging policy in the following (dirty) way:
> 
> ```json
>  {
>     "if": {
>         "not": {
>             "anyOf": [
>                 {
>                     "value": "[resourceGroup().name]",
>                     "like": "MC_*"
>                 },
>                 {
>                     "field": "name",
>                     "like": "aks-vnet-*"
>                 },
>                 {
>                     "field": "name",
>                     "like": "aks-agentpool-*"
>                 },
>                 {
>                     "field": "tags[env]",
>                     "in": [
>                         "dev",
>                         "test",
>                         "verif",
>                         "preprod",
>                         "prod"
>                     ]
>                 }
>             ]
>         }
>     },
>     "then": {
>         "effect": "deny"
>     }
> }
> ```

i just came here after having todo the same in my case i so far only seen the nsg failure so have this: `"like": "aks-agentpool-*-nsg"` and a separate one for ignoring kubernetes created / managed pvcs 

> {
>   "field": "[concat('tags[', parameters('kubernetes_pvc_tagName'), ']')]",
>   "notEquals": ""
>  },

**Comment by siegenthalerroger** [comment] 2022-01-03 10:03
We're also encountering some weirdness surrounding this, though it may be specific to our IT-providers configuration. It appears some tags are being (or were for a while) being propagated, others are not. For us specifically adding the tags to the node-pool and the aks-service was enough, however adding new managed services would fail (e.g. container insights) so this is still a required feature from AKS.

**Comment by OlehZarevych** [comment] 2022-01-20 23:02
Any updates ?

**Comment by byteknacker** [comment] 2022-02-23 16:52
I really need this feature as I have to work around this for now. I have an Azure Policy that blocks the creation of resources without a certain tag. If the tags do not propagate through, then the policy is non-compliant.

**Comment by mmckechney** [comment] 2022-03-01 20:04
It appears that some resources are still not getting tags. Running a create command:
`az aks create --resource-group <rg> --name <cluster> --tags dept=IT costcenter=9999  --generate-ssh-keys`

Tags are not getting added to these resources in the managed resource group:

- Route Table
- Managed Identity 

When running an update
`az aks update --resource-group <rg> --name <cluster> --tags dept=IT costcenter=9999 `

Tags are not getting added to these resources in the managed resource group:

- Public IP Address
- Network Security Group
- Virtual Network
- Load Balancer
- Managed Identity

**Comment by miwithro** [comment] 2022-03-03 18:56
@mmckechney the key for AKS RP Tags is that they only apply to AKS managed resources.  In the case of the Route Table and the MI they are not actually AKS RP managed resources.  So in order to get the same tags on those resources I would recommend customers also run “az tag” on those individual resources to line things up.

For the Managed Resource Group tags, AKS does/will tag them.  I believe the issue you are eluding to was actually an Azure Policy problem that has now been fixed.

**Comment by artisticcheese** [comment] 2022-03-31 17:30
@miwithro Can you please clarify your statement about tagging on AKS managed resources vs non-managed resources. When we use ARM template we just specify what resources we want to create and tags for them, what happens inside ARM processing is beyond something we control. Who's responsibility for this to resolve? We are using IaC and hence can not rely on imperative commands to circumvent platform limitations. As of right now route table as well as NSG which is created by deployment is not automatically tagged and hence as of March 31, 2022 it's impossible to deploy AKS via infrastructure code with all resources tagged per customer's requirement

**Comment by mlushpenko** [comment] 2022-03-31 21:56
@artisticcheese I see this issue as open, am I missing something?

**Comment by artisticcheese** [comment] 2022-03-31 22:26
Sorry, this was meant for Microsoft. It's marked as done in AKS story

![image](https://user-images.githubusercontent.com/13176884/161159833-3b7830c9-200c-485a-8dd3-89c674cf36d4.png)

**Comment by miwithro** [comment] 2022-04-04 15:55
We have GA'ed AKS Resource Tags already.  We are adding in some more tagging capabilities for additional resources like NAT Gateway, multiple Load balancers, private link resources etc.

**Comment by artisticcheese** [comment] 2022-04-04 15:59
@miwithro But this does not work as you can see. How it can go GA in such state? The list is above which does not get tags added. Resources you mentioned are not in that list. Is there a list which resources are supported and which are not?

**Comment by miwithro** [comment] 2022-05-17 10:43
@artisticcheese I moved it to GA because we added everything native to the AKS RP.  Now we are adding LBs, IPs, Identities etc to increase the coverage of what can be tagged.  To clean up the confusion I just moved it back to In Progress too.

**Comment by byteknacker** [comment] 2022-05-25 08:31
It would be great to 1. be able to tag any resource that is associated with the AKS at creation time including auto-generated resources 2. actually tagging those auto-generated resources with the same tags inherited by the tags attached to the AKS. 

If this is not possible, then Azure Policies requiring all resources and resource groups to be tagged will cause the creation of AKS and its auto-generated resources to fail. I also suggest to generally not to separate the creation of AKS from the creation of associated resources. This adds complexity and is a headache to track with Terraform. 

If you write just for the AKS on Terraform, then the default node pool is auto-generated but they are "untracked". If you use another resource to "track" the auto-generated default node pool, then not all features are in Terraform nor can you control it properly in the Azure Portal. 

Either give us all the control for the auto-generated items or keep them together the AKS itself. I would prefer all the associated resources to be grouped somehow into one giant AKS resource where I can control prior to creation everything except the master node perhaps. I would even like to have some sort of control over the master node except the ones of maintenance.

**Comment by artisticcheese** [comment] 2022-05-31 21:50
> Hey all, You can now tag the following resources on AKS.
> 
> The AKS cluster The route table that's associated with the cluster The public IP that's associated with the cluster The network security group that's associated with the cluster The virtual network that's associated with the cluster The AKS managed kubelet msi associated with the cluster The AKS managed addon msi associated with the cluster The private DNS zone associated with the private cluster The private endpoint associated with the private cluster

How do you test this? Do we need to use specific version of API or it's enabled by default for any new clusters?

**Comment by byteknacker** [comment] 2022-07-06 09:22
Does this error still persist if you use terraform? I had to set my Azure policies to audit only because I cannot enforce tagging on all resources due to this behaviour. If I do enforce deny action using Azure policies, then those auto-generated Azure resource for AKS will not be able to spin up because some of them cannot get the tags inherited. 

I can see two kind of solutions: either Azure makes so that all the auto-generated resources will automatically inherit all tags from the parent AKS resource or you do not auto-generate anything and let the user configure and control the all sub-components of the AKS cluster.

**Comment by miwithro** [comment] 2022-07-07 18:48
@byteknacker These items can now be tagged.

The AKS cluster
The route table that's associated with the cluster
The public IP that's associated with the cluster
The load balancer that's associated with the cluster
The network security group that's associated with the cluster
The virtual network that's associated with the cluster
The AKS managed kubelet msi associated with the cluster
The AKS managed addon msi associated with the cluster
The private DNS zone associated with the private cluster
The private endpoint associated with the private cluster

Is there something else you need tagged?

**Comment by artisticcheese** [comment] 2022-07-07 19:03
@miwithro Were there some changes made recently? After your original message on May 31st this did not work for any of us. You seem just cut and paste original message right now. So were there additional changes done since May 31st to make it work since it did not work for us so far.

**Comment by miwithro** [comment] 2022-07-07 19:24
@artisticcheese yes we added a few new components in the last release.  Can you update your cli and try again.

**Comment by artisticcheese** [comment] 2022-07-07 19:55
Still does not work for me. I deploy through portal.
```
Reconcile route table failed. Details: RouteTableReconciler retry failed: Category: ClientError; Code: Unspecified; SubCode: RequestDisallowedByPolicy; Message: ; InnerMessage: ; Dependency: Microsoft.Network/routeTables; OrginalError: Code=\"RequestDisallowedByPolicy\" Message=\"Resource 'aks-agentpool-37296500-routetable' was disallowed by policy. Policy identifiers: '[{\\\"policyAssignment\\\":{\\\"name\\\":\\\"Enforce playground tagging\\\",\\\"id\\\":\\\"/providers/Microsoft.Management/managementGroups/development-mg/providers/Microsoft.Authorization/policyAssignments/e5d171efe8cb457ba756ff4e\\\"},\\\"policyDefinition\\\":{\\\"name\\\":\\\"Intapp allow tag and array of specific values\\\",\\\"id\\\":\\\"/providers/Microsoft.Management/managementGroups/DevOps-mg/providers/Microsoft.Authorization/policyDefinitions/3fc12572-8986-4885-9778-73a83b686116\\\"}}]'.\" Target=\"aks-agentpool-37296500-routetable\" AdditionalInfo=[{\"info\":{\"evaluationDetails\":{\"evaluatedExpressions\":[{\"expression\":\"type\",\"expressionKind\":\"Field\",\"expressionValue\":\"Microsoft.Network/routeTables\",\"operator\":\"NotEquals\",\"path\":\"type\",
```

**Comment by miwithro** [comment] 2022-07-07 20:01
@artisticcheese  which API are you using?

**Comment by miwithro** [comment] 2022-07-07 20:02
@zjpjack

**Comment by zjpjack** [comment] 2022-07-07 21:04
@artisticcheese you add mc some new tags on portal and then got that error? Or you create mc on portal then got that error?

**Comment by artisticcheese** [comment] 2022-07-07 21:06
I go to portal, choose to create new kubernetes cluster, provide required tags, it successfully submits and then errors out in about 10 minutes with cluster resource created and error attached being shown

**Comment by chandraneel** [comment] 2022-07-08 20:26
@artisticcheese thanks for reporting the issue, we are taking a look at the portal side of the changes. Will update here once we identify the fix.

**Comment by mahia127** [comment] 2022-07-13 07:16
@miwithro adding VMs and storage accounts to the list of resources which should be tagged

**Comment by zjpjack** [comment] 2022-07-21 19:26
@artisticcheese The issue is fixed. We will start to release it next Monday

**Comment by imtarunsingh** [comment] 2022-08-01 05:15
Issue is still not fixed. We are facing the same error. 

`(ReconcileRouteTableError) Reconcile route table failed. Details: RouteTableReconciler retry failed: Category: ClientError; Code: Unspecified; SubCode: RequestDisallowedByPolicy; Message: ; InnerMessage: ; Dependency: Microsoft.Network/routeTables; OrginalError: Code="RequestDisallowedByPolicy" Message="Resource 'aks-agentpool-********-routetable' was disallowed by policy. Reasons: 'Require a tag \"CreatedBy\" for this resource.'. See error details for policy resource IDs." Target="aks-agentpool-********-routetable" AdditionalInfo=[{"info":{"evaluationDetails":{"evaluatedExpressions":[{"expression":"tags[CreatedBy]","expressionKind":"Field","operator":"Exists","path":"tags[CreatedBy]","result":"True","targetValue":"false"}],"reason":"Require a tag \"CreatedBy\" for this resource."},"policyAssignmentDisplayName":"Require a tag \"CreatedBy\" on resources","policyAssignmentId":"/providers/Microsoft.Management/managementGroups/******/providers/Microsoft.Authorization/policyAssignments/*****","policyAssignmentName":"**********","policyAssignmentScope":"/providers/Microsoft.Management/managementGroups/GSInitiatives","policyDefinitionDisplayName":"Require a tag on resources","policyDefinitionEffect":"deny","policyDefinitionId":"/providers/Microsoft.Authorization/policyDefinitions/****","policyDefinitionName":"********"},"type":"PolicyViolation"}]; AKSTeam: Networking, Retriable: false.`

**Comment by zjpjack** [comment] 2022-08-01 07:54
@imtarunsingh this fix hasn't been rolled out to any major regions. What region you are trying to use? I will update here when the fix hits that region

**Comment by imtarunsingh** [comment] 2022-08-01 08:44
> @imtarunsingh this fix hasn't been rolled out to any major regions. What region you are trying to use? I will update here when the fix hits that region

East US

**Comment by zjpjack** [comment] 2022-08-15 18:34
@imtarunsingh please try again, the fix is rolled out to eastus

**Comment by artisticcheese** [comment] 2022-08-15 18:39
> @imtarunsingh please try again, the fix is rolled out to eastus

What about other regions? Can you provide full list where it's supposed to be available?

**Comment by zjpjack** [comment] 2022-08-15 21:00
@artisticcheese other regions are available too

**Comment by mazwettler** [comment] 2022-08-30 13:43
Is there a way to stop AKS from propgating tags to related resources?
We run into issues because we have a different on our route-table then on AKS, and AKS keeps overwriting the tags on the route-table.

**Comment by mazwettler** [comment] 2022-08-31 06:47
We have different teams for managing network resources and application resources like aks cluster. So network team wants to put tags like "created-by:noc" on the route table which gets overwritten once the aks is deployed by developers which use tag "created-by:dev-team".
Even if we change it afterwards again back to "noc" it instantly gets overwritten again by aks managed identity.

**Comment by byteknacker** [comment] 2022-09-03 17:01
Ok, it is good to see that some users actually do not want the tags to be propagated. I think the problem is just that when you set up an AKS, Azure automatically creates some additional resources that you then can actually see inside the console having a somehow different lifecycle and tagging possibility. Maybe it is good to let the customer choose at the creation time whether or not to propagate tags to automatically generated resources. The other way around is to hide the auto generated resources from us and do not display it on Azure portal at all. All of the information that we will get will be inside of the actual AKS resource and not in a newly created resource group. You can still manage everything but only inside the AKS resource. 

For now I made my Azure policies such that it does not deny any creation. So I cannot test which tags are still required. But in general, it should be all the resources that are also checked by Azure Policies and that are displayed as a separate resource in the Portal. This is the only logical solution in my opinion. Otherwise, Azure policies will say: here is a resource A that is not tagged, you cannot create it. But resource A is auto generated by Azure because of an AKS creation. It does not make sense. You have to sync Azure Policies and any auto generated resource within Azure in such a way that it is consistent.

**Comment by artisticcheese** [comment] 2022-09-03 17:47
Having tags on depended resources is not just housekeeping issue but it's also used for cost attribution and management. Regardless whether those are shown or not they need to have tags for cost purposes

**Comment by Stretch96** [comment] 2022-10-28 16:10
I ended up doing this:

https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/pull/32

Which is basically a script ran after the creation of the Azure Container App envrionment to find the associated 'MC_' resource group, and add the tags in

**Comment by cristian98149** [comment] 2022-12-13 08:32
Hi all,
I'm experiencing the same issue but with Container Insight. I have an Azure Policy that requires some tags and the deployment fails because tags specified to aks resource are not reported to Container Insight resource that is automatically created by Azure during AKS deployment.

`"statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"AddContainerInsightsSolutionError\",\"message\":\"Resource request failed due to RequestDisallowedByPolicy. Please see https://aka.ms/aks-requestdisallowedbypolicy for more details. The detailed error message: Code=\\\"RequestDisallowedByPolicy\\\" Message=\\\"Resource 'ContainerInsights(aks)' was disallowed by policy. Reasons: 'The resorce must be compliant to policy 'Resources Tags': Enforces required tags Environment, Client ad Purpose.'. See error details for policy resource IDs.\\\" Target=\\\"ContainerInsights(aks)\\\" AdditionalInfo=[{\\\"info\\\":{\\\"evaluationDetails\\\":{\\\"evaluatedExpressions\\\":[{\\\"expression\\\":\\\"tags[Environment]\\\",\\\"expressionKind\\\":\\\"Field\\\",\\\"operator\\\":\\\"Exists\\\",\\\"path\\\":\\\"tags[Environment]\\\",\\\"result\\\":\\\"True\\\",\\\"targetValue\\\":\\\"false\\\"}],\\\"reason\\\":\\\"The resorce must be compliant to policy 'Resources Tags': Enforces required tags Environment, Client ad Purpose.\\\"},\\\"policyAssignmentDisplayName\\\":\\\"\\\",\\\"policyAssignmentId\\\":\\\"/subscriptions/**************/providers/Microsoft.Authorization/policyAssignments/subscription******\\\",\\\"policyAssignmentName\\\":\\\"subscription************\\\",\\\"policyAssignmentParameters\\\":{\\\"client\\\":\\\"Client\\\",\\\"environment\\\":\\\"Environment\\\",\\\"purpose\\\":\\\"Purpose\\\"},\\\"policyAssignmentScope\\\":\\\"/subscriptions/****************************\\\",\\\"policyDefinitionDisplayName\\\":\\\"Resources Tags\\\",\\\"policyDefinitionEffect\\\":\\\"deny\\\",\\\"policyDefinitionId\\\":\\\"/subscriptions/*****************/providers/Microsoft.Authorization/policyDefinitions/resources-tags\\\",\\\"policyDefinitionName\\\":\\\"resources-tags\\\"},\\\"type\\\":\\\"PolicyViolation\\\"}]\"}]}}",`

**Comment by MarkKharitonov** [comment] 2022-12-16 16:35
We have exactly the same situation as described in https://github.com/Azure/AKS/issues/1200#issuecomment-1231689872 by @mazwettler - we create out RTs before the AKS cluster and yet AKS cluster assumes ownership on the RTs by pushing its tags to it.

I did not have the time to read the entire thread, so it is possible someone already reported it. The real problem is that suppose we want to change the tags on the RT. Since AKS cluster decided to own it, it would push its own tags onto the RT. Moreover, even if we want to synchronize the tags on AKS and on RT we witnessed a situation where the tags were changed by us on both AKS and RT and yet the cloud controller manager had the old tags still cached and was pushing them onto the RT, even though the AKS cluster had the new tags.

The support tracking case (for those who can access it) is 2211240040006776

**Comment by palma21** [comment] 2022-12-16 18:43
Last comment is more about not having tags, whereas this thread is about having. The short answer there is it depends on the RT case. A case of User Defined Route, the UDR is not owned by AKS or K8s and is not tagged. A kubenet case, the RT is indeed used by k8s (it's essential to the functioning of kubenet) and is owned by k8s (not AKS per se). FYI the new overlay mode is better and more recommended and doesn't require route tables.

For the comments above on lack of tags, please do open a ticket and we'll see if there's a gap or the best way for it. Typically Azure monitor workspaces are deployment independently of AKS, so they aren't tag, but you can tag them though or precreate them already tagged. But we're happy to look into it

**Comment by MarkKharitonov** [comment] 2022-12-17 05:34
@palma21 - would you happen to know when the overlay mode will not require a preview feature enabled? Long shot, but maybe you know when the azurerm terraform provider will be updated with this feature?

**Comment by aristosvo** [comment] 2022-12-17 08:34
> Long shot, but maybe you know when the azurerm terraform provider will be updated with this feature?

This seems to have made it already in the `azurerm` Terraform provider: https://github.com/hashicorp/terraform-provider-azurerm/issues/19397

**Comment by MarkKharitonov** [comment] 2022-12-17 19:58
@aristosvo - excellent. I just assumed it was not there yet, glad to be wrong. Thank you.

**Comment by timja** [comment] 2022-12-20 13:32
Still doesn't seem to work properly from the CLI =/

```
az aks create \
    --resource-group ${GROUP} \
    --location uksouth \
    --name ${MEMBER_CLUSTER_1} \
    --node-count 1 \
    --network-plugin azure \
    --vnet-subnet-id "/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${GROUP}/providers/Microsoft.Network/virtualNetworks/${FIRST_VNET}/subnets/${MEMBER_1_SUBNET}" \
    --generate-ssh-keys \
    --tags application=core builtFrom=timja-local businessArea=anything expiresAfter=2022-12-24 environment=sandbox
```

This is following the fleet manager sample:
https://learn.microsoft.com/en-gb/azure/kubernetes-fleet/quickstart-create-fleet-and-members

VMSS does not have the tags passed down

![image](https://user-images.githubusercontent.com/21194782/208678737-dd0f8fde-80fb-41a1-bfe2-9dea8285afce.png)

```
(RequestDisallowedByPolicy) Provisioning of resource(s) for container service aks-member-1 in resource group timja-fleet-test failed. Message: Resource 'aks-nodepool1-46417579-vmss' was disallowed by policy. Reasons: 'Resource doesn't meet the tagging requirements'. See error details for policy resource IDs.. Details:
Code: RequestDisallowedByPolicy
Message: Provisioning of resource(s) for container service aks-member-1 in resource group timja-fleet-test failed. Message: Resource 'aks-nodepool1-46417579-vmss' was disallowed by policy. Reasons: 'Resource doesn't meet the tagging requirements. See https://github.com/hmcts/azure-policy/blob/master/policies/tagging/README.md'. See error details for policy resource IDs.. Details:
```

**Closed** 2023-02-03 19:36 UTC
Labels: enhancement, feature-request, resolution/shipped

**Comment by timja** [comment] 2023-02-07 11:41
@kaarthis why did you just randomly close this?

I just reproduced https://github.com/Azure/AKS/issues/1200#issuecomment-1359353943 in UK South at least
