### ISSUE TITLE
customize node config

### ISSUE THREAD

**Issue by unacao** [Azure/AKS#323] opened 2018-04-24 22:54 UTC
Is there any way to customize the kubelet config such as KUBELET_HARD_EVICTION_THRESHOLD in the AKS cluster?

**Comment by slack** [comment] 2018-04-25 02:38
Right now no, beyond `EVICTION_THRESHOLD` what would you like to configure?

**Comment by unacao** [comment] 2018-04-25 18:12
possibly the configuration mentioned here #245

**Comment by sfrolich** [comment] 2018-05-07 21:05
I have some rather large images in ACR that timeout pulling the images. Some info here:
https://blog.openai.com/scaling-kubernetes-to-2500-nodes/
https://github.com/Azure/AKS/issues/245

changing to KUBELET_OPTS=--image-pull-progress-deadline=10m
on all my agent nodes solved my problem.

Being able to edit these should be made easier as I'm sure as more and more customers use AKS, each customer's scenario will require changing kubelet options.

**Comment by kautsig** [comment] 2018-05-08 09:20
This seems like a duplicate of #245

**Comment by doubleyewdee** [comment] 2019-03-01 21:53
I'm actually curious about whether and how we could use a different option (--cpu-manager-policy) passed in to KUBELET_OPTS as part of our node provisioning. Is there a generic way to do this or is the plan to expose specific functionality through other AKS knobs and have those turn on the appropriate flags indirectly for users?

**Comment by jnoller** [comment] 2019-03-01 22:21
@doubleyewdee It would be the latter - depending on the complexity of the option (some aren't well suited for AKS as a managed solution). AKS would expose the knobs and then handle application behind the scenes.

**Comment by zerda** [comment] 2019-08-06 15:24
How about [Dynamic Kubelet Configuration](https://kubernetes.io/blog/2018/07/11/dynamic-kubelet-configuration/) ?

I'm using `--authentication-token-webhook=true` to enable service account tokens to be used to authenticate to the kubelet.

It's required by `kube-prometheus` to scrape the kubelet metrics.

**Comment by henrylilei** [comment] 2019-08-30 10:22
@jnoller I understand that certain configs are not suitable for managed AKS, but is it possible to have a blacklist/whitelist on the dynamic configurations? So that we can at least setup the cluster and VMSS better suited to the latency sensitive production traffic.

Some of the latency and perf related settings for AKS that I wish to be able to set when I have Cluster AutoScaler enabled,
- cpu-manager-policy
- cpu-cfs-quota
- pod-max-pids

Thank you for your consideration.

**Comment by faustos** [comment] 2019-10-04 21:42
I would need to set ConfigMapAndSecretChangeDetectionStrategy

**Comment by jayush** [comment] 2019-10-18 04:52
What is the latest status of this ask?

**Comment by jeff1985** [comment] 2019-11-04 23:42
Custom kubelet config would also allow to solve #686 which is failing an important deployment on my cluster

**Comment by henrylilei** [comment] 2019-11-05 01:52
I settled with updating the kubelet config using Kured, please check out this [gist](https://gist.github.com/henrylilei/733e4b2b5256c348a2c5ca46a48175da). It works with VMSS and HPA/CA, but this feels like a hack to me and I would love to see AKS to support this natively.

**Comment by kortatu** [comment] 2020-03-25 16:39
> How about [Dynamic Kubelet Configuration](https://kubernetes.io/blog/2018/07/11/dynamic-kubelet-configuration/) ?
> 
> I'm using `--authentication-token-webhook=true` to enable service account tokens to be used to authenticate to the kubelet.
> 
> It's required by `kube-prometheus` to scrape the kubelet metrics.

Dynamic Kubelet configuration is great but first you need to chante this kubelet option `--dynamic-config-dir ` as stated here https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/
So again, we need a way of specifying some options in Azure AKS nodes at creation time.

**Comment by LudoNieuw** [comment] 2020-10-02 13:14
I'm curious about an update to this issue. I am myself facing issues with scraping the kubelet from <node-internal-ip>:2550/metrics (http scrape) but am getting a 'connection refused' message thrown back...

**Comment by m1o1** [comment] 2020-10-02 14:00
I might be wrong about this but I believe the kubelet binds to localhost, so it's inaccessible to prometheus

**Comment by LudoNieuw** [comment] 2020-10-05 14:32
> 
> 
> I might be wrong about this but I believe the kubelet binds to localhost, so it's inaccessible to prometheus
Prometheus is in most cases deployed inside the cluster (also my situation), so it should be able to access it, but it turns out the http port is removed without any public mention in recent AKS rollouts...

**Comment by palma21** [comment] 2020-10-12 23:51
AKS will soon provide for more bootstrap options to confiture the node OS and kubelet.

**Comment by slawekww** [comment] 2020-10-13 10:12
More options should be available for other K8S services:  allow to configure additional parameters for kube-api, kube-controller-manager etc. If AKS shall play production grade cluster, we need to have capabilities to setup parameters according to guidelines.

**Comment by slawekww** [comment] 2020-10-26 17:52
It is possible to update kubelet (any node config actually) via DaemonSet like example:
https://docs.nginx.com/nginx-service-mesh/setup/aks/

**Comment by palma21** [comment] 2020-11-09 18:59
@slawekww any specific requests/use cases for setting parameters on those components? please do open a specific issue with those, happy to discuss there.

**Comment by arunmahadevan** [comment] 2020-12-04 22:52
Looking for options to customize the kueblet root dir.

```
--root-dir string     Default: `/var/lib/kubelet`
  | Directory path for managing kubelet files (volume mounts, etc).
```

**Comment by aidapsibr** [comment] 2020-12-09 21:19
@palma21 Hey, we are looking to evaluate this preview, is there any samples you can share?

**Comment by ohadschn** [comment] 2021-03-07 18:53
I would add setting logging verbosity (`--v`) to the list - could be invaluable for test clusters.

**Comment by palma21** [comment] 2021-09-08 15:59
https://docs.microsoft.com/en-us/azure/aks/custom-node-configuration

**Comment by venkatalolla** [comment] 2021-09-27 22:07
@palma21 when will the `custom-node-configuration` is going to be **GA**?
https://docs.microsoft.com/en-us/azure/aks/custom-node-configuration

**Comment by sonnyhcl** [comment] 2021-09-29 05:42
As claimed in [Support for custom log options
](https://github.com/Azure/AKS/issues/1062#issuecomment-889109736), `containerLogMaxSizeMB`/`containerLogMaxFiles` should be avaiable as a valid node config. While I tried updating my AKS cluster and doesn't work. 

So I have similiar question on when containerLog related config goes GA.

**Comment by abarqawi** [comment] 2021-09-29 13:45
@palma21 any ETA please ?

> @palma21 when will the `custom-node-configuration` is going to be **GA**? https://docs.microsoft.com/en-us/azure/aks/custom-node-configuration

**Comment by MarcosMMartinez** [comment] 2021-11-22 20:40
Is there a plan to allow for custom config of _**--kube-config=cpu=xxxx,memory=xxxx**_ for customers that prefer to have more simplistic QoS configs for deployments? (this would be swell)

**Closed** 2022-07-08 21:20 UTC
Labels: enhancement, feature-request, kubelet, action-required

**Comment by ohadschn** [comment] 2022-07-11 15:43
For reference, I believe these are the relevant shipped features:
* https://docs.microsoft.com/en-us/azure/aks/custom-node-configuration
* https://docs.microsoft.com/en-us/azure/aks/support-policies#shared-responsibility
