### ISSUE TITLE
Enable Service Account Token Volume Projection

### ISSUE THREAD

**Issue by giggio** [Azure/AKS#1288] opened 2019-10-25 18:08 UTC
**What happened**:

The Service Account Token Volume Projection is not enabled right now for AKS. According to the [docs](https://docs.microsoft.com/en-us/azure/aks/servicemesh-istio-install?pivots=client-operating-system-linux#install-the-istio-components-on-aks):

> The SDS (secret discovery service) and Istio CNI Istio features are currently in Alpha, so thought should be given before enabling these. In addition, **the Service Account Token Volume Projection Kubernetes feature (a requirement for SDS) is not enabled in current AKS versions**.

Because of this, support for Let's Encrypt with Istio does not work, as [it depends on SDS](https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/).

**What you expected to happen**:

Suport for Service Account Token Volume Projection is enabled, and we can use cert-manager/Let's encrypt with Istio on AKS.

**Comment by bhicks329** [comment] 2019-10-28 06:53
Looks like a duplicate of https://github.com/Azure/AKS/issues/1208 

Would be great to get a specific answer on this.

**Comment by jluk** [comment] 2019-11-07 20:48
Closing this as a duplicate of #1208, let's converge on that issue to track the latest for this. Thank you everyone.

**Closed by jluk** 2019-11-07 20:48 UTC
Labels: triage
