### ISSUE TITLE
Pod Autoscalers not working in 1.9.6

### ISSUE THREAD

**Issue by nocon** [Azure/AKS#355] opened 2018-05-09 09:21 UTC
Hi, we've recently migrated to 1.9.6, which resulted in horizontal pod autoscalers ceasing work. We're seeing the following errors:

```unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io) ```

```failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io) ```

Here's the HPA declaration:
```{
  "kind": "HorizontalPodAutoscaler",
  "apiVersion": "autoscaling/v1",
  "metadata": {
    "name": "gateway",
    "namespace": "gateway",
    "selfLink": "/apis/autoscaling/v1/namespaces/gateway/horizontalpodautoscalers/gateway",
    "uid": "378b5333-52bf-11e8-8daa-0a58ac1f171d",
    "resourceVersion": "3616549",
    "creationTimestamp": "2018-05-08T12:56:25Z",
    "annotations": {
      "autoscaling.alpha.kubernetes.io/conditions": "[{\"type\":\"AbleToScale\",\"status\":\"True\",\"lastTransitionTime\":\"2018-05-08T12:56:36Z\",\"reason\":\"SucceededGetScale\",\"message\":\"the HPA controller was able to get the target's current scale\"},{\"type\":\"ScalingActive\",\"status\":\"False\",\"lastTransitionTime\":\"2018-05-08T12:57:06Z\",\"reason\":\"FailedGetResourceMetric\",\"message\":\"the HPA was unable to compute the replica count: unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)\"}]"
    }
  },
  "spec": {
    "scaleTargetRef": {
      "kind": "Deployment",
      "name": "gateway",
      "apiVersion": "extensions/v1beta1"
    },
    "minReplicas": 3,
    "maxReplicas": 10,
    "targetCPUUtilizationPercentage": 80
  },
  "status": {
    "lastScaleTime": "2018-05-08T13:13:06Z",
    "currentReplicas": 3,
    "desiredReplicas": 3
  }
}
```

How can we fix this?

**Comment by shahiddev** [comment] 2018-05-10 09:45
duplicate of #318 ?

**Closed** 2018-05-10 14:02 UTC
