### ISSUE TITLE
Rogue helm chart in AKS cluster with revision going up every 30 seconds overlay-upgrade-data-addon-0.1.0

### ISSUE THREAD

**Issue by SebTardif** [Azure/AKS#3597] opened 2023-04-06 08:36 UTC
I used AKS in Azure cloud. I started to have an odd rogue helm chart showing up with revision number going up to very high number. It seems to increase the revision each 30 seconds.

name: overlay-upgrade-data-adapter-helmrelease
namespace: 625fc4ba83c7e000011019ba
chart: overlay-upgrade-data-addon-0.1.0-59898b98085ba21ebd07333464bd0f46cabc4021

That appears to be a Microsoft creation, probably used to configure that managed AKS cluster, but Microsoft Support (which seem to outsource to India) are totally lost.

It would be great that someone smart take care of it! 

Support ticket: 2304050040003337

**Comment by AYM1607** [comment] 2023-04-17 17:03
Hey @SebTardif I'm Mariano from the AKS engineering team.

The behavior you're observing is by design, we reconcile that Helm release every 30 seconds to ensure it stays consistent with its goal state. As you might have observed, the version number is constantly increasing but we're only keeping 2 revisions at any particular time.

We're looking into increasing the reconciliation interval, but even at the current rate, you wouldn't observe a roll-over in the version number for 2000 years, so no need to worry.

We're also renaming these helm releases to `aks-managed-overlay-upgrade-data` to make it clear that we own and manage it for you.

**Comment by AYM1607** [comment] 2023-04-20 19:21
Closing as this is by design. Feel free to re-open if you have any additional concerns.

**Closed by AYM1607** 2023-04-20 19:21 UTC
Labels: triage, action-required
