### ISSUE TITLE
New node pools are onboarded to Default Log Analytics workspace

### ISSUE THREAD

**Issue by artisticcheese** [Azure/AKS#1146] opened 2019-08-12 13:23 UTC
**What happened**:
AKS cluster created with custom Log Analytics Workspace, when added new nodepools to it they are onboarded automatically to Default Log Analytics Workspace and not inherit cluster Log Analytics workspace. This happens with Windows nodepool (might be happening with Linux too)

**What you expected to happen**:
New nodepools shall be sending logs to the same workspace as parent AKS or at least allow to specify which workspace they shall go to (currently there is no command available to specify workspace in `az aks nodepool`

**How to reproduce it (as minimally and precisely as possible)**:
Create new AKS cluster with customer Log Analytics Workspace and add new node pool to it. Node pool will not be connected to cluster workspace

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.14.3
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by eidnirav** [comment] 2019-08-12 13:41
in this situation where I specified a workspaceID when creating an aks cluster, I actually have noticed that the new  VMSS is not added to any Log Analytics workspace, and I have to add the vmss manually.

**Comment by eidnirav** [comment] 2019-08-13 02:53
I updated the windows VMSS using "az vmss extension set", and got the following message when I browsed to the "insights" tab of the VMSS in the portal... looks like only some regions are fully supporting this. could this be root cause (why the workspace specified during aks creation is not propogated to its vmss)?

![image](https://user-images.githubusercontent.com/16802874/62911802-ab933f80-bd53-11e9-91b0-9c5c6e44cf19.png)

**Comment by brobichaud** [comment] 2019-08-14 21:57
I too am seeing that new nodepools do not get associated with the log analytics workspace the cluster was defined to use. However I was able to go the VMSS section of the Azure Portal, choose the Insights blade and select the correct log analytics workspace. It indicated success after a few minutes and looking at the VM blade of the Log Analytics section shows those nodepools are now associated with it.

So for me at least the problem does exist but I can manually fix it (assuming I remember to do so when I create a nodepool).

**Comment by eidnirav** [comment] 2019-08-16 19:31
@brobichaud are you getting your logs in LogA? I thought this was working for me- could swear after I deployed a new cluster in a region supporting vmss node pools- that this worked. but i do not see any log messages from my linux AND windows nodepools. LogA says that the vmss's are associated, and the MMA extension is installed for the windows node pool (I think this is the extension that forwards container logs, but am not sure). Also, OMSAgent container is running on linux nodes. But query of containerlog returns 0 results.

**Comment by brobichaud** [comment] 2019-08-16 20:12
@eidnirav I am getting data in my workspace after manually connecting it to the VMSS. My current usage of Log Analytics with my cluster is Azure Monitors integration with K8s.

**Comment by brobichaud** [comment] 2019-10-25 18:07
I created a new nodepool today and am seeing data flow into log analytics without having to manually connect it in the VMSS blade of the Azure Portal. I'm wondering if there was a fix on the AKS (or VMSS) side of things?

**Comment by TomGeske** [comment] 2020-07-24 09:29
This one should be fixed. 

I'm closing this one for now. Keep commenting if you have further questions.

**Closed by TomGeske** 2020-07-24 09:29 UTC
Labels: azure/oms, bug
