### ISSUE TITLE
Auto scaling support min count zero

### ISSUE THREAD

**Issue by oscar60310** [Azure/AKS#1565] opened 2020-04-21 04:19 UTC
We can scale our node pools to zero now (#1050) , is it possible to support min count to zero too?
It's useful if CA can turn off every machine in user mode node pools.

**What happened**:
AKS doesn't allow the min count of user mode node pools to be zero.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Set `minCount` property to `0` and `enableAutoScaling` to `true` for any node pool.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.3
- API version: 2020-03-01

**Comment by ohorvath** [comment] 2020-04-22 11:21
Agreed, I'm not sure we should use this feature if mincount cannot be set to zero.

**Comment by tomkerkhove** [comment] 2020-06-18 15:05
😍 This feature

**Comment by jluk** [comment] 2020-06-30 16:31
As an update here, AKS supports manual scale to zero for all user node pools at the moment. This can be done through any client.

The work to support autoscale to and from zero is in-flight and we will have news to share in the coming weeks. Thanks for everyone's participation and feedback through this critical scenario!

**Comment by JosPolfliet** [comment] 2020-07-24 12:44
Hi @jluk , any update on this?

**Comment by palma21** [comment] 2020-07-24 23:12
Update here: https://github.com/Azure/AKS/issues/52#issuecomment-660897690

It's slated for the end of the month.

**Comment by vaishakcloud** [comment] 2020-08-04 13:56
Any updates?

**Comment by ykale** [comment] 2020-08-11 23:53
Will this feature work on the already running AKS cluster, lets say version v1.15.11, only by updating the CLI version/portal ?

**Comment by palma21** [comment] 2020-08-12 01:25
@ykale Yes.

this feature is about to be released keep an eye on the release notes.

**Comment by Shuanglu** [comment] 2020-08-18 23:38
@palma21  whether the autoscale setting on portal will hv the change as well?

**Comment by rogelioamancisidor** [comment] 2020-08-19 07:34
I am testing the new functionality and it was ok to create a nodepool with `--min-node 0 --enable-cluster-autoscaler --mode user`.  The nodepool scales down to 0 nodes if there are no running jobs. However, it does not scales up to 1 node after i send a new yaml manifest to run a new job. `kubectl get pods` shows that the status of my job is `pending`. Is it something that I a misunderstanding about how this functionality works?

**Comment by marwanad** [comment] 2020-08-19 16:39
@rogelioamancisidor what region is your cluster in and do you have node labels specified on your pool?

**Comment by rogelioamancisidor** [comment] 2020-08-19 19:13
@marwanad the region is west europe and you mean by node labels the parameter `--name`, then yes

**Comment by marwanad** [comment] 2020-08-19 19:27
@rogelioamancisidor I was referring to the `--labels` parameter. What's the output you see on the pod events when you describe the pending job pod?

**Comment by rogelioamancisidor** [comment] 2020-08-19 22:25
Name:           myjob-xtb6j
Namespace:      default
Priority:       0
Node:           aks-bayes1-33515997-vmss000000/
Labels:         controller-uid=5514ec61-ba12-4e07-ab46-66cf6ec2ac85
                job-name=myjob
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  Job/myjob
Containers:
  myjob:
    Image:      rogelioandrade/theano_setup:v3
    Port:       <none>
    Host Port:  <none>
    Command:
      bash
      ./running_aks_one.sh
    Limits:
      memory:          100Gi
      nvidia.com/gpu:  1
    Requests:
      memory:          100Gi
      nvidia.com/gpu:  1
    Environment:       <none>
    Mounts:
      /mnt/azure from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hmcld (ro)
Volumes:
  azure:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  azurefile
    ReadOnly:   false
  default-token-hmcld:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-hmcld
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

**Comment by marwanad** [comment] 2020-08-19 23:05
@rogelioamancisidor there's not output under the events? Usually, there's an indicator that the pod is pending waiting for a node and why CA didn't issue a scale up for that

It seems that this pod is attached to a node `aks-bayes1-33515997-vmss000000` already in your case. There's most likely something else going on.

**Comment by rogelioamancisidor** [comment] 2020-08-20 06:11
@marwanad under events says `<none>`. Is there anything I need to take care in the yaml manifest?

**Comment by akosbalazs** [comment] 2020-08-20 10:53
@marwanad I had the exact same issue as @rogelioamancisidor, also in the West Europe region. It looks like when you specify 0 as `min-count` and 1 as `max-count` it won't scale up because it thinks it already reached maximum capacity:
```
Events:
  Type     Reason             Age                        From                Message
  ----     ------             ----                       ----                -------
  Normal   TriggeredScaleUp   98s                        cluster-autoscaler  pod triggered scale-up: [{aks-gpupool-29545764-vmss 0->1 (max: 1)}]
  Normal   NotTriggerScaleUp  <invalid> (x14 over 88s)   cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 max limit reached
  Warning  FailedScheduling   <invalid> (x3 over 2m12s)  default-scheduler   0/5 nodes are available: 5 Insufficient nvidia.com/gpu.
```

When I set `max-count` as 2 it scales up as expected. It looks like a small bug in the auto-scheduler.

@rogelioamancisidor I assume you have some taints in your GPU nodepool to prevent other pods being scheduled on those nodes, did you add a tolerance to that taint to your GPU job's yaml manifest?

**Comment by rogelioamancisidor** [comment] 2020-08-20 12:36
@akosbalazs thanks for your input. I'll set `max-count 2` and test it. 

No I dont add a tolerance since I am the only one who has access to the resource group where  we have the GPU nodepool.

**Comment by marwanad** [comment] 2020-08-20 16:58
@akosbalazs working on a repro now but from your example:

```
pod triggered scale-up: [{aks-gpupool-29545764-vmss 0->1 (max: 1)}]
```
Doesn't this show that it scaled up from zero? It won't get beyond 1 because your `maxCount` is 1.

**Comment by akosbalazs** [comment] 2020-08-20 17:01
@marwanad it shows it _triggered_ the scale up from the AS. It doesn't say it actually scaled. If you look at the next line in the events log it says it won't actually scale to 1 because it would exceed the maximum (which isn't true of course). Once I set `max-count` to 2 it managed to scale.

**Comment by akosbalazs** [comment] 2020-08-20 17:13
@rogelioamancisidor how do you prevent other pods in your cluster being scheduled on your GPU node if you don't taint that node (or actually all of them in the nodepool) ? Or is it in a different resource group than the rest of your AKS cluster? I've never tried that - although that might be a reason why it's not triggered.

BTW I noticed something in your YAML manifest, you request 100GB of memory - you need at least an NC12 node for that. HTH. Although the weird part is that your job seems to get scheduled on the normal pool even though it requests GPU capabilities.

**Comment by marwanad** [comment] 2020-08-20 17:48
@akosbalazs So I did the following:
1. Create a new cluster in WestEU.
2. Create a nodepool with count = 0, minCount = 0, maxCount =1 and also added some labels to the pool in case your deployment uses selector
3. Schedule a nginx pod deployment with a node selector.

Pod events:
```
Events:
  Type     Reason            Age                  From                Message
  ----     ------            ----                 ----                -------
  Normal   TriggeredScaleUp  7m18s                  cluster-autoscaler                      pod triggered scale-up: [{aks-pool1-28738850-vmss 0->1 (max: 1)}]
  Warning  FailedScheduling  6m29s (x3 over 7m50s)  default-scheduler                       0/3 nodes are available: 3 node(s) didn't match node selector.
  Warning  FailedScheduling  5m25s                  default-scheduler                       0/4 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 3 node(s) didn't match node selector.
  Normal   Scheduled         5m24s                  default-scheduler                       Successfully assigned default/nginx-68bf8988fd-2hbjg to aks-pool1-28738850-vmss000000
  Normal   Pulling           5m13s                  kubelet, aks-pool1-28738850-vmss000000  Pulling image "nginx"
  Normal   Pulled            5m4s                   kubelet, aks-pool1-28738850-vmss000000  Successfully pulled image "nginx"
  Normal   Created           5m                     kubelet, aks-pool1-28738850-vmss000000  Created container nginx
  Normal   Started           5m                     kubelet, aks-pool1-28738850-vmss000000  Started container nginx
```
CA configmap:
```
Events:
  Type    Reason         Age   From                Message
  ----    ------         ----  ----                -------
  Normal  ScaledUpGroup  7m1s  cluster-autoscaler  Scale-up: setting group aks-pool1-28738850-vmss size to 1
```
Also scaled it down to zero, then back up to 1 and wasn't able to repro.

I'll try with GPUs next

**Comment by marwanad** [comment] 2020-08-20 18:01
@akosbalazs also fwiw, I do see a scale event to 1 around 2020-08-20T10:42:34.7049615Z for that VMSS. Was this before or after you set the maxCount to 2?

**Comment by akosbalazs** [comment] 2020-08-20 18:12
@marwanad Thanks for the repro. No idea why it works for you. 😁  After I set `max-count` to 2 it successfully scaled up but I can't say when I did that change exactly, sorry. Something to consider possibly: the nodepool is actually a few weeks old at least, I just mostly kept it at 0 nodes unless we needed a GPU node for testing, then I manually scaled up to 1 then back to 0.

**Comment by marwanad** [comment] 2020-08-20 18:29
@akosbalazs hmm, happy to debug your case further. When you set `max-count` to 2 - does it add 1 or 2 nodes? From the events, it makes it seem that it's trying to scale to 2 which could be due to the GPU allocatable calculations.

**Comment by akosbalazs** [comment] 2020-08-20 19:51
@marwanad I've just submitted a job that requires a GPU. The autoscaler scaled up to 1 node (from 0) as expected. You can check the aforementioned VMSS now, it should have 1 node.

**Comment by akosbalazs** [comment] 2020-08-20 19:56
@marwanad FWIW it took about 5 minutes from the "TriggeredScaleUp" message to actually have the new node appear and the pod be scheduled -- is this to be expected?

**Comment by marwanad** [comment] 2020-08-20 20:07
@akosbalazs that depends on a lot of factors. VM SKUs, availability, etc and also time for installing GPU drivers if its a GPU node. "TriggeredScaleUp" is approximately when the request is sent to VMSS to scale. 

I'm assuming this was with maxCount = 2? Does this work with `maxCount = 1`?

**Comment by akosbalazs** [comment] 2020-08-20 20:30
@marwanad yes, that was with `max-count` 2. I updated the `max-count` to 1 via azure-cli and rescheduled a job that needs GPU, but now it doesn't even print the "TriggeredScaleUp" message in the events. Same VMSS if you want to look into it. Weird.

**Comment by marwanad** [comment] 2020-08-20 21:22
@akosbalazs It's failing to build the instance template for your case because `Standard_NC6_Promo` isn't in the list of SKUs supported in 1.15 [[x](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.15/cluster-autoscaler/cloudprovider/azure/azure_instance_types.go)].

Basically, CA needs to predict what kind of node it's expecting and attempts to build a template. It's failing [here](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.15/cluster-autoscaler/cloudprovider/azure/azure_scale_set.go#L555-L564) in your case because of the `_Promo` suffix. The logic was changed in [1.18](https://github.com/kubernetes/autoscaler/pull/2871) to not consider the Promo suffix when building the list but the change wasn't cherry-picked to earlier releases.

**Comment by akosbalazs** [comment] 2020-08-20 21:26
@marwanad that's a separate issue, isn't it? I would guess setting the maximal count has no relation to picking the node template. But then why did it work earlier today (admittedly with `max-count` set to 2)?

**Comment by marwanad** [comment] 2020-08-20 21:37
@akosbalazs I don't think the issue is related to `max-count` but your order of operations.

In the case when you changed `max-count` to 2, it already had a cached view of what the node would look like because when the CA pod restarted after your change - there was already one node to build the template of (and hence not going through the static list of instances check). This time round, your pool had 0 nodes when you changed `max-count`, so the template build up logic was executed.

So in your case: With `max-count: 1, min-count: 0` - manual scale to 1 then after a while delete the VM to ensure that a template exists and is cached in CA. Then, trying scheduling the GPU workload again. It should work.

I'll back-port the `Promo` instances change.

**Comment by akosbalazs** [comment] 2020-08-20 21:46
@marwanad Good catch! I manually scaled up to one node once earlier and hence it might have had a cached view of the node template. Very unlucky timing it seems as earlier today it worked twice already (even when it scaled from 0 to 1) and later on it failed because the node template was missing from the cache.

Thanks for the backport, much appreciated!

**Comment by marwanad** [comment] 2020-08-20 23:40
@akosbalazs this is most likely because GPU capacity is only reflected on the node object after GPU drivers are installed. So, that's why it attempts to scale multiple times here. We've identified an issue there and will be releasing a fix.

**Comment by rogelioamancisidor** [comment] 2020-08-21 06:39
@marwanad  @akosbalazs  I forgot that at the top of aks I run a sh file with some modifications to the usual kubectl commands. The sh file was not created by me, but now that I think twice it must contain some taints.

**Comment by marwanad** [comment] 2020-08-21 06:59
@akosbalazs sorry I take what I said back about that `NotTriggerScaleUp` log you're seeing- I was thinking of a different scenario. 
You're seeing this error because there's an issue in the binpacking estimator for upcoming nodes in the 1.15 upstream version of CA. The logic was fixed on 1.16+. So on 1.15, you shouldn't see this log if your maxCount is greater than 1. In all cases, you can safely ignore this error and assume it's bad logging. 

There won't be "multiple scale attempts" or anything of the sort. With 1.16+, that event shouldn't misfire.

**Comment by ohorvath** [comment] 2020-08-24 18:16
Auto scaling to zero works fine for us now, thank you. Could you please provide some information what changed in cluster autoscaler, like upstream version etc.? It seems it fails to scale if we specify antiaffinity for failure-domain.beta.kubernetes.io/zone. We had no issues before the change.

**Comment by marwanad** [comment] 2020-08-24 18:40
@ohorvath can you share the errors you're seeing? On the pending pod and also the cluster autoscaler configmap? Are you saying it fails to scale from zero with that anti-affinity? Or, it fails to scale with that in non-zero cases?

**Comment by ohorvath** [comment] 2020-08-24 20:15
We see this in both scenarios zero and non-zero. We are not 100% sure that's related to this change, but we had no issues before the new AKS release last week. 

`Normal   NotTriggerScaleUp  32s                cluster-autoscaler  pod didn’t trigger scale-up (it wouldn’t fit if a new node is added): 1 node(s) didn’t match node sele│
│ctor, 1 node(s) didn’t match pod affinity/anti-affinity, 1 node(s) didn’t satisfy existing pods anti-affinity rules`

[configmap.txt](https://github.com/Azure/AKS/files/5120003/configmap.txt)

> podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: hiveserver2
        topologyKey: failure-domain.beta.kubernetes.io/zone

If we change this anti-affinity rule to a hostname based one, it works fine.

**Comment by marwanad** [comment] 2020-08-24 22:19
@ohorvath the release also bumped the scheduler version dependency in CA to fix an issue with init containers which I doubt is related. Just trying to infer your setup a bit but I'm pretty sure you're hitting a known case based on this line:

```
1 node(s) didn’t match pod affinity/anti-affinity, **1 node(s) didn’t satisfy existing pods anti-affinity rules**
```

CA doesn't support nodepools that span multi-AZ because it assumes that every node in that nodepool is exactly identical which includes being in the same AZ. It builds a template off of live node in that nodepool and uses it to see if pods can be scheduled on that node. You might've lucked out with an earlier run with your setup. The recommendation is to have one nodepool per AZ.

**Comment by ohorvath** [comment] 2020-08-24 22:34
@marwanad Thanks, I had the same conclusion. :) May I suggest to mention this [here](https://docs.microsoft.com/en-us/azure/aks/availability-zones#limitations-and-region-availability) or [here](https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler)?

**Comment by marwanad** [comment] 2020-08-24 22:40
@ohorvath yup, will do. That's a shortcoming on our side - sorry about that.

**Comment by ohorvath** [comment] 2020-08-24 23:11
@marwanad Thanks. It's not a big deal honestly, we just want to make sure to provide a fully supported solution for our customers.

**Comment by zeroX-tj** [comment] 2020-08-25 10:44
> @rogelioamancisidor above might be helpful for you as well. The `nodeSelector` is a signal for the scheduler to ensure that the pods only land on the nodes that have this label on them. You can set node labels by specifying the `--labels` parameters when creating a nodepool. All nodes in that nodepool will have that label on them.

Thank you, in the past the agentpool label was added automatically iirc, adding `--labels 'agentpool=agentpoolSelectorName'` solved using the nodeSelector indeed.

**Comment by marwanad** [comment] 2020-08-25 18:03
@zeroX-tj FYI, there's a fix rolling out for that case. The agentpool label is added automatically to all nodes in a nodepool and you shouldn't ever need to specify it via `--labels`.If you're scaling from zero and have a selector on the agentpool name - you might need that extra step.

**Comment by ohorvath** [comment] 2020-08-25 19:33
Today I did some testing with autoscaler. It seems if we create an AKS cluster with AZ disabled the node label value for failure-domain.beta.kubernetes.io/zone will be 0 for all nodes. Same behaviour as previously but now the scaling is not working if we have an affinity against this label. I think that shouldn't worked before also but checked and old AKS cluster and still working. 

With AKS AZ enabled clusters the label values will be centralus-0, centralus-1 etc. and scaling is working even if we have an affinity against the label. No error message. 

I tried to manually modify these label values and it seems if at least one node label value for failure-domain.beta.kubernetes.io/zone is different than others, cluster autoscaler starts scaling up even we have the affinity rule. Also have error messages but scaling is working.

**Comment by marwanad** [comment] 2020-08-25 21:11
@ohorvath sorry let me try and recap what you mentioned:

- Are we talking scale from zero in this case or just normal scale? I'm assuming normal scale. 

Feel free to file a SR or find me on Slack if the conversation is going to deviate from that GitHub issue.

- Are you saying that in an older AKS cluster - if you have an affinity against  `failure-domain.beta.kubernetes.io/zone:0` CA tries to scale this nodepool? Do the pods get scheduled on that? And on the new release - it doesn't scale? The correct behaviour should be the second one but I'd like to dig deeper into the second case. 

> With AKS AZ enabled clusters the label values will be centralus-0, centralus-1 etc. and scaling is working even if we have an affinity against the label. No error message.

- This didn't work with the case you mentioned yesterday, did it? Which affinity rules are you setting. The ones you shared above would translate to `the pod cannot be scheduled o a node that is in the same zone as a pod that has app: hiveserver2` right?

> I tried to manually modify these label values and it seems if at least one node label value for failure-domain.beta.kubernetes.io/zone is different than others,

You'd need to restart the cluster autoscaler pod somehow if you modify labels because it caches a template of a node from that nodepool.

**Comment by ohorvath** [comment] 2020-08-25 21:39
> @ohorvath sorry let me try and recap what you mentioned:
> 
> * Are we talking scale from zero in this case or just normal scale? I'm assuming normal scale.
> 
> Feel free to file a SR or find me on Slack if the conversation is going to deviate from that GitHub issue.
> 
> * Are you saying that in an older AKS cluster - if you have an affinity against  `failure-domain.beta.kubernetes.io/zone:0` CA tries to scale this nodepool? Do the pods get scheduled on that? And on the new release - it doesn't scale? The correct behaviour should be the second one but I'd like to dig deeper into the second case.
> 
> > With AKS AZ enabled clusters the label values will be centralus-0, centralus-1 etc. and scaling is working even if we have an affinity against the label. No error message.
> 
> * This didn't work with the case you mentioned yesterday, did it? Which affinity rules are you setting. The ones you shared above would translate to `the pod cannot be scheduled o a node that is in the same zone as a pod that has app: hiveserver2` right?
> 
> > I tried to manually modify these label values and it seems if at least one node label value for failure-domain.beta.kubernetes.io/zone is different than others,
> 
> You'd need to restart the cluster autoscaler pod somehow if you modify labels because it caches a template of a node from that nodepool.

Sorry, it's a normal scale. I think our issue is not related to the scale to 0 feature itself but linked to another change happened with the same release. Maybe scheduler changes. I'll send a mail to your public email address listed here with my findings and if you think it's worth investigating I can submit a SR too. We just want understand what's happening to avoid similar situations in the future. Thanks for your help.

**Comment by akosbalazs** [comment] 2020-09-04 18:23
@marwanad Thanks for the help & tips so far. We've been using NC6 (non-promo) instances and the scaling to/from zero works like a charm. Any ETA on when the fix for the `_Promo` suffix will be backported to 1.15? We can also consider upgrading to 1.16 if needed. 1.18 isn't available in the West Europe region yet and we need to keep our data inside the EU.

**Comment by akosbalazs** [comment] 2020-09-07 23:08
@marwanad Thanks for the help & tips so far. We've been using NC6 (non-promo) instances and the scaling to/from zero works like a charm. Any ETA on when the fix for the `_Promo` suffix will be backported to 1.15? We can also consider upgrading to 1.16 if needed. 1.18 isn't available in the West Europe region yet and we need to keep our data inside the EU.

**Comment by Robert-Stam** [comment] 2020-09-08 06:25
Is there any ETA for this feature to land into GA?

**Comment by marwanad** [comment] 2020-09-09 18:13
@akosbalazs should be available by end of this week.

@palma21 any timelines for GA?

**Comment by jluk** [comment] 2020-09-10 21:52
The scenario to use this is GA, the closure of core CLI parity will be rolling on 9/22 with the next release.

As a result I'm moving this to GA state given the functionality is ready and we are closing the client gaps only.

**Closed** 2020-09-10 23:26 UTC
Labels: cluster-autoscaler, feature, feature-request, nodepools

**Comment by btnguyen2k** [comment] 2020-09-13 14:30
A few notes:
- This only works with Azure CLI. On the portal, the min-node is till 0.
- You may have to create new node pool with the new scale setting.
- You can create new node pool with `--node-count 0` (cool!)

And does anyone know how long will it take for the nodepool to scale down to 0? I created new node pool with `--min-count 0`, have been waiting for >10 mins and my node pool still does not scale down to 0.

**Comment by marwanad** [comment] 2020-09-13 18:40
> A few notes:
> 
> * This only works with Azure CLI. On the portal, the min-node is till 1.
> * You may have to create new node pool with the new scale setting.
> * You can create new node pool with `--node-count 0` (cool!)
> 
> And does anyone know how long will it take for the nodepool to scale down to 0? I created new node pool with `--min-count 0`, have been waiting for >10 mins and my node pool still does not scale down to 0.
@btnguyen2k 

Thanks for reporting, will follow-up with the portal team on that to fix the slider.

If you're measuring from the time you created the pool, then assuming the pool has been empty - it would take around 20 mins. 10 min for scale down cool down period (this is because you just created the nodepool, so `scale-down-delay-after-add` applies) and then the `scale-down-unneeded-time` will start ticking and by default it's 10 minutes. Check the first part of my comment [here](https://github.com/Azure/AKS/issues/1565#issuecomment-678410566). Both values are configurable via the autoscaler profile so you have full control over how long. You should be able to retrieve the CA logs as well and see if there's anything blocking the node deletion. If you describe the node, you should see the below taint:
```
Taints:             DeletionCandidateOfClusterAutoscaler=1600021636:PreferNoSchedule
```
which would indicate that the node is marked for deletion and it's just a matter of satisfying the `scale-down-unneeded-time` at that point.
