### ISSUE TITLE
Inconsistency between Azure and Calico NetworkPolicy when combining Ingress and Egress

### ISSUE THREAD

**Issue by NillsF** [Azure/AKS#1158] opened 2019-08-19 01:06 UTC
**What happened**:
When deploying a combination of Ingress and Egress network policies there is an inconsitency between Calico and Azure NetworkPolicy. Design below:
![design](https://pbs.twimg.com/media/ECSdzj0UwAEayze?format=jpg&name=medium)

Ingress policy on label app=web, allowing traffic from trusted=yes
Egress policy on trusted=yes, allowing egress to env=dev

Behavior:
**Azure NetworkPolicy**: Ingress policy rules, traffic from trusted=yes goes to both env=dev and env=prod
**Calico**: Both policies rule: traffic from trusted=yes only flows to env=dev, not to env=prod. 

**What you expected to happen**:
I expected the Calico behavior. 
**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox-curl-1
  labels:
    trusted: "yes"
spec:
  containers:
  - name: busybox
    image: yauritux/busybox-curl
    args:
    - sleep
    - "1000000"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-dev
  labels:
    app: "web"
    env: "dev"
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-prod
  labels:
    app: "web"
    env: "prod"
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: policy1-allow-trusted-busybox
spec:
  podSelector:
    matchLabels:
      app: web
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          trusted: "yes"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: policy2-allow-to-dev
spec:
  podSelector:
    matchLabels:
      trusted: "yes"
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          env: dev
```
```bash
kubectl create -f inconsitency.yaml
kubectl get pods -o wide #to get IP addresses
kubectl exec -it busybox-curl-1 sh
curl *ip of nginx-dev* #this should work
curl *ip of nginx-prod* #this works with Azure NetworkPolicy - not with Calico
```

**Anything else we need to know?**:
I believe to be related - but distinct - to #1138 .

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9", GitCommit:"3e4f6a92de5f259ef313ad876bb008897f6a98f0", GitTreeState:"clean", BuildDate:"2019-08-05T09:14:29Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
test cluster, running nginx and busybox
- Others:

**Comment by sauryadas** [comment] 2019-08-20 03:11
Duplicate of #1135 will track 1135

**Closed by sauryadas** 2019-08-20 03:11 UTC
Labels: network-policies

**Comment by aanandr** [comment] 2019-08-20 17:23
@NillsF - there are conflicting policies here, where the ingress policy for "web" allows traffic from "yes" to "web" (so both dev and prod should receive traffic) but the egress policy for "yes" allows traffic only to dev. Are these policies in different files or the same file? 
I am checking if my understanding is right. So please confirm. We are not handling conflicting policies properly but have some fixes on the way. But once you confirm i would like to ascertain that the fix handles this scenario.

**Comment by NillsF** [comment] 2019-08-20 17:30
Hi @aanandr : when I deployed them they were in different files. I deployed policy1 first and policy2 afterwards. I believe the policies aren't actually "conflicting", I believe they are distinct policies. 1 policy applies to the EGRESS traffic of trusted=yes // 1 policy applies to the INGRESS traffic of app=web.

**Comment by aanandr** [comment] 2019-08-20 17:51
It is implicit overlap because there are two policies for communication between yes and web.
Is this a customer scenario, i.e. has some customer configured it this way today? Frankly speaking the policy definition could be simpler for such cases.

**Comment by ball-hayden** [comment] 2019-08-20 19:16
@aanandr I've also experienced this, and feel that this is a very reasonable use case.

Good examples of where this is relevant is in the `redis` and `postgresql` stable helm charts. These define network policies that allow ingress from pods with a specific label.

If there is also a network policy targeting client pods, I would expect that egress from the client pods is controlled by that network policy, not by another network policy in the namespace that allows ingress from pods with that label.

**Comment by NillsF** [comment] 2019-08-20 19:21
@aanandr : my case isn't a specific client use case, I ran into it when playing around / learning about NetworkPolicies. Reported it as I believe other will run into it as the use case to be a valid one. It's only reasonable that network traffic gets filtered first outbound - and then again inbound. Different teams could be managing the egress/ingress applications and have different policies they require.

Other implementations of NetworkPolicy do address this kind of Policy - I was able to create this without issue using Calico.

**Comment by aanandr** [comment] 2019-08-20 21:13
Thanks @ball-hayden and @NillsF for the information. This is very useful.
We have added support for overlapping policies. We will test out to make sure this scenario also works with that change.

**Comment by HansK-p** [comment] 2020-02-13 21:23
I have problems I'm pretty sure are similar. I prefer to use both Egress and Ingress network policies as it is somewhat limited what can be achieved when using only Ingress or only Egress network policies in a namespace. This has worked well with Calico, but gives a (seemingly) unpredictable and unstable results in AKS v1.15.7 (and earlier) with azure networking plugins.
