### ISSUE TITLE
No incoming connection possible from POD in Terminating state

### ISSUE THREAD

**Issue by jakubneubauer** [Azure/AKS#2598] opened 2021-10-15 13:03 UTC
It seems that network policy with ingress allowing communication from some PODs by label selector disallows communication from PODs in Terminating state. This makes graceful shutdown impossible for them if they need to communicate with the pod with ingress networking policy during graceful shutdown period. 

**What happened**:
Two pods, let's say A and B. A is providing service, B is calling the service A. On first pod a network policy is applied, allowing incoming communication only from pod B, defined by a label selector.
Pod B is written with Graceful shutdown, during termination it calls service A.
This doesn't work - connection from B to A fails during graceful period, while B is in Terminating state.

**What you expected to happen**:
Pod B can connect to A until it is gracefully shutdown.

**How to reproduce it (as minimally and precisely as possible)**:
As described.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-16T02:43:21Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"4966fd0dded6419fd23233a38c8905c67a3ea78e", GitTreeState:"clean", BuildDate:"2021-08-17T02:06:07Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
- 8
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
   - HTTP microservices (Java, .net)
- Others:

**Comment by jakubneubauer** [comment] 2021-10-15 13:10
This is our AKS networking:

API server address
kube-4b9e70e2.hcp.westeurope.azmk8s.io

Network type (plugin)
Azure CNI

Pod CIDR
-

Service CIDR
10.158.64.0/18

DNS service IP
10.158.64.10

Docker bridge CIDR
172.17.0.1/16

Network Policy
Azure

Load balancer
Standard

HTTP application routing
Not enabled

Private cluster
Not enabled

Authorized IP ranges
Not enabled

Application Gateway ingress controller
Not enabled

**Comment by vakalapa** [comment] 2021-10-20 16:44
Azure Network Policy Manager proactively cleans up a POD and its IP from relevant IPSets as soon as it gets an update event with "deletionTimestamp" set, creating issue in Azure-Container-Networking repo where NPM is. 

The solution can be one of two things, either do not delete on update pod events, OR wait until after terminationGracePeriodSeconds expires to delete a pod.

**Comment by JungukCho** [comment] 2021-11-03 00:41
@jakubneubauer Thank you for sharing files and detailed instructions to reproduce the issue. 
I could reproduce the issue and confirmed NPM has limitation. 
We are working on the feature and update you when it is ready.

**Comment by JungukCho** [comment] 2021-11-11 00:07
Hello, @jakubneubauer and @phealy  

We added the feature in NPM and it will be enabled in a next NPM release.
If there is no concern, we can close this issue.

**Comment by jakubneubauer** [comment] 2021-11-11 10:09
@JungukCho thank you. Can you tell me, how can I recognize, or even better, be notified when it will be in production in Azure? Thanks

**Comment by JungukCho** [comment] 2021-11-11 19:04
@jakubneubauer I am sorry that we do not have notification mechanism yet. You can find release information here - [aks release note](https://github.com/Azure/AKS/releases).

For a next NPM release, we expect that it will be the mid of december timeline without releasing hiccups since we have couple of items to be released together.

Please let us know if you have concerns.

**Comment by JungukCho** [comment] 2021-11-17 17:08
@jakubneubauer If you are ok, would you please close this and re-open issue if you have?

**Closed** 2021-11-17 17:28 UTC
Labels: feature-request, network-policies
