### ISSUE TITLE
Node NotReady without reason

### ISSUE THREAD

**Issue by ErickWendel** [Azure/AKS#587] opened 2018-08-08 12:56 UTC
**What happened**:
Past week, my cluster is with `NotReady`, to solve this, I run `scale --node-count 1` and `--node-count 6` and now restarting my services it is working. 

Today, I saw my cluster and now is with NotReady again without reason
```

NAME                       STATUS     ROLES     AGE       VERSION
aks-nodepool1-27465827-0   Ready      agent     25d       v1.9.9
aks-nodepool1-27465827-1   NotReady   agent     22h       v1.9.9
aks-nodepool1-27465827-2   Ready      agent     22h       v1.9.9
aks-nodepool1-27465827-3   Ready      agent     14h       v1.9.9
aks-nodepool1-27465827-4   Ready      agent     14h       v1.9.9
aks-nodepool1-27465827-5   Ready      agent     14h       v1.9.9 


kubectl describe node aks-nodepool1-27465827-1

Name:               aks-nodepool1-27465827-1
Roles:              agent
Labels:             agentpool=nodepool1
                    beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=Standard_DS1_v2
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=eastus
                    failure-domain.beta.kubernetes.io/zone=0
                    kubernetes.azure.com/cluster=MY_CLUSTER
                    kubernetes.io/hostname=aks-nodepool1-27465827-1
                    kubernetes.io/role=agent
                    storageprofile=managed
                    storagetier=Premium_LRS
Annotations:        node.alpha.kubernetes.io/ttl=0
                    volumes.kubernetes.io/controller-managed-attach-detach=true
CreationTimestamp:  Tue, 07 Aug 2018 11:10:59 -0300
Taints:             <none>
Unschedulable:      false
Conditions:
  Type                 Status    LastHeartbeatTime                 LastTransitionTime                Reason                     Message
  ----                 ------    -----------------                 ------------------                ------                     -------
  NetworkUnavailable   False     Tue, 07 Aug 2018 11:11:16 -0300   Tue, 07 Aug 2018 11:11:16 -0300   RouteCreated               RouteController created a route
  OutOfDisk            False     Wed, 08 Aug 2018 02:06:12 -0300   Tue, 07 Aug 2018 11:10:59 -0300   KubeletHasSufficientDisk   kubelet has sufficient disk space available
  MemoryPressure       Unknown   Wed, 08 Aug 2018 02:06:12 -0300   Wed, 08 Aug 2018 02:06:54 -0300   NodeStatusUnknown          Kubelet stopped posting node status.
  DiskPressure         Unknown   Wed, 08 Aug 2018 02:06:12 -0300   Wed, 08 Aug 2018 02:06:54 -0300   NodeStatusUnknown          Kubelet stopped posting node status.
  Ready                Unknown   Wed, 08 Aug 2018 02:06:12 -0300   Wed, 08 Aug 2018 02:06:54 -0300   NodeStatusUnknown          Kubelet stopped posting node status.
Addresses:
  InternalIP:  10.240.0.4
  Hostname:    aks-nodepool1-27465827-1
Capacity:
 cpu:     1
 memory:  3524680Ki
 pods:    110
Allocatable:
 cpu:     1
 memory:  3422280Ki
 pods:    110
System Info:
 Machine ID:                 d508809ec4884e4a81a6c6bb65b90961
 System UUID:                2A12839E-D8BB-2143-8486-5B8DBFC88399
 Boot ID:                    a70d27d9-4df7-4452-826a-0e9ba318c2a8
 Kernel Version:             4.15.0-1018-azure
 OS Image:                   Ubuntu 16.04.5 LTS
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://1.13.1
 Kubelet Version:            v1.9.9
 Kube-Proxy Version:         v1.9.9
PodCIDR:                     10.244.0.0/24
ExternalID:                  MY_ID
ProviderID:                  MY_PROVIDER
Non-terminated Pods:         (14 in total)
  Namespace                  Name                                         CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                                         ------------  ----------  ---------------  -------------
  default                    es-ingest-6f74964db8-5tzm9                   250m (25%)    1 (100%)    0 (0%)           0 (0%)
  default                    fluent-bit-n9cvp                             0 (0%)        0 (0%)      0 (0%)           0 (0%)
  default                    mongo-0                                      0 (0%)        0 (0%)      0 (0%)           0 (0%)
  homologation               gs1-batch-sync-product-676fd644b6-9lksv      0 (0%)        0 (0%)      0 (0%)           0 (0%)
  homologation               gs1-ms-product-validation-689d4b465-lbxjx    0 (0%)        0 (0%)      0 (0%)           0 (0%)
  homologation               mongo-0                                      0 (0%)        0 (0%)      0 (0%)           0 (0%)
  homologation               nats-deployment-795d98b4f9-8xqqx             0 (0%)        0 (0%)      0 (0%)           0 (0%)
  homologation               rabbitmq-74dffbc49f-c6rwn                    0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-proxy-bd5mj                             100m (10%)    0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-svc-redirect-7j4sd                      0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                tiller-deploy-f7bd48bf-kb6q4                 0 (0%)        0 (0%)      0 (0%)           0 (0%)
  production                 gs1-api-product-register-56c897685f-nw6j6    0 (0%)        0 (0%)      0 (0%)           0 (0%)
  production                 gs1-ms-getin-7ccf85864c-tf5ns                0 (0%)        0 (0%)      0 (0%)           0 (0%)
  production                 mongo-0                                      0 (0%)        0 (0%)      0 (0%)           0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ------------  ----------  ---------------  -------------
  350m (35%)    1 (100%)    0 (0%)           0 (0%)
Events:         <none>
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: v1.10.2
Server Version: v1.9.9
```

- Size of cluster (how many worker nodes are in the cluster?)
6
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Node.js Apps, Elastic Search
- Others:

**Comment by jskulavik** [comment] 2018-08-08 17:47
Hi @ErickWendel,

Can you please share your cluster info (sub id, resource group, resource id) @ aks-gh-feedback@service.microsoft.com

**Comment by ErickWendel** [comment] 2018-08-08 17:53
I'll send!!

**Comment by jskulavik** [comment] 2018-08-08 22:27
Hi @ErickWendel,

As a _managed service_ AKS will routinely apply patches, upgrades, and security amendments to the various components that comprise Kubernetes infrastructure on Azure.  In this case however, it appears that we needed to just be patient while that node in question was busy being rescheduled.  You should have full confidence in placing your apps on your cluster, even when one of your nodes is in a `NotReady` state as the robustness of Kubernetes will direct processing to the other available nodes in your cluster.

**Comment by aumanjoa** [comment] 2018-10-08 13:48
Hey, Is there any solution to this problem. It just happened for us in our production AKS cluster which includes customer impact.  

We saw that a node is getting in "NotReady" state and all pods have the status "Unknown" . 

Is there not a self healing for nodes? Why if a pod is not ready its not regenerated on a node which is in ready state?

**Comment by xxthegonzxx** [comment] 2019-02-05 23:33
Any update on this? It seems like AKS nodes going into NotReady state is problematic

**Comment by it-slav** [comment] 2019-02-08 08:15
Since 2 days I have the same issue
2 out of 3 nodes stays in NotReady state forever.

**Comment by vcorr** [comment] 2019-02-08 09:20
The easiest way to get nodes back to ready state seems to be to just restart the VM. Not elegant, but at least you get your node back in a few minutes.
There was this promising update few days ago from Microsoft, but there seems to be no timeline when this would be available: https://azure.microsoft.com/en-us/updates/node-auto-repair-support-for-aks/

**Comment by it-slav** [comment] 2019-02-08 09:37
I think he update stopped my deployment scripts from working, 
Suddenly az aks create does not accept
--nodepool-name $NODEPOOLNAME anylonger
I get "Operation failed with status: 'Bad Request'. Details: The value of parameter agentPoolProfile.name is invalid."

I have tried to restart the VMs and it does not help

**Comment by jnoller** [comment] 2019-02-08 14:09
Hi @it-slav - github isn't a great place to debug issues which are cluster-specific as you would need to supply sensitive data for the AKS team to pull up the information and get approval for log extraction. Please file a technical support issue in the azure portal and describe the issue, subscription ID, etc and link to this issue.

**Comment by nanab4u** [comment] 2019-02-26 11:46
Any update on this ?  Restarted the VMs which fixed the issue for us but the requests were going in to "Unknown" pod in the unhealthy node.

**Comment by jnoller** [comment] 2019-02-26 13:34
@nanab4u this can occur for many reasons; did you file a support ticket to escalate to engineering on call so we can root cause?

**Comment by jnoller** [comment] 2019-04-04 15:00
Closing as Duplicate of #274

**Closed by jnoller** 2019-04-04 15:00 UTC
Labels: scale-notready

**Comment by poochwashere** [comment] 2020-03-18 19:29
Scaling the cluster up or down has resolved this for me a few times in the past.
