### ISSUE TITLE
AKS upgrade removes node prior to pods being rescheduled and ready

### ISSUE THREAD

**Issue by scott1138** [Azure/AKS#1224] opened 2019-09-19 17:11 UTC
During AKS upgrades we experience outages because the upgrade continues to the next node before all scheduled pods are in a ready state.

The upgrade should wait for all scheduled pods to be ready before continuing.

Upgrade any cluster running a significant number of pods.

It seems like all of the pod images downloading simultaneously on new nodes delay the pod start.  We have pod disruption budgets set, but it doesn't seem to matter since the wording says that the upgrade only waits for pods to be scheduled.

version 1.14.6
5 nodes
workloads - http microservices, azure devops agents

**Comment by jluk** [comment] 2019-09-26 17:35
@scott1138 currently in our upgrade flow we wait a maximum of 20 minutes for the drain to complete prior to removing the node to continue with upgrade, this is currently in place to avoid sending your cluster into a failed upgrade state.

Are your pods taking longer than 20 minutes to be rescheduled into a ready state or do you see nodes being removed faster than that and prior to pods being set to ready on new nodes? 

As an aside, we have planned work to improve the resiliency of upgrade and minimizing possible impact to user deployed pods but in the meantime we want to capture more specifics of what is hitting you.

**Comment by ajlane17** [comment] 2019-09-26 18:28
Hello @jluk , I'm @scott1138 's colleague and can provide additional details. We have a few clusters, but characteristically, they are all similar: 
- Between 5-7 nodes
- Running 200-400 pods
- Front end services are configured with pod-level anti-affinity and multiple replicas, pod disruption budgets configured to 1 as the allowance, and custom readiness probes
- Each node hosts anywhere from 30-60 pods typically
- The vast majority of the deployments are built off of a handful images are several hundred megabytes each
- There are 2-5 large pods per cluster, 5-7 gigabytes, based off of one image that are configured with pod-level anti-affinity

What we see is that when a new node is rolled in, it appears Kubernetes tries to download all of the pods simultaneously, which in our case are all based on a very small subset of images, and it seemingly downloads each image to completion regardless of the image technically being completely downloaded already via another created pod that's completed and in running status. 

All of that is fine, but what we see during the upgrade, is that, depending on the node load, it can take an extraordinarily long time to download all of the images with the approach outlined above. We run into a scenario where the AKS upgrade has run through all of the nodes before the first node has finished downloading images, creating a service disruption.

**Comment by ajlane17** [comment] 2019-10-02 22:22
To follow up, we've identified the "issue". As was mentioned, we have one large image (several GB) that runs a few replicas. All of our images are hosted in Azure's ACR. The bandwidth limit for the ACR service at the premium tier is 100Mbps, which is where the bottleneck is coming from. We upgrade multiple clusters in parallel, and these very large images are the root cause of the slow download performance across the board. We've tested the process after removing the large images (reducing replicas to 0) prior to the upgrade and there was no downtime.

**Comment by jluk** [comment] 2019-10-02 23:49
Thanks for the follow-up @ajlane17 and the details. I had a response that never sent, but it ran along the lines of investigating the image download. Glad you figured out the problem on the image download front, closing this issue. 

I am however aligned AKS upgrade can improve so we are acting on it.

In the current model AKS does not block indefinitely for a drain to complete, but we have scoped work to improve the upgrade flow to be more efficient in how we replace nodes. In addition we will also be instrumenting better detection by integrating into Azure planned maintenance down the road to stay in sync with expected disruption. Thanks for the report and working with us.

**Closed by jluk** 2019-10-02 23:49 UTC
Labels: Upgrade, known-issue
