### ISSUE TITLE
AKS does not create Loadbalancer in the correct subnet

### ISSUE THREAD

**Issue by hibri** [Azure/AKS#221] opened 2018-03-05 11:56 UTC
I'm using https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters and the Terraform provider
https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html

AKS spins up the agent nodes in the specified subnet. However when I spin up a service with the yaml below, the internal load balancer is spun up in the MC_ resource group and the Vnet in the MC_resource group and not in the subnet specified in vnetSubnetID parameter

```yaml
apiVersion: v1
kind: Service
metadata:
  name: kuard-service-internal
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: kuard-front
```

**Comment by murraypete-tfedemo** [comment] 2018-03-05 14:33
Example response received:

`Error creating load balancer (will retry): Failed to ensure load balancer for service default/kuard-service-internal: [ensure(default/kuard-service-internal): lb(kubernetes-internal) - failed to ensure host in pool: "network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"NetworkInterfaceAndInternalLoadBalancerMustUseSameVnet\" Message=\"Network interface /subscriptions/xxxxxxx/resourceGroups/MC_aks-cluster_westeurope/providers/Microsoft.Network/networkInterfaces/aks-pool0001-17812977-nic-0 uses internal load balancer /subscriptions/xxxxxxx/resourceGroups/aks-cluster_westeurope/providers/Microsoft.Network/loadBalancers/kubernetes-internal but does not use the same VNET `

Expected behaviour for AKS clusters using private vNets is the internal balancer appears in the same vNet as the agent NICs, which would allow successful creation.

**Comment by murraypete** [comment] 2018-03-05 14:44
Example response received:

`Error creating load balancer (will retry): Failed to ensure load balancer for service default/kuard-service-internal: [ensure(default/kuard-service-internal): lb(kubernetes-internal) - failed to ensure host in pool: "network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"NetworkInterfaceAndInternalLoadBalancerMustUseSameVnet\" Message=\"Network interface /subscriptions/xxxxxxx/resourceGroups/MC_aks-cluster_westeurope/providers/Microsoft.Network/networkInterfaces/aks-pool0001-17812977-nic-0 uses internal load balancer /subscriptions/xxxxxxx/resourceGroups/MC_aks-cluster_westeurope/providers/Microsoft.Network/loadBalancers/kubernetes-internal but does not use the same VNET`

Expected behaviour for AKS clusters using private vNets is the internal balancer appears in the same vNet as the agent NICs, which would allow successful creation.

**Comment by feiskyer** [comment] 2018-03-08 08:35
Seems the subnet configured in azure cloud provider is not same with virtual machine's primary interface's subnet.

A workaround of this problem is set service annotation `service.beta.kubernetes.io/azure-load-balancer-internal-subnet=<subnet-name>`

**Comment by hibri** [comment] 2018-03-08 09:58
@feiskyer we tried this but the annotation is ignored. It seems to be in 1.9 which hasn't been rolled out yet. #103

**Comment by cdhunt** [comment] 2018-05-09 18:33
Adding the `azure-load-balancer-internal-subnet` annotation appears to cause AKS to try and create an LB in the correct Subnet as I received 403 error when it tried to configure the subnet.  I got past that by adding the Service Principle as a Contributor to the subnet. However, I'm now stuck on a less descriptive error.

```
Error creating load balancer (will retry): failed to ensure load balancer for service default/azure-vote-front: ensure(default/azure-vote-front): lb(kubernetes-internal) - failed to get subnet: aks-vnet-11111111/aks-subnet
```

**Comment by wittry** [comment] 2018-05-11 13:58
I am experiencing the same issue. The internal loadbalancer is created just fine when using aks basic network but but fails when using aks with advanced network. External loadbalancer creates fine on both however.

Using YAML of:

apiVersion: v1
kind: Service
metadata:
  name: lb-int
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - name: hydro
    port: 80
    targetPort: hydro-port
  selector:
    app: hydro

and error of: 
Code=\"NetworkInterfaceAndInternalLoadBalancerMustUseSameVnet\" 

Network interface 
/subscriptions/xxxxxxxxxxx/resourceGroups/MC_xxxxxxxxxx_centralus/providers/Microsoft.Network/networkInterfaces/aks-agentpool-10057859-nic-0 

uses internal load balancer
/subscriptions/xxxxxxxxxxx/resourceGroups/MC_hxxxxxxxxxx_centralus/providers/Microsoft.Network/loadBalancers/kubernetes-internal 

but does not use the same VNET 
/subscriptions/xxxxxxxxxxx/resourceGroups/MC_xxxxxxxxxx_CENTRALUS/providers/Microsoft.Network/virtualNetworks/AKS-VNET-99999999) as the load balancer.

**Comment by bjd145** [comment] 2018-05-11 15:50
I am getting the same error in the Central US region as wittry.  I do see the LB created as kubernetes-local but the backend pool named 'kubernetes' that is not associated to any availability set.

**Comment by noelbundick** [comment] 2018-05-11 19:56
I'm able to repro this as well. I'm seeing `"vnetName": "aks-vnet-28513887"` inside `/etc/kubernetes/azure.json` on my nodes. 

Looks like AKS auto-created a VNET and populated azure.json with its details rather than the VNET I specified at cluster creation time.

**Comment by JunSun17** [comment] 2018-05-11 23:14
@noelbundick Yes, the default VNET got created and the wrong azure.json is a known issue and a fix is underway.

I am looking at the LB issue and will update soon.

**Comment by JunSun17** [comment] 2018-05-12 22:50
@hibri @murraypete @feiskyer @cdhunt @wittry @bjd145 @noelbundick 

Confirmed the reported internal LB creation issue. It is tied to the wrong Azure Cloud Config consumed in controller manager pod. The fix is currently being tested, and I will update in this issue.

Thanks for reporting this issue and your patience!

**Comment by serbrech** [comment] 2018-05-16 08:48
Experienced this today too. keep us posted on a resolution :)

**Comment by JunSun17** [comment] 2018-05-16 16:30
The fixed has been tested and it is in the process of releasing. It is expected to be rolled out next week. 

Unfortunately a new cluster needs to be deployed to fix this issue. Sorry for the inconvenience.

**Comment by JunSun17** [comment] 2018-05-17 23:17
@hibri @murraypete @feiskyer @cdhunt @wittry @bjd145 @noelbundick @serbrech @valorl 
The fix has been sent out and in the pipeline for releasing. My estimate is that the whole releasing process will take 3-4 days WW.

**Comment by feiskyer** [comment] 2018-05-18 07:39
It gets the subnet from configured VNET in /etc/kubernetes/azure.json ( `vnetName`).

**Comment by valorl** [comment] 2018-05-18 08:12
Alright, my apologies, I didn't completely understand the `azure.json` issue before. I tried to manually edit `azure.json` on all my nodes with proper `vnetName` `vnetResourceGroup`  and `subnetName` , but the ILB still got created in the incorrect subnet. Is there something in K8S I need to restart maybe ? Should this hack even work?

**Comment by valorl** [comment] 2018-05-18 08:26
Yeah ok, so that's not gonna work for me since my subnet is in a different vnet, which itself is in a different resource group. Looking at the source, there don't seem to be any annotations for that, only the subnet name. Hopefully the fix is gonna arrive soon :)

**Comment by feiskyer** [comment] 2018-05-18 08:33
@valorl That's not supported on Azure. They should be on same vnet.

**Comment by valorl** [comment] 2018-05-18 09:00
@feiskyer Well my nodes are on the same VNET, it's just that the correct VNET isn't in `azure.json` so I was looking for a workaround. But yeah if the requirement is that it has to be the same VNET, it makes sense there's no annotation for it.

**Comment by feiskyer** [comment] 2018-05-18 09:17
@valorl See https://github.com/Azure/AKS/issues/221#issuecomment-390042748, The fix is in the pipeline for releasing now.

@JunSun17 What actions could do for existing clusters after the release?

**Comment by JunSun17** [comment] 2018-05-18 18:07
@feiskyer customer will need to recreate a new cluster to have the ILB working.

**Comment by jjindrich** [comment] 2018-05-21 19:42
I'm getting still same error.

**Comment by JunSun17** [comment] 2018-05-21 19:51
@kapopken @jjindrich Just checked and the fix has not been rolled to central US yet. Please give it another one or two days. Thanks!

**Comment by JunSun17** [comment] 2018-05-21 20:32
@valorl Sure, I asked and below is the rolling out schedule:

5/21 Canada region
5/22 US region
5/23 West Europe region

Thank you for the patience!

**Comment by kapopken** [comment] 2018-05-21 20:39
@JunSun17 When you say 5/22 US region. Does that mean all US regions?

**Comment by JunSun17** [comment] 2018-05-21 20:41
@kapopken yes, 5/22 for all US regions.

**Comment by DDebray** [comment] 2018-05-24 07:43
It has not been deployed to West Europe region yet or?

**Comment by hadr10** [comment] 2018-05-24 07:48
Still the same error for West Europe, I tried today to recreate the AKS cluster

**Comment by hadr10** [comment] 2018-05-24 07:55
Still the same error for West Europe, I tried today to recreate the AKS cluster

**Comment by kattelus** [comment] 2018-05-24 08:34
Same here for West Europe. Any news about rollout status?

**Comment by psxvoid** [comment] 2018-05-24 09:39
Working for me in WestEurope.

**Comment by alexisP** [comment] 2018-05-24 09:46
@psxvoid Seriously? My cluster created few minutes ago still have the same issue...

**Comment by frontbyte** [comment] 2018-05-24 10:20
@alexisP Sorry, the first load balancer I was created successfully for me somehow but further attempts are failing.

**Comment by psxvoid** [comment] 2018-05-24 10:22
@alexisP Sorry, the first load balancer was created successfully for me somehow (public ip was obtained) but further attempts are failing.

**Comment by tobiasrosenhoff** [comment] 2018-05-24 11:34
I have the same problem in West Europe. Is the US regions working?

**Comment by JunSun17** [comment] 2018-05-24 13:32
@DDebray @hadr10 @kattelus @psxvoid @alexisP @tobiasrosenhoff Just checked and west europe has not received the latest release yet. US regions have been rolled out now.

Will update about the release status shortly, thank you for the patience!

**Comment by kapopken** [comment] 2018-05-24 14:31
@JunSun17 still getting this error
![akserror](https://user-images.githubusercontent.com/739819/40492018-2dc442c0-5f35-11e8-8e65-d24a6fe2e2ae.PNG)

**Comment by valorl** [comment] 2018-05-24 14:33
@kapopken As mentioned earlier in the thread, the fix requires creating a new cluster. Just to clarify, did you do that and still get the error ?

**Comment by kapopken** [comment] 2018-05-24 14:34
@valorl Yes I created it 30 minutes ago

**Comment by DDebray** [comment] 2018-05-24 14:45
For me its working now, thank you :)

**Comment by valorl** [comment] 2018-05-24 14:51
@DDebray which region? west-europe or US ?

**Comment by DDebray** [comment] 2018-05-24 14:57
west-europe

**Comment by JunSun17** [comment] 2018-05-24 15:09
@kapopken this looks to be some permission issue to get the subnet. Is your subnet located in the same region as your cluster to be deployed?

**Comment by kapopken** [comment] 2018-05-24 15:40
@JunSun17 I'll try again. Should be same region but I have made mistakes before :). I'll report back today

**Comment by iremmats** [comment] 2018-05-24 18:12
Had same issue earlier today in West Europe but now it seems its fixed.

**Comment by hadr10** [comment] 2018-05-25 06:58
Works for me too in West Europe, thanks

**Comment by JunSun17** [comment] 2018-05-25 16:34
Great to see it works!

@kapopken there is a choice to create a VNET/Subnet when creating an AKS cluster, I think you can try that and see if it works. If it works, then you can probably try a different pre-created VNET/Subnet, hopefully it will help to isolate some possible issues and narrow down the root cause.

**Comment by kapopken** [comment] 2018-05-27 13:28
@JunSun17  I'll try that technique. Using an existing did not work

**Comment by kapopken** [comment] 2018-05-31 12:57
@JunSun17  finally got back to this and got the issue solved. The problem was I had this annotation from before the fix went into place     service.beta.kubernetes.io/azure-load-balancer-internal-subnet: 
Once I removed that, it worked and provisioned LB in correct subnet!
Thanks for help

**Comment by pcj** [comment] 2018-06-06 21:28
Slightly off topic, but I'm trying to use this feature and -- while it provisions seemingly successfully -- I cannot curl the service as expected.  

So I'm wondering: is there a minimum kubernetes version needed to use the `service.beta.kubernetes.io/azure-load-balancer-internal: "true"` feature?

**Comment by amandadebler** [comment] 2018-07-04 12:43
I am still having this problem with a cluster created today in West Europe, version 1.10.3.

**Comment by kapopken** [comment] 2018-07-04 13:10
@amandadebler can you post more details?

**Comment by amandadebler** [comment] 2018-07-09 07:48
Turned out that the Service Principal the cluster was created under did not have (Network) Contributor on the VLAN the cluster subnet was in. Our subscription owner is very hesitant to give the suggested permissions to us, so we're trying to work out the absolute minimums.

His biggest concern is that our own accounts or the Service Principals are able to make changes to the Network Security Group, beyond the rules that need to be added for exposed Kubernetes services.

**Comment by ans-cst** [comment] 2018-08-03 07:30
I am also having an issue using ARM template to deploy an AKS cluster.

Loadbalancer is created but does not configure the backend pool to point to the avSet of the AKS nodes.

**Comment by jnoller** [comment] 2019-04-02 16:18
Original issue resolved.

**Closed by jnoller** 2019-04-02 16:18 UTC
