### ISSUE TITLE
kubectl periodically fails to connect to the API server with no such host

### ISSUE THREAD

**Issue by alika** [Azure/AKS#882] opened 2019-03-27 22:05 UTC
**What happened**:
I periodically cannot connect to our AKS cluster with kubectl:
```
$ kubectl cluster-info

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: dial tcp: lookup global-260e2f2d.hcp.westus2.azmk8s.io: no such host

$ kubectl get no
Unable to connect to the server: dial tcp: lookup global-260e2f2d.hcp.westus2.azmk8s.io: no such host
```
After about 5-10 minutes it successfully connects. This is occurring several times a day, and being experienced by multiple engineers.

**What you expected to happen**:
I expect to be able to connect to the AKS consistently with kubectl.

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl cluster-info`

**Anything else we need to know?**:

- This started to occur after I recreated the AKS cluster with the same name (delete, create).
- I'm using the Terraform for AKS ([azurerm_kubernetes_cluster resource](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html)) to create and maintain the AKS cluster.
- There are similar no such host errors in the tunnelfront pod logs
- Similar to #104 

**Environment**:
- Kubernetes: 1.11.8
- Size: 5 x Standard_DS3_v2
- Workloads: jenkins, cert-manager, harbor, cockroachdb

**Comment by jnoller** [comment] 2019-03-27 22:59
@alika please open an azure support ticket in the portal so the team can RCA the issue, also I'd recommend deleting the subscription ID/region from your ticket ASAP (this is why we ask for support requests so this information doesn't get out).

**Comment by alika** [comment] 2019-03-28 01:06
@jnoller, unfortunately this particular subscription does not have a support plan in which i can create technical support requests.

**Comment by robinkb** [comment] 2019-03-28 08:34
FYI, GitHub saves a history of all edits made. That means your information is still easily retrieved.

**Comment by alika** [comment] 2019-03-28 16:02
@robinkb, do you have a suggestion on how to purge this somehow? Or do I need to scrap this cluster?

**Comment by robinkb** [comment] 2019-03-28 16:33
@alika Here you go: https://help.github.com/en/articles/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history

The problem is not really the ID of your cluster, but your subscription ID. You cannot change that by scrapping the cluster. See this StackOverflow question on why it might be considered sensitive: https://stackoverflow.com/questions/45661109/are-azure-subscription-id-aad-tenant-id-and-aad-app-client-id-considered-secre

There is no way to change the ID of a subscription, I don't think. So it is up to you to judge whether or not the ID of this particular subscription must be kept secret.

**Comment by alika** [comment] 2019-03-28 16:52
@robinkb, Thanks for the delete history reference.

**Comment by jnoller** [comment] 2019-04-05 18:09
Duplicate of #232

**Closed by jnoller** 2019-04-05 18:09 UTC

**Comment by speciesunknown** [comment] 2020-01-07 11:43
@jnoller

This is not a duplicate of #232 

The error here is "no such host" whereas #232 is about timeouts.

**Comment by sappojisetty** [comment] 2020-03-04 12:25
I'm trying to create a kubernetes cluster and the namespace using terraform and I see this issue. Can somebody help me to find solution for this?
I'm using Terraform v0.12.21

**Comment by m-osh** [comment] 2020-04-23 05:18
I just encountered the same issue in v0.12.21 as well 
@sappojisetty did you figure it out?

**Comment by sappojisetty** [comment] 2020-04-23 07:53
> I just encountered the same issue in v0.12.21 as well
> @sappojisetty did you figure it out?

I fixed this issue by running the command `kubectl config use-context <cluster-name>` before applying the terraform.
