### ISSUE TITLE
Capacity errors returned on AKS create in WestEurope

### ISSUE THREAD

**Issue by Michael-Coetzee** [Azure/AKS#1214] opened 2019-09-17 11:41 UTC
**What happened**:
Everytime we create a AKS cluster with terrafom we get this error:

Error: Error waiting for completion of Managed Kubernetes Cluster "<obscured>" (Resource Group "<obscured>"): Code="ResourcesOverConstrained" Message="Azure Container Service is unable to provision an AKS cluster in westeurope, due to an operational threshold. Please try again later or use an alternate location. For more details please refer to: https://github.com/Azure/AKS/blob/master/preview_regions.md."

link doesnt not work either
 
**What you expected to happen**:
That the AKS cluster get's created without error

**How to reproduce it (as minimally and precisely as possible)**:
run a very generic simple terrafom file to orchestrate the resource creation on azure 

**Anything else we need to know?**:

**Environment**:
kubernetes version  = 1.14.6
nodes = 2
vm_size = standardb2ms

**Comment by jluk** [comment] 2019-09-17 19:02
@Michael-Coetzee could (1) share the TF deployment file you're using with necessary secrets removed and (2) confirm if you are enabling the IP whitelisting feature for this specific cluster?

**Comment by Michael-Coetzee** [comment] 2019-09-17 20:11
Hey @jluk 

(1) here we go

variable "cluster_name" {
}

variable "stepping_ip" {
}

variable "agent_count" {
}

variable "client_id" {
}

variable "client_secret" {
}

variable "env" {
}

variable "vmsize" {
}

variable "location" {
}

variable "kube_version" {
}

variable "ssh_public_key" {
}

variable "project" {
  type = string
}

variable "subscription_id" {
  type    = string
  default = "caee32e1-13f1-4cef-a4d3-39475cae21ce"
}

module "resource-group" {
  source       = "git::ssh://some-repo.git//terraform/modules/resources"
  resource_env = var.env
  location     = var.location
  project      = var.project
}

resource "azurerm_kubernetes_cluster" "cluster" {
  name                = "${var.cluster_name}${var.project}"
  location            = var.location
  resource_group_name = module.resource-group.name
  dns_prefix          = "${var.cluster_name}${var.project}"
  kubernetes_version  = var.kube_version
  api_server_authorized_ip_ranges = [var.stepping_ip]

  linux_profile {
    admin_username = "some-admin-username"

    ssh_key {
      key_data = file(var.ssh_public_key)
    }
  }

  agent_pool_profile {
    name            = "some-name"
    count           = var.agent_count
    vm_size         = var.vmsize
    os_type         = "Linux"
    os_disk_size_gb = 30
  }

  service_principal {
    client_id     = var.client_id
    client_secret = var.client_secret
  }

  tags = {
    env = var.env
  }
}

module "ip" {
  source              = "git::ssh://**some-repo**.git//terraform/modules/ips"
  resource_group_name = azurerm_kubernetes_cluster.cluster.node_resource_group
  ip_env              = var.env
  project             = "**some-project**"
  location            = var.location
}

output "kube_config" {
  value = azurerm_kubernetes_cluster.cluster.kube_config_raw
}

output "host" {
  value = azurerm_kubernetes_cluster.cluster.kube_config[0].host
}

output "ip" {
  value = module.ip.ip_address
}

output "node_resource_group" {
  value = azurerm_kubernetes_cluster.cluster.node_resource_group
}

(2) yes i am see the section "api_server_authorized_ip_ranges = [var.stepping_ip]"

I have a followup question if i may... see screenshot attached
![image (4)](https://user-images.githubusercontent.com/8096175/65075847-f5e18f00-d997-11e9-94fd-0a36797ae353.png)
sorry for the orange text

**Comment by jluk** [comment] 2019-09-17 21:51
Thanks @Michael-Coetzee this looks to be occurring because you have the defined IP whitelisting feature enabled which requires some specialized capacity right now. 

For immediate mitigation/validation you can remove that feature and the cluster should be fine in that region, you can deploy to a separate region. 

We have a fix for this IP whitelisting capacity which should be out next Wednesday if you can wait until then. Apologies for this and thanks for the report/details, will wait on the proper solution and an ack from you prior to closing this issue.

**Comment by Michael-Coetzee** [comment] 2019-09-17 22:35
Hey @jluk Taking your questions into account, i removed the whitelisting section and ran it again, it created the cluster successfully. I will script the api WL for now. Thanks again, looking forward to hearing from you next week with some good news hopefully

**Comment by jluk** [comment] 2019-09-17 22:52
Thanks for testing to validate that was the issue, will get back to you once the fix is everywhere!

**Comment by rverschuur** [comment] 2019-09-18 10:27
We now have 2 tickets with the same issue. Since this one is open i repost my  comment on https://github.com/Azure/AKS/issues/38  here:

I can confirm that it doesnt work in west europe:

```
PS D:\> az aks create
>> -g $name
>> --name $name
>> --node-resource-group $nodeResourceGroup
>> --service-principal $appId
>> --client-secret $password
>> --network-plugin azure
>> --vnet-subnet-id $subnetId
>> --node-count 3
>> --node-vm-size Standard_B2s
>> --location westeurope
>> --generate-ssh-keys
>> --kubernetes-version 1.14.6
>> --service-cidr 192.168.0.0/16
>> --dns-service-ip 192.168.0.10

The behavior of this command has been altered by the following extension: aks-preview

Deployment failed. Correlation ID: abc35493-d2ee-4012-a1f5-eXXXX. Azure Container Service is unable to provision an AKS cluster in westeurope, due to an operational threshold. Please try again later or use an alternate location. For more details please refer to: https://github.com/Azure/AKS/blob/master/preview_regions.md.
```

**Comment by kewtree1408** [comment] 2019-09-18 11:59
Hello, I have the same problem with West Europe. I'm setting up Azure Terraform. For debug, I used this [basic example](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/examples/kubernetes/basic/main.tf).

I've got the same error:
```
Error: Error waiting for completion of Managed Kubernetes Cluster "mytag-k8s" (Resource Group "mytag-k8s-resources"): Code="ResourcesOverConstrained" Message="Azure Container Service is unable to provision an AKS cluster in westeurope, due to an operational threshold. Please try again later or use an alternate location. For more details please refer to: https://github.com/Azure/AKS/blob/master/preview_regions.md."

  on main.tf line 6, in resource "azurerm_kubernetes_cluster" "example":
   6: resource "azurerm_kubernetes_cluster" "example" {
```

I've tried the same configuration for North Europe and it started working. But not for West.

**Comment by tbertenshaw** [comment] 2019-09-18 15:16
we have the same issue on all our subscriptions provisioning to `westeurope` `ukwest` and `northeurope` work fine

**Comment by jluk** [comment] 2019-09-18 16:23
Thanks for the reports we're looking into it right now

**Comment by jvermast** [comment] 2019-09-18 17:14
Just received capacity errors deploying an AKS cluster to West Europe as well. 

At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
Details:
Conflict: {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "ResourcesOverConstrained",
        "message": "Azure Container Service is unable to provision an AKS cluster in westeurope, due to an operational threshold. Please try again later or use an alternate location. For more details please refer to: https://github.com/Azure/AKS/blob/master/preview_regions.md."
      }
    ]
  }
} undefined
Task failed while creating or updating the template deployment.

**Comment by gcarrarom** [comment] 2019-09-18 17:15
I'm re running into this issue as well for westeurope

```Azure Container Service is unable to provision an AKS cluster in westeurope, due to an operational threshold. Please try again later or use an alternate location. For more details please refer to: https://github.com/Azure/AKS/blob/master/preview_regions.md. ```

**Comment by jluk** [comment] 2019-09-18 17:16
Confirming that there are ongoing capacity issues even for all clusters in this region, our on-call team is working on this right now to expand this. Thanks for your patience we will continue to provide updates here.

**Comment by jluk** [comment] 2019-09-19 00:20
This issue has been mitigated and new capacity is live. I will leave this open until tomorrow for folks to verify before closing. Thank you.

**Comment by rverschuur** [comment] 2019-09-19 07:16
Good morning everybody,

Retried it based on the new status. I get an internal server error now (so something has changed):

```
PS D:\git\innotractor\docker\docs> az aks create `
>>     -g $name `
>>     --name $name `
>>     --node-resource-group $nodeResourceGroup `
>>     --service-principal $appId `
>>     --client-secret $password `
>>     --network-plugin azure `
>>     --vnet-subnet-id $subnetId `
>>     --node-count 3 `
>>     --node-vm-size Standard_B2s `
>>     --location westeurope `
>>     --generate-ssh-keys `
>>     --kubernetes-version 1.14.6 `
>>     --service-cidr 192.168.0.0/16 `
>>     --dns-service-ip 192.168.0.10
The behavior of this command has been altered by the following extension: aks-preview
Deployment failed. Correlation ID: 0a716883-c55e-4cbf-9275-db0f8031211e. Internal server error
```

**Comment by bbcnt** [comment] 2019-09-19 08:08
Just thought I would share, I've successfully created a cluster in West Europe sing terraform. I had the same issue as everyone here yesterday. Thanks for fixing it guys.

**Comment by rverschuur** [comment] 2019-09-19 12:56
I can confirm it works now. The second attempt worked.

**Comment by gcarrarom** [comment] 2019-09-19 13:13
Yes, working here as well. Clusters up and running 👍

**Comment by jluk** [comment] 2019-09-19 21:31
Thanks for the confirms everyone, apologies for this incident, we are reviewing the root cause and will be implementing fixes found through the post-mortem. Closing as impact is resolved and completed.

**Closed by jluk** 2019-09-19 21:31 UTC
Labels: known-issue

**Comment by MrMCake** [comment] 2019-09-25 09:21
Hey folks,
since yesterday I'm failing to deploy some of my clusters in a random fashion. To be precise, I have a test-pipeline running that deploys 2 clusters total and starting yesterday either one or both fail with the error message ```ControlPlaneProvisioningInternalError``` during ARM deployment.

The full error message is:
```PowerShell
(---)
VERBOSE: 8:00:16 AM - Checking deployment status in 15 seconds
##[error]System.Exception: 8:00:31 AM - Resource Microsoft.ContainerService/managedClusters 'xx-xxx-sbx-we-ttaks' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "ControlPlaneProvisioningInternalError",
        "message": "Internal server error"
      }
    ]
  }
}' found
```

Does anybody experience similar issues?

**Comment by jnoller** [comment] 2019-09-25 14:14
@MrMCake please open a support ticket - internal server errors are not normal but not the same error as this.
