### ISSUE TITLE
AKS Cluster Autoscaler stopped working

### ISSUE THREAD

**Issue by anjz** [Azure/AKS#1313] opened 2019-11-14 10:27 UTC
**What happened**:

We are using Kubernetes Cluster Autoscaler provisioned by AKS using the `--enable-cluster-autoscaler` flag.
After being working as expected for some time, it suddenly stopped working. It is not adding new nodes despite having Pending pods or removing nodes when they are underutilized.

This is the cluster autoscaler log message that we get every 10 minutes:

```
I1114 09:58:55.343387       1 azure_manager.go:261] Refreshed ASG list, next refresh after 2019-11-14 09:59:55.3433775 +0000 UTC m=+578717.580345028
I1114 09:58:55.367698       1 utils.go:514] Decreasing size of aks-default-xxxxxxxx-vmss, expected=8 current=7 delta=-1
E1114 09:58:55.367731       1 static_autoscaler.go:239] Failed to fix node group sizes: failed to decrease aks-default-xxxxxxxx-vmss: attempt to delete existing nodes targetSize:8 delta:-1 existingNodes: 8
```

It looks like autoscaler thinks the nodes in the cluster doesn't match the nodes in the vmss, but this is not the case.
VMSS has 7 instances and running `kubectl get nodes` gives 7 nodes. Seems to me that they're in sync (also ids match).

**What you expected to happen**:

Cluster autoscaler scaling up/down properly

**How to reproduce it (as minimally and precisely as possible)**:

I couldn't identify any way of reproducing the issue. It just happens at some point. I've seen this behaviour in more than 1 cluster.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: 1.14.8
- Size of cluster: min nodes 5, max 100
- General description of workloads in the cluster:
We run some services written in Go and also some Kubernetes jobs (which we delete 2h after completion).

**Comment by immunochomik** [comment] 2019-11-14 10:29
We see the same issue in our cluster, the autoscler works for few hours and then stops 
!!!

**Comment by jluk** [comment] 2019-11-14 18:30
Thank you folks for the report, the AKS team is investigating and will communicate any discovery. Please upvote this comment if you started seeing this issue after 11/10.

**Comment by jluk** [comment] 2019-11-14 23:09
@anjz or @immunochomik can you please open a support request so our engineering team can take a look at your cluster? does it enter and stay in broken state or does it self-resolve at some point?

we've been unable to reproduce the issues provided on our own so would like to look at your clusters.

**Comment by immunochomik** [comment] 2019-11-15 09:54
@jluk We have already done it

**Comment by immunochomik** [comment] 2019-11-15 09:55
It is not a problem with our particular cluster, it is clearly a bug on your side just fix it pleas !!!

**Comment by jluk** [comment] 2019-11-15 20:31
@anjz Could you share your support ticket number so I can track for updates from my side?

We understand you are experiencing an issue, as stated I was unable to reproduce the problem. With your ticket we'll have on-call SREs investigate. By being able to reproduce or get details on the issue  from specific clusters we are able to faster diagnose and resolve the issue.

**Comment by anjz** [comment] 2019-11-18 10:21
Here the support ticket number: 119111522000486

**Comment by djsly** [comment] 2019-11-28 13:42
this is my Support Request: 119111524000469 , 4th time we see this.  We need to disable and reenable the CA feature to fix it. since we cannot simply restart the pod (no access)

```
11/28/2019, 1:11:50.000 PM	E1128 13:11:50.405508 1 static_autoscaler.go:240] Failed to fix node group sizes: failed to decrease aks-linux-37536111-vmss: attempt to delete existing nodes targetSize:26 delta:-1 existingNodes: 26	
11/28/2019, 1:11:50.000 PM	I1128 13:11:50.405450 1 utils.go:514] Decreasing size of aks-linux-37536111-vmss, expected=26 current=25 delta=-1	
11/28/2019, 1:11:40.000 PM	E1128 13:11:40.357515 1 static_autoscaler.go:240] Failed to fix node group sizes: failed to decrease aks-linux-37536111-vmss: attempt to delete existing nodes targetSize:26 delta:-1 existingNodes: 26	
11/28/2019, 1:11:40.000 PM	I1128 13:11:40.301802 1 azure_manager.go:261] Refreshed ASG list, next refresh after 2019-11-28 13:12:40.301787203 +0000 UTC m=+671124.369921116	
11/28/2019, 1:11:40.000 PM	I1128 13:11:40.357439 1 utils.go:514] Decreasing size of aks-linux-37536111-vmss, expected=26 current=25 delta=-1	
11/28/2019, 1:11:30.000 PM	I1128 13:11:30.203219 1 utils.go:514] Decreasing size of aks-linux-37536111-vmss, expected=26 current=25 delta=-1	
11/28/2019, 1:11:30.000 PM	E1128 13:11:30.203299 1 static_autoscaler.go:240] Failed to fix node group sizes: failed to decrease aks-linux-37536111-vmss: attempt to delete existing nodes targetSize:26 delta:-1 existingNodes: 26	
11/28/2019, 1:11:19.000 PM	I1128 13:11:19.543331 1 utils.go:514] Decreasing size of aks-linux-37536111-vmss, expected=26 current=25 delta=-1
```

I have opened https://github.com/kubernetes/autoscaler/issues/2594

**Comment by Starblade42** [comment] 2019-12-05 18:40
We've been encountering this issue as well in our non-AKS Azure clusters that use the Cluster Autoscaler component. 1.15.1 in our case.

**Comment by nilo19** [comment] 2019-12-10 06:37
It seems we got unregistered node unexpectedly after long time's running. Will add some log to gain insight into it.

**Comment by nilo19** [comment] 2019-12-18 01:45
The bug has been fixed by https://github.com/kubernetes/autoscaler/pull/2613.

There will be a hotfix soon.

**Comment by palma21** [comment] 2020-01-21 17:41
Hotfixed rolled out

**Closed by palma21** 2020-01-21 17:41 UTC
Labels: SR-opened, autoscaler, known-issue
