### ISSUE TITLE
Creating Windows nodepool with availability zones fails

### ISSUE THREAD

**Issue by brobichaud** [Azure/AKS#1133] opened 2019-07-31 23:03 UTC
**What happened**: Trying to create a Windows nodepool that utilizes availability zones in a newly created cluster that uses AZ's and Standard LB. I am receiving this error when trying to create the nodepool:

>  Operation failed with status: 'Bad Request'. Details: Standard Load Balancer is required for availability zone.

**What you expected to happen**: For the nodepool creation command using az to complete and spread nodes across zones.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create new cluster and include these options:
>         --load-balancer-sku standard
>         --node-zones 1 2 3
2. Create a Windows nodepool and include this option:
>         --node-zones 1 2 3

Here's the full command used to create the cluster:
> az aks create -g mycluster -n mycluster -p mycluster -l westus2 --node-resource-group mycluster-aks --node-vm-size Standard_D1_v2 --node-count 1 --node-zones 1 2 3 --enable-vmss --load-balancer-sku standard --network-plugin azure --kubernetes-version 1.14.3 --generate-ssh-keys --service-principal myprincipal --client-secret mysecret --windows-admin-username myadminuser --windows-admin-password myadminpwd --enable-addons monitoring --workspace-resource-id mylogwkspc

And the full command to create the nodepool:
> az aks nodepool add -g mycluster --cluster-name mycluster -n win1 --os-type Windows --node-vm-size Standard_F8s_v2 --node-count 2 --node-zones 1 2 3 --kubernetes-version 1.14.3

**Anything else we need to know?**:
Using the "az aks show" command results in the snippet below that shows the cluster is using a standard LB:

> "networkProfile": {
>     "dnsServiceIp": "10.0.0.10",
>     "dockerBridgeCidr": "172.17.0.1/16",
>     "loadBalancerSku": "standard",
>     "networkPlugin": "azure",
>     "networkPolicy": null,
>     "podCidr": null,
>     "serviceCidr": "10.0.0.0/16"
>   }
> 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.3
- Size of cluster (how many worker nodes are in the cluster?): 2 Standard_F8s_v2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): DotNetCore Api & UI, DotNetFramework Workers
- Others:

**Comment by jluk** [comment] 2019-08-01 06:39
Thanks @brobichaud we're looking into this bug

**Comment by xizhamsft** [comment] 2019-08-01 23:00
Found the problem. Will fix in next week's release.

**Comment by brobichaud** [comment] 2019-08-01 23:02
> Found the problem. Will fix in next week's release.

Will the fix work with existing clusters that were created to support AZ's by creating a new Windows nodepool?

**Comment by xizhamsft** [comment] 2019-08-01 23:55
> > Found the problem. Will fix in next week's release.
> 
> @xizhamsft Will the fix work with existing clusters that were created to support AZ's by creating a new Windows nodepool?

Yeap. It should

**Comment by brobichaud** [comment] 2019-08-02 00:00
@xizhamsft thank you! I'd appreciate it if you could update this issue when the fix is deployed. I am anxious to try it out. :-)

**Comment by jluk** [comment] 2019-08-02 07:46
Xiaofang made a fix and set for release next week. Will let you know next week when to retry to confirm resolution.

**Comment by sundipnair** [comment] 2019-08-06 09:15
@xizhamsft , Have you created a new issue for this or should I watch this issue?

**Comment by xizhamsft** [comment] 2019-08-08 21:16
@sundipnair , @brobichaud , the fix is  available in US regions now. Please give it a try. It will reach all regions by end of this week.

**Comment by brobichaud** [comment] 2019-08-08 22:44
@xizhamsft I've tried to create a new nodepool a few times and am seeing errors like this:
> Deployment failed. Correlation ID: 5a00e266-0326-4383-81f3-535a37133740. autorest/azure: Service returned an error. Status=404 Code="DeploymentNotFound" Message="Deployment 'f1818e2c-43b7-4c7b-aae5-5def6c4891ee' could not be found."

Here's the cli command I am using:
`az aks nodepool add -g mygroup --cluster-name mycluster -n win5 --os-type Windows --node-vm-size Standard_F8s_v2 --node-count 2 --node-zones 1 2 3`

The cluster itself was created (as described in this initial issue with these options:
> --load-balancer-sku standard
> --node-zones 1 2 3

**Comment by xizhamsft** [comment] 2019-08-14 21:09
@brobichaud Sorry for the late reply. The reason for the failure is that Standard_F8s_v2 is not available for zones 1, 2, 3 in westus2 region. You have to choose another sku. I think E8-4s_v3 should work. 

We need to improve the error message for this failure. I will work on that.

**Comment by brobichaud** [comment] 2019-08-14 21:16
@xizhamsft ah, that makes some sense. Do you happen to know the cli or powershell query to discover what SKU's are available in each AZ within a region?

**Comment by jluk** [comment] 2019-08-14 21:46
@brobichaud I think this is what you are looking for:
https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-list-skus

Closing this issue now that we've resolved root cause and taken an item to improve the error message.

**Closed by jluk** 2019-08-14 21:46 UTC
Labels: bug, windows, zones
