### ISSUE TITLE
Incorrect path for nginx ingress health probes

### ISSUE THREAD

**Issue by shiv-rajawat** [Azure/AKS#2903] opened 2022-04-22 10:24 UTC
**What happened**: Upon installing nginx ingress using helm, the default health probe with HTTP/HTTPS is getting configured with path as "/". As a result, the inbound connectivity to that nginx public IP is not working. 

**What you expected to happen**: The path should be "/healthz" with HTTP/HTTPS health probes.

**How to reproduce it**: Install nginx ingress using helm
`helm install ingress-nginx ingress-nginx/ingress-nginx`

Check the AKS loadbalancer health probes for path in nginx ingress probes (HTTP/HTTPS).

![health-probe](https://user-images.githubusercontent.com/29551093/164689898-bc0c3ea8-91f2-4115-bd68-620d04aa9bde.png)

**Anything else we need to know?**: The issue is only reproducing for us in selected West Europe AKS clusters.

**Environment**:
- Kubernetes version: 1.22.6
- Size of cluster: 30 nodes
- General description of workloads in the cluster - HTTP microservices, Angular applications

**Comment by LennartHaggkvistHM** [comment] 2022-04-22 12:44
This is also affecting us.

My conclusions are:
* It is not only west Europe - we have the problem in east Australia as well
* Old clusters has LB health probes of type TCP  - but the newly created clusters use HTTP or HTTPS
* Those health probes seems to be using the wrong path - manually changing to /healtz worked

**Comment by mkoertgen** [comment] 2022-04-22 19:08
Same for me. Scenario: AKS (EastUS2) + ingress-nginx (via helm). 

My observations:
- Frontend-IP-config for Azure Load Balancer in the MC-rg then fails.
- Old clusters are using TCP-Probes mapped to the k8s-service-ports.
- New clusters are using HTTP/HTTPS-Probes mapped to 80/443 respectively.
- As a result no traffic is routed to the ingress-controller since health probes fail.

Workaround:
When manually changing health probes back to TCP and mapped ports, health probes reconcile after a while

![image](https://user-images.githubusercontent.com/7235760/164778542-01d18899-bcf5-4f5c-a30f-f624368af3e3.png)

Load Balancer starts routing traffic

![image](https://user-images.githubusercontent.com/7235760/164778303-3f11c16a-f400-4d4a-86da-f1ab660acdb2.png)

And we finally get our nice nginx 404-page again

![image](https://user-images.githubusercontent.com/7235760/164778631-6dcd460a-a4a9-4e1d-bfbb-6f24753123a8.png)

**Comment by jabbera** [comment] 2022-04-23 16:40
I just lost 4 hours of my weekend trying to diagnose this issue.....

**Comment by shiv-rajawat** [comment] 2022-04-23 16:59
Well, I lost my entire day to debug this issue. Surprisingly I’m not able to reproduce this issue in other clusters in the same region.

**Comment by jabbera** [comment] 2022-04-23 17:07
The only notable change I can think of is my dev cluster that didn't see the issue was created as 1.22.06 whereas my production cluster was an upgrade.

**Comment by jabbera** [comment] 2022-04-23 17:25
@miwithro support might be saved a ton of tickets if this could be tracked down. I also opened a sev A over it.

**Comment by shiv-rajawat** [comment] 2022-04-23 17:44
> @miwithro support might be saved a ton of tickets if this could be tracked down. I almost opened a sev A over it.

We already have a Sev B opened.

**Comment by jabbera** [comment] 2022-04-23 19:11
Same issue with my DR cluster in centralus.

**Comment by sebader** [comment] 2022-04-25 08:39
Same issue here, AKS 1.22.6 in various regions (at least Sweden Central and Brazil south). Did anybody figure out a solution yet apart from the manual workaround?

**Comment by aristosvo** [comment] 2022-04-25 14:20
It seems the same or similar as [this solved issue](https://github.com/kubernetes/ingress-nginx/issues/8501#issuecomment-1108428615) on the `kubernetes/ingress-nginx` repo itself.

Use the flag `--set controller.service.externalTrafficPolicy=Local` should probably fix it.

**Comment by ivanthelad** [comment] 2022-04-26 08:11
Hi, 
is this behaviour by design?The cloud provider documentations states that the default path for the probe will be "/" if not specified. 
The [table ](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/site/content/en/topics/loadbalancer.md#custom-load-balancer-health-probe) thats that for http/https endpoints the default probe will be "/"

previously the behaviour used to be "/healthz" but a recent change altered this  https://github.com/kubernetes-sigs/cloud-provider-azure/commit/6cdd799230ced6084c7b3fa38bde7cd2108da1fc where the default path was modified 

The cloud provides logic can be found here. 
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/2b91a85af9436e8826bf7c8c79fb055e6d58ad8a/pkg/provider/azure_loadbalancer.go#L1977

one work around would be to supply the annotation to the nginx helm install 
https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml#L454

**Comment by heoelri** [comment] 2022-04-26 08:35
> It seems the same or similar as [this solved issue](https://github.com/kubernetes/ingress-nginx/issues/8501#issuecomment-1108428615) on the `kubernetes/ingress-nginx` repo itself.
> 
> Usage of the flag `--set controller.service.externalTrafficPolicy=Local` should probably fix it.
> 
> I'm not 100% sure if this is just a workaround or the fix, but I'll leave that discussion for the AKS team.

Setting `controller.service.externalTrafficPolicy` to `Local` when deploying the `ingress-nginx` helm chart as mentioned by @aristosvo in https://github.com/Azure/AKS/issues/2903#issuecomment-1108641389 did the trick on our end and solved the issue. The LB's health probe then points again to path `/healthz` instead of `/` - now for HTTP and HTTPS in a single health probe.

**Comment by ivanthelad** [comment] 2022-04-26 12:24
What I see, the  reason for this issue comes down to the helm chart adopting appProtocol spec combined with the cloud provider respecting the appProtocol setting.  So when a service is created with appProtocol the LB will probe directly to pod process (via the kube-proxy hop). I think previously the probe was based on the NodeHealthPort  created on each node. In this case the 503 would be returned from the kubernetes api if the pod endpoint was not available on the target host. 
https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/controller-service.yaml#L70


In general, i would guess the underlying CloudProvider was updated on AKS that has resulted in th appProtocol been respected and hence the changes to the probe where "/" is set when not path annotation is supplied. possible fixes 
 -  Manually set the annotation on the service that includes the health check path 
 -  upgrade your nginx helm chart setting the param "Values.controller.service.appProtocol" to false

**Comment by ivanthelad** [comment] 2022-04-26 12:25
i expect other applications that use to service spec appProtocol to be effected

**Comment by phealy** [comment] 2022-04-26 12:52
A documentation PR has been merged to add `--set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz` to the `helm` commands, which will tell Cloud Provider how to set the health probe properly. Docs will be updated in the next build, later today.

**Comment by sebader** [comment] 2022-04-26 12:59
@phealy thanks for updating the docs. While this makes all sense to me, including the solution, I want to point out this this is a major breaking change for many people out there and it was clearly not announced as such.

**Comment by jabbera** [comment] 2022-04-28 16:42
> happily testing AKS upgrade to 1.22 in UAT before 20/04 and then suddenly find when they go to a production roll out it starts breaking.

This is exactly what happened to me on Saturday. I had a literal panic since there is no rollback. Also missed a little league game over it.

**Comment by idmurphy** [comment] 2022-04-28 22:16
@phealy  - is a "beta" option really considered a suitable solution for a production issue?  When is this GA?

**Comment by sebader** [comment] 2022-04-29 10:29
@idmurphy all the cloud provider-specific annotations are using the same syntax. This does not mean any of these are in preview. https://kubernetes-sigs.github.io/cloud-provider-azure/topics/loadbalancer/#loadbalancer-annotations (same for AWS https://kubernetes.io/docs/concepts/services-networking/service/#other-elb-annotations)

**Comment by knunery** [comment] 2022-05-01 22:56
THANK YOU [mkoertgen](https://github.com/mkoertgen)! Running into this issue. I was about to open a ticket for this issue.

**Comment by feiskyer** [comment] 2022-05-03 04:03
Sorry to see the appProtocol support inside cloud provider has broken ingress-nginx for AKS clusters >=1.22. The issue was caused by two reasons: 

* 1) the new version of nginx ingress controller added appProtocol and its probe path has to be /healthz; 
* 2) the new version of cloud-controller-manager added HTTP probing with default path / for appProtocol=http services.

AKS is rolling out a fix to keep backward compatibility (ETA is 48 hours from now) with fix [cloud-provider-azure#1626](https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1626). After this fix, the default probe protocol would only be changed to appProtocol for clusters >=1.24 (refer [docs](https://kubernetes-sigs.github.io/cloud-provider-azure/topics/loadbalancer/#custom-load-balancer-health-probe) for more details).

Before the rollout of this fix, please upgrade the existing ingress-nginx with `--set controller.service.externalTrafficPolicy=Local` for faster mitigation. 

And for newly created helm releases, you could also set `--set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz` to ensure `/healthz` probe path be used with HTTP/HTTPS protocol (AKS docs has been updated with this annotation as well, e.g. [here](https://docs.microsoft.com/en-us/azure/aks/ingress-basic?tabs=azure-cli)).

**Closed by feiskyer** 2022-05-03 04:03 UTC
Labels: question, networking/load-balancers
