### ISSUE TITLE
Migrate from AKS 2022-04-02-preview API before 1 September 2023 

### ISSUE THREAD

**Issue by teocrispy91** [Azure/AKS#3639] opened 2023-05-05 04:05 UTC
I received an email from microsoft stating tha 2022-04-02 api will get deprecated and will no longer work after sept 2023 and the api will no longer work what does this actually mean?

**Comment by ageisen2000** [comment] 2023-05-05 17:46
Is it possible to check what users used this command or what clusters are effected currently? We use terraform to create our AKS cluster and I don't see anywhere that we specifically reference this api.

**Comment by wedge76** [comment] 2023-05-09 06:55
I received the same email and didn't know how to proceed with the information given either in the email or to provided links.

At the end I performed these steps:

1. Enlist your extensions by: `az extension list`
2. Update a specific extension, like: `az extension update --name "aks-preview"`
3. Check the version again: `az extension list`

**Comment by Nitesh002** [comment] 2023-05-09 09:26
Did the above solution worked? Is it showing the new version?

**Comment by benoit-parmentier-2** [comment] 2023-05-09 11:53
Azure support response

> This API change should not affect any workloads you have running on AKS. 
> 
> The only important thing here is that outdated versions of tools that may use this API will no longer work, tools would include az cli, Terraform etc.
> To avoid any issues with any tools you may be using with this API depreciation, you should generally just be able to update the tool and continue on.
> 
> If you are not referencing this API specifically in any of your code etc, this should be the only step you have to take.

**Comment by easimon** [comment] 2023-05-09 14:03
I received a different response telling me that affected clusters (which happens to be all of our clusters) itself require "migration". To migrate, I should just update all the things

* Terraform to the latest available release
* Terraform AzureRM provider to the latest available release
* The AKS cluster(s) in question to the latest available Kubernetes version

And during the AKS upgrade to latest Kubernetes version (using latest terraform + AzureRM), the cluster would be "migrated" to the latest API version, whatever that means. To me this reads, that the cluster and/or workloads could be affected if I don't upgrade before the preview API version is retired.

While the response @benoit-parmentier-2 received sounds more plausible, we'll upgrade all the things "to be safe".

**Comment by matthchr** [comment] 2023-05-16 15:31
@easimon asked:
> The AKS cluster(s) in question to the latest available Kubernetes version

This is not required.

This change only impacts the REST API version used to communicate with AKS. It has no bearing or impact on the _Kubernetes version_. You do **not** need to upgrade your clusters Kubernetes version because of this notice.

We recommend you upgrade Terraform/AzureCLI/any SDKs you're using to the latest release. If you're using ARM template or BICEP, the API version is specified in the template or BICEP file and you can update it there if you're on an older `-preview` API version.

@ageisen2000 asked:
> Is it possible to check what users used this command or what clusters are effected currently? We use terraform to create our AKS cluster and I don't see anywhere that we specifically reference this api.

If you use Terraform and are using `AzureRM` version 3.29 or later you are safe. To your question, yes it should be possible to query what API version has been used via `az monitor activity-log list`. Unfortunately right now there is a bug preventing this query from containing the API version, which you obviously would need in order to find the calls that are "at risk" of failing after 1 September 2023. We are working with the monitoring team to get that bug fixed in a few weeks. 

We will sync back here as soon as we have more information on the fix for the issue mentioned above, including a complete `az monitor activity-log list` commandline you can use to find calls using this deprecated API version.

**Comment by easimon** [comment] 2023-05-16 16:13
@matthchr Thanks for the information. Meanwhile we upgraded our clusters as well, which was due anyway. 

You should tell this to the Azure Support engineers as well, as at least some of them seem to have no idea and start guessing wildly.

**Comment by matthchr** [comment] 2023-05-16 18:54
Since I have you here:

Would this additional information in the email have helped make things clearer?


> You may be consuming this API through a tool such as Terraform or az cli:
> - For az cli: update the CLI itself and the aks-preview extension (if used) to the latest version by running `az upgrade` and `az > extension update --name "aks-preview"`.
> - For Terraform: Update to the latest version of Terraform AzureRM. To determine what version of the API a particular Terraform release is using, check the [Terraform release notes](https://learn.microsoft.com/en-us/azure/developer/terraform/provider-version-history-azurerm)  or git log [this file](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/containers/client/client.go) .
> - For other tools: Update the tool to the latest version.
> 
> If you're not sure what client or tool you're using which could be using this API version, check [activity logs](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log) using the following command:
> ```
> az monitor activity-log list --offset 30d --max-events 10000 --namespace microsoft.containerservice <exact command TBD,  once bug mentioned above is fixed>"
> ```

If not, what additional information in the email would have helped?

**Comment by ageisen2000** [comment] 2023-05-16 22:11
@mattchr yes, that would've been a lot better to have some way of figuring out which resources are using these API calls.

**Comment by wedge76** [comment] 2023-05-17 05:54
@matthchr I agree with ageisen2000, this would have been more helpful and less confusing. Thanks anyway.

**Comment by easimon** [comment] 2023-05-17 13:55
@matthchr yes, that would have been helpful enough to understand what API is actually meant and how it happens to be called. While I assumed that the mail meant the Azure API that manages the cluster (and hence my tools calling it, i.e. terraform), I was not sure.

Also, I am always nervous that "having created something using a preview feature" could somehow result in a resource that needs recreation because that preview feature changed in an incompatible way. So, explicitly mentioning that ("you do not need to upgrade / recreate the cluster itself, just the tools and you're fine") would help as well.

**Comment by mbrosda** [comment] 2023-05-30 06:28
Hello @matthchr ,
is there some update about this bug fix? It shouldn't be a big deal to add the API version to the activity logs so that one can monitor the usage of certain API versions via "az monitor activity-log list". Anywhere where we can upvote?

**Comment by matthchr** [comment] 2023-06-02 19:05
Missed your ping @mbrosda, sorry for the slow response.

api-version is supposed to be in `az monitor activity-log list`. It's actually a bug that it's not. We found and reported that bug and a fix is currently being worked on + rolled out. ETA is ~2 weeks from now. I'll come back here and update once it's actually confirmed fixed.

**Comment by matthchr** [comment] 2023-06-09 17:56
The fix to expose apiVersion in `az monitor activity log` has been rolled out.
```
API_VERSION=2022-04-02-preview
az monitor activity-log list --offset 30d --max-events 10000 --namespace microsoft.containerservice --query "[?eventName.value == 'EndRequest' && contains(not_null(httpRequest.uri,''), '${API_VERSION}')]"
```

Will now show you all calls made using this APIVersion in the last 30d. You should be able to track down the callers based on the identity field.

You can also see the [official announcement issue](https://github.com/Azure/AKS/issues/3696) which describes this and includes details about all of the APIs whose deprecation has been announced.

**Comment by matthchr** [comment] 2023-06-09 17:56
I'm going to go ahead and close this issue - further questions about this should be moved to #3696. Thanks for your patience.

**Closed by matthchr** 2023-06-09 17:56 UTC
Labels: question
