### ISSUE TITLE
[Virtual Nodes] Unable to delete AKS due to inability to delete ACI network resources

### ISSUE THREAD

**Issue by zer0big** [Azure/AKS#1427] opened 2020-02-05 15:20 UTC
**What happened**:

Unable to remove AKS. 
When attempting to remove an aks using command "az aks delete --name zerobigdemoaks --resource-group temp0130", the following error occurs:

`zerobig@ZEROBIG-NT800:/mnt/d/Azure-Study/20200205 - AKS$ az aks delete --name zerobigdemoaks --resource-group temp0130
Are you sure you want to perform this operation? (y/n): y
Deployment failed. Correlation ID: 86ee5b55-5b95-4d24-91d0-e3e20008c508. ResourceGroupReconciler retry timed out: Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=409 -- Original Error: Code="ResourceGroupDeletionBlocked" Message="Deletion of resource group 'MC_temp0130_zerobigdemoaks_japaneast' failed as resources with identifiers 'Microsoft.Network/networkProfiles/vk-4c552796fd5ae9643bf068fe336c3b44ddc75205e1bde5112652d8ebc8148b8d' could not be deleted. The provisioning state of the resource group will be rolled back. The tracking Id is 'b0299653-7efa-43a9-8962-fdf5d9cd8d80'. Please check audit logs for more details." Details=[{"AdditionalInfo":null,"Code":null,"Details":null,"Message":"{\"error\":{\"code\":\"NetworkProfileAlreadyInUseWithContainerNics\",\"message\":\"Network profile /subscriptions/f8764f39-01ee-4631-9941-77b286ed971b/resourceGroups/MC_temp0130_zerobigdemoaks_japaneast/providers/Microsoft.Network/networkProfiles/vk-4c552796fd5ae9643bf068fe336c3b44ddc75205e1bde5112652d8ebc8148b8d is already in use with container nics 
eeadc77b-a791-4ca3-9b35-7ce9995131a2_eth0; cannot update or delete\",\"details\":[]}}","Target":"/subscriptions/f8764f39-01ee-4631-9941-77b286ed971b/resourceGroups/MC_temp0130_zerobigdemoaks_japaneast/providers/Micro`

Also using command "az group delete -n temp0130", the following error occurs:

`zerobig@ZEROBIG-NT800:/mnt/d/Azure-Study/20200205 - AKS$ az group delete -n temp0130 
Are you sure you want to perform this operation? (y/n): y
Deployment failed. Correlation ID: 58314d07-3beb-4df0-b258-f73ad68559fe. Operation failed with status: 'Conflict'. Details: 409 Client Error: Conflict for url: https://management.azure.com/subscriptions/f8764f39-01ee-4631-9941-77b286ed971b/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1URU1QMDEzMC1KQVBBTkVBU1QiLCJqb2JMb2NhdGlvbiI6ImphcGFuZWFzdCJ9?api-version=2019-07-01
`
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I created this aks cluster 7 days ago. I also tried to remove this resource group on the azure portal. but couldn't remove at all. 

![image](https://user-images.githubusercontent.com/38598117/73853890-ebeff800-4874-11ea-9e0f-49dbb6d69251.png)

![image](https://user-images.githubusercontent.com/38598117/73853774-c4992b00-4874-11ea-805f-ad35c05fb6fa.png)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.8
- Size of cluster (how many worker nodes are in the cluster?): 1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): for aci demo
- Others:

**Comment by jluk** [comment] 2020-02-05 17:31
@zer0big apologies for this issue, this is an active issue caused by the ACI service. 

Could you please open a support request filed to ACI to resolve this?

**Comment by zer0big** [comment] 2020-02-05 23:15
@jluk This is the status of the worker node.

`zerobig@ZEROBIG-NT800:/mnt/d/Azure-Study/20200205 - AKS$ kubectl get nodes
NAME                     STATUS     ROLES   AGE     VERSION
virtual-node-aci-linux   NotReady   agent   6d14h   v1.14.3-vk-azure-aci-v1.2.1
zerobig@ZEROBIG-NT800:/mnt/d/Azure-Study/20200205 - AKS$ kubectl describe node virtual-node-aci-linux
Name:               virtual-node-aci-linux
Roles:              agent
Labels:             alpha.service-controller.kubernetes.io/exclude-balancer=true
                    beta.kubernetes.io/os=linux
                    kubernetes.io/hostname=virtual-node-aci-linux
                    kubernetes.io/os=linux
                    kubernetes.io/role=agent
                    type=virtual-kubelet
Annotations:        node.alpha.kubernetes.io/ttl: 0
CreationTimestamp:  Thu, 30 Jan 2020 17:15:28 +0900
Taints:             node.kubernetes.io/unreachable:NoSchedule
                    virtual-kubelet.io/provider=azure:NoSchedule
Unschedulable:      false
Conditions:
  Type                 Status    LastHeartbeatTime                 LastTransitionTime                Reason                     Message
  ----                 ------    -----------------                 ------------------                ------                     -------
  Ready                Unknown   Thu, 30 Jan 2020 17:31:03 +0900   Thu, 30 Jan 2020 17:31:43 +0900   NodeStatusUnknown          Kubelet stopped posting node status.
  OutOfDisk            False     Thu, 30 Jan 2020 17:31:03 +0900   Thu, 30 Jan 2020 17:15:28 +0900   KubeletHasSufficientDisk   kubelet has sufficient disk space available
  MemoryPressure       Unknown   Thu, 30 Jan 2020 17:31:03 +0900   Thu, 30 Jan 2020 17:31:43 +0900   NodeStatusUnknown          Kubelet stopped posting node status.
  DiskPressure         Unknown   Thu, 30 Jan 2020 17:31:03 +0900   Thu, 30 Jan 2020 17:31:43 +0900   NodeStatusUnknown          Kubelet stopped posting node status.
  NetworkUnavailable   False     Thu, 30 Jan 2020 17:31:03 +0900   Thu, 30 Jan 2020 17:15:28 +0900   RouteCreated               RouteController created a route
  PIDPressure          Unknown   Thu, 30 Jan 2020 17:15:28 +0900   Thu, 30 Jan 2020 17:31:43 +0900   NodeStatusNeverUpdated     Kubelet never posted node status.
Addresses:
  InternalIP:  10.240.0.15
Capacity:
 cpu:     10k
 memory:  4Ti
 pods:    5k
Allocatable:
 cpu:     10k
 memory:  4Ti
 pods:    5k
System Info:
 Machine ID:
 System UUID:
 Boot ID:
 Kernel Version:
 OS Image:
 Operating System:           Linux
 Architecture:               amd64
 Container Runtime Version:
 Kubelet Version:            v1.14.3-vk-azure-aci-v1.2.1
 Kube-Proxy Version:
Non-terminated Pods:         (1 in total)
  Namespace                  Name                               CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                  ----                               ------------  ----------  ---------------  -------------  ---
  default                    aci-helloworld-6d4c6bf75f-r7lsp    0 (0%)        0 (0%)      0 (0%)           0 (0%)         6d14h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests  Limits
  --------           --------  ------
  cpu                0 (0%)    0 (0%)
  memory             0 (0%)    0 (0%)
  ephemeral-storage  0 (0%)    0 (0%)
Events:              <none>`

**Comment by jluk** [comment] 2020-02-05 23:39
Thanks for confirming and the extra info, this looks to be the known issue with ACI with an inability to delete delegated subnets. The ACI team is aware of this - but please open a support request to the ACI service if you need immediate deletion.

**Comment by zer0big** [comment] 2020-02-05 23:43
I see. thanks for your guidance.

**Comment by macolso** [comment] 2020-02-11 15:54
Hi @zer0big, so at this point it looks like you've tried to delete with "az aks" and Azure Portal. Have you tried these steps? 
```cli
# Change the name of your resource group, cluster and network resources as needed
RES_GROUP=myResourceGroup
AKS_CLUSTER=myAKScluster
AKS_VNET=myVnet
AKS_SUBNET=myVirtualNodeSubnet

# Get AKS node resource group
NODE_RES_GROUP=$(az aks show --resource-group $RES_GROUP --name $AKS_CLUSTER --query nodeResourceGroup --output tsv)

# Get network profile ID
NETWORK_PROFILE_ID=$(az network profile list --resource-group $NODE_RES_GROUP --query [0].id --output tsv)

# Delete the network profile
az network profile delete --id $NETWORK_PROFILE_ID -y

# Delete the subnet delegation to Azure Container Instances
az network vnet subnet update --resource-group $RES_GROUP --vnet-name $AKS_VNET --name $AKS_SUBNET --remove delegations 0```

If so and you still can't delete, we'll go ahead and manually clean up your resources via your support ticket. After that, you should be able to assume operations as usual.

**Comment by jluk** [comment] 2020-02-18 23:53
Seeing as @macolso provided remediation steps, I'm going to close this issue. Thanks for the report and feedback @zer0big !

**Closed by jluk** 2020-02-18 23:53 UTC
Labels: known-issue, virtual-nodes

**Comment by zer0big** [comment] 2020-02-20 00:39
@macolso Thanks for your guide. I've just found that zerobigdemoaks is deleted already. :)
