### ISSUE TITLE
Connection to the Pod is refused in windows node

### ISSUE THREAD

**Issue by partha-sarathi-sarkar** [Azure/AKS#1471] opened 2020-03-04 06:27 UTC
**What happened**: pod port-forward is not working windows node 

**What you expected to happen**: After port-forwarding connection should be established and should  redirect to the desire page.

**How to reproduce it (as minimally and precisely as possible)**:
kubectl port-forward <podname> 9999:3142
**output:**
E0304 11:50:05.697242   43964 portforward.go:400] an error occurred forwarding 9999 -> 3142: error forwarding port 3142 to pod c4723a7cc9184412ffdea1366bf0887d8be067df58278815fea252448c6de209, uid : Error executing in Docker Container: 1: 2020/03/04 06:20:05 Failed to connect to localhost:3142 because dial tcp [::1]:3142: connectex: No connection could be made because the target machine actively refused it.
E0304 11:50:05.699244   43964 portforward.go:400] an error occurred forwarding 9999 -> 3142: error forwarding port 3142 to pod c4723a7cc9184412ffdea1366bf0887d8be067df58278815fea252448c6de209, uid : Error executing in Docker Container: 1: 2020/03/04 06:20:05 Failed to connect to localhost:3142 because dial tcp [::1]:3142: connectex: No connection could be made because the target machine actively refused it.

**Anything else we need to know?**:
I have deployed a service in Linux node , port-forward the pod it is working fine

**Environment**: Windows
- Kubernetes version (use `kubectl version`): 1.17.1
- Size of cluster (how many worker nodes are in the cluster?) 2

**Comment by MikkelHegn** [comment] 2020-03-04 22:16
Connection refused usually means no-one is listening on the port provided. Can you please share the pod or svc description you are trying to reach.

I cannot reproduce this issue.

**Comment by MikkelHegn** [comment] 2020-03-11 10:52
Closing due to no update

**Closed by MikkelHegn** 2020-03-11 10:52 UTC
Labels: windows
