### ISSUE TITLE
AKS worker nodes: support for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by fnerdman** [Azure/AKS#2883] opened 2022-04-03 10:35 UTC
The kernel version in 18.04 is just to old, I need a newer kernel version for mainline SGX support and others seem to require 20.04 as well:
https://github.com/Azure/AKS/issues/2706
https://github.com/Azure/AKS/issues/2829
https://github.com/Azure/AKS/issues/1579

**Comment by alexeldeib** [comment] 2022-04-04 19:49
https://github.com/Azure/AKS/issues/1579#issuecomment-1087945632

we're working on this

> https://github.com/Azure/AKS/issues/2829

okay that's a funny one to call out, because we _missed_ a CVE by being too far behind ;) point taken on feature support however, I know that's a problem.

**Comment by gandharv-kapoor** [comment] 2022-05-31 19:38
Any update on the ETA? We want to use newer versions of Nvidia Trition which are only supported on Ubuntu 20.04.

**Comment by jabbera** [comment] 2022-06-01 00:34
@gandharv-kapoor https://github.com/Azure/AKS/issues/2897#issuecomment-1130267469

**Comment by alexeldeib** [comment] 2022-07-29 21:04
edited to clarify we're going to 22.04 directly

maybe I should have used the other one since there's more context -_- sorry for confusion

**Comment by miwithro** [comment] 2022-08-11 12:34
Duplicate of #2897 closing.

**Comment by dhirschfeld** [comment] 2022-08-12 01:36
@miwithro - #2897 has been closed and locked as a dup of *this* issue!

Until this feature is delivered, one or the other issue should probably remain open.

**Comment by nijave** [comment] 2022-08-30 14:05
Will this only target k8s 1.25 or will it target older k8s versions? 18.04 mainstream support runs out April 2023 and 1.24 and possibly 1.23 should still be supported then

**Comment by alexeldeib** [comment] 2022-09-08 22:59
^planned for 1.25 only right now but we are aware of that potential timeline issue, cc @justindavies

**Comment by max-lepikhin** [comment] 2022-09-16 02:24
1.25 is out, any updates on timing of 22.04 image for AKS? 

We need it for Intel SGX driver - linux kernel 5.11+ (vs current 18.04 with kernel 5.4).

**Comment by jingai-db** [comment] 2022-09-30 04:25
friendly ping :-)

**Comment by zerodefect** [comment] 2022-09-30 11:47
Found this release announcement here - https://github.com/Azure/AKS/releases

> Starting with Kubernetes 1.25, the following changes will be made default:
Ubuntu 22.04 for x86, AMD and ARM64 architectures will be the default host.

**Comment by robin-wayve** [comment] 2022-10-17 13:25
So there isn't going to be a 20.04 image? Only 18.04 and then 22.04?

**Comment by zerodefect** [comment] 2022-10-17 13:28
It looks that way. It would be nice to have confirmation.

**Comment by jabbera** [comment] 2022-10-17 15:31
> It looks that way. It would be nice to have confirmation.

https://github.com/Azure/AKS/issues/2883#issuecomment-1199944067

**Comment by max-lepikhin** [comment] 2023-02-16 21:14
Related, are there any plans to update Linux kernel from current 5.15 to 6.0+? Specifically, it is required for confidential containers with [Gramine](https://github.com/gramineproject/gramine/releases/tag/v1.4).

**Comment by max-lepikhin** [comment] 2023-06-15 20:49
1.25 with 22.04 is available, thank you. Still the kernel is lagging significantly:
Kernel Version:             5.15.0-1035-azure
[Gramine requires 6.0](https://github.com/gramineproject/gramine/releases/tag/v1.4) for dynamic memory allocation.

What is the roadmap for updating kernel?

**Comment by allyford** [comment] 2024-08-20 19:06
Closing this issue as 22.04 is currently supported. @max-lepikhin please create a separate issue for kernel updates. We will likely consider 6.0 or above in Ubuntu 24.04.

**Closed by allyford** 2024-08-20 19:06 UTC
Labels: feature-request, action-required, fixing
