### ISSUE TITLE
Windows containers on AKS: failure in a Windows system call: The paging file is too small for this operation to complete.

### ISSUE THREAD

**Issue by hallgeirl** [Azure/AKS#1941] opened 2020-11-04 12:10 UTC
**What happened**:
Some of our pods (Windows Server containers running IIS workloads that may be heavy on memory) sometimes crash due to the readiness probe failing with an error saying the pagefile is too small. We also see crashes in the web application itself with OutOfMemoryExceptions that I strongly suspect is related to this. I have given the full kubectl describe on one of the nodes that have been experiencing this problem, as well as kubectl top, below.

We use memory request = memory limit = 1800Mi (as you also see from kubectl describe pod below). The pods are WELL below this, running at about 1200MB usage per pod, and 64% or less memory usage on our nodes. I have logged on to a couple of the nodes and found that they have a static pagefile of 8GB set. From checking "Get-CimInstance -Class Win32_PageFileUsage -ComputerName $Computer | Select-Object *" on one of the nodes, I get some info about usage (but not sure how accurate it is, or how this behaves together with Windows Server containers):

```
FilePath            : D:\pagefile.sys
AutoManagedPageFile : False
TotalSize(in MB)    : 8096
CurrentUsage(in MB) : 2339
PeakUsage(in MB)    : 4714
TempPageFileInUse   : False
```

This happens after our pods have been running for a while. If we reboot everything (all nodes) we're OK for a few days before the issues returns. 

We currently use the Standard DS11 v2 VM size for nodes.

Some of my suspicions:
- IIS (or other components inside the Windows Server containers) for some reason utilizes pagefile instead of physical memory for some reason. And with a small-ish pagefile, it can get exhausted after a while.
- IIS (or something else) doesn't play well with Kubernetes and the lack of pagefile within the container itself(?)

My questions:
- Is there some way of increasing the pagefile size of the Windows nodes in AKS, or making the sizing dynamic instead of static? 8GB is quite small, and the D drive it's stored on has more capacity (28GB total). A followup question would be if it's possible to increase the D drive size on the nodes.
- Is there some way of telling the container to NOT use pagefile, if it's not possible to increase the pagefile size?
- Is there some OTHER explanation for our crashes that we can investigate?

**Readiness probe (batch script):**
This is a fairly naive script, but it does its job on checking the health endpoint (we have curl installed on the container image).
```
if not exist C:\ContainerConfigured.tag (exit 1)

curl -s -o /dev/null -w "%%{http_code}" http://localhost:81/biz/health | findstr /C:200
IF %errorlevel%==1 (echo "One or more health checks failed" && exit 1) 
```

**Liveness probe (batch script):**
```
if not exist C:\ContainerConfigured.tag (exit 0)

C:\Windows\System32\inetsrv\appcmd.exe list apppool | findstr /C:"Stopped"
echo %errorlevel%
IF %errorlevel%==0 (echo "One or more app pools are stopped" && exit 1) 

```

**kubectl top pod:**
We use memory request = memory limit = 1800Mi (as you also see from kubectl describe pod below). The pods are WELL below this.
```
> kubectl top pod -n si
NAME                           CPU(cores)   MEMORY(bytes)
360-1930-si-6d856566d4-hjkpw   27m          1246Mi
360-1930-si-6d856566d4-kqpbg   30m          1175Mi
360-1930-si-6d856566d4-kxdm6   30m          1184Mi
```

**kubectl top node:**
As you can see all nodes are well below the limit (64% is the "worst contenter"):
```
> kubectl top node
NAME                                CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
aks-nodepool1-35944519-vmss000000   117m         6%     2619Mi          24%
aks-nodepool1-35944519-vmss000001   193m         10%    2900Mi          26%
aks-nodepool1-35944519-vmss000002   216m         11%    4167Mi          38%
aks-nodepool1-35944519-vmss000003   258m         13%    3549Mi          32%
aks-nodepool1-35944519-vmss000004   160m         8%     2206Mi          20%
aks-nodepool1-35944519-vmss000005   102m         5%     3439Mi          31%
akswinpol00002f                     288m         15%    5904Mi          60%
akswinpol00002u                     222m         11%    5311Mi          54%
akswinpol00003h                     214m         11%    4718Mi          48%
akswinpol00003v                     316m         16%    5508Mi          56%
akswinpol000044                     484m         25%    5909Mi          60%
akswinpol00004b                     260m         13%    5344Mi          54%
akswinpol00004e                     260m         13%    4667Mi          47%
akswinpol00004t                     490m         25%    5495Mi          55%
akswinpol00004u                     234m         12%    4650Mi          47%
akswinpol000052                     306m         16%    5369Mi          54%
akswinpol000053                     282m         14%    5482Mi          55%
akswinpol000054                     274m         14%    5136Mi          52%
akswinpol000055                     158m         8%     4918Mi          50%
akswinpol000056                     474m         24%    5601Mi          56%
akswinpol000057                     410m         21%    5974Mi          60%
akswinpol000058                     248m         13%    5265Mi          53%
```

**kubectl describe pod:**
```
PS C:\Users\farm1796Admin> kubectl describe pod -n si                                     360-1930-si-6d856566d4-kxdm6
Name:           360-1930-si-6d856566d4-kxdm6
Namespace:      si
Priority:       0
Node:           akswinpol000056/10.240.2.112
Start Time:     Wed, 04 Nov 2020 10:55:21 +0100
Labels:         360/retrieve-logs=true
                antiAffinityToken=360.360-1930-si
                app.kubernetes.io/component=webapp
                app.kubernetes.io/instance=360-1930-si
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=360
                app.kubernetes.io/part-of=360
                app.kubernetes.io/version=5.7.1058
                deploymentName=360-1930-si
                helm.sh/chart=360-5.7.1058
                pod-template-hash=6d856566d4
                revision=3
Annotations:    prometheus.io/path: /metrics
                prometheus.io/port: 5000
                prometheus.io/scrape: true
Status:         Running
IP:             10.240.2.120
Controlled By:  ReplicaSet/360-1930-si-6d856566d4
Containers:
  360:
    Container ID:  docker://bba45f2d29e0b0a290035b6e209b15932d83a4f8180fd0d7a0fb6f4eaf880561
    Image:         techdevcontainers.azurecr.io/360:5.7.1058
    Image ID:      docker-pullable://techdevcontainers.azurecr.io/360@sha256:e30d9265ae92ab8e78a6f9e02146b16abb5c985b858b14b0dda9dbcbb6a2ce56
    Port:          81/TCP
    Host Port:     0/TCP
    Args:
      app-startup
    State:          Running
      Started:      Wed, 04 Nov 2020 12:01:17 +0100
    Last State:     Terminated
      Reason:       Error
      Exit Code:    -1073741510
      Started:      Wed, 04 Nov 2020 10:58:39 +0100
      Finished:     Wed, 04 Nov 2020 12:01:11 +0100
    Ready:          True
    Restart Count:  2
    Limits:
      cpu:     225m
      memory:  1800M
    Requests:
      cpu:      150m
      memory:   1800M
    Liveness:   exec [cmd /C C:/batch/liveness.bat] delay=5s timeout=1s period=30s #success=1 #failure=3
    Readiness:  exec [cmd /C C:/batch/readiness.bat] delay=1s timeout=1s period=30s #success=1 #failure=3
    Environment:
      CONFIG_URL:               *******
      CONFIG_USER:              <set to the key 'username' in secret '360-1930-si'>  Optional: false
      CONFIG_PASSWORD:          <set to the key 'password' in secret '360-1930-si'>  Optional: false
      sicc.instrumentationkey:  a6e30331-8989-41bc-b406-d9da42cdab93
      LogLevel:                 Verbose
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from 360-1930-si-token-26zn2 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  360-1930-si-token-26zn2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  360-1930-si-token-26zn2
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=windows
                 kubernetes.io/role=agent
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
                 os=windows:NoSchedule
Events:
  Type     Reason     Age                 From                      Message
  ----     ------     ----                ----                      -------
  Warning  Unhealthy  23m (x2 over 24m)   kubelet, akswinpol000056  Readiness probe failed: container 37631c3445b3e93d44ee490079e01b95d5e0d7fd6be493db815d03d3c4dfc6a3 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The paging file is too small for this operation to complete. (0x5af) extra info: {"CommandLine":"cmd /C C:/batch/readiness.bat","WorkingDirectory":"/","Environment":{"COMPLUS_NGenProtectedProcess_FeatureEnabled":"0","CONFIG_PASSWORD":"*******","CONFIG_URL":"*******","CONFIG_USER":"Config_si","KUBERNETES_PORT":"tcp://10.0.0.1:443","KUBERNETES_PORT_443_TCP":"tcp://10.0.0.1:443","KUBERNETES_PORT_443_TCP_ADDR":"10.0.0.1","KUBERNETES_PORT_443_TCP_PORT":"443","KUBERNETES_PORT_443_TCP_PROTO":"tcp","KUBERNETES_SERVICE_HOST":"10.0.0.1","KUBERNETES_SERVICE_PORT":"443","KUBERNETES_SERVICE_PORT_HTTPS":"443","LogLevel":"Verbose","ROSLYN_COMPILER_LOCATION":"c:\\RoslynCompilers\\tools","SVC_360_1930_SI_PORT":"tcp://10.0.117.184:81","SVC_360_1930_SI_PORT_81_TCP":"tcp://10.0.117.184:81","SVC_360_1930_SI_PORT_81_TCP_ADDR":"10.0.117.184","SVC_360_1930_SI_PORT_81_TCP_PORT":"81","SVC_360_1930_SI_PORT_81_TCP_PROTO":"tcp","SVC_360_1930_SI_SERVICE_HOST":"10.0.117.184","SVC_360_1930_SI_SERVICE_PORT":"81","sicc.instrumentationkey":"a6e30331-8989-41bc-b406-d9da42cdab93"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
  Normal   Killing    23m                 kubelet, akswinpol000056  Container 360 failed liveness probe, will be restarted
  Warning  Unhealthy  23m (x3 over 24m)   kubelet, akswinpol000056  Liveness probe failed: container 37631c3445b3e93d44ee490079e01b95d5e0d7fd6be493db815d03d3c4dfc6a3 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The paging file is too small for this operation to complete. (0x5af) extra info: {"CommandLine":"cmd /C C:/batch/liveness.bat","WorkingDirectory":"/","Environment":{"COMPLUS_NGenProtectedProcess_FeatureEnabled":"0","CONFIG_PASSWORD":"*******","CONFIG_URL":"*******","CONFIG_USER":"Config_si","KUBERNETES_PORT":"tcp://10.0.0.1:443","KUBERNETES_PORT_443_TCP":"tcp://10.0.0.1:443","KUBERNETES_PORT_443_TCP_ADDR":"10.0.0.1","KUBERNETES_PORT_443_TCP_PORT":"443","KUBERNETES_PORT_443_TCP_PROTO":"tcp","KUBERNETES_SERVICE_HOST":"10.0.0.1","KUBERNETES_SERVICE_PORT":"443","KUBERNETES_SERVICE_PORT_HTTPS":"443","LogLevel":"Verbose","ROSLYN_COMPILER_LOCATION":"c:\\RoslynCompilers\\tools","SVC_360_1930_SI_PORT":"tcp://10.0.117.184:81","SVC_360_1930_SI_PORT_81_TCP":"tcp://10.0.117.184:81","SVC_360_1930_SI_PORT_81_TCP_ADDR":"10.0.117.184","SVC_360_1930_SI_PORT_81_TCP_PORT":"81","SVC_360_1930_SI_PORT_81_TCP_PROTO":"tcp","SVC_360_1930_SI_SERVICE_HOST":"10.0.117.184","SVC_360_1930_SI_SERVICE_PORT":"81","sicc.instrumentationkey":"a6e30331-8989-41bc-b406-d9da42cdab93"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
  Warning  Unhealthy  23m                 kubelet, akswinpol000056  Readiness probe failed: container 37631c3445b3e93d44ee490079e01b95d5e0d7fd6be493db815d03d3c4dfc6a3 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The requested virtual machine or container operation is not valid in the current state. (0xc0370105) extra info: {"CommandLine":"cmd /C C:/batch/readiness.bat","WorkingDirectory":"/","Environment":{"COMPLUS_NGenProtectedProcess_FeatureEnabled":"0","CONFIG_PASSWORD":"*******","CONFIG_URL":"*******","CONFIG_USER":"Config_si","KUBERNETES_PORT":"tcp://10.0.0.1:443","KUBERNETES_PORT_443_TCP":"tcp://10.0.0.1:443","KUBERNETES_PORT_443_TCP_ADDR":"10.0.0.1","KUBERNETES_PORT_443_TCP_PORT":"443","KUBERNETES_PORT_443_TCP_PROTO":"tcp","KUBERNETES_SERVICE_HOST":"10.0.0.1","KUBERNETES_SERVICE_PORT":"443","KUBERNETES_SERVICE_PORT_HTTPS":"443","LogLevel":"Verbose","ROSLYN_COMPILER_LOCATION":"c:\\RoslynCompilers\\tools","SVC_360_1930_SI_PORT":"tcp://10.0.117.184:81","SVC_360_1930_SI_PORT_81_TCP":"tcp://10.0.117.184:81","SVC_360_1930_SI_PORT_81_TCP_ADDR":"10.0.117.184","SVC_360_1930_SI_PORT_81_TCP_PORT":"81","SVC_360_1930_SI_PORT_81_TCP_PROTO":"tcp","SVC_360_1930_SI_SERVICE_HOST":"10.0.117.184","SVC_360_1930_SI_SERVICE_PORT":"81","sicc.instrumentationkey":"a6e30331-8989-41bc-b406-d9da42cdab93"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
  Normal   Started    23m (x3 over 88m)   kubelet, akswinpol000056  Started container 360
  Normal   Pulled     23m (x3 over 88m)   kubelet, akswinpol000056  Container image "techdevcontainers.azurecr.io/360:5.7.1058" already present on machine
  Normal   Created    23m (x3 over 88m)   kubelet, akswinpol000056  Created container 360
  Warning  Unhealthy  21m (x13 over 88m)  kubelet, akswinpol000056  Readiness probe failed:
```

**What you expected to happen**:
I expect pods to not crash due to a too small pagefile when there's plenty of memory available for the pod.

**How to reproduce it (as minimally and precisely as possible)**:
I guess try to deploy several heavy IIS applications, and add a readiness probe.

**Anything else we need to know?**:
We have been plagued by instability on our Windows-based containers for quite some time. Early debugging, with input from MS support indicated memory issues as the cause. Subsequently we have increased our memory requests and memory limits, to see if that resolved the issue. We have a separate issue on this that is open: https://github.com/Azure/AKS/issues/1461 
I feel this issue here warranted a separate issue though since it's specific to the pagefile, which may be the issue here.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"e3808385c7b3a3b86db714d67bdd266dc2b6ab62", GitTreeState:"clean", BuildDate:"2020-07-15T20:50:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
Currently 16 windows nodes, 6 linux nodes.

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
On windows nodes: IIS workloads serving web applications.
- Others:

**Comment by miwithro** [comment] 2021-01-26 13:03
@AbelHu can you assist?

**Comment by AbelHu** [comment] 2021-01-26 14:20
@miwithro please reference https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#memory-reservations-and-handling
```
Windows does not have an out-of-memory process killer as Linux does. Windows always treats all user-mode memory allocations as virtual, and pagefiles are mandatory. The net effect is that Windows won't reach out of memory conditions the same way Linux does, and processes page to disk instead of being subject to out of memory (OOM) termination. If memory is over-provisioned and all physical memory is exhausted, then paging can slow down performance.
```

**Comment by miwithro** [comment] 2021-01-26 14:43
@hallgeirl FYI.

**Comment by AbelHu** [comment] 2021-04-13 01:48
@hallgeirl Can we close this issue now? It is by design.

> @miwithro please reference https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#memory-reservations-and-handling
> 
> ```
> Windows does not have an out-of-memory process killer as Linux does. Windows always treats all user-mode memory allocations as virtual, and pagefiles are mandatory. The net effect is that Windows won't reach out of memory conditions the same way Linux does, and processes page to disk instead of being subject to out of memory (OOM) termination. If memory is over-provisioned and all physical memory is exhausted, then paging can slow down performance.
> ```

**Closed** 2021-04-15 06:01 UTC
Labels: resolution/answer-provided, windows
