### ISSUE TITLE
Allow users to mutate default storage class

### ISSUE THREAD

**Issue by deepaksood619** [Azure/AKS#1075] opened 2019-06-27 07:31 UTC
**What happened**:
1. `kubectl edit sc/default`
2. Changed `reclaimPolicy: Delete` to `ReclaimPolicy: Retain`
3. Saving using `:wq` gives error `error: storageclasses.storage.k8s.io "default" is invalid` and reopens the edit mode.
4. Have to cancel the edit using `:q`
5. `kubectl describe sc/default` shows old configuration

**What you expected to happen**:
Change the reclaimPolicy to Retain, and volumes will not be deleted once pvc is deleted

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl edit sc/default`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?) `7`
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:
adding `AllowVolumeExpansion:  True` to sc/default succeeded

**Comment by jnoller** [comment] 2019-07-12 15:18
@andyzhangx for triage

**Comment by andyzhangx** [comment] 2019-07-12 15:31
This is by design, the built-in storage classes cannot be changed.

**Comment by deepaksood619** [comment] 2019-07-12 16:15
@andyzhangx why is this? For starters it would be difficult to change all pvc to different storage class if they found about this later in the development process. We then have to migrate all the data.

What's the right way to change a PVCs storage class to a different one with all the data intact. What would be the migration step?

**Comment by bigbrozer** [comment] 2019-07-23 09:47
Would be good to have the possibility to set a different default storage class via `storageclass.beta.kubernetes.io/is-default-class=true` but it seems that any edited value are reverted (which is something I understand as it is storage class provided by AKS service).

**Comment by stromvirvel** [comment] 2020-01-15 19:51
It works if you do like this:
```
kubectl get sc default > default-sc.yaml
kubectl delete sc default
# change reclaimPolicy in YAML file
kubectl apply -f default-sc.yaml
```

But I'm afraid I'm doing something unsupported as @andyzhangx wrote that the `default` storageclass cannot be changed.

Anyway, when deleting a PVC, the underlying PV and Azure Disk are retained. What's a pain for me here is that when manually deleting the PV object, the underlying Azure Disk **doesn't get** deleted. Which IMO is unexpected.

**Comment by DanielSCon40** [comment] 2020-07-02 12:23
Is there a timeline when this gets implemented? Are there any workarounds on how to make the scheduler use a different StorageClass by a special attribute?

**Comment by jluk** [comment] 2020-10-13 20:35
This should be completed per the following announcements, closing as a result.

https://azure.microsoft.com/en-us/updates/azure-kubernetes-service-mutate-default-storage-class-feature/

https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv#create-a-storage-class

**Closed by jluk** 2020-10-13 20:35 UTC
Labels: feature, feature-request, storage

**Comment by bergerx** [comment] 2020-10-14 07:22
@jluk I checked the linked pages but didnt get how to change the default storage class. First one just tells its enabled. Second just discuss about how to add new SCs. But neither tells how yo change the default SC.

**Comment by andyzhangx** [comment] 2020-10-14 08:49
With the fix roll out, here is the way how to change the default storage class on AKS:
 - prepare default storage class and save to your local env, e.g. `default.yaml`
```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: default
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: Premium_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
 - Run following two commands consecutively:
```console
kubectl delete sc default && kubectl apply -f default.yaml
```

 - check whether default storage class is changed:
```console
kubectl get sc default -o yaml
```

You could also use same way to to change other built-in storage classes, make sure `storageclass.beta.kubernetes.io/is-default-class: "true"` is removed in the new storage class config.

**Comment by andyzhangx** [comment] 2020-10-14 08:51
cc @palma21
