### ISSUE TITLE
[Feature Request] Backend health status 'Unhealthy' for AKS and AGIC AppGateway in different vnets

### ISSUE THREAD

**Issue by VijayRod** [Azure/AKS#1953] opened 2020-11-10 06:40 UTC
This is for application-gateway to work with AKS Windows pool, in peered vnet.

**What happened**:
Deploying AKS cluster with AGIC, with AppGateway in different vnet, results in AppGateway's (Windows) backend health status '_Unhealthy_' with message '_Time taken by the backend to respond to application gateway's health probe is more than the timeout threshold in the probe setting_'.

**What you expected to happen**:
It must work, and without this message.

**How to reproduce it (as minimally and precisely as possible)**:
AKS cluster, having Linux and Windows pools, with AGIC AppGateway in different vnet: Backend health of Linux pool is _Healthy_. Backend health of Windows pool is _Unhealthy_.
Ref: https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-existing

**Anything else we need to know?**:
Abel and I discussed below. 
- AKS does not know about AppGateway vnet, so this is currently by design.
- Recommendation is to use app-gateway in a different subnet within the same vnet when using Windows nodes
- Manually adding cidr (steps below) in ExceptionList works, however is not recommended, since it will not persist with node recreate during upgrade etc. 

Steps to manually add cidr:
- C:\k\azurecni\netconf\10-azure.conflist has ExceptionList in OutBoundNAT endpoint policy.
- As a workaround, I added the subnet of the Application gateway, to the exception list in Windows node, and rebooted the node.

**Comment by AbelHu** [comment] 2020-11-10 06:43
cc @keikhara

**Comment by VijayRod** [comment] 2020-11-12 10:10
Doc update - https://github.com/MicrosoftDocs/azure-docs/pull/65968

**Comment by johannespetereit** [comment] 2020-11-12 18:27
Thank you for taking on the issue. I'm a bit taken back that one can phrase a feature request like that ("What you expected to happen: It must work, and without this [error] message.").

Regardless of classification, in my view following the recommendation mentioned above breaks the advertised usage of AGW as a centralized reverse proxy, as one must deploy the proxy into the same network as AKS. Do you really recommend that we rebuild the entire azure infrastructure around an AKS vnet? Please confirm, honest question.

I also have trouble following the by design argument: AGIC has no trouble functioning on linux nodes accross VNETs, so (without questioning the inner workings of azure) isn't this exclusively a windows node problem?

**Comment by VijayRod** [comment] 2020-11-14 13:21
This is exclusively on Windows node(s), for cluster nodes and application gateway in different virtual networks. (Updated 'How to reproduce it').

**Comment by ShubhasisMathur** [comment] 2020-11-28 12:14
@Azure/aks-pm. Any tentative timelines for this feature to be General Available?

**Comment by akshaysngupta** [comment] 2021-05-02 06:13
@palma21 We have seen similar issue before where windows nodes were not reachable through another VNET - it didn't matter if It was app gateway or another VM.

**Comment by CJJ69** [comment] 2021-07-26 12:08
https://github.com/Azure/AKS/issues/1960#issuecomment-886551752

**Comment by qpetraroia** [comment] 2021-08-18 16:54
@keikhara, @AbelHu, @mscatyao: do we have any updates on this?

**Comment by AbelHu** [comment] 2021-08-19 03:29
cc @justindavies

**Comment by miwithro** [comment] 2021-09-01 16:49
@akshaysngupta is there a fix here?

**Comment by RickardOh** [comment] 2021-10-08 22:24
Any updates. This is update is needed badly or a work around.
Is there no way to use agic in vnet1 -> (peering) vnet2 (AKS)

**Comment by AbelHu** [comment] 2022-03-15 02:58
AKS team has requested a feature in Windows container networking team for it. It needs Windows containers networking not SNAT the outbound packets by default.

**Comment by MostefaKamalLala** [comment] 2022-06-29 02:39
Did anyone beside @AbelHu take a look at #3024 to see if it's related?

**Comment by allyford** [comment] 2022-08-18 16:49
#3128 Is currently in development and will allow customers to disable Outbound NAT, resolving issues like this.

**Comment by dus-d** [comment] 2022-12-27 22:27
Does this issue only affect NAT Gateway clusters or does it affect SLB as well?  It appears the preview feature is only allowed in clusters with an outbound type of NAT Gateway.

**Comment by ShiqianTao** [comment] 2022-12-28 03:04
> Does this issue only affect NAT Gateway clusters or does it affect SLB as well? It appears the preview feature is only allowed in clusters with an outbound type of NAT Gateway.

Hi @dus-d . Both of them have this issue. The cluster requires NAT Gateway to handle pod outbound communication if the agent pool disables Windows OutboundNAT. You can update the cluster outbound type from SLB to NAT Gateway (by the way, NAT Gateway is more expensive than SLB.)

**Comment by dus-d** [comment] 2022-12-28 03:55
Thanks @ShiqianTao.  So currently changing the cluster outbound type to NAT Gateway is the only persistent means of resolving this?  And is it intended behavior that subnets from peered VNETs are not added to the _ExceptionList_ in the CNI config?

**Comment by ShiqianTao** [comment] 2022-12-28 07:07
> Thanks @ShiqianTao. So currently changing the cluster outbound type to NAT Gateway is the only persistent means of resolving this? And is it intended behavior that subnets from peered VNETs are not added to the _ExceptionList_ in the CNI config?

Yes. You are right. At present: The solution is to use NAT Gateway and disable Windows OutboundNAT; it cannot auto-update the _ExceptionList_ on existing nodes.

**Comment by AbelHu** [comment] 2023-02-06 01:56
Reopen it since the feature is not GA

**Comment by ShiqianTao** [comment] 2023-10-19 02:56
Hi @AbelHu @VijayRod @chasewilson @allyford . I have confirmed that this issue was fixed by Windows OS updates. Customers simply need to upgrade their node image to the latest version to pick the fix, [reference](https://learn.microsoft.com/en-us/azure/aks/node-image-upgrade). There is no requirement to use the feature `--disable-windows-outbound-nat`. So I think we can close this issue.

**Comment by AbelHu** [comment] 2023-10-19 04:16
Thank @shiqiantao to validate it in both WS2019 and WS2022. Close the issue.

**Closed by AbelHu** 2023-10-19 04:16 UTC
Labels: feature-request, windows, azure/application-gateway, addon/agic
