### ISSUE TITLE
kube-svc-redirect generates huge amount of logs

### ISSUE THREAD

**Issue by librannk** [Azure/AKS#851] opened 2019-02-25 12:58 UTC
*What happened**:

kube-svc-redirect generates huge amount of logs, EFK stack is just getting filled up with these logs... any fix for this?

*What you expected to happen**:
Only logs whenever acessed 

**How to reproduce it (as minimally and precisely as possible)**:
Check pod log in kube-system

**Anything else we need to know?**:

**Environment**:
- AKS 2 node, kubenetes v 1.12

**Comment by dschuld** [comment] 2019-03-22 07:40
Did you come up with a way to solve this? Same problem here, it generates way too much log output.

**Comment by librannk** [comment] 2019-03-22 08:28
azure support sucks regret using this instead of AWS.....yup filtered out in fluentd, it's still generating but I am no logging it...

**Comment by jnoller** [comment] 2019-04-02 20:51
Duplicate of #732

**Closed by jnoller** 2019-04-02 20:51 UTC

**Comment by librannk** [comment] 2019-04-03 02:50
@jnoller , why has this issue been closed, the one you shared as duplicate still isnt resolved yet... thereby its still n open issue and people are facing the problem

**Comment by jnoller** [comment] 2019-04-03 12:46
Because I am cleaning up stale bugs, deduplicating them (this is a dupe) and preparing the repository to post a public 6-12 month roadmap

**Comment by librannk** [comment] 2019-04-05 04:36
ok thanks...do keep this is your roadmap if possible
