### ISSUE TITLE
Why "scheduler" and "controller-manager" are unhealthy?

### ISSUE THREAD

**Issue by kvolkovich-sc** [Azure/AKS#311] opened 2018-04-19 07:45 UTC
Region: `westeurope`
Upgraded from `1.9.2` to `1.9.6`.

`kubectl get cs`

```
NAME                 STATUS      MESSAGE                                                                                        ERROR
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: getsockopt: connection refused   
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: getsockopt: connection refused   
etcd-0               Healthy     {"health": "true"}    
```

`kubectl describe node`

```
Warning  FailedNodeAllocatableEnforcement  3m (x111 over 3h)  kubelet, aks-agentpool-87985075-0  Failed to update Node Allocatable Limits "": failed to set supported cgroup subsystems for cgroup : Failed to set config for supported subsystems : failed to write 14683791360 to memory.limit_in_bytes: write /var/lib/docker/overlay2/d47544d24d89218a3483968337468ae77ab3aada321ccdcd822b0dcaa698a133/merged/rootfs/var/lib/docker/overlay2/d47544d24d89218a3483968337468ae77ab3aada321ccdcd822b0dcaa698a133/merged/sys/fs/cgroup/memory/memory.limit_in_bytes: invalid argument
```

**Comment by DaveAurionix** [comment] 2018-04-27 08:57
Yes I get exactly this situation as well when performing the upgrade.

**Comment by Zimmergren** [comment] 2018-04-27 09:13
I'm also seeing this issue as of today. 

Background:
- Standard E4 v3 machines
- West Europe
- The cluster was created on the latest available version (1.9.6), so no upgrade
- The cluster has been working for five days since I stood it up

I noticed these issues starting happening this morning, and a `kubectl get cs` outputs `Unhealthy`:

```
NAME                 STATUS      MESSAGE                                                                                        ERROR
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: getsockopt: connection refused
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: getsockopt: connection refused
etcd-0               Healthy     {"health": "true"}
```

**Comment by JasonvanBrackel** [comment] 2018-05-16 21:17
This may be related to 
https://github.com/Azure/AKS/issues/173

**Comment by mboersma** [comment] 2018-08-07 20:08
This is a duplicate of earlier issue #173. I'm closing this so we can track progress of the Kubernetes upstream fix there.

**Closed by mboersma** 2018-08-07 20:08 UTC

**Comment by kadisi** [comment] 2018-12-06 07:41
did you set `Type=notify` option on your controller-manager or scheduler service file ?
