### ISSUE TITLE
streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 1; INTERNAL_ERROR

### ISSUE THREAD

**Issue by juan-lee** [Azure/AKS#676] opened 2018-10-03 16:45 UTC
**Symptoms**
Pods using the in cluster config to perform a watch on a resource will see intermittent timeouts and the following error in the pod log.

`streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 1; INTERNAL_ERROR`

If the client performing the watch isn't handling errors gracefully, applications can get into an inconsistent state. Impacted applications include, but are not limited to, nginx-ingress and tiller (helm).

A specific manifestation of this bug is the following error when attempting a helm deployment.

`Error: watch closed before Until timeout`

**Root Cause**
1. The configuration of azureproxy results in unexpected timeouts for outbound watches targeting kubernetes.svc.cluster.local.
2. On the client side, the client-go implementation of watch.Until does not handle intermittent network failures gracefully. See [watch closed before Until timeout](https://github.com/helm/helm/issues/2918), [Fix broken watches](https://github.com/kubernetes/kubernetes/pull/50102), and [Fix waiting in kubectl rollout status](https://github.com/kubernetes/kubernetes/pull/67817) for more details.

**Workaround**
For the pods/containers that see the `INTERNAL_ERROR` in their logs add the following environment variables to the container spec. Be sure to replace `<your-fqdn-prefix>` and `<region>` so the aks kube-apiserver FQDN is correct.

``` yaml
spec:
  containers:
    env:
    - name: KUBERNETES_PORT_443_TCP_ADDR
      value: <your-fqdn-prefix>.hcp.<region>.azmk8s.io
    - name: KUBERNETES_PORT
      value: tcp://<your-fqdn-prefix>.hcp.<region>.azmk8s.io:443
    - name: KUBERNETES_PORT_443_TCP
      value: tcp://<your-fqdn-prefix>.hcp.<region>.azmk8s.io:443
    - name: KUBERNETES_SERVICE_HOST
      value: <your-fqdn-prefix>.hcp.<region>.azmk8s.io
```

**Comment by DenisBiondic** [comment] 2018-10-04 07:28
Is this not the same root cause as to performance degradation issue which is also still opened? https://github.com/Azure/AKS/issues/620

**Comment by necevil** [comment] 2018-10-04 14:11
I saw this tagged from the TLS Handshake error thread — https://github.com/Azure/AKS/issues/14
Can anyone confirm this as one of the issues leading to the above?

**Comment by juan-lee** [comment] 2018-10-04 19:13
> I saw this tagged from the TLS Handshake error thread — #14
> Can anyone confirm this as one of the issues leading to the handshake timeout?
> 
> Would the above work around with environmental variables be a potential workaround for the timeout issue?

@necevil I don't think this is related to #14. This issue is about calling kube-apiserver from inside of the cluster vs. outside.

**Comment by digeler** [comment] 2018-10-07 11:12
any Eta for permanent fix ?

**Comment by juan-lee** [comment] 2018-10-07 16:50
> any Eta for permanent fix ?

I don't have an ETA yet, but the fix is actively being worked on. The permanent fix will be to apply the same mitigation automatically for customer pods. I recommend applying the mitigation if you're running into this issue until we can have the fix automatically applied.

**Comment by DenisBiondic** [comment] 2018-10-08 20:52
Wait, are you saying the workaround from above is the proper fix for this issue, and you are not working on a solution to reliably access the master plane without being routed over the public internet?

**Comment by DenisBiondic** [comment] 2018-10-09 07:30
@juan-lee Will tunnelfront be removed then?

**Comment by holmesb** [comment] 2018-10-09 09:18
This is affecting cert-manager too.  Errors continue after deleting & recreating the pod.

**Comment by DenisBiondic** [comment] 2018-10-09 09:21
Yeah, it affects each container that has a connection to the master plane (different operators, external dns, ingress controller, cert manager etc.)

**Comment by mattfarina** [comment] 2018-10-10 13:50
@holmesb if you're installing cert-manager via Helm you can add the following to your custom values.yaml (passed in with the `-f` flag):

```yaml
env:
- name: KUBERNETES_PORT_443_TCP_ADDR
  value: <your-fqdn-prefix>.hcp.<region>.azmk8s.io
- name: KUBERNETES_PORT
  value: tcp://<your-fqdn-prefix>.hcp.<region>.azmk8s.io:443
- name: KUBERNETES_PORT_443_TCP
  value: tcp://<your-fqdn-prefix>.hcp.<region>.azmk8s.io:443
- name: KUBERNETES_SERVICE_HOST
  value: <your-fqdn-prefix>.hcp.<region>.azmk8s.io
```

You can get your specific URL from the portal.

Note, tiller uses client-go so it inherits the bugs client-go has as was previously pointed out.

**Comment by ttelfer** [comment] 2018-10-15 19:01
Also running into this problem using [https://github.com/argoproj/argo-events](url). Currently using Azure AKS 1.11.3.

**Comment by dkipping** [comment] 2018-10-16 09:56
> **Workaround**
> For the pods/containers that see the `INTERNAL_ERROR` in their logs add the following environment variables to the container spec. Be sure to replace `<your-fqdn-prefix>` and `<region>` so the aks kube-apiserver FQDN is correct.
> 
> ```yaml
>         env:
>         - name: KUBERNETES_PORT_443_TCP_ADDR
>           value: <your-fqdn-prefix>.hcp.<region>.azmk8s.io
>         - name: KUBERNETES_PORT
>           value: tcp://<your-fqdn-prefix>.hcp.<region>.azmk8s.io:443
>         - name: KUBERNETES_PORT_443_TCP
>           value: tcp://<your-fqdn-prefix>.hcp.<region>.azmk8s.io:443
>         - name: KUBERNETES_SERVICE_HOST
>           value: <your-fqdn-prefix>.hcp.<region>.azmk8s.io
> ```

Is there a possibility to inject this into a tiller-deploy pod already running on my cluster or does this have to be done at initialisation time?
Can I even pass these environment variables as parameters or is this only possbile by changing the yaml?

**Comment by evandervalk** [comment] 2018-10-16 14:52
I'm running into the same issue.

I've tried the workaround described by @dkipping to no avail. Setting the environment variables on the tiller-deploy doesn't seem to work.

**Comment by dkipping** [comment] 2018-10-16 15:11
could you apply the values to the tiller-deploy deployment at least? so are they saved and still there when you print out or enter the specs of the tiller-deploy again?

If they got applied, could you check that they got applied to a (newly spawned) tiller-deploy-<id> pod too?

**Comment by dkipping** [comment] 2018-10-16 15:28
> I would assume these environment variables should be defined on `kube-ingress-nginx-ingress-controller` rather than `tiller-deploy`?

Yes, sounds like it.
I guess you can't break more than not having it running by trying to add the environment variables there.

**Comment by evandervalk** [comment] 2018-10-16 15:29
I will try and report back.

**Comment by wutingbupt** [comment] 2018-10-16 15:38
Workaround works for me actually

**Comment by jonathanjfshaw** [comment] 2018-10-16 18:40
The workaround of patching my Tiller deployment with those variables fixed my Helm issues,.

For anyone wondering, the value you need to use "<your-fqdn-prefix>.hcp.<region>.azmk8s.io" can be found in the overview page of the Azure UI for your cluster, called "API server address".

**Comment by bergerx** [comment] 2018-10-18 13:52
Can we have a rough idea about when the fix will be released.

We cant update the Deployment definitions in some cases (https://github.com/gardener/gardener/issues/462) and we've been thinking about implementing a mutating admission webhook to inject these extra env vars automatically to certain pods (based on some annotation or som other pod properties). But it doesn't seem to be a trivial task and I'm not sure if it's easy to obtain the external apiserver endpoint within the cluster.

Also of the fix will be coming soon all this work will be redundant. So having an estimate here could help us saving time.

**Comment by juan-lee** [comment] 2018-10-18 17:48
> Can we have a rough idea about when the fix will be released.
> 
> We cant update the Deployment definitions in some cases ([gardener/gardener#462](https://github.com/gardener/gardener/issues/462)) and we've been thinking about implementing a mutating admission webhook to inject these extra env vars automatically to certain pods (based on some annotation or som other pod properties). But it doesn't seem to be a trivial task and I'm not sure if it's easy to obtain the external apiserver endpoint within the cluster.
> 
> Also if the fix will be coming soon, all this work will be redundant. So having an estimate here could help us saving time.

The fix has been merged and will rollout over the course of the next week.

**Comment by nphmuller** [comment] 2018-10-18 17:52
@juan-lee That’s great news. Can you keep us updated when the fix has been rolled out? I’m personally interested in the rollout for West Europe.

**Comment by agolomoodysaada** [comment] 2018-10-18 18:56
Amazing news! Please keep us posted for regions: EastUS and EastUS2.
Thank you

**Comment by strtdusty** [comment] 2018-10-18 22:15
@juan-lee  if you could post any info about how we will know when our clusters are patched that would be super cool.

**Comment by DenisBiondic** [comment] 2018-10-19 08:53
@strtdusty One way is to simply monitoring for the log message (stream ID 1; INTERNAL_ERROR). We have multiple thousands of these log errors ATM)

**Comment by strtdusty** [comment] 2018-10-19 14:20
There must be a better way than to just look for a decrease in those error logs.  If your fix involves universally changing KUBERNETES_PORT_443_TCP_ADDR etc then we could exec into a pod and check the environment variable?  There must be some definitive way of knowing.

**Comment by andrew-dinunzio** [comment] 2018-10-19 14:45
Similarly you can do `kubectl get pod <pod_name> -o jsonpath='{.spec.containers[*].env[?(@.name=="KUBERNETES_PORT_443_TCP_ADDR")].value}'`

**Comment by strtdusty** [comment] 2018-10-19 15:15
Thanks @andrew-dinunzio  that seems like a good idea.

**Comment by juan-lee** [comment] 2018-10-22 22:11
Update: the fix is rolling out, but we'll be testing it in production before making it broadly available. If everything goes as planned, we'll release the fix next week.

**Comment by apeschel** [comment] 2018-10-24 18:51
@juan-lee Is it possible to opt in for this fix before it's broadly available?

**Comment by weinong** [comment] 2018-10-24 21:56
@apeschel and to anyone who wants to preview the fix, please send your subscription ID to aks-help@service.microsoft.com and reference to this issue.

Thanks

**Comment by andig** [comment] 2018-10-26 08:17
@juan-lee wrote:

> Root cause: The configuration of azureproxy results in unexpected timeouts for outbound watches targeting kubernetes.svc.cluster.local.

I'm experiencing the streamwatcher errors in a cluster that does not have azureproxy deployed. Is that the same issue or a different one?

**Comment by andig** [comment] 2018-10-26 08:28
Note: you can get the API server like this:

    kubectl config view -o jsonpath='{.clusters[?(@.name=="<your cluster>")].cluster.server}'

**Comment by hazsetata** [comment] 2018-10-26 15:32
@juan-lee Similar error happens also with Java based apps, if they use [Fabric8 / Kubernetes Client](https://github.com/fabric8io/kubernetes-client) library (including [Spring Cloud Kubernetes](https://github.com/spring-cloud/spring-cloud-kubernetes) based apps).

I was able to apply a similar container env variable for my apps like this:

```
- name: KUBERNETES_MASTER
  value: "<your-fqdn-prefix>.hcp.<region>.azmk8s.io"
```

Should I create a separate issue, so a fix for that could be also done?

**Comment by nphmuller** [comment] 2018-10-26 15:35
My fix preview results so far:

I've just done a couple of helm deployments which used to fail (often, but not always) before the fix. 
Also so far no timeout errors for cert-manager and external-dns.

Looks promising!

**Comment by andig** [comment] 2018-10-26 15:52
I can confirm that after deploying the fix on cluster autoscaler the errors are gone from the logs. I'm still seeing https://github.com/Azure/AKS/issues/704 but that might be unrelated.

**Comment by strtdusty** [comment] 2018-10-26 16:01
@nphmuller curious about the preview fix ... was it Microsoft applied or did they give you a mutating webhook to apply manually?  Wondering if we applied it and had problems what the rollback would look like.

**Comment by nphmuller** [comment] 2018-10-26 16:16
@strtdusty It's a feature flag they set on AKS. For now only applied to new clusters. Not sure if the feature can be disabled manually.

**Comment by dharmeshkakadia** [comment] 2018-10-29 22:38
I get the following error while trying to use the workaround mentioned by @juan-lee in the original post. 

```
x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ca")
```

Looks like the azure control plane doesnt have the right certs or the pod needs additional config?

**Comment by fhoy** [comment] 2018-11-02 11:52
It's been a while since the last "official" note now; is there any news on general availability of the fix?
Also, will the permanent fix require us to recreate clusters?

**Comment by mbrancato** [comment] 2018-11-02 13:29
@dharmeshkakadia I was asking about this the other day but didn’t get an answer. It seems that all the AKS apiserver certs are self-signed. I’m a little shocked that kubectl doesn’t provide a warning by default. Currently, any pod that connects to the apiserver will need to ignore certificate trust.

**Comment by erewok** [comment] 2018-11-02 19:56
Hi all, I too am wondering when the fix for this is going to be rolled out and if we'll have to do anything to benefit from it. We have two, small AKS clusters but they're running business critical applications and seeing these errors coming from the nginx-ingress-controller makes me nervous.

**Comment by weinong** [comment] 2018-11-02 20:49
https://azure.microsoft.com/en-us/updates/watch-stream-error-fix/
we will be rolling this out to all clusters starting next week.

**Comment by adinunzio84** [comment] 2018-11-02 21:13
I imagine people using Istio will now need to create a ServiceEntry object to access the apiserver, since the FQDN won't be in Istio's service "registry".

**Comment by fhoy** [comment] 2018-11-05 08:52
@weinong : Good to know. Is this being rolled out region by region, and if so, is there a set sequence? I am particularly interested in when this will be rolled out in region westeurope.

**Comment by alibengtsson** [comment] 2018-11-06 14:09
Hi,when will the fix be released for 
centralus and southeastasia ? 

thanks in advanced

**Comment by martinhartig** [comment] 2018-11-09 12:42
fix has reached westeurope. 
Indeed, it has solved several issues. Thx.

**Comment by LanceTheDev** [comment] 2018-11-12 07:59
Still getting the Issue:
2018-11-12T07:49:47.964622Z	error	Unable to decode an event from the watch stream: stream error: stream ID 1529; INTERNAL_ERROR
2018-11-12T07:49:47.964882Z	error	Unable to decode an event from the watch stream: stream error: stream ID 1519; INTERNAL_ERROR

Do I need to reinstall Istio for this fix to work?

**Comment by alibengtsson** [comment] 2018-11-12 08:03
> Still getting the Issue:
> 2018-11-12T07:49:47.964622Z	error	Unable to decode an event from the watch stream: stream error: stream ID 1529; INTERNAL_ERROR
> 2018-11-12T07:49:47.964882Z	error	Unable to decode an event from the watch stream: stream error: stream ID 1519; INTERNAL_ERROR
> 
> Do I need to reinstall Istio for this fix to work?
try to only restart/delete the envoy ingress gateway and reboot/delete your pods check the logs again in ingress controller.

**Comment by wutingbupt** [comment] 2018-11-12 08:59
Hi,

Do we need to do anything for our cluster? Or it will be applied automatically?

Br,
Tim

**Comment by andig** [comment] 2018-11-12 09:46
I understood:

> @strtdusty It's a feature flag they set on AKS. For now only applied to new clusters. Not sure if the feature can be disabled manually.

So you'll have to recreate the cluster.

**Comment by mmosttler** [comment] 2018-11-12 15:28
@adinunzio84 You mentioned that with this fix there may need to be an additional ServiceEntry needed for Istio.  We are having the issue described and also have Istio installed so I am curious if you have the fix and what ServiceEntry you had to add?

**Comment by juan-lee** [comment] 2018-11-12 23:05
> b



> Hi,
> 
> Do we need to do anything for our cluster? Or it will be applied automatically?
> 
> Br,
> Tim

The fix is no longer behind a feature flag. All new clusters will get it automatically. Existing clusters will need to do a scale or upgrade to get the fix.

**Comment by wutingbupt** [comment] 2018-11-13 09:06
@juan-lee Thanks for your reply, we rebuilt our cluster yesterday, however, I still can see this problem this morning. 
We are in westeurope, and the cluster version is 1.11.3

Br,
Tim

**Comment by alibengtsson** [comment] 2018-11-13 11:44
Hi, i redeployed with terraform in westeurope and centralus region. with nginx ingress controller. I can confirm from my side that the messages are gone from the log file.
i used version 1.11.2.

thanks for the fix.

**Comment by juan-lee** [comment] 2018-11-13 15:00
> @juan-lee Thanks for your reply, we rebuilt our cluster yesterday, however, I still can see this problem this morning.
> We are in westeurope, and the cluster version is 1.11.3
> 
> Br,
> Tim

Can you provide some more details? Does the pod in question have the appropriate KUBERNETES_ environment variables set.

**Comment by adinunzio84** [comment] 2018-11-13 18:03
@mmosttler Haven't fully tested this yet, but I imagine it will be something like this:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: azmk8s-se
spec:
  hosts:
  - "*.azmk8s.io.net"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
```

I used a wildcard, but you can put your apiserver's FQDN there instead to be more specific... Let me know if you come up with something better though.

**Comment by weinong** [comment] 2018-12-03 18:03
thanks for reporting back. i'm closing the issue for now

**Closed by weinong** 2018-12-03 18:03 UTC
Labels: known-issue

**Comment by dharmeshkakadia** [comment] 2018-12-04 18:41
I am still seeing this issue even this week in east us.

**Comment by juan-lee** [comment] 2018-12-04 23:20
> I am still seeing this issue even this week in east us.

Can you elaborate on your scenario? Also, keep in mind that pods will need to be restarted in order to get the fix. You can check to see if a pod has the fix by seeing if KUBERNETES_PORT, etc env variables are set for each container.
