### ISSUE TITLE
SNAT allocated ports reset during scaling operation

### ISSUE THREAD

**Issue by landro** [Azure/AKS#1673] opened 2020-06-15 10:53 UTC
**What happened**:

I increased the minimum number of nodes in default pool (2->3 autoscaling pool), and that reset snat allocated ports back to default of 1024

**What you expected to happen**:

no change

**Environment**:

1.15.10

**Comment by jluk** [comment] 2020-06-15 21:25
@landro do you have a support ticket tied to this issue we can inspect? cc @marwanad / @paulgmiller

**Comment by landro** [comment] 2020-06-15 22:00
No, not this exact case. I reproduced the issue on all of our 6 clusters. 

We have a support ticket though for a reset that probably happened due to a reconciliation process triggered by AKS. See 120051822001429 for details.

We've had this value reset to the default several times now (either triggered by some management operation triggered by us, or some kind of management operation on the masters, triggered by you) - I'm surprised that this can happen in a GA product like this. Not impressed to say the least, especially given the fact that it apparently takes a long time to get this fixed and released. We've actually had to put in place dedicated monitoring to make sure we get alerted whenever the value is reset.

**Comment by jluk** [comment] 2020-06-15 22:45
Thanks for sharing the SR @landro, it looks like this was a bug on your initial report which already has a fix captured for release. The acknowledgement of the issue and a notice of this fix should have come back to you on the support ticket, but I can patch in the info for you here.

It is rolling out on the active service release, which should be global in the next 8 days. This fix will be notated on the aks release notes publishing this week as well. I will leave this open until the fix is global and you confirm the issue is resolved.

**Comment by jluk** [comment] 2020-08-07 23:31
This should be resolved now, closing as a result. If you still hit this specific issue just let us know and I will revisit.

**Closed by jluk** 2020-08-07 23:31 UTC
Labels: networking/load-balancers, resolution/fix-released
