### ISSUE TITLE
pod cannot connect to other services in aks cluster

### ISSUE THREAD

**Issue by ruowan** [Azure/AKS#2362] opened 2021-06-02 09:36 UTC
**What happened**:

We have two services in aks cluster. One is **liveValidation** service and another service is **enumerator** service. And **liveValidation** service periodly call enumerator service via HTTP.  There are two liveValidation service pods. Recently one of the pod call enumerator service failed the reason is `connect EHOSTUNREACH 10.0.179.21:80`， but another one works well and no errors.

My question is how to debug and fix this kind of networking issue. I enter two pods and run command. 

```
curl https://opnapi-enumerator/api/alive
```

one is succeed, another is failed.  Error log is here, and it seems a networking infrastructure or node issue. 

```
/usr/app # curl http://openapi-enumerator/api/alive
{"title":"OpenAPI Enumerator is alive"}
```

```
/usr/app # curl http://openapi-enumerator/api/alive
curl: (7) Failed to connect to openapi-enumerator port 80: Host is unreachable
```

svc info.
```
$ kubectl describe svc openapi-enumerator
Name:              openapi-enumerator
Namespace:         openapi-platform
Labels:            app.kubernetes.io/managed-by=Helm
Annotations:       meta.helm.sh/release-name: enumerator
                   meta.helm.sh/release-namespace: openapi-platform
Selector:          app=openapi,role=enumerator
Type:              ClusterIP
IP:                10.0.179.21
Port:              internal  80/TCP
TargetPort:        5010/TCP
Endpoints:         10.244.4.241:5010,10.244.5.67:5010
Session Affinity:  None
Events:            <none>
```

**What you expected to happen**:

I expect all the pod have the same behavior.  All pod should succeed.

_Great thanks if you could give me some trouble shooting guideline._

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"4d62230f10af41cec2851b5b113874f6d2098297", GitTreeState:"clean", BuildDate:"2021-03-22T23:01:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?) 6
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
HTTP microservices
- Others:

**Comment by justindavies** [comment] 2021-06-17 11:02
Hi @ruowan, do this issue happen consistently, or is it temporary?

**Comment by Silvenga** [comment] 2021-07-06 17:07
We were also seeing the same randomly - the service was resolving to the correct IP. Killing the pod the service was pointing to allows other pods to one again use the service. I've only seen this problem under AKS, and not on bare metal clusters.

It was somewhat reproducible (from memory):

```
Pod B -> Service A -> pod A
```

- Pod A crashes with OOM (or is killed by OOM).
- K8s restarts pod (ready probes pass).
- Pod B can no longer communicate with Pod A via service A
- Deleting Pod A (statefulset creases Pod C) allows Pod B to communicate via service A once again.

We've since remove to another HA setup to mitigate this problem - although now we are seeing similar problems (uses endpoints directly) - which lead me back here.

**Comment by ruowan** [comment] 2021-08-18 05:51
@justindavies once it happened, it can not connect to other service consistently.  My solution is to disable pod schedule to the issued node. it works for me now.

**Comment by phealy** [comment] 2021-09-29 16:55
@ruowan We attempted to reproduce this quickly without success - can you please share some more details?

- Is this still happening?
- What is your cluster CNI configuration?
- Does this happen when the pods are on the same node, different nodes, or regardless?

**Comment by ruowan** [comment] 2021-09-30 06:45
No happening. It's only happen on the specific node. When I disable the wrong node schedule, it recovery. I guess it may be caused by node network issue.

**Closed** 2021-11-03 06:03 UTC
Labels: resolution/answer-provided
