### ISSUE TITLE
API Server certificate not valid

### ISSUE THREAD

**Issue by mmillard0** [Azure/AKS#4083] opened 2024-02-05 17:56 UTC
**Describe the bug**
All our AKS cluster API Server address have certificate issue. 

**To Reproduce**
1. Open a browser and https api server address like https://api.server.address.azmk8s.io
2. Response: "Your connection is not private"
3. NET::ERR_CERT_AUTHORITY_INVALID

**Expected behavior**
Certificate with valid authority certification.

**Screenshots**
![API_Certificate_invalid](https://github.com/Azure/AKS/assets/77118562/c901534f-d596-4c28-90f1-6d14cf16251a)

**Comment by philwelz** [comment] 2024-02-06 02:34
This is intended by design as of the PKI requirements from Kubernetes described [here](https://kubernetes.io/docs/setup/best-practices/certificates/#how-certificates-are-used-by-your-cluster).

The Azure docs for AKS describing that the API server cert is signed by the cluster CA can be found [here](https://learn.microsoft.com/en-us/azure/aks/certificate-rotation#aks-certificates-certificate-authorities-and-service-accounts)

Using validly signed (CA) certs is not on the AKS roadmap  - [details](https://github.com/Azure/AKS/issues/1066#issuecomment-505511167)

I will close the issue. Feel free to re-open if the answer is not satisfying.

**Closed by philwelz** 2024-02-06 02:34 UTC
Labels: bug
