### ISSUE TITLE
Windows Nodes losing ability to connect to resources outside the cluster

### ISSUE THREAD

**Issue by brobichaud** [Azure/AKS#1014] opened 2019-05-27 22:35 UTC
**What happened**:
I have a small cluster with 2 Windows nodes setup and a dozen pods deployed. Everything runs fine for about 36 hours, then the Windows nodes lose the ability to connect to resources outside of the cluster. Even a simple curl to google fails:

curl -k -I www.google.com
curl: (7) Failed to connect to www.google.com port 80: Timed out

**What you expected to happen**:
External internet resources should always be available.

**How to reproduce it (as minimally and precisely as possible)**:
Create a cluster with Windows nodes. Deploy some pods that use external internet resources. Wait for approximately 36 hours, then pods will fail to connect. Remoting into the Windows nodes and running curl will also fail. Rebooting the Windows nodes resolves the problem for another 36 hours or so.

It also appears that maybe restarting kubelet on the node fixes it as well. I am not confident about this as I have seen it work but I also believe I have seen it not work.

**Anything else we need to know?**:
This is a pretty plain jane AKS setup with Windows nodes.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.0
- Size of cluster (how many worker nodes are in the cluster?): 2 Windows Nodes of type F8s_v2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Mixture of AspNetCore web apps and simple command line worker apps. Mixture of nanoserver and servercore container images.

- Others:
I don't know how to debug this. I can collect or look at logs in c:\k, but I have no idea what to look for.

**Comment by MikkelHegn** [comment] 2019-05-28 12:44
A few question to help us dig deeper:

1. Do you use readiness probes in the cluster? We have a known issue where Windows will run low on ports due to readiness probes.
1. Will a server reboot solve the connectivity issues?

**Comment by brobichaud** [comment] 2019-05-28 13:32
> A few question to help us dig deeper:
> 1. Do you use readiness probes in the cluster? We have a known issue where Windows will run low on ports due to readiness probes.

Yes I do. Of the 19 pods deployed on this cluster 8 of them have readiness probes.

> 2. Will a server reboot solve the connectivity issues?

Yes a node reboot clears the problem up for about 36 hours, then it returns. I had thought restarting the kubelet fixed the problem but when it does it is very short lived, like an hour or two at most.

**Comment by MikkelHegn** [comment] 2019-05-28 13:38
Thanks for confirming - for now the best option is to disable the readiness probes. Please let us know if that helps. I'll get back to this issue once I know more about how we can confirm and get a fix rolling.

**Comment by brobichaud** [comment] 2019-05-30 21:22
This really is a significant issue for us and is a big regression from an AKS-Engine based cluster we had built with Windows nodes on k8s v1.13.3. Not having readiness probes leaves us in a risky state when deploying new versions of our pods.

I also am seeing problems with pods spinning up and lacking egress connectivity. I end up having to delete the pod and let k8s recreate it, sometimes 6 or 8 times before it finally can access external resources. Do you think that is related or shall I submit a different issue for that?

**Comment by zhiweiv** [comment] 2019-05-31 00:59
@brobichaud 
For the pod egress issue, is it same with https://github.com/Azure/aks-engine/issues/189?
Azure cni 1.0.18 improved, but I can still observed same issue, I use some codes to ensure dns at the beginning of the program.

AKS Windows is still using 1.0.17.

**Comment by brobichaud** [comment] 2019-05-31 01:29
@zhiweiv no this issue sounds different from the one you referenced in that the lack of egress in this issue lasts for long periods, or rather goes away entirely until a reboot of the node. Separately I do also experience pod startups where they fail to connect externally but even that lasts for long periods or requires a pod delete and restart multiple times to fix.

**Comment by MikkelHegn** [comment] 2019-06-03 10:28
@brobichaud - can I ask you to open a support case through the Azure Portal to help us look further in to the problems you are experiencing?

**Comment by brobichaud** [comment] 2019-06-03 21:52
@MikkelHegn I've created a support ticket. I referenced both this issue 1014 and 1029. Support case# 119060324000404.

Will this end up coming back to your team or is this a separate thing?

**Comment by MikkelHegn** [comment] 2019-06-04 09:39
Thanks - support cases re handled by a different team, and we are handling any escalations based on product bugs / improvements we need to make. We also review support cases for product improvements we need to make.

Main reason I suggested a support case is to make sure we initiate troubleshooting and debugging to get the right root cause.

**Comment by cpunella** [comment] 2019-06-04 13:34
Hi there, I'm experiencing the same issue... after some day, windows node seems to not be able to resolve DNS. On this node, there is a single pod published without readiness probe... 

This is the result of running a ping command within the windows pod:
**Ping request could not find host www.google.it. Please check the name and try again.**

Restart the node "fix" the issue... I'll open a ticket through the portal when it will happen again....

**Comment by brobichaud** [comment] 2019-06-04 15:23
@cpunella I wonder if you submitting as support ticket might be useful, to offer the support guys another perspective on what seems like a similar issue?

**Comment by MikkelHegn** [comment] 2019-07-03 11:56
Please reach out if readiness probes issue are blocking: mikhegn@microsoft.com - thx...

**Comment by djsly** [comment] 2019-07-30 12:35
@MikkelHegn , we are getting a lot of timeout with the probes as well on Windows. 

```
"Liveness probe failed: Get http://<server>/CheckLiveness: dial tcp <ip>:80: connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

"Liveness probe failed: Get http://<server>/CheckLiveness: net/http: request cancelled while waiting for connection (Client.Timeout exceeded while awaiting headers)".
```

Could also be caused by the port exhaustion of the readiness probe ? (we have the readiness probes enabled as well)

**Comment by ngrigoriev** [comment] 2019-08-06 14:32
As a workaround, should we consider "exec" liveness probes instead of httpGet? Although this "exec" will most likely will still do an HTTP request inside of the containers so I am not sure if it will make a difference.

**Comment by MikkelHegn** [comment] 2019-08-09 10:20
Liveness / readiness probe issue is in the upcoming Windows image to be release on patch Tuesday in September. That image will be available in AKS soon thereafter.

**Comment by mkostersitz** [comment] 2019-08-09 16:49
> As a workaround, should we consider "exec" liveness probes instead of httpGet? Although this "exec" will most likely will still do an HTTP request inside of the containers so I am not sure if it will make a difference.

@ngrigoriev, @JocelynBerrendonner  is out on PTO. Let me try to answer this instead.

running a probe like action with exec is most likely not going to change the outcome I am afraid. I did a quick test on my cluster and saw a small statistically non relevant decrease in failed probes. especially because if the liveness probe failed the exec seemed to fail in 30-40% of the cases too in around 24 hours I had the test running.
Sorry to not have better news.

**Comment by ngrigoriev** [comment] 2019-08-16 16:59
@mkostersitz Do I understand correctly that the fix is includes in 1.14.5? Thanks!

**Comment by ngrigoriev** [comment] 2019-08-16 17:15
@mkostersitz Do I understand correctly that the fix is includes in 1.14.5? Thanks!

**Comment by JocelynBerrendonner** [comment] 2019-08-16 18:39
@ngrigoriev, there is a known issue in Windows that impacts liveness probes. The fix is currently available in Windows 10 1903 (https://support.microsoft.com/en-us/help/4505903/windows-10-update-kb4505903), and should normally be available next Tuesday (August 20th) for Windows 10 1809. I will keep this thread posted once the fix is out.

I unfortunately do not know of any workaround for the liveness probe issue at this point of time. Once the fix is applied to all the Windows nodes, Kubernetes liveness probes should work correctly.

@brobichaud, your issue looks a bit different. Did you try disabling the liveness probes as @MikkelHegn suggested as a workaround? This should help us understand if the issue you are seeing is indeed the known liveness probe issue or if it is something else.

Thank you!

**Comment by brobichaud** [comment] 2019-08-16 20:10
@JocelynBerrendonner I did indeed disable liveness probes and it mitigates the problem. @MikkelHegn mentions the Windows update coming that will make it into AKS and resolve this problem. I have left liveness probes disables until this is fixed.

**Comment by JocelynBerrendonner** [comment] 2019-08-19 17:50
Thank you for confirming, @brobichaud 

Heads up that the Windows fix for the liveness probe issue is now available online at the following locations:
For Windows 10/Windows server 2019 version 1903, the fix comes as part of cumulative update KB4505903. Link: https://support.microsoft.com/en-us/help/4505903/windows-10-update-kb4505903
For Windows 10/Windows server 2019 version 1809, the fix comes as part of cumulative update KB4512534. Link: https://support.microsoft.com/en-us/help/4512534/windows-10-update-kb4512534

Once the patch is installed, liveness probe should work properly.
Please let us know if you have any questions/issue with these patches!

Thank you,

**Comment by brobichaud** [comment] 2019-08-19 18:14
@JocelynBerrendonner thanks for the update! Applying patches manually in AKS is a tricky business when you take into account scale-out/in of worker nodes, so I'd like to avoid that with our clusters. Could you update this issue when the newly patched Server 1809 version is available to AKS with new nodepool creations? That way we can test it within the constraints of normal processes.

**Comment by daschott** [comment] 2019-08-19 18:18
@brobichaud FYI the fix should now be available on both Windows Server 1809 and 1903. Can you try it out and see if it resolves the issue?

**Comment by brobichaud** [comment] 2019-08-19 18:27
@daschott yeah, thanks, I do get that the fix is available as a manual patch. But if I apply it to my nodes today, then scale out that nodepool (or create a new nodepool) I no longer have the fix consistently on my nodes. So end result is that it's too fragile for me. Once it is available to AKS officially then I am all over it! :-)

**Comment by daschott** [comment] 2019-08-19 18:32
@brobichaud Understandable, @MikkelHegn or me should be able to confirm once it is available on AKS nodepools; feel free to ping again in 30 days if you don't hear back by then.

**Comment by brobichaud** [comment] 2019-08-19 18:33
@daschott awesome, thank you!

**Comment by MikkelHegn** [comment] 2019-08-27 08:00
@bobrundle - I haven't seen a scenario where you loose DNS after a while. Do you see this issue only for new container instances as they start up, or container instances running continuously?

The latest Windows OS version in AKS is .557 - if your on an older version, you'll have to first upgrade your cluster to a newer Kubernetes version, then create a new Windows node pool and migrate your workload over. This is required as we had a breaking change in the VM image data a while back.

**Comment by MikkelHegn** [comment] 2019-08-27 13:24
You can upgrade the existing cluster by:
1. Upgrade the cluster 'az aks upgrade' to a newer K8 version
2. Create a new node pool
3. Move the workloads over to the new node pool

Are the clusters similar in size and resource usage? What's the state of the core-dns pods when this happens, does a new container instance also fail with DNS if deployed while the nodes are in this state?

Would be good to get supports eyes on this when it happens again.

**Comment by brobichaud** [comment] 2019-10-02 23:05
@MikkelHegn @PatrickLang, now that it is October is there any update on whether this is available to AKS clusters yet?

**Comment by brobichaud** [comment] 2019-10-11 16:27
@daschott is there any update on whether this update is available for AKS Windows nodepool upgrades?

**Comment by jluk** [comment] 2019-10-14 21:05
The update will be rolling out on this week's service release, so it should be global by 10/22 at the latest. We'll have the release notes up in a few days.

**Comment by brobichaud** [comment] 2019-10-14 22:37
Thanks @jluk, it would be great for this issue to be updated/closed when it's fully deployed

**Comment by djsly** [comment] 2019-10-14 22:54
Will it be only a kube-proxy update or will it require a windows node upgrade ?

**Comment by jluk** [comment] 2019-10-15 17:24
I'll be out of office next week but @MikkelHegn can confirm when rollout is complete.

@djsly it requires a node upgrade.

**Comment by PatrickLang** [comment] 2019-10-18 17:28
The updated Windows image with this fix was in the 10/14 rollout. Can you try adding a deleting & creating a new nodepool and see if the problem is fixed there?

**Comment by vikalpj** [comment] 2019-10-23 15:37
@PatrickLang @MikkelHegn @jluk As per the above mentioned release dates. 

I can't find a way to get the nodes updated on AKS cluster. I already followed the steps mentioned in 
https://github.com/Azure/AKS/issues/1014#issuecomment-525299366 .

The windows version I am always getting to is 
<img width="813" alt="Screenshot 2019-10-23 21 00 20" src="https://user-images.githubusercontent.com/5318237/67409793-ad417500-f5d8-11e9-90d2-f3834cf9cc1b.png">

As of now new kubernetes version I have in the cluster is 1.14.7.

**Comment by MikkelHegn** [comment] 2019-10-24 13:34
The release has now been rolled out to all regions. To get a new Windows OS version, you have two options:

1. Upgrade the cluster to a new K8 version
2. Upgrade the clsuter to the same K8 version (repair), then new Windows node pools will be based off the new OS version.

**Closed by MikkelHegn** 2019-10-24 13:34 UTC
Labels: windows

**Comment by vikalpj** [comment] 2019-10-25 15:30
@MikkelHegn Thanks for the confirmation.

The node seems to be updated now.

**Comment by brobichaud** [comment] 2019-10-25 15:38
I have also successfully provisioned a new nodepool with the correct Windows version and moved all my workloads to it. I have re-deployed all of my pods with readiness probes re-enabled. I want to give it at least 48 hours to prove this fix is successful. I'll update this issue next week with results.

**Comment by djsly** [comment] 2019-10-25 17:14
@ngrigoriev can we ask for the Probes to also be enabled on our side to reenforce the validation?

**Comment by brobichaud** [comment] 2019-10-28 16:23
> I have also successfully provisioned a new nodepool with the correct Windows version and moved all my workloads to it. I have re-deployed all of my pods with readiness probes re-enabled. I want to give it at least 48 hours to prove this fix is successful. I'll update this issue next week with results.

We've now been running for over 72hrs with readiness probes enabled and have seen no issues whereas we were seeing issues after just 36 hours in the past. Looks good!

**Comment by asbjorne** [comment] 2019-10-29 11:46
I'm having similar issues and want to check the windows version of the nodes. 
What is correct windows version of the node (with the mentioned corrective windows update) and how do I verify that my nodes are running this version? I have RDP access to the nodes.

**Comment by djsly** [comment] 2019-10-29 12:17
Check the OS profile in the VMSS tab using the azure Portal.

**Comment by asbjorne** [comment] 2019-10-29 12:25
Thanks! The version of my new nodes is 17763.557.20190604 (nodepool created yesterday). I'm currently running 1.14.6. I'll try to do an upgrade and re-check the version number after.

**Comment by brobichaud** [comment] 2019-10-29 13:31
@asbjorne you are looking for Windows version 10.0.17763.737 on your Windows nodes. After upgrading to 1.14.7 of k8s you'll want to create a new nodepool to get the new version. It may also work to then upgrade your nodes to the latest image in the VMSS blade of the Azure Portal.

**Comment by ngrigoriev** [comment] 2019-10-29 14:05
@asbjorne I have noticed that the "systeminfo" command shows N/A instead of complete version number. I do not fully trust what is shown in the portal :) But I have found that "ver" command actually does show the complete version:

```
C:\tmp>systeminfo | findstr Version
OS Version:                10.0.17763 N/A Build 17763
BIOS Version:              American Megatrends Inc. 090007 , 6/2/2017

C:\tmp>ver

Microsoft Windows [Version 10.0.17763.832]
```

**Comment by brobichaud** [comment] 2019-10-29 14:54
@ngrigoriev using this command gives you the detail you need:

`kubectl get nodes -o wide `

**Comment by asbjorne** [comment] 2019-10-29 20:39
After doing upgrade of k8s on the node pool, it's now running version 10.0.17763.737. Hopefully this resolves our issues with the node loosing network connection ability outside the cluster.

Thanks everyone for your help!
