### ISSUE TITLE
AGIC support for Kubenet

### ISSUE THREAD

**Issue by Tbohunek** [Azure/AKS#2461] opened 2021-07-28 15:27 UTC
**What happened**:
Application Gateway Ingress Controller is not supported with `kubenet` network plugin because AGIC subnet does not have kubenet routes.

**What you expected to happen**:
As proposed in https://github.com/Azure/application-gateway-kubernetes-ingress/issues/931, whenever AGIC receives new backend to add, it should check whether it has a route for that on its subnet and if no, copy it over.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy AKS with Kubenet
2. Enable AGIC plugin

**Anything else we need to know?**:
Workaround to use AKS RT on AGIC subnet does not work in case default route deeds to point at central Firewall.

**Environment**:
- Kubernetes version: `any`
- Size of cluster: `any`
- General description of workloads in the cluster: `any`

**Comment by robincher** [comment] 2021-09-09 09:16
I think a workaround is to create App GW separately via terraform (or another other tool) ,and deploy an ingress controller with nodeport. I have tried this, but unable to achieve full-automation as the azure provider doesn't output some of the information required (specifically VM scale sets details for the App GW backend pool).

**Comment by phealy** [comment] 2021-09-09 13:56
The AKS solution to this, as you're aware, is to use the same RT on the AppGw subnet. I also understand why that can't work for you, and I think the proposed solution is worth looking into. However, as this change would be in the AGIC component, which is owned by the Application Gateway team, any work or updates on this issue should be tracked in Azure/application-gateway-kubernetes-ingress#931. Please follow that issue and comment there. Thanks!

Marking as duplicate of Azure/application-gateway-kubernetes-ingress#931

**Closed** 2021-09-10 15:00 UTC
Labels: resolution/duplicate
