### ISSUE TITLE
Unable to connect to the server: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by dsandersAzure** [Azure/AKS#14] opened 2017-10-30 20:56 UTC
Hi, when I create an AKS cluster, I'm receiving a timeout on the TLS handshake. The cluster creates okay with the following commands:

```
az group create --name dsK8S --location westus2

az aks create \
  --resource-group dsK8S \
  --name dsK8SCluster \
  --generate-ssh-keys \
  --dns-name-prefix dasanderk8 \
  --kubernetes-version 1.8.1 \
  --agent-count 2 \
  --agent-vm-size Standard_A2

az aks get-credentials --resource-group dsK8S --name dsK8SCluster
```
The response from the create command is a JSON object:
{
  "id": "/subscriptions/**OBFUSCATED**/resourcegroups/dsK8S/providers/Microsoft.ContainerService/managedClusters/dsK8SCluster",
  "location": "westus2",
  "name": "dsK8SCluster",
  "properties": {
    "accessProfiles": {
      "clusterAdmin": {
        "kubeConfig": "**OBFUSCATED**"
      },
      "clusterUser": {
        "kubeConfig": "**OBFUSCATED**"
      }
    },
    "agentPoolProfiles": [
      {
        "count": 2,
        "dnsPrefix": null,
        "fqdn": null,
        "name": "agentpool1",
        "osDiskSizeGb": null,
        "osType": "Linux",
        "ports": null,
        "storageProfile": "ManagedDisks",
        "vmSize": "Standard_A2",
        "vnetSubnetId": null
      }
    ],
    "dnsPrefix": "dasanderk8",
    "fqdn": "dasanderk8-d55f0987.hcp.westus2.azmk8s.io",
    "kubernetesVersion": "1.8.1",
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "**OBFUSCATED**"
          }
        ]
      }
    },
    "provisioningState": "Succeeded",
    "servicePrincipalProfile": {
      "clientId": "**OBFUSCATED**",
      "keyVaultSecretRef": null,
      "secret": null
    }
  },
  "resourceGroup": "dsK8S",
  "tags": null,
  "type": "Microsoft.ContainerService/ManagedClusters"
}

I've now torn down this cluster but this has happened three times today.

Any help?

David

**Comment by dsandersAzure** [comment] 2017-11-03 16:55
Update 11/03: I'm now able to create clusters successfully in uswest2; however, I'm still getting TLS handshake errors:

```
az aks browse --resource-group *OBFUSCATED* --name *OBFUSCATED*
Merged "*OBFUSCATED*" as current context in /tmp/tmpB988cA
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
error: error upgrading connection: error dialing backend: dial tcp 10.240.0.4:10250: getsockopt: connection refused
```

Are we still in the realm of capacity issues or is there another underlying issue here? This should work, right?

David

**Comment by dsandersAzure** [comment] 2017-11-03 16:58
Sometime I should look before I write :)

I see the problem. The proxy is trying to connect to 10.240.0.4 which is the private IP of one of the agents and won't (and shouldn't) be reachable from the Internet. I'm guessing this is the underlying issue here.

**Comment by amazaheri** [comment] 2017-11-03 22:28
+1 originally this worked fine, I noticed the isse today when I deleted the cluster and tried to recreate it.

**Comment by amazaheri** [comment] 2017-11-04 17:30
I get this regardless of using West US 2 or UK West: 
~ amazaheri$ az aks browse -n mtcirvk8s -g mtcirvacs-rg
Merged "mtcirvk8s" as current context in /var/folders/sf/p87ql6z9271_1l7cp6hgt2d40000gp/T/tmpHZ_Er0
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
error: error upgrading connection: error dialing backend: dial tcp 10.240.0.4:10250: getsockopt: connection refused

**Comment by amazaheri** [comment] 2017-11-06 00:22
Looks like we are good now, thanks for all the work! QQ: I cannot connect with Cabin app to my cluster using token. The app shows cluster as running but I can see any of the nodes, namespaces, etc. looks like the auth fails at some point. Thoughts?https://github.com/bitnami/cabin/issues/75

**Comment by eirikm** [comment] 2017-11-09 11:52
I'm having the same problem in West US 2 at the moment:

`$ kubectl get pods --all-namespaces
Unable to connect to the server: net/http: TLS handshake timeout`

**Comment by nyuen** [comment] 2017-11-09 12:28
same issue here on West US 2

**Comment by krol3** [comment] 2017-11-09 15:25
The cluster aks is in  West US 2. I have the same issue.

kubectl get nodes
Unable to connect to the server: net/http: TLS handshake timeout
--------------------------------------
az aks browse --resource-group xxxx-rg --name xxxx
Merged "stagingK8sCluster" as current context in /tmp/tmpx6o89zj7
Unable to connect to the server: net/http: TLS handshake timeout
Command '['kubectl', 'get', 'pods', '--namespace', 'kube-system', '--output', 'name', '--selector', 'k8s-app=kubernetes-dashboard']' returned non-zero exit status 1.

**Comment by dsandersAzure** [comment] 2017-11-09 18:41
11/9: I'm still getting issues and have reverted back to unmanaged cluster using ACS and Kubernetes as the controller. Look forward to when AKS becomes a little more stable,.

**Comment by twitchax** [comment] 2017-11-09 22:18
I am having these same issues!

**Comment by krol3** [comment] 2017-11-10 02:19
@dsandersAzure I did the same, I created using ACS !!

**Comment by yejason** [comment] 2017-11-10 02:42
AKS still in preview, for now, it seems west us 2 is not available, but ukwest is ok. We can create aks in ukwest now. 

```
C:\Users\jason>az group create --name akss --location ukwest
{
  "id": "/subscriptions/xxxxxxx-222b-49c3-xxxx-xxxxx1e29a7b15/resourceGroups/akss",
  "location": "ukwest",
  "managedBy": null,
  "name": "akss",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null
}

C:\Users\jason>az aks create --resource-group akss --name myK8sCluster --agent-count 1 --generate-ssh-keys
{| Finished ..
  "id": "/subscriptions/xxxxxxxx-222b-49c3-xxxx-0361e29axxxx/resourcegroups/akss/providers/Microsoft.ContainerService/managedClusters/myK8sCluster",
  "location": "ukwest",
  "name": "myK8sCluster",
  "properties": {
    "accessProfiles": {
      "clusterAdmin": {
        "kubeConfig": "YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VWNGVrTkRRWEVyWjBGM1NVSkJaMGxSWlhVMGVXRnBOekp3TlhadmNsUjRha2hMTldReGVrRk9RbWRyY1docmFVYzVkekJDUVZGelJrRkVRVTRLVFZGemQwTlJXVVJXVVZGRVJYZEthbGxVUVdWR2R6QjRUbnBGZUUxVVFYZE5WRlV4VFdwS1lVWjNNSGhQVkVWNFRWUkJkMDFVVlRGTmFrcGhUVUV3ZUFwRGVrRktRbWRPVmtKQlRWUkJiVTVvVFVsSlEwbHFRVTVDWjJ0eGFHdHBSemwzTUVKQlVVVkdRVUZQUTBGbk9FRk5TVWxEUTJkTFEwRm5SVUZ6TlRCRENsaGFNSEJCZWtJdlYxWnRjR1ZZTkhwaFRtZzVXRFJIVjIxWWFHTnpaelIyZVRWVGQxaDNVVTB2U1dkMWRGbGFVRzFUTjFCelVUUXJZazluWkZCWGVXSUtaREp6YWxSclJsVXZPRzVMYzJzM0sxcHhPRmxWTURFMFpVWkJXamx2UlRWNUsyRmhLMlZ
```

**Comment by eivim** [comment] 2017-11-10 13:21
I believe capacity issues in ukwest is ongoing, hoping AKS will expand to other locations in Europe soon. Had a 1.7.7 cluster in ukwest that broke a couple of days ago. Attempted to recreate today, but it is still in a bad state. 

```
$ kubectl get pods -n kube-system
NAME                                    READY     STATUS             RESTARTS   AGE
heapster-b5ff6c4dd-dkkll                2/2       Running            0          46m
kube-dns-v20-6c8f7f988b-cb4cg           3/3       Running            0          46m
kube-dns-v20-6c8f7f988b-ztn5r           3/3       Running            0          46m
kube-proxy-thz9p                        1/1       Running            0          46m
kube-svc-redirect-qhwz6                 0/1       CrashLoopBackOff   13         46m
kubernetes-dashboard-7f7d9489fc-d9x7d   0/1       CrashLoopBackOff   12         46m
tunnelfront-xzjq8                       0/1       CrashLoopBackOff   13         46m

$ kubectl logs kube-svc-redirect-qhwz6 -n kube-system
Error from server: Get https://aks-agentpool1-28161470-0:10250/containerLogs/kube-system/kube-svc-redirect-qhwz6/redirector: dial tcp 10.240.0.4:10250: getsockopt: connection refused
```

**Comment by qmfrederik** [comment] 2017-11-10 13:41
@eivim I'm seeing the exact same behavior.

**Comment by qmfrederik** [comment] 2017-11-10 13:51
So, provisioning in westuk gives me a cluster with crashing pods; provisioning in westus2 doesn't work at all:

> Azure Container Service is unable to provision an AKS cluster in westus2, due to an operational threshold. Please try again later or use an alternate location. For more details please refer to: https://github.com/Azure/AKS/blob/master/preview_regions.md.

**Comment by acesyde** [comment] 2017-11-26 08:24
Hi,

Same here today, I created an aks 1.8.1 on westeurope and it's ok, but one hour later I upgraded to 1.8.2 and since 

> Unable to connect to the server: net/http: TLS handshake timeout

kubectl 1.8.0 and 1.8.4 same error.

**Comment by kahootali** [comment] 2017-11-28 10:55
Having the same issue. I have two clusters, One East US and other Central US,
The central US works fine but when I switch context to East US, it gives the error 
`Unable to connect to the server: net/http: TLS handshake timeout`

**Comment by relferreira** [comment] 2017-11-28 12:30
I'm having the same issue after downscaling my cluster in East US!

**Comment by hanzenok** [comment] 2017-11-30 13:57
Hi everyone,

Having same issue today on westeurope. And when I try to create a new cluster in this location, it gives an error:
`Deployment failed. Correlation ID: <id>. Azure Container Service is unable to provision an AKS cluster in westeurope, due to an operational threshold. Please try again later or use an alternate location. For more details please refer to: https://github.com/Azure/AKS/blob/master/preview_regions.md.`

**Comment by garystafford** [comment] 2017-12-06 02:04
Still an issue. Any resolution? This is my third running cluster I have lost the ability to communicate with in East US. Doing an upgrade or scaling up the nodes does not work properly - a complete deal breaker on considering AKS. Either of these commands results in `Unable to connect to the server: net/http: TLS handshake timeout`. I've tried numerous commands, restarting nodes, etc. Nothing seems to recover the cluster access.

**Comment by wtam** [comment] 2017-12-06 04:57
I encounter the same  TLS handshake timeout connection issue after I manually scale the node count from 1 to 2!  My cluster is in Central US What's wrong?

**Comment by slack** [comment] 2017-12-20 00:12
Thanks for your patience through our preview.

We've had a few bugs in scale and upgrade paths that prevented the api-server from passing its health check after upgrade and/or scale. A number of bug fixes in this area went out over the last few weeks that have made upgrades more reliable.

Last week, for clusters in East US, we had an operational issue that impacted a number of older  customer clusters between 12/11 13:00PST and 12/12 16:01PST.

Health and liveness of the api-server is now much better. If you haven't upgraded recently I'd recommend issuing `az aks upgrade`, even to the same kubernetes-version, as that will push the latest configuration to clusters. This rollout step is currently being automated and should be transparent in the future.

**Comment by acesyde** [comment] 2017-12-20 07:10
@slack thank you it work ;)

**Comment by aleksen** [comment] 2018-01-05 14:44
@slack Having the same problem still after upgrading to 1.8.2 in westeurope. Is there a problem in that region?

**Comment by douglaswaights** [comment] 2018-01-08 12:43
After downgrading to 2.0.23 i was able to install the cluster but after getting the credentials downloaded I also have the same problem in westeurope...

kubectl get nodes
Unable to connect to the server: net/http: TLS handshake timeout

doing an az aks upgrade to 1.8.2 failed for me too incidentally.

**Comment by jakobli** [comment] 2018-01-08 14:39
running into the same issue, cluster in West Europe, upgrade to 1.8.2 fails with: Deployment failed. Correlation ID: 858d3cf0-0d4e-417d-a2ee-22f627892e51. Operation failed with status: 200. Details: Resource state Failed

**Comment by aleksen** [comment] 2018-01-08 14:46
@jakobli the error message you get I got when I hit my CPU quota. Are you sure you have extra D2 CPUs available? If I'm not wrong, aks commissions new vms before putting down the old ones

**Comment by jakobli** [comment] 2018-01-08 15:11
@aleksen Thanks for the tip, but I checked we have loads of quota left for D2.

**Comment by jakobli** [comment] 2018-01-08 15:31
So tried deploying directly with version 1.8.2 Deploy with without any issues but kubectl get nodes still gets Unable to connect to the server: net/http: TLS handshake timeout

**Comment by Karreg** [comment] 2018-01-18 09:21
The bug has been closed on github but the issue is still there. None of the proposed fix work in westeurope. Can someone reopen this issue? It's pending for a month and there's no resolution 😞

**Comment by D43m0n** [comment] 2018-01-18 13:35
I'm seeing the same issue too after deploying a new cluster (v1.7.7) in `westeurope`:
```$ kubectl get nodes
Unable to connect to the server: net/http: TLS handshake timeout
```

**Comment by fox1t** [comment] 2018-01-22 16:14
Hi, same issue here. I just created a cluster using AKS in westeurope reagion and i am unable to connect to it.
kubectl get no

Unable to connect to the server: net/http: TLS handshake timeout

Are someone looking actively into this?

**Comment by tslavik** [comment] 2018-01-23 13:29
Interesting. I had the same problem with cluster created yesterday. An hour before I deleted an old and created a new one (v1.8.1) using the same service principal and it works.

**Comment by peskybp** [comment] 2018-02-05 18:20
Problem definitely still exists.  Hitting it with a v1.8.6 cluster in eastus.  Have seen it across numerous versions, and I can no longer justify simply "recreating a cluster" as a workaround.

`$ kubectl get nodes
Unable to connect to the server: net/http: TLS handshake timeout`

Can we please get some visibility into the actual status of properly fixing this? Very hard to justify using AKS for production when we don't have any idea when it is going to fail.  Worse, there are sufficient functional differences between ACS and AKS to make swapping back and forth a non-starter as well...

**Comment by rafnijs** [comment] 2018-02-07 15:48
deployed AKS in Azure region west-Europe
I have the same problem: 
 .\kubectl get nodes
Unable to connect to the server: net/http: TLS handshake timeout

**Comment by tiborb** [comment] 2018-02-08 16:37
Having an issue suddenly when trying to use the CLI.
```
kubectl get pods
Unable to connect to the server: net/http: TLS handshake timeout
```

**Comment by rafnijs** [comment] 2018-02-08 16:40
Yes, The same behavior. I delete and recreate the cluster and it works fine now.

**Comment by tiborb** [comment] 2018-02-08 16:43
@rafnijs recreate the cluster? imho that solution seems quite a bit radical to me

**Comment by tiborb** [comment] 2018-02-08 16:47
az login sometimes solves the problem, seems to be a random issue

**Comment by peskybp** [comment] 2018-02-08 16:48
@tiborb Completely agree.  The only "solution" that has been touted is delete and recreate.  Which would be fine if there was an easy way to transfer everything, but...

(1) AKS Master API being non-responsive means I can't even dump out the current cluster config, so no easy "migration" and surely no way to know when it would randomly fail.

(2) AKS uses a managed resource group, which if I delete the existing cluster ALSO GETS DELETED.  That means any Managed Disks that were oh so pleasantly created for me get lost on cluster delete unless I manually migrate EACH ONE before hand.

Its been about 5 days for me now in this state, where access returns intermittently.  For those same 5 days I have had a support ticket open with Azure and have gotten basically nothing back except "I will check with the dev team".  Its been nearly 48 hours now since the last response from them, and I am thinking of just ditching the Azure based implementation as it clearly isn't ready for real world use.

**Comment by fox1t** [comment] 2018-02-08 17:02
I spoke with MS Azure Italia on phone 2 days ago and they pointed me out that AKS is still in preview. When a service is flagged like that, it is stil not production ready and the support they offer isn't active. For the moment the best way to spin up a kubernetes cluster on azure is ACS with orchestrator set to `kubernetes`. We use it in production since 1 year and it never has any problem at all.

**Comment by tiborb** [comment] 2018-02-08 17:08
My orchestrator is:
Kubernetes version
V1.8.1

I suppose it should be stable.

**Comment by fox1t** [comment] 2018-02-08 17:20
It is not a kubernetes problem, even if it seems like that. It is a AKS that is not handling correctly cluster creation and networking. As i said, just use ACS with kubernetes instead of AKS and it will work like a charm.

**Comment by fox1t** [comment] 2018-02-08 17:21
You can find ACS CLI commands here: https://docs.microsoft.com/en-us/cli/azure/acs?view=azure-cli-latest

**Comment by SurushS** [comment] 2018-02-14 08:12
I have had AKS running on Westeurope for about 4 months now running 1.8.1. Somehow this morning lost all connectivity with all the containers running and the dashboard through az aks browse. After doing an az aks upgrade to 1.8.7 everything is running normal again. It's a shame I don't know what caused this issue. Hopefully this stuff doesn't happen when it goes GA.

**Comment by nugusbayevkk** [comment] 2018-02-26 08:59
hello guys, i have the same problem.
this problem occur on windows 10 pro, docker ce edge 18.02.0-ce-win52(15372) when adding new services, pods to the cluster.
after increasing memory for docker process problem solved.
is it possible to add some checks(available memory, cpu,  etc ) in adding new pods, deployments, services to the cluster?

**Comment by asos-tonygorman** [comment] 2018-02-27 09:46
Also happening on my cluster in EUW

**Comment by Zehelein** [comment] 2018-03-05 09:03
Same for me - does not work anymore in EUW

**Comment by alonisser** [comment] 2018-03-08 06:51
Same for me, suddenly stopped connecting with the TLS error, west europe 1.8.7

**Comment by gvanderberg** [comment] 2018-03-08 16:06
Same here, cannot connect to my aks cluster anymore.  Tried using PowerShell Azure CLI and Bash - Ubuntu - Azure CLI.

xxx:~$ kubectl config current-context
companyname
xxx:~$ kubectl proxy
Starting to serve on 127.0.0.1:8001
I0308 18:02:14.211741   18892 logs.go:41] http: proxy error: net/http: TLS handshake timeout
xxx:~$ kubectl get nodes
Unable to connect to the server: net/http: TLS handshake timeout

**Comment by brendandburns** [comment] 2018-03-08 16:37
Please send the details of your cluster (subscription, resource group, cluster name) in via Azure support or to me (bburns [at] microsoft).

The TLS disconnect indicates a problem with the API Server, which can have multiple different causes. The oncall team can investigate and mitigate the problems if you send the relevant information.

Thanks
--brendan

**Comment by drewsmith** [comment] 2018-03-08 17:34
+1 

Having this issue as well and I can't log a support request without subscribing to the $100/mo plan.

**Comment by JunSun17** [comment] 2018-03-08 20:49
@dsandersAzure @drewsmith I have mitigated your issues and it should work now.

**Comment by ziXet** [comment] 2018-03-10 18:11
We are running AKS on production. Yesterday (friday at 22:00 GMT) the kube API stopped working. we are getting "Unable to connect to the server: net/http: TLS handshake timeout".
The agents are working properly. So we do not have downtime. What should we do?

**Comment by ziXet** [comment] 2018-03-10 21:54
@brendandburns Can you please also take a look at my case?

**Comment by brendandburns** [comment] 2018-03-11 01:02
Can you send your subscription, resource group and cluster name to my Microsoft email?

Thanks
--brendan

________________________________

**Comment by Novitoll** [comment] 2018-03-12 09:57
+1 Same stuff. It's been few hours since it's started. Can not access to pods, `kubectl proxy` does not work as well.

**Comment by ziXet** [comment] 2018-03-12 13:26
@brendandburns I already contacted support and they are investigating the issue. I hope I could get it back since it's our production!
I'm sure this incident(loosing kube API) is not limited to us, do you have any further update to share with us?

**Comment by Karreg** [comment] 2018-03-12 13:36
Pretty frustrating to see this issue not solved.

@ziXet that was a bit (very) audacious to go to production on a system that is in preview state :open_mouth:

**Comment by ziXet** [comment] 2018-03-12 13:42
@Karreg I only had a kubernetes 1.7 option on ACS the time I was releasing. But I wanted 1.8 which was only available in Preview. To be honest I never expected this kind of massive failure even in Preview. For example many people are using Azure Managed Postgres even though it's still in Preview.

**Comment by Karreg** [comment] 2018-03-12 14:28
The issue of "previews" that take ages to go live...

**Comment by tslavik** [comment] 2018-03-12 14:43
I had the same issue. Than tried to upgrade cluster and finished with this error 

> Deployment failed. Correlation ID: c69f4d4e-87b7-4136-9a9d-b05c93670515. Timeout while polling for control plane provisioning status

What is interesting, my cluster now is available again through "kubectl proxy --port=XXXX" 
When I look into portal I see kubernetes version 1.9.1 but "kubectl get nodes" return 1.8.1 and at portal I have error message "This container service is in a failed state"

**Comment by ziXet** [comment] 2018-03-12 14:46
I did not run the upgrade command. I thought it may make things worse.. I'm still waiting for support...

**Comment by tslavik** [comment] 2018-03-12 14:52
I understand. It depends on what is happened behind. For me it is test environment. Fortunately production is still ok. May be it will be helpful to investigate the issue.

**Comment by SurushS** [comment] 2018-03-12 14:55
This issue caused me to have to create a new cluster last week. Now after a week my new cluster is suddenly not responding to kubectl create apply or delete commands and the az aks show command says my new cluster has a failed provision state.  So again I’m disappointed in the state of aks even in preview. Now today trying to create a new cluster and it’s still creating since this morning in two different subscriptions. I’m at a loss for words....

**Comment by brendandburns** [comment] 2018-03-12 16:02
Many apologies. We are having an ongoing issue in some production environments related to cluster creation. Our oncall engineers are working to restore service.

I'll keep this thread updated as we have more information.

--brendan

________________________________

**Comment by alonisser** [comment] 2018-03-12 19:52
@brendandburns  I believe updating your status page https://azure.microsoft.com/en-us/status/ would have been helpful and would lead less noise to here

**Comment by SurushS** [comment] 2018-03-13 06:51
Any update on th matter ? I still have Yep clusters in Creating State that also cannot be deleted. Hesitant to try to make new cluster since all there impact resource cap limits

**Comment by brendandburns** [comment] 2018-03-13 15:48
You can delete the underlying resource group MC_* to free resources.

--brendan

________________________________

**Comment by ziXet** [comment] 2018-03-13 20:16
@brendandburns I did not hear back from the support!! Do you mind if I send you the subscription ID? At least I need an answer if it's not recoverable. I have to create a new cluster and migrate everything manually in that case.

**Comment by brendandburns** [comment] 2018-03-13 21:57
Sure, my email is earlier in this thread.

--brendan

________________________________

**Comment by SurushS** [comment] 2018-03-14 17:48
@brendandburns. Is it okay if I send you an e-mail. I have some questions regarding kubernetes options in general and ACS , AKS and so so forth. We are currently looking at our options and whether we want to use Azure or AWS for our PaaS. Hopefully you can give me some insights I need to make a proper decision. Promise it won’t be a long dreadful message. Please let me know if that’s okay.

**Comment by ziXet** [comment] 2018-03-15 19:21
Hi @brendandburns, Do you have any update ?

**Comment by brendandburns** [comment] 2018-03-16 00:09
Did you send cluster details via email? If so I didn't see it, please resend.

--brendan

________________________________

**Comment by ziXet** [comment] 2018-03-16 00:19
@brendandburns I just resent it.

**Comment by ziXet** [comment] 2018-03-19 14:35
I gave up! Azure Support and Brendan did not respond! Already moved everything to ACS. AKS sucks at the moment. (might change my mind later)

**Comment by tslavik** [comment] 2018-03-19 14:56
We are interested in AKS. I thought that GA of AKS should be in 1Q2018. Could someone confirm or exlude?

**Comment by ziXet** [comment] 2018-03-19 15:00
@tslavik Speaking of GA, postgresql supposed to have GA in November 2017 but it's still in Preview!

**Comment by giorgited** [comment] 2018-03-27 04:04
@ziXet have fun with ACS... we were having so much issues with that.. Azure Support replied once a week with not so much helpful emails so we just gave up. We are trying AKS now, and yet i did have the TLS handshake timeout issue, it seems like it comes and goes for me.

**Comment by brendandburns** [comment] 2018-03-27 04:31
Giorgi,
please feel free to email us when you see issues bburns [at] microsoft, with subscription, resource group and cluster name.

We're trying to track down the remaining issues that cause TLS timeouts, and more data is always useful.

Thanks
--brendan

________________________________________

**Comment by jfelten** [comment] 2018-03-31 18:29
Here's another data point for you:

I am able to reproduce this issue on a bare metal cluster running on CentOS 7 using 1.10.0 on a new node managed via kubeadm.   I had never seen this issue prior to 1.10.0. The issue appears to be that the api server port opens before it is ready to process TLS traffic.  Waiting 10 seconds or so makes the problem go away, but is a pain for automation scripts.  It would be helpful if the api server would not accept traffic before it is ready.

**Comment by kvolkovich-sc** [comment] 2018-04-01 17:02
Have similar issue right now.

`kubectl get pods`

`Unable to connect to the server: net/http: TLS handshake timeout`

**Comment by giorgited** [comment] 2018-04-02 14:54
Any update on this?

**Comment by brendandburns** [comment] 2018-04-02 15:48
This is an umbrella symptom caused by many different issues. We continue to fix them, but others crop up.

Please don't take the fact that these issues continue as a sign that we aren't finding and fixing problems (we are), but we're keeping this open for people to report new problems as they occur.

As before please send details to Azure support or to me directly (bburns at Microsoft) and we will have oncall investigate the cause.

Thanks!
Brendan

--brendan

________________________________

**Comment by alexandruradovici** [comment] 2018-04-06 11:56
Hello,

We have an AKS service in the EastUS region. We are not able to connect to it using kubectl, is there any issue in this region? 

````
az aks get-credentials --resource-group [resource] --name [service name]
kubectl get nodes
````

we get 
````
Unable to connect to the server: net/http TLS handshake timeout
````

What would you advise us to do to be able to connect?

**Comment by polys** [comment] 2018-04-06 12:56
Same issue for an AKS cluster in East US:
`Unable to connect to the server: net/http: TLS handshake timeout`

It only started happening today; everything was working just fine yesterday.

I tried connecting from my own machine, a docker container and the Azure Cloud Shell... all unsuccessful. I guess the issue is server side...

**Comment by brendandburns** [comment] 2018-04-06 16:35
Alexandru can you send me your information?

________________________________________

**Comment by brendandburns** [comment] 2018-04-06 17:27
Can you send me the subscription id and region too? send to bburns [at] microsoft if you prefer.

Thanks.

________________________________________

**Comment by shrutir25** [comment] 2018-04-09 19:14
@amitshowry - I have resolved the issue on your cluster through the AKS support case. A couple of pods were stuck in terminating, amongst other things. I have summarized it in the case notes. Feel free to ping me if the issue reoccurs.

**Comment by omgsarge** [comment] 2018-04-10 15:12
AKS in West Europe, just started getting this issue about 15 minutes ago. All fine until then, we were testing a container which was stuck in a termination/backoff loop but to my knowledge this shouldn't bring the cluster management itself down. Containers within the cluster appear to still be operating (as one of our services is still up and running, though we cannot get to see it).

It just appears the proxying/management services are unable to connect, same issue - TLS handshake failure

**Comment by angrox** [comment] 2018-04-16 13:01
We have the same issue in WEU with one of our clusters. Is there a chance to get via ssh on the machines when deploying an ssh forward pod is not possible?

**Comment by qmfrederik** [comment] 2018-04-17 07:47
@brendandburns Here's another case with TLS handshake failures: 118041117980513

**Comment by hokusp** [comment] 2018-04-19 13:45
@brendandburns same problem here EU West. It started happening after I upgraded to 1.9.6

**Comment by gourlaa** [comment] 2018-04-19 15:36
Same problem, I just open a ticket.

**Comment by aevitas** [comment] 2018-04-23 07:58
This issue keeps popping up intermittently for me, rendering AKS virtually unusable in a production scenario.

**Comment by my3sons** [comment] 2018-04-25 14:18
Looks like our US East cluster is down with this today. Anyone else experiencing same issue there?

**Comment by giorgited** [comment] 2018-04-25 14:46
One of our clusters also went down yesterday evening in West US. Recerating works but there must be a better workaround for this..

**Comment by ericbarch** [comment] 2018-04-25 16:31
Just started seeing this issue in US East a few hours ago. Never experienced it before. Error occurs whether using Azure Cloud Shell or my local system.

**Comment by traffk-viet** [comment] 2018-04-25 18:16
Hi. I'm also experiencing this issue from US East using my local system.

**Comment by benclapp** [comment] 2018-04-26 01:16
I'm also experiencing the issue on two of our clusters in the us east region.

**Comment by Vista-Group** [comment] 2018-04-26 01:16
We're also experiencing the issue on two of our clusters in the us east region.

**Comment by CraigCarpenter** [comment] 2018-04-26 07:44
We've also been experiencing this issue for the last 7 hours.  One cluster in US East.

**Comment by goudarzi** [comment] 2018-04-26 08:42
Same here... Will see if I can find what the issue is - it just started happening. Last time I was working with my AKS cluster was two/three days ago. Everything was working fine.

**Comment by Martin-Aulich** [comment] 2018-04-26 09:08
me too in west-europe.

**Comment by valdemarrolfsen** [comment] 2018-04-26 09:09
Same issue here, the whole cluster is down... This kind of unreliability should not be this frequent. Experiencing the issue in West Europe. This is why I am considering moving away from the whole Azure platform...

**Comment by florinciubotariu** [comment] 2018-04-26 11:44
Same problem for West-Europe.
Can we get some information about when is this going to be fixed?

**Comment by rakeshv1** [comment] 2018-04-26 14:25
Same issue here. Our cluster is deployed in east us

**Comment by ziXet** [comment] 2018-04-26 14:31
Wo0w! these reports clearly show that AKS is not even ready for the Preview! Glad I have switched to ACS quickly!

**Comment by florinciubotariu** [comment] 2018-04-26 14:49
Recreating the cluster in East US seems to work.
The recreation of the cluster was made with:
`az aks create --resource-group myResourceGroup --name myAKSCluster --node-count 1 --generate-ssh-keys`

**Comment by my3sons** [comment] 2018-04-26 15:27
yes, the only solution for us as well was to recreate the cluster

**Comment by gourlaa** [comment] 2018-04-26 21:59
I juste receive an email from Microsoft :
“After working with my backend engineer it appears that one of the nginx customer ingress controller was stlale. We restarted the nginx ingress controller pods  on the cluster and now the APIServer is now responding to 100%.“
Do you still have the issue ?

**Comment by gustavotroisgarcia** [comment] 2018-04-26 22:14
Apparently the issue was solved, but I need to check our 3 clusters to confirm. I’m not at office right now, I’ll check as soon as I can and let you know.

**Comment by CraigCarpenter** [comment] 2018-04-27 02:47
The issue was resolved for me.

**Comment by gustavotroisgarcia** [comment] 2018-04-27 02:50
The issue was resolved for me too. I'm able to access cluster resources again.

**Comment by ericbarch** [comment] 2018-04-27 10:42
Via Azure support, I was told it was a backplane issue that engineering just resolved (at least for our account). We're back up and running without having to recreate the cluster. :+1:

**Comment by 4c74356b41** [comment] 2018-04-28 14:06
so this looks like a game, will the cluster be available. it was yesterday, but not today. I've cleared out .kube directory and regrabbed the credentials but... you get the idea. any real steps I can take?

**Comment by mlda065** [comment] 2018-05-04 08:26
I just got the same error again today.

**Comment by raycrawford** [comment] 2018-05-08 18:51
I am getting the TLS handshake error at 2:30 PM EST in East US:

```
kubectl get nodes
Unable to connect to the server: net/http: TLS handshake timeout
```

**Comment by 4c74356b41** [comment] 2018-05-08 19:42
Also, for me kubectl\api calls from my laptop do not work, they work from Azure Cloud Shell only.

**Comment by mlda065** [comment] 2018-05-09 07:51
I discovered the cause of my issue. In the portal my AKS cluster is still listed as "Creating...". It's been like that for several days now.

I tried a different region, with the default VM size, and that worked. It still took a long time to go from "Creating..." to normal, but it did get there eventually. Then all the subsequent commands worked.

**Comment by necevil** [comment] 2018-06-06 19:09
Solution for me was to scale the Cluster nodes up by 1 (temporarily) and then once the new load launch connect.  I was then successful and could scale the cluster down to the original size.

Full background can be found over here:
https://stackoverflow.com/questions/50726534/unable-to-connect-net-http-tls-handshake-timeout-why-cant-kubectl-connect

**Comment by emanuelecasadio** [comment] 2018-07-05 11:49
Same problem here. Sometimes I just cannot use kubectl.

**Comment by SnehaJosephSTS** [comment] 2018-07-20 04:17
**I am still facing this issue while running the "kubectl get nodes" command.** I have tried the following but with no luck :(
1. Upgrading Kubernetes Version
2. Increasing node count via portal and then running "kubectl get nodes".
3. Re-logging via "az login"

**Comment by omgsarge** [comment] 2018-07-20 19:16
@SnehaJosephSTS - we had to re-create our cluster after AKS went GA. Haven't had the issue since then. Upgrade for us did not work, nor did scaling.

**Comment by danielrmartin** [comment] 2018-07-21 15:15
I am getting the error this morning. while trying to get nodes on a new cluster in eastus.

**Comment by jawahar16** [comment] 2018-07-24 16:32
I am getting the same issue in eastus. I enabled "rbac" with the AKS create command.,

az aks create --resource-group my-AKS-resource-group --name my-AKS-Cluster --node-count 3 --generate-ssh-keys --enable-rbac

**Comment by mlda065** [comment] 2018-08-14 04:51
> And if the node vm is very small, it can leave pods no place to schedule, including some mission critical pods

Isn't that a *very big* issue?

I've had many cluster break irreparably in this way. 
This bug doesn't just happen when scaling to 1. I've seen if happen when scaling nodes both up and down whilst there are too many pods.
In my experience, AKS scaling tends to cause the cluster to cease to work more often than not. 
The workaround is to delete the whole cluster and redeploy on a new one. 

Thankfully I'm not dealing with a production workload, but imagine if I was. I'd be livid.
I don't think I would ever choose to deploy a real production workload on AKS, because of this bug.

Is it possible to somehow get the scheduler to prioritise the system pods over the workload pods?

**Comment by agolomoodysaada** [comment] 2018-09-26 18:49
After lots of back and forth with Azure support, we reached to this workaround. I have yet to try it as they fixed the issue on their end. However, it might help someone else facing this.

Anyway, here's their message:

```
This is usually means that tunnelfront cannot connect to tunnelend

1. ssh to the agent node which running the tunnelfront pod
2. get tunnelfront logs: "docker ps" -> "docker logs <tunnelfront_container_id>"
3. "nslookup <ssh-server_fqdn>" whose fqdn can be get from above command -> if it resolves ip, which means dns works, then go to the following step
4. "ssh -vv azureuser@<ssh-server_fqdn> -p 9000" ->if port is working, go to the next step
5. "docker exec -it <tunnelfront_container_id> /bin/bash", type "ping [google.com](http://google.com/)", if it is no response, which means tunnel front pod doesn't have external network, then do following step
6. restart kube-proxy, using "kubectl delete po <kube-proxy_pod> -n kube-system", choose the kube-proxy which is runing on the same node with tunnelfront. customer can use "kubectl get po -n kube-system -o wide"
```

P.S.
Dear Azure team,

We should close this issue as the bug still occurs from time to time. This is not considered an acceptable workaround. It's a mitigation for those whose clusters are stuck and cannot access logs, exec, or helm deployments. We still need a permanent fix designed for failure on either tunnelfront or tunnelend.

**Comment by Starefossen** [comment] 2018-10-01 08:32
Created a new cluster after GA and now out of a sudden getting a bunch of TLS handshake timeout from AKS. This does not give the feeling that AKS is anything near GA.

**Comment by jskulavik** [comment] 2018-10-04 04:39
Please see #676 - we are actively working to resolve this issue

**Comment by mcobzarenco** [comment] 2018-10-05 14:04
Just set up a new cluster - our production deployment is on Google Cloud,'s Kubernetes but we're doing an Azure deployment for a client. Set up a cluster with one node and I wanted to investigate differences to the GCP deployement, essentially do a dry run. However, it seems like all `kubectl` operations as well as `az browse" fail with:
```
net/http: TLS handshake timeout
```
az version 2.0.46
kubectl 1.9.7

**Comment by emirhosseini** [comment] 2018-11-29 19:56
Any update on this issue? We're still experiencing it

**Comment by siyangy** [comment] 2018-12-05 22:00
We've been hitting this for a year, and the explanation earlier was that we were using a preview version of AKS cluster. Now we've moved to a new cluster (supposed after GA) and are still seeing it. I think it's worth bumping the priority as the issue has been around for a long while and is affecting a lot of folks.

**Comment by adamsem** [comment] 2019-01-07 13:47
I found the solution!!!

**Comment by adamsem** [comment] 2019-01-08 14:05
Separate vnet for AKS or migrate to AWS :)

**Comment by jnoller** [comment] 2019-02-09 17:16
Hi Everyone;

AKS has rolled out a lot of enhancements and improvements to mitigate this including auto-detection of hung/blocked API servers, kubelets and proxies. One of the final components is to scale up the Master components to meet the overall workload load against the master APIs.

This issue (this github issue) contains a lot of cluster-specific reports - as we can not safely request the data for your accounts to do deeper introspection here on github, I'd ask if you could please file Azure technical support issues for diagnosis (these support issues get routed to our back end on-call team as needed for resolution).

Additionally, the errors displayed can also correlate to underlying service updates in some cases (especially if you are seeing it randomly, for a limited amount of time). This will be helped with the auto scaling (increased master count) being worked on.

For issues that come up after I close this, please file new github issues that include instructions for re-creation on any AKS cluster (e.g. general not-tied-to-your-app-or-cluster). This will help support and engineering debug.

**Closed by jnoller** 2019-02-09 17:16 UTC
Labels: bug, known-issue

**Comment by sanojdev89** [comment] 2019-09-12 07:42
kubectl get pods --insecure-skip-tls-verify=true
works on jenkins server but fails while running via a jenkins job
