### ISSUE TITLE
ARM Policy Blocking Creation of AKS

### ISSUE THREAD

**Issue by pjbgf** [Azure/AKS#211] opened 2018-02-27 15:38 UTC
The subscriptions within my tenant have Azure policies which blocks NICs being created without NSGs to protect them. 

Whenever I try to create a new AKS cluster I get the error below:

```
Deployment failed. Correlation ID: c0327bab-6803-4079-ab84-517a48b74432. Provisioning of resource(s) for container service aks-cluster123 in resource group aks-security-research failed. 
Message: The template deployment failed with multiple errors. Please see details for more information.. 
Details: [{"code":"RequestDisallowedByPolicy","message":"Resource 'aks-nodepool1-12868434-nic-0' was disallowed by policy. Policy identifiers: '[{\"policyDefinitionId\":\"/subscriptions/*REDACTED*/providers/Microsoft.Authorization/policyDefinitions/EnforceNSGOnNetworkInterfaces\",\"policyAssignmentId\":\"/subscriptions/*REDACTED*/providers/Microsoft.Authorization/policyAssignments/Enforce NSG on network interfaces\"}]'.","target":"aks-nodepool1-12868434-nic-0"},{"code":"RequestDisallowedByPolicy","message":"Resource 'aks-nodepool1-12868434-nic-1' was disallowed by policy. Policy identifiers: '[{\"policyDefinitionId\":\"/subscriptions/*REDACTED*/providers/Microsoft.Authorization/policyDefinitions/EnforceNSGOnNetworkInterfaces\",\"policyAssignmentId\":\"/subscriptions/*REDACTED*/providers/Microsoft.Authorization/policyAssignments/Enforce NSG on network interfaces\"}]'.","target":"aks-nodepool1-12868434-nic-1"},{"code":"RequestDisallowedByPolicy","message":"Resource 'aks-nodepool1-12868434-nic-2' was disallowed by policy. Policy identifiers: '[{\"policyDefinitionId\":\"/subscriptions/*REDACTED*/providers/Microsoft.Authorization/policyDefinitions/EnforceNSGOnNetworkInterfaces\",\"policyAssignmentId\":\"/subscriptions/*REDACTED*/providers/Microsoft.Authorization/policyAssignments/Enforce NSG on network interfaces\"}]'.","target":"aks-nodepool1-12868434-nic-2"}]
```

Although the error message, an item with the cluster name is created on the resource group as expected. The secondary resource group is created, however empty and nothing else happens next.

Given that the nodes are managed by Azure, it feels that those Azure Policies should not impact them. They certainly should not give the "in-between" state, in which a cluster appears to be created, however it isn't really.

**Comment by amanohar** [comment] 2018-03-02 01:16
@pjbgf the agents nodes are created in customer's subscription and respect the policies applied at the subscription level and do not try to override/bypass them. 

This is because admins in some organizations don't want other members in their companies to bypass rules set at an org level. Would it be possible to get an exception at the resource group level and on the AKS side we could try to inherit the policy from the primary resource group in to the secondary resource group?

Regarding: 
>They certainly should not give the "in-between" state, in which a cluster appears to be created, however it isn't really.

A PUT operation does not perform rollback (by design) but the resource will be in failed state and customer can delete it.

**Comment by pjbgf** [comment] 2018-03-08 09:25
@amanohar thank you for your response, we will try to do the "exception at resource group level" and apply to both resource groups. 

Given that AKS creates a resource group of its own, I think that your suggestion makes a lot of sense, namely, having the second RG to inherit the policies from the primary.

As for the "PUT operation", it is conceptually reasonable that making a REST request against Azure API leads to a failed state on this specific case which is then not rolled back. However, as an end-user, creating an AKS cluster through the Portal or the Azure CLI,  the result does not feel consistent with the experience I use to have using other Azure services. 

If this is the way forwards, that is fine, it may just make sense to highlight that to the end-user. I knew there was something wrong as I already had several clusters created by then, and knew there was an extra resource group that should be created.

Another point on this specific problem, I noticed that if the cluster is already created, and such a policy is applied, every time a new Kubernetes LoadBalancer service is created within the cluster, it never acquires a Public IP address. Also leading to a "corrupted state" with no useful information to track the root problem.

**Closed** 2019-08-09 00:57 UTC
Labels: resource-groups
