### ISSUE TITLE
[Feature] AKS Fleet Management upgrade support for auto scheduling

### ISSUE THREAD

**Issue by aizuddin85** [Azure/AKS#4284] opened 2024-05-14 03:01 UTC
**Is your feature request related to a problem? Please describe.**
Currently we are using auto-upgrade for all our AKS clusters. The problem with this approach is that we dont have control which environment will get upgrade first (ie dev or prod which one first, we dont have control), and we are exploring AKS KFM, and found that upgrade execution required to be manually triggered unlike auto-upgrade. 

**Describe the solution you'd like**
Using AKS Fleet Management cluster upgrade group and stage, we can set a time scheduling to automate this upgrade start.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by serbrech** [comment] 2024-06-04 06:46
@aizuddin85 this is in progress. stay tuned :)

https://github.com/Azure/AKS/issues/4102

**Comment by serbrech** [comment] 2024-08-27 04:06
closing as duplicate of #4102

**Closed by serbrech** 2024-08-27 04:06 UTC
Labels: feature-request
