### ISSUE TITLE
vmssCSE extension failing

### ISSUE THREAD

**Issue by NatsArumugam** [Azure/AKS#4584] opened 2024-10-10 04:05 UTC
All of the sudden we are seeing all of our nodes in nodepools of particular SKU (Standard_NC24rs_v3) reporting failed states. On further investigation we see it as "vmssCSEExtension" failing. We do have 2 other nodepools from different SKUs which are all working and not having this issue.

We do have around 5 AKS instance and in all of them the nodepools of this particular SKU are failing.

VM has reported a failure when processing extension 'vmssCSE' (publisher 'Microsoft.Azure.Extensions' and type 'CustomScript'). Error message: 'Enable failed: failed to execute command: command terminated with exit status=34 [stdout] { "ExitCode": "34", "Output": "53403]: primaryNicIP is unset, exiting...

This started showing up on all of our clusters from  Sunday, October 6, 2024 at 12:43:53 AM

**Comment by djsly** [comment] 2024-10-10 23:33
Which region?  Different ones ? All the same ?

**Comment by NatsArumugam** [comment] 2024-10-11 00:32
Yes. Different regions and all are same. West US 2, Canada Central and West Europe

**Comment by PixelRobots** [comment] 2024-10-11 19:42
It would be best to open a support request for this. As it seems more an issue with compute rather than AKS.

**Comment by cameronmeissner** [comment] 2024-10-29 17:17
this issue was caused by an incorrect `jq` query used to parse IMDS network interface response content at node provisioning time

fixed by: https://github.com/Azure/AgentBaker/pull/5100

said fix is now available in all AKS regions, any impacted customer will need to perform a reimaging operation to pick up the fix (e.g. with a node image upgrade)

**Closed by cameronmeissner** 2024-10-29 17:17 UTC
