### ISSUE TITLE
Windows pods cannot reach themselves via service IP

### ISSUE THREAD

**Issue by giskou** [Azure/AKS#2608] opened 2021-10-26 12:10 UTC
**What happened**:
Windows pods cannot reach themselves via service IP

**What you expected to happen**:
A windows deployment with one replica and a service on top of it should be able to reach the service IP, which refers to itself.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an aks cluster with AzureCNI and some windows nodes
2. Deploy the following test application
```
---
apiVersion: v1
kind: Service
metadata:
  name: win-webserver
  labels:
    app: win-webserver
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: win-webserver
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: win-webserver
  name: win-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: win-webserver
  template:
    metadata:
      labels:
        app: win-webserver
      name: win-webserver
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/os
          value: windows
      containers:
        - name: windowswebserver
          image: mcr.microsoft.com/windows/servercore:1809
          command:
            - powershell.exe
            - -command
            - "<#code used from https://gist.github.com/wagnerandrade/5424431#> ; $$listener = New-Object System.Net.HttpListener ; $$listener.Prefixes.Add('http://*:80/') ; $$listener.Start() ; $$callerCounts = @{} ; Write-Host('Listening at http://*:80/') ; while ($$listener.IsListening) { ;$$context = $$listener.GetContext() ;$$requestUrl = $$context.Request.Url ;$$clientIP = $$context.Request.RemoteEndPoint.Address ;$$response = $$context.Response ;Write-Host '' ;Write-Host('> {0}' -f $$requestUrl) ;  ;$$count = 1 ;$$k=$$callerCounts.Get_Item($$clientIP) ;if ($$k -ne $$null) { $$count += $$k } ;$$callerCounts.Set_Item($$clientIP, $$count) ;$$ip=(Get-NetAdapter | Get-NetIpAddress); $$header='<html><body><H1>Windows Container Web Server</H1>' ;$$callerCountsString='' ;$$callerCounts.Keys | % { $$callerCountsString+='<p>IP {0} callerCount {1} ' -f $$ip[1].IPAddress,$$callerCounts.Item($$_) } ;$$footer='</body></html>' ;$$content='{0}{1}{2}' -f $$header,$$callerCountsString,$$footer ;Write-Output $$content ;$$buffer = [System.Text.Encoding]::UTF8.GetBytes($$content) ;$$response.ContentLength64 = $$buffer.Length ;$$response.OutputStream.Write($$buffer, 0, $$buffer.Length) ;$$response.Close() ;$$responseStatus = $$response.StatusCode ;Write-Host('< {0}' -f $$responseStatus)  } ; "
```
3. Run the following tests to verify the application is working fine
```
kubectl exec -it deployment/win-webserver -- curl.exe -v --max-time 10 http://localhost:80 -H "Connection: close"
* Rebuilt URL to: http://localhost:80/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.55.1
> Accept: */*
> Connection: close
>
< HTTP/1.1 200 OK
< Content-Length: 97
< Server: Microsoft-HTTPAPI/2.0
< Date: Tue, 26 Oct 2021 12:02:21 GMT
< Connection: close
<
<html><body><H1>Windows Container Web Server</H1><p>IP 10.xxx.xxx.xxx callerCount 1 </body></html>* Closing connection 0
```
4. The following times out always.
```
kubectl exec -it deployment/win-webserver -- curl.exe -v --max-time 10 http://win-webserver:80 -H "Connection: close"
* Rebuilt URL to: http://win-webserver:80/
*   Trying 10.xxx.xxx.xxx...
* TCP_NODELAY set
* Connection timed out after 10000 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 10000 milliseconds
command terminated with exit code 28
```

**Anything else we need to know?**:
This happens since kubernetes 1.20. In version 1.19 everything worked fine.
Both upgrades to 1.20 from 1.19 and new 1.20 clusters have the issue.
It is also present on 1.21.

Scaling the deployment to 2, makes curl work every other time, when the other pod is picked in round robin.
Generally, services on other pods work just fine.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.9
- Size of cluster (how many worker nodes are in the cluster?): 2 linux, 1 windows
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): N/A

**Related Issues**
https://github.com/Azure/aks-engine/issues/4079
https://github.com/Azure/AKS/issues/2236
https://github.com/Azure/AKS/issues/2322

**Comment by AbelHu** [comment] 2021-11-05 04:41
@giskou This issue is related to WinDSR. When disabling WinDSR, `kubectl exec -it deployment/win-webserver -- curl.exe -v --max-time 10 http://win-webserver:80 -H "Connection: close"` succeeds. cc @daschott

**Comment by daschott** [comment] 2021-11-05 04:59
@AbelHu The cause of this is that Azure CNI is missing loopbackDSR policy support. Azure CNI needs to be extended with loopbackDSR policy to support connecting to DSR service that may redirect to source pod.

**Comment by AbelHu** [comment] 2021-11-05 05:08
> @AbelHu The cause of this is that Azure CNI is missing loopbackDSR policy support. Azure CNI needs to be extended with loopbackDSR policy to support connecting to DSR service that may redirect to source pod.

@daschott Do we still need AzureCNI support loopbackDSR policy even with the latest fix in WinDsr?

**Comment by daschott** [comment] 2021-11-05 05:11
@AbelHu yes, this is still required

**Comment by giskou** [comment] 2021-11-05 10:10
@AbelHu How can I disable WinDSR in AKS?

**Comment by smnmtzgr** [comment] 2021-11-05 10:16
@giskou are you using ingress-nginx?

**Comment by giskou** [comment] 2021-11-05 10:17
@smnmtzgr yup

**Comment by smnmtzgr** [comment] 2021-11-05 10:49
Have you tried setting this:
`controller:
  replicaCount: 2
  podAnnotations:
    co.elastic.logs/enabled: "true"
    co.elastic.logs/processors.add_labels.labels.aks.system: "1"
  publishService:
    enabled: true
  service:
    externalTrafficPolicy: Cluster
`

instead of _externalTrafficPolicy: Local_?

**Comment by giskou** [comment] 2021-11-05 10:59
My issue is unrelated to nginx-ingress; it's pure pod networking.
I know that there is an issue with WinDSR and nginx-ingress but that's a different story.

**Comment by AbelHu** [comment] 2021-11-05 11:14
@giskou you can try @smnmtzgr 's suggestion. To disable WinDSR, AKS CSS will check it with you via your support ticket.

**Comment by giskou** [comment] 2021-11-05 11:21
@AbelHu but the issue I describe above has nothing to do with nginx.
Answering yes to the question "are you using ingress-nginx?" was very general and not related to this.
Even the question was totally out of topic.

**Comment by AbelHu** [comment] 2021-11-05 11:26
@giskou Local has different route logic since you are using the service ip. https://blog.getambassador.io/externaltrafficpolicy-local-on-kubernetes-e66e498212f9

**Comment by giskou** [comment] 2021-11-05 11:32
ExternalTrafficPolicy can only be set on NodePort and LoadBalancer service.
We are using normal ClusterIP services.

**Comment by giskou** [comment] 2021-11-05 11:37
To sum up, I think there are two options here:
* fix Azure CNI to work with loopbackDSR (ideal, more permanent solution)
* disable WindDSR (workaround)

The second option will work for us, since we don't use calico policies on windows yet.
At some point we will, so the first option should be considered long term.

**Comment by giskou** [comment] 2021-11-05 11:41
@AbelHu @daschott  Is there a case with Azure CNI for supporting loopbackDSR that we can follow?
Or is this even planed?

**Comment by AbelHu** [comment] 2021-11-05 12:06
@giskou we are asking Azure Container Networking team to support loopbackDSR in Azure CNI.

**Comment by AbelHu** [comment] 2021-11-19 02:35
Fix PR in Azure CNI: https://github.com/Azure/azure-container-networking/pull/1116

**Comment by AbelHu** [comment] 2021-12-08 10:38
It will be fixed in AKS RP release v20211209

**Closed** 2021-12-19 08:00 UTC
Labels: known-issue, windows, resolution/fix-released

**Comment by AbelHu** [comment] 2021-12-22 07:21
AKS RP release v20211209 is available in all regions in global Azure. If WinDSR is not disabled in user's subscription, user can upgrade the cluster to any newer version to get the fix. Creating new Windows agent pools also work.
