### ISSUE TITLE
Service Tag Annotation is not being enforced

### ISSUE THREAD

**Issue by tshaiman** [Azure/AKS#2281] opened 2021-04-19 18:34 UTC
**What happened**:
using AKS version 1.19.4 and with nginx-ingress controller I have created the following custom definition for the ingress-nginx controller : 

```yaml
controller:
  service:
    annotations:
      service.beta.kubernetes.io/azure-allowed-service-tags: "AzureFrontDoor.Backend"
    loadBalancerSourceRanges: ["20.193.26.137/32","<other_ip>"]

```
The definitions appear as  NSG rules accordingly , but the FrontDoor is still blocked from access.  the loadBalancerSourceRanges rule is being respected correctly.
when removing the loadBalancerSourceRanges list, only then, the FrontDoor rule is being enforced.

working example (which prevents us from enforcing specific IP ranges) :

```yaml
controller:
  service:
    annotations:
      service.beta.kubernetes.io/azure-allowed-service-tags: "AzureFrontDoor.Backend"
   
```

**What you expected to happen**:
The Front Door service tag should be enforced along side with the loadBalancerSourceRanges as they both appear in the NSG rule list. 
**How to reproduce it (as minimally and precisely as possible)**:
- create AKS cluster in any region
- install nginx-ingress controller
- apply the above custom definitions and notice that FrontDoor traffic is blocked when there Source rangers are defined.

**Anything else we need to know?**:

could be related to https://github.com/Azure/AKS/issues/1813

**Environment**:
- Kubernetes version (use `kubectl version`):  1.19.4
- Size of cluster (how many worker nodes are in the cluster?) 4 worker nodes , 2-5 nodes each ,size : Standard_D3_v2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) : Https web server with nodeJS as Linux containers.

**Comment by AustinSmart** [comment] 2021-08-11 16:49
Pulling the relevant info from [#1813](https://github.com/Azure/AKS/issues/1813#issuecomment-679388447) (as far as I have experienced and understand the issue).

The `loadBalancerSourceRanges` are being reconciled in two spots. At the NSG level, and [at the node level as iptable rules](https://github.com/kubernetes/kubernetes/blob/2585d78c79054a6d85620eb5430a1498bb747967/pkg/proxy/iptables/proxier.go#L1184).

The `service.beta.kubernetes.io/azure-allowed-service-tags` are only being reconciled at the NSG level.

Service Tag traffic will make it through the loadbalancer, but not through the node firewall.
If no `loadBalancerSourceRanges` is provided, the iptable rules are left open on the node, and the Service Tag traffic will make it through the node firewall.

**Comment by tshaiman** [comment] 2021-08-11 17:32
@AustinSmart  this is great summery Austin . thank you very much.

I think the ticket can be closed as this is "by-design" issue

**Comment by AustinSmart** [comment] 2021-08-11 17:39
If this is by design, then some clarification in the docs for the `service.beta.kubernetes.io/azure-allowed-service-tags` annotation may be needed. Currently the [documentation states](https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#additional-customizations-via-kubernetes-annotations):
```
Below is a list of annotations supported for Kubernetes services with type LoadBalancer, these annotations only apply to INBOUND flows:
[...]
service.beta.kubernetes.io/azure-allowed-service-tags | List of allowed service tags | Specify a list of allowed service tags separated by comma.
```
There is no indication that this flow would not complete for _all_  "Kubernetes services with type LoadBalancer"

**Comment by tshaiman** [comment] 2021-08-11 17:42
@AustinSmart I agree and already opened a bug on the docs

**Comment by Shuanglu** [comment] 2021-08-12 05:20
When loadBalancerSourceRanges have been set on service spec, service.beta.kubernetes.io/azure-allowed-service-tags won’t work because of DROP iptables rules from kube-proxy. The CIDRs from service tags should be merged into loadBalancerSourceRanges to make it work.

https://kubernetes-sigs.github.io/cloud-provider-azure/topics/loadbalancer/#loadbalancer-annotations

**Comment by qpetraroia** [comment] 2021-09-01 16:41
Hey, @zr-msft 

Can you take a look at this?

**Comment by feiskyer** [comment] 2021-11-29 02:27
Already documented at https://kubernetes-sigs.github.io/cloud-provider-azure/topics/loadbalancer/#loadbalancer-annotations.

**Closed by feiskyer** 2021-11-29 02:27 UTC
Labels: docs, Feedback
