### ISSUE TITLE
AKS - Inability to use BLB with multiple node pools

### ISSUE THREAD

**Issue by Aanuka** [Azure/AKS#1651] opened 2020-06-04 09:04 UTC
**What happened**:
AKS Cluster scaled with a new node pool. During cordon on the first node pool and pods being moved over we noticed that a few services could not reach their external dependencies anymore. During investigation we saw that the pods where located on nodes in the new node pool and that their egress IP did not follow the same logic as described in:
https://docs.microsoft.com/en-US/azure/aks/egress

**What you expected to happen**:
New nodes to get added to already deployed LoadBalancer and use that IP for egress.

**How to reproduce it (as minimally and precisely as possible)**:
- Setup AKS with 1 node pool
- Configure Service with External LoadBalancer (i.e nginx ingress)
- curl within a pod to verify external IP
- Add a second node pool to the cluster
- Cordon one node to force over pods
- curl within a pod that is placed on a new node to verify external IP

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.14.8
- Size of cluster (how many worker nodes are in the cluster?)
3 in First Node Pool
3 in Second Node Pool

**Comment by oscar60310** [comment] 2020-07-02 04:11
Same problem. I can't find any VMSS which create by AKS node pools so it's not possible to add them to backend pool manually.
@Aanuka Do you have any solution?

**Comment by Aanuka** [comment] 2020-07-03 13:18
> Same problem. I can't find any VMSS which create by AKS node pools so it's not possible to add them to backend pool manually.
> @Aanuka Do you have any solution?

No resolution yet.

**Comment by palma21** [comment] 2020-07-27 08:46
Are you using AKS with Basic Load Balancer by any change? That seems like what would happen if you do.

Multiple nodepools require Standard Load Balancer.

Do you have a Support Ticket so we may verify your cluster?

**Comment by Aanuka** [comment] 2020-07-27 10:05
> Are you using AKS with Basic Load Balancer by any change? That seems like what would happen if you do.
> 
> Multiple nodepools require Standard Load Balancer.
> 
> Do you have a Support Ticket so we may verify your cluster?

Correct that the cluster has a Basic Load Balancer (It was created before Standard Load Balancer was available).
I take it that there are still no migration path for Basic -> Standard Load Balancer?

No support ticket open for this yet, and it seems that this was already known in case of a Basic Load Balancer?

**Comment by palma21** [comment] 2020-08-07 23:23
Yes, indeed https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#limitations

We've added additional validations to prevent deploying this unsupported case. The issue is that the Basic LB can't load balance across multiple VMSS pools.

**Comment by palma21** [comment] 2020-08-07 23:24
We're working on a migration path for BLB to SLB as we speak.

**Comment by jluk** [comment] 2020-08-07 23:35
Adding the relevant issue for tracking streamlining the ability to migrate. https://github.com/Azure/AKS/issues/1687

Closing this issue as a known gap in using BLB with multiple node pools, AKS now has validation which requires use of SLB to access multiple node pools.

**Closed by jluk** 2020-08-07 23:35 UTC
Labels: SR-Support Request, question
