### ISSUE TITLE
Tunnel Front liveliness probe fails, when creating an aks cluster using capz  

### ISSUE THREAD

**Issue by LochanRn** [Azure/AKS#2336] opened 2021-05-18 08:26 UTC
**What happened**:
Tunnel Front liveliness probe is failing when creating an aks cluster using capz.

I created an AKS cluster using capz, the cluster was created successfully but I was unable to get logs for any of the pods.
I was able to get or describe pods. I then checked the tunnel front pod and the liveliness probe kept failing even after multiple restarts.

I was also unable to exec into any of the pods. Could not ssh using an aks-ssh pod.  
So I created another vm in the same network and then was able to ssh into the worker-node when I checked the tunnel-front logs. 

```
WRN: Attempt:[11] - failed:Get secret:[tunnelfront] from kubernetes. will retry
2021-05-17T17:08:47.543290049Z stderr F Error in configuration: 
2021-05-17T17:08:47.54333185Z stderr F * unable to read client-cert /var/lib/kubelet/pki/kubelet-client-current.pem for default-auth due to open /var/lib/kubelet/pki/kubelet-client-current.pem: no such file or directory
2021-05-17T17:08:47.54333955Z stderr F * unable to read client-key /var/lib/kubelet/pki/kubelet-client-current.pem for default-auth due to open /var/lib/kubelet/pki/kubelet-client-current.pem: no such file or directory
2021-05-17T17:08:47.548080186Z stdout F WRN: Attempt:[12] - failed:Get secret:[tunnelfront] from kubernetes. will retry 
```

I then inspected the deployment file. I found that the volume mounts was wrongly mapped.
I have attached the buggy yaml named bug.yaml and a tunnel-front.yaml which is the correct one.
Even after applying the right yaml the correct yaml keeps getting over-written by the bug.yaml and the pod keeps failing.

I also added the variables.sh and cluster1.yaml used to create the aks cluster using clusterctl.

**What you expected to happen**:
An aks cluster to be created and working fine. No issues with tunnel-front pod.

**How to reproduce it (as minimally and precisely as possible)**:
Create a Kind cluster.
set-up all the env variables as mentioned in the variables.sh.
clusterctl init --infrastructure azure
kubectl apply -f cluster1.yaml  # cluster1.yaml is provided in the attachments.

**Anything else we need to know?**:
None

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20,5
- Size of cluster (how many worker nodes are in the cluster?) 2 worker pools with 1 node and vm size Standard_D2s_v3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) None
- Others: None

Zip file containing bug.yaml, tunnel-front.yaml cluster1.yaml and variables.ssh
[tunnel-front-aks.zip](https://github.com/Azure/AKS/files/6499594/tunnel-front-aks.zip)

**Comment by junaid18183** [comment] 2021-05-19 08:59
I have faced the same issue but on 
AKS K8s version -  1.18.14 
ap_vm_size - Standard_A4_v2
The root cause I found out is the tunnelfront pod is missing the `kubelet-client-current.pem` I fixed by hostpath volume mounting /var/lib/kubelet in `tunnelfront` pod.

FYI I did not observe this issue in 1.19.9

**Comment by LochanRn** [comment] 2021-05-19 09:06
Yup I applied the same fix in to the tunnelfront volume mounts. I added the right yaml in the zip as well.

I found this issue in K8s version - 1.20.5
ap_vm_size - Standard_D2S_v3

**Comment by junaid18183** [comment] 2021-05-19 09:54
Wow, so it does not work in 1.18 and 1.20 but works in 1.19. Interesting not sure how AKS is managing the POD definition of `tunnelfront` across versions. 
Also somewhere I read AKS is also [planning](https://github.com/Azure/AKS/issues/2186) to retire the `tunnelfront`  and add `connectivity`

**Comment by miwithro** [comment] 2021-08-10 18:11
@LochanRn we are deprecating tunnel-front for konnectivity.

**Comment by palma21** [comment] 2021-09-02 17:47
Do you have this same issue with normally create clusters or just via capz?

**Comment by LochanRn** [comment] 2021-09-02 19:03
I don't this issue any more it was only with capz though.

**Comment by palma21** [comment] 2021-09-02 19:52
Ok, let us know if you have any further issues!

**Comment by miwithro** [comment] 2021-09-02 20:40
@thomas1206 can you have someone look into this issue?

**Closed** 2021-09-11 11:28 UTC
Labels: Feedback, resolution/other
