### ISSUE TITLE
The total number of secondary ipconfigurations in network profile for scale set XXX exceeds the maximum allowed value of 256

### ISSUE THREAD

**Issue by tjcrone** [Azure/AKS#1124] opened 2019-07-24 22:06 UTC
I have VMSS being scaled by AKS and got the following error when trying to scale from 2 to 3 nodes: `The total number of secondary ipconfigurations 500 in network profile for scale set XXX exceeds the maximum allowed value of 256.` My cluster has a VNET with /16 subnets for all the various components. Am I missing some sort of setting here? Can I increase the number of "secondary ipconfigurations"? Thanks!

**Comment by tjcrone** [comment] 2019-07-25 09:25
When deploying this cluster via the CLI I changed max-pods to 250, which I believe is the maximum. But for some reason Kubernetes reserves all of these addresses when a node is created. So we had 500 secondary IP addresses at the outset. Is this expected behavior? I am expecting this cluster to scale to dozens if not a hundred nodes for short periods of time, so regardless of what max-pods is, it looks like we will run out of secondary IP addresses if the quota remains 256.

**Comment by victornoel** [comment] 2019-07-30 07:31
@tjcrone have you figured a way to increase the max number of "secondary ipconfigurations"?

I want nodes with more than 30 pods by default, but at the same time I want to be able to put more than 2 nodes in my node pool.

**Comment by tjcrone** [comment] 2019-07-30 11:23
@victornoel, my problem was a little different. I never figured out what was going on, but it's possible that Kubernetes was trying to reserve IP addresses for twice the number (500) of the maximum pods allowed per node for this cluster which was at the time 250. I think it might have gotten confused.

Anyway, the good news is that you can increase the maxumum number of pods when creating a cluster using the --max-pods argument on the command line, and I believe the current maximum is 250. The bad news is that it does not look like it is possible to change this number [after a cluster has been created](https://github.com/Azure/aks-engine/issues/542). Hope this helps!

**Comment by victornoel** [comment] 2019-07-30 12:07
@tjcrone hmm, the `--max-pods` configuration is per node pool, so you can create new node pools with a different value for this parameter.

I believe the problem here is that if you set `--max-pods` to 250, then you can't scale your node pool to more than 2 nodes, because of the bug we both encountered.

**Comment by tjcrone** [comment] 2019-07-30 13:21
I'm not sure that was my experience. The [documentation](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest) indicates that this is the maximum pods per node. The default quota for secondary IP addresses (256) is also per NIC, meaning per node. But perhaps you are right that this is a bug that crops up under certain circumstances.

**Comment by victornoel** [comment] 2019-07-30 13:39
@tjcrone at least we are in agreement about max pod being per node yes.

I don't know about the quota for secondary ip addresses, where did you find this information? As per the error message, I thought it was a quota par scaling set, not per NIC (hence the error, since if it was per NIC, things would work because 250 is less than 256 :).

**Comment by caruccio** [comment] 2019-08-08 22:48
Have you guys found the solution? I've noticed AKS creates a second resource group for the node pools with address space's CIDR  10.x.x.x/24, which matches the `maximum allowed value of  256`.

**Comment by caruccio** [comment] 2019-08-09 14:11
Please ignore my previous post. It was totally unrelated to this issue.

**Comment by victornoel** [comment] 2019-08-20 16:02
According to some exchanges with the support, this is a bug and should be fixed in an upcoming version of AKS (they say maybe around the end of month…).

A workaround would be to, I cite:
> reduce the number of ipconfigs per VM so that the total number of ipconfig in the entire scale set does not exceed 256

I haven't looked into it yet though.

**Comment by tjcrone** [comment] 2019-08-21 18:46
cc @yangsiyu007

**Comment by karyjac** [comment] 2019-08-22 17:58
might be related to https://github.com/Azure/aks-engine/issues/1741

**Comment by jluk** [comment] 2019-09-16 19:57
@tjcrone we made a release that should address an issue very similar to this and I think it should be resolved so I'm closing this. If you still reproduce though please comment and I will re-open to look back into it.

**Closed by jluk** 2019-09-16 19:57 UTC
Labels: triage
