### ISSUE TITLE
kubectl can't connect to one of the nodes

### ISSUE THREAD

**Issue by rytmis** [Azure/AKS#738] opened 2018-11-29 21:03 UTC
**What happened**:
`kubectl logs <podname>` fails with an error:
Error from server: Get `<address to logs>?sinceSeconds=300`: dial tcp: lookup <node> on 172.30.0.10:53: no such host

This happens for every pod on that particular node.

**What you expected to happen**:
Expected kubectl to work.

**How to reproduce it (as minimally and precisely as possible)**:
Don't know. 

**Anything else we need to know?**:
This seems to have begun happening at around the same time the kube-dns, kube-proxy, omsagent etc. system pods have last been recreated.

Edit: I drained the node. Once the pods got recreated on another node, kubectl logs worked again. I then uncordoned the node and deleted the pods, after which they got recreated on the affected node -- and kubectl logs fails again, with the same message.

Edit: The omsagent pod is failing to create on the affected node, with this error message:

Error: host IP unknown; known addresses: [{Hostname aks-agentpool-40179180-1}]

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?) 3

- General description of workloads in the cluster
ASP.NET Core web sites

- Others:

**Comment by wojciech12** [comment] 2018-12-03 10:59
@rytmis contact support. In my case they did something and suddenly the node got back its IP. If you do not want to wait for them, just restart the node.

**Comment by DenisBiondic** [comment] 2018-12-03 13:05
There is actually a "bug" in kubelet in which it loses the internal IP address. You can check by running 'kubectl describe node  | grep -A 3 Addresses', your node will probably not have the address. Root cause of this issue is lost connectivity between master plane and worker node, after which the kubelet fails to recover properly. 

Check the kubelet logs, it should show "Using Node Hostname from cloudprovider:" until the connection is lost (try to find out when was the last entry with this message).

Also check https://github.com/Azure/acs-engine/issues/3503

**Comment by feiskyer** [comment] 2018-12-03 14:17
The fix is cherry-picking to 1.11 release https://github.com/kubernetes/kubernetes/pull/70400. Still pending now.

**Comment by rytmis** [comment] 2018-12-18 15:39
1.11.6 is out and this fix is in it, so I'm closing this now.

**Comment by jnoller** [comment] 2019-01-17 16:45
1.11.6 has not been released into AKS. Reopening until we complete testing and rollout

**Comment by jnoller** [comment] 2019-04-05 18:07
Completed rollout! Closing

**Closed by jnoller** 2019-04-05 18:07 UTC
