### ISSUE TITLE
Lack of garbage collection of orphaned resources in the cluster auto-scaler. 

### ISSUE THREAD

**Issue by axelgMS** [Azure/AKS#861] opened 2019-03-05 14:54 UTC
Customer requested an issue on GitHub to account for the lack of garbage collection of orphaned resources in the cluster auto-scaler. The autoscaler has created something like 3k ip configuration in the loadbalancer causing huge instability in NRP. We should be garbage collecting unused resources. Customer implemented a script to clean up unused NICs/IPconfigurations and it has stabilized the cluster.

**What happened**:  429 throttling errors being sent because of excessive orphaned resources with Autoscaler.

**What you expected to happen**: Garbage Collection of unused resources

**How to reproduce it (as minimally and precisely as possible)**: 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jeffmartinxyz** [comment] 2019-03-05 22:06
I wanted to add a few more details:

**Cause**
The cause here is that the cluster-autoscaler does not remove orphaned ip configurations. This means that every time the cluster scales up and scales down, new ip configurations are subsequently added, but never removed. 

The effects below were observed on a loadbalancer that had ~3k ip configurations associated with it. The sheer amount of ip configurations in the loadbalancer causes the Azure Networking providers to hang for ~5 minutes at a time.

**Effect**

- The loadbalancer may hang indefinitely when provisioning public IPs to Kubernetes LoadBalancer objects.
- The cloud-provider module will send many requests to the loadbalancer. However, the loadbalancer will not be able to respond to most request as it is busy. These will fail as 429 "RetryableError".
-  The loadbalancer frequently retries to update the loadbalancer in this scenario, so much so that 429s will be thrown due to rate limiting from ARM. These will have an error code of "SubscriptionRequestThrottled".

**Comment by yangl900** [comment] 2019-04-02 18:03
@jeffmartinxyz could you clarify it is VMSS auto scaler or regular VM auto scaler? Also, do you mean it was the frontend public IP configurations associated with the LB? The basic LB can only associate 200 IP configurations (https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits), how is it possible to associate 3k IP?

**Comment by jeffmartinxyz** [comment] 2019-04-03 15:55
@yangl900 This was in regards to the VM auto-scaler, not the VMSS. I was offbase with the ~3k ip configurations in the backend address pool. The limit for that is 200. However, NRP was still throwing  429 "RetryableError" when enumerating over those ip configurations.

**Comment by jluk** [comment] 2019-08-05 16:18
@jeffmartinxyz resurrecting this - so this is about manual scaling (not the cluster autoscaler) correct? Any updates on this front, trying to catch up to see the broader impact this issue may be having today.

**Comment by jluk** [comment] 2019-08-08 23:00
@jeffmartinxyz I am closing this issue as it looks to only happen on VMAS + cluster autoscaler. this configuration is not supported in AKS given VMSS is a pre-requisite to use the CA feature.

**Closed by jluk** 2019-08-08 23:00 UTC
Labels: triage
