### ISSUE TITLE
AKS Nodepool Snapshots - Can no longer create a nodepool from a snapshot taken in a different Subscription

### ISSUE THREAD

**Issue by aido123** [Azure/AKS#3037] opened 2022-06-28 16:25 UTC
**Describe the bug**
It is no longer possible to create a nodepool from a snapshot taken in a different Subscription

**To Reproduce**
Az CLI 2.37.0
Create a cluster X in subscription A
Create a  snapshot 1 of a nodepool in the cluster
Create a new cluster Y in Subscription B
Try to create a nodepool in Cluster Y from the snapshot 1 in Subscription A

**Expected behavior**
Nodepool should be created

**Environment (please complete the following information):**
Broken with az cli 2.37.0
Working with az cli 2.33.1

**Comment by kaarthis** [comment] 2023-03-10 19:59
will check with the Nodepool Snapshot crew - @chengliangli0918

**Comment by chengliangli0918** [comment] 2023-03-11 05:13
@kaarthis This issue is azure-cli regression in 2.34.0 - 2.37.0 caused by https://github.com/Azure/azure-cli/pull/21592. It was fixed in azure-cli 2.39.0 (Aug 2022) and later

**Comment by chzbrgr71** [comment] 2023-09-01 18:49
Closing with above fix.

**Closed by chzbrgr71** 2023-09-01 18:49 UTC
Labels: bug, resolution/answer-provided
