### ISSUE TITLE
Not able to enable cluster autoscaler after disabling

### ISSUE THREAD

**Issue by vishnujanardhanan** [Azure/AKS#1248] opened 2019-10-03 08:26 UTC
**What happened**: az aks enable-cluster-autoscaler fails

**What you expected to happen**: enable cluster auto scaling

**How to reproduce it (as minimally and precisely as possible)**:
Disabled the cluster autoscaler - all good
--------
az aks update -n myCluster -g myCluster-rg --disable-cluster-autoscaler

Trying to enable the autoscaler back on - failed with the error
------
az aks update -n myCluster -g myCluster-rg --enable-cluster-autoscaler --min-count 1 --max-count 2
Operation failed with status: 'Bad Request'. Details: Cannot manually scale and enable cluster autoscaler in the same update operation on VMSS Agentpool 'default'.

Trying to enable only with min-count - failed 
-------
az aks update -n myCluster -g myCluster-rg --enable-cluster-autoscaler --min-count 1
Please specifying both min-count and max-count when --enable-cluster-autoscaler or --update-cluster-autoscaler set.

Tried using the update cluster autoscaler - failed
------
az aks update -n myCluster -g myCluster-rg --update-cluster-autoscaler --min-count 1 --max-count 2
Cluster autoscaler is not enabled for this managed cluster.
Run "az aks update --enable-cluster-autoscaler" to enable cluster with min-count and max-count.

Trying to enable with min-count 1 and max-count 1, so no node scaling required - failed
---------
az aks update -n myCluster -g myCluster-rg --enable-cluster-autoscaler --min-count 1 --max-count 1
Operation failed with status: 'Bad Request'. Details: Cannot manually scale and enable cluster autoscaler in the same update operation on VMSS Agentpool 'default'.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.13.10
- Size of cluster (how many worker nodes are in the cluster?): 1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Vanilla cluster
- Others:

**Comment by jluk** [comment] 2019-10-07 20:01
@vishnujanardhanan how long are you waiting between each of those commands? 

There are 2 things to consider:
1. It takes a moment for the disable command to complete, if trying to manually scale or re-enable before that is complete you'll see errors similar to what you received.
2. Do you have multiple agent pools enabled on that cluster?

**Comment by vishnujanardhanan** [comment] 2019-10-08 06:57
@jluk I did wait for the confirmation from az cli before triggering the scale command
I destroyed the cluster, so dont know how many agent pools it created. I can come back to you in few days on this query.

**Comment by vishnujanardhanan** [comment] 2019-10-08 07:30
@jluk I had only one node pool on the cluster, which was the default one created by aks. I didn't create a node pool as such. Is agent pool and node pool same?

**Comment by jluk** [comment] 2019-10-08 15:46
Thanks for clarifying - agent pool == node pool. @feiskyer or @palma21 do you know what could be happening here?

**Comment by palma21** [comment] 2019-10-16 22:52
Were you able to see this behavior again? I'm not being able to reproduce.

**Comment by vishnujanardhanan** [comment] 2019-10-29 12:45
@palma21 i'll test and come back in few days.

**Comment by jluk** [comment] 2020-02-03 17:14
@vishnujanardhanan I'm closing this since it's been 3 months. If there's an ongoing issue though, please feel free to open a new one.

**Closed by jluk** 2020-02-03 17:14 UTC
Labels: Needs Information, autoscaler
