### ISSUE TITLE
Time sync broken on one node

### ISSUE THREAD

**Issue by kamilzzz** [Azure/AKS#2251] opened 2021-04-07 15:45 UTC
**What happened**:

Time is off by ~30 seconds on one VM.
We have AKS cluster with 3 node pools in 3 AZs in West Europe.

Node pools were created last Friday. On the Friday everything was fine as we didn't notice any 401 errors from applications running in the cluster.

Yesterday we have noticed that we are randomly getting 401 responses from our services and it turned out time is not synchronized on one VM.

`timedatectl` output from broken node:

```
Local time: Wed 2021-04-07 15:40:09 UTC
Universal time: Wed 2021-04-07 15:40:09 UTC
RTC time: Wed 2021-04-07 15:40:09
Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: no
systemd-timesyncd.service active: no
RTC in local TZ: no
```

Time on other VMs is synchronized correctly.
All nodepools are using `AKSUbuntu-1804gen2containerd-2021.03.29` image.

`timedatectl` output from node with synchronized time:
```
Local time: Wed 2021-04-07 15:39:50 UTC
Universal time: Wed 2021-04-07 15:39:50 UTC
RTC time: Wed 2021-04-07 15:39:50
Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
systemd-timesyncd.service active: no
RTC in local TZ: no
```
Shouldn't here `systemd-timesyncd.service` be active anyway?

---

Also for some reason I see differences between machines. For example:
- node with broken time sync has `ntpd` (https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync#use-the-default) installed while others do not
- `systemctl status systemd-timesyncd.service` on broken node:
```
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:systemd-timesyncd.service(8)
```
- `systemctl status systemd-timesyncd.service` on other nodes:
```
System has not been booted with systemd as init system (PID 1). Can't operate.
```

**What you expected to happen**:
Time to be correctly synchronized.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.7
- Size of cluster (how many worker nodes are in the cluster?): 3 VMs right now

**Comment by miwithro** [comment] 2021-04-08 16:41
@xuto2

**Comment by palma21** [comment] 2021-04-08 18:11
Hi @kamilzzz do you have to have open a support ticket for this? The first output is definitely not expected.

**Comment by palma21** [comment] 2021-04-08 18:13
Also, would you be able to check if Chrony is running on your not-synced node?

**Comment by kinkist** [comment] 2021-04-09 05:43
Hi @palma21 
We had a same issue.

issue number "TrackingID#2104010060003889"
I reported a root cause of this.

Root Cause
  - cse script -> failed installation of chrony package.

**Comment by kamilzzz** [comment] 2021-04-09 08:43
Hi @palma21

Unfortunately yesterday I had to recreate a cluster for different reasons.
Before that I checked that after restarting this particular VM its time was correct, but I'm quite sure `timedatectl` was still showing:
```
System clock synchronized: **no**
```

Also right now i'm not 100% sure but if I remember correctly I tried to verify chrony on that node before and I got an error that chrony is not installed, so probably that's the same issue which @kinkist reported.

**Comment by adriankostrubiak-tomtom** [comment] 2021-04-09 19:11
We just ran into this same issue, and it was breaking our authentication with oauth2-proxy, giving us errors such as

```
Error redeeming code during OAuth2 callback: could not verify id_token: oidc: current time 2021-04-09 18:27:26.0216652 +0000 UTC m=+282835.151041901 before the nbf (not before) time: 2021-04-09 18:28:34 +0000 UTC
```

We cordoned and drained the node, but unfortunately the autoscaler killed it before I could get on there to investigate further.

Our nodepool containing the impacted node is up to date.  Below are some details on the nodepool.


It would be good to understand what is going on here.

------------

```bash
=> az aks nodepool get-upgrades --cluster-name xxx-redacted-xxx --nodepool-name primary -g xxx-redacted-xxx
{
  "id": "xxx-redacted-xxx",
  "kubernetesVersion": "1.19.7",
  "latestNodeImageVersion": "AKSUbuntu-1804gen2containerd-2021.03.29",
  "name": "default",
  "osType": "Linux",
  "resourceGroup": "xxx-redacted-xxx",
  "type": "Microsoft.ContainerService/managedClusters/agentPools/upgradeProfiles",
  "upgrades": null
}

=> az aks nodepool list -g xxx-redacted-xxx --cluster-name xxx-redacted-xxx
.....
  {
    "agentPoolType": "VirtualMachineScaleSets",
    "availabilityZones": [
      "1",
      "2",
      "3"
    ],
    "count": 5,
    "enableAutoScaling": true,
    "enableNodePublicIp": false,
    "id": "xxx-redacted-xxx",
    "kubeletConfig": {
      "allowedUnsafeSysctls": null,
      "cpuCfsQuota": null,
      "cpuCfsQuotaPeriod": null,
      "cpuManagerPolicy": null,
      "failSwapOn": null,
      "imageGcHighThreshold": 75,
      "imageGcLowThreshold": 50,
      "topologyManagerPolicy": null
    },
    "linuxOsConfig": null,
    "maxCount": 15,
    "maxPods": 110,
    "minCount": 3,
    "mode": "User",
    "name": "primary",
    "nodeImageVersion": "AKSUbuntu-1804gen2containerd-2021.03.29",
    "nodeLabels": null,
    "nodeTaints": null,
    "orchestratorVersion": "1.19.7",
    "osDiskSizeGb": 128,
    "osDiskType": "Ephemeral",
    "osType": "Linux",
    "podSubnetId": null,
    "powerState": {
      "code": "Running"
    },
    "provisioningState": "Succeeded",
    "proximityPlacementGroupId": null,
    "resourceGroup": "xxx-redacted-xxx",
    "scaleSetEvictionPolicy": null,
    "scaleSetPriority": null,
    "spotMaxPrice": null,
    "tags": {
      ...
    },
    "type": "Microsoft.ContainerService/managedClusters/agentPools",
    "upgradeSettings": {
      "maxSurge": "20%"
    },
    "vmSize": "Standard_DS3_v2",
    "vnetSubnetId": "xxx-redacted-xxx"
  },
.....
```

**Comment by kinkist** [comment] 2021-04-10 11:23
![E7EA30E6-023D-41B9-8093-D682B5BD9A7C](https://user-images.githubusercontent.com/42393278/114268146-91cf6180-9a3a-11eb-9054-1e7bb083bfb3.jpeg)
this is cse installation logs

**Comment by Vandersteen** [comment] 2021-04-12 08:00
How did you fix the issue ?

**Comment by miwithro** [comment] 2021-04-12 13:52
We are working on an updated VHD with an incorporated fix.  In the interim can you ensure Chrony is installed and functional on your node/s?

**Comment by kinkist** [comment] 2021-04-13 06:58
https://github.com/Azure/AgentBaker/pull/738

**Comment by palma21** [comment] 2021-04-15 04:32
Mitigations:
- Install crony of affected node or
- Delete / scale down the affected node and scale it again. (you main also cordon / drain and let Cluster autoscaler take care of it)

Fix:
- A new node image that ensures this race condition installing chrony doesn't happen is being release, the release notes will contain the details.

**Comment by dhananjaya-senanayake** [comment] 2021-04-15 13:14
Ran into the same issue, support issue ID 2104150060004312

**Comment by miwithro** [comment] 2021-04-15 13:16
Hello,  did you apply mitigations above?
Mitigations:

Install crony of affected node or
Delete / scale down the affected node and scale it again. (you main also cordon / drain and let Cluster autoscaler take care of it)

We will have a fixed VHD out soon.

**Comment by dhananjaya-senanayake** [comment] 2021-04-15 13:20
> Hello, did you apply mitigations above?
> Mitigations:
> 
> Install crony of affected node or
> Delete / scale down the affected node and scale it again. (you main also cordon / drain and let Cluster autoscaler take care of it)
> 
> We will have a fixed VHD out soon.

In an auto scaling cluster manual fix will have little effect. Manual scale down will have effect on existing worker nodes.

**Comment by dhananjaya-senanayake** [comment] 2021-04-15 13:22
> Mitigations:
> 
> * Install crony of affected node or
> * Delete / scale down the affected node and scale it again. (you main also cordon / drain and let Cluster autoscaler take care of it)
> 
> Fix:
> 
> * A new node image that ensures this race condition installing chrony doesn't happen is being release, the release notes will contain the details.

@palma21 https://docs.microsoft.com/en-us/azure/aks/node-updates-kured will this work ? since the most of the affected worker nodes are older in age.

**Comment by dhananjaya-senanayake** [comment] 2021-04-16 02:26
Any ETA on the permanent fix for this ?

**Comment by OthmanAljundi-01** [comment] 2021-04-16 11:00
you configure the following deamonset which will install chrony on all nodes including new scaled ones 
wget https://raw.githubusercontent.com/OthmanAljundi-01/AKS/main/k8s-install-chrony-ds.yml
kubectl apply -f k8s-install-chrony-ds.yml

**Comment by xuto2** [comment] 2021-05-06 07:08
The permanent fix is out - upon your next node image ugprade or k8s version upgrade or cluster/agent pool creation (any operation that will get you a new vm or vmss (but not vmss instance)), you will get chrony  (except in westus and norwaywest which is in release, but you will get ntp).

**Closed by xuto2** 2021-05-06 07:08 UTC
Labels: SR-Support Request, bug

**Comment by xuto2** [comment] 2021-05-07 18:08
westus is on too.
Below is AKS general release notes, but I think we missed the chrony one so you couldn't find it.
https://github.com/Azure/AKS/releases
