### ISSUE TITLE
Upgrade AKS to the Moby container run time

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#723] opened 2018-11-16 16:29 UTC
Type: bug fix/enhancement.

See Azure feedback forum for the parent thread: https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/34917076-increase-kubernetes-node-docker-version-to-17-05-x

This is a tracking bug on the AKS repository to track when we officially enable the latest Moby container runtime inside of AKS. As of ACS-Engine 0.25 the Moby runtime is supported. 

This issue only tracks the enablement of Moby in AKS.

**Comment by seanmck** [comment] 2018-11-17 02:07
Duplicate of #63 .

**Closed by seanmck** 2018-11-17 02:07 UTC
