### ISSUE TITLE
AKS cluster unavaiable for 2-3 minutes during scaling up/down

### ISSUE THREAD

**Issue by JuneZhao** [Azure/AKS#745] opened 2018-12-05 02:20 UTC
The problem is actually quite simple: if you add a node to the cluster, the cluster becomes inaccessible via kubectl for a few seconds (or dozen of seconds).
The same issue occurs if you remove a node from the cluster.
 
This problem occurs even with a new cluster without any additional pods running on it, so it is quite easy to reproduce.

**What you expected to happen**:

Cluster should always be accessible whenever we scale up/down the cluster.

**How to reproduce it (as minimally and precisely as possible)**:
I think the problem is easier to reproduce if you follow the logs of a pod before adding/removing a node:
In the case of your cluster:
1) follow the logs of a pod:   kubectl logs -f mollified-clownfish-wordpress-fc8d967d5-wjfqr 
2) add a node to the cluster
3) the previous kubectl command will be interrupted

**Anything else we need to know?**:
We observed below
Some kube-proxy pods are not working properly, thus impacting the kubectl command.
After a few minutes, everything comes back to normal.

Is it possible to fix this issue? I understand that the problem occurs only a few minutes for each scaling operation but I am using a cluster autoscaler to automatically add and remove nodes, therefore the problem occurs quite frequently. I checked that the problem does not occur with other Kubernetes managed services (I particularly checked AWS EKS), so I think this is AKS-related.
If it is impossible to fix the issue in AKS?

**Environment**: AKS
- Kubernetes version (use `kubectl version`): 1.11.3
- Size of cluster (how many worker nodes are in the cluster?) 4

**Comment by jnoller** [comment] 2019-04-05 17:53
Duplicate of #274

**Closed by jnoller** 2019-04-05 17:53 UTC
