### ISSUE TITLE
AZ AKS Browse does not work from WSL (Bash for Windows)

### ISSUE THREAD

**Issue by cvs79** [Azure/AKS#6] opened 2017-10-26 06:45 UTC
When trying az aks browse gives an 

_Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
error: error upgrading connection: error dialing backend: dial tcp 10.240.0.5:10250: getsockopt: connection refused_

**Comment by rspaulino** [comment] 2017-10-26 10:53
@cvs79 your issue is not related just to WSL, I been having the same issue on a Mac using bash they're having issue with capacity and some internals I got it to work by using them UK WEST location instead of the West US.

**Comment by amazaheri** [comment] 2017-11-04 17:14
Mine still fails regardless of USWest 2 or WestUK irvinemtcs-MacBook-Pro:~ amazaheri$ az aks browse -n mtcirvk8s -g mtcirvacs-rg
Merged "mtcirvk8s" as current context in /var/folders/sf/p87ql6z9271_1l7cp6hgt2d40000gp/T/tmpHZ_Er0
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
error: error upgrading connection: error dialing backend: dial tcp 10.240.0.4:10250: getsockopt: connection refused

**Comment by brendandburns** [comment] 2017-11-08 01:09
I believe that this is root caused by #2.

**Comment by amazaheri** [comment] 2017-11-08 01:11
Indeed! It looks like fixed and I have a working Cluster in West US 2

**Comment by jespernohr** [comment] 2017-11-11 22:13
I am getting this error now in ukwest

**Comment by benc-uk** [comment] 2017-11-12 11:13
It worked once for me, I deleted the AKS instance created another (several in fact) and it no longer works!  
I've tried 1.7 and 1.8 as the version, and the same problem. This is in ukwest, as westus2 is **still** having capacity issues. 

I'm seeing this when I view all pods
```
NAMESPACE     NAME                                       READY     STATUS             RESTARTS   AGE
kube-system   po/heapster-553147743-hgj8b                2/2       Running            0          3m
kube-system   po/kube-dns-v20-1654923623-29b5v           3/3       Running            0          3m
kube-system   po/kube-dns-v20-1654923623-f3lk5           3/3       Running            0          3m
kube-system   po/kube-proxy-b1dtf                        1/1       Running            0          3m
kube-system   po/kube-proxy-lbhn6                        1/1       Running            0          3m
kube-system   po/kube-svc-redirect-4jph9                 0/1       CrashLoopBackOff   4          3m
kube-system   po/kube-svc-redirect-jvn88                 0/1       CrashLoopBackOff   5          3m
kube-system   po/kubernetes-dashboard-3427906134-3vssw   0/1       CrashLoopBackOff   4          3m
kube-system   po/tunnelfront-p06vc                       0/1       CrashLoopBackOff   4          3m
kube-system   po/tunnelfront-s5zn7                       0/1       CrashLoopBackOff   4          3m
```

**Comment by slack** [comment] 2017-12-20 00:23
We have changed up the regions and tunnel infra, closing out this issue. If folks still have problems please open new issues.

**Closed by slack** 2017-12-20 00:23 UTC
