### ISSUE TITLE
[BUG] API Server DNS record is not deleted when its AKS cluster is deleted

### ISSUE THREAD

**Issue by nizdansel** [Azure/AKS#4500] opened 2024-08-22 18:46 UTC
**Describe the bug**
Scenario:  
- creating a private AKS cluster with --private-dns-zone option that refer to an existing private DNS zone to record API server endpoint FQDN (privatelink.northeurope.azmk8s.io for instance)
- deleting the AKS cluster
- the expected behavior is to have the API server DNS record deleted

=> The API server DNS record is not deleted when the cluster is deleted.

**To Reproduce**
1. Create private DNS zone following Microsoft documentation: https://learn.microsoft.com/fr-fr/azure/private-link/private-endpoint-dns#containers
2. Create a VNET and Subnet 
3. Create a RG
4. Create a private AKS cluster with --private-dns-zone option
5. Delete the AKS cluster 

**Expected behavior**
When deleting the AKS cluster, it is expected to have all its associated resources deleted including its API server DNS record.

**Screenshots**
N/A

**Environment (please complete the following information):**
 -  CLI Version: tested with 2.58 (aks-preview 2.0.0b4 ) and 2.63.0 (aks-preview 7.0.0b6 ) and 
 - Kubernetes version : 1.30

**Additional context**
The same bug behavior is reproduced when:
- creating and deleting the AKS cluster with az cli and with Terraform
- deleting the cluster via Azure portal

**Comment by tesharp** [comment] 2024-08-28 07:13
We have observed the same issue. I'd say it started about 2. August. We run automated tests for creating and destroying clusters and they had been working perfectly till this point. After that they didn't delete the dns record anymore and recreating the cluster fails as dns record already exists.

**Comment by nizdansel** [comment] 2024-08-28 09:29
I confirm that we meet the same issue when stopping the cluster. The DNS record remains int the Private DNS Zone.

**Comment by umersyed** [comment] 2024-08-28 13:11
I tested just now and can confirm that the issue is still there. The API Server DNS record is not getting deleted when Cluster is Stopped. We are in Canada Central region. For us the issue started since around 30-Jul-2024.

**Comment by levimm** [comment] 2024-08-29 07:54
@umersyed confirmed it's due to a different issue. 
It's caused by a recent regression that when private dns zone is in a different subscription than AKS subscription, we would fail to delete the private dns record. We're rolling back the release now. Needs a few days to reach Canada Central.

**Comment by nizdansel** [comment] 2024-08-29 11:48
I have just tested on North Europe region. It is not working when stopping the cluster and when deleting It. @levimm please let us know when the rollback is effective to test again. Thanks in advance

**Comment by levimm** [comment] 2024-09-03 01:34
@nizdansel  both north europe and canada central have the fix now, please try again.

**Comment by oolfloo** [comment] 2024-09-03 11:20
Should the fix be deployed to westeurope as well? 
I just tested and for us, it did not work.

**Comment by umersyed** [comment] 2024-09-03 14:40
> @nizdansel both north europe and canada central have the fix now, please try again.

Tested for Canada Central and looks better now. Thanks

**Comment by nizdansel** [comment] 2024-09-03 17:25
hi @levimm, thanks for your feedback. I have just tested it now in North Europe and it works fine when stopping the cluster and when deleting it. I tested with a cluster that was already created and with a newly created cluster. It works for all my tests.

**Comment by levimm** [comment] 2024-09-04 00:57
@oolfloo  west europe would take several more hours.

**Comment by tesharp** [comment] 2024-09-04 08:58
Looks like its working in Norway East as well. Thanks

**Comment by levimm** [comment] 2024-09-04 10:12
the fix is all released now. I'm closing this.

**Closed by levimm** 2024-09-04 10:12 UTC
Labels: bug, Private-cluster

**Comment by roofiq** [comment] 2025-04-23 15:20
I have the same issue on France Central. When I remove cluster and recreate it, it tries to call previous API server
