### ISSUE TITLE
Kubernetes 1.10

### ISSUE THREAD

**Issue by asymmetric** [Azure/AKS#350] opened 2018-05-07 15:10 UTC
A reply to [this](https://github.com/Azure/AKS/issues/88) issue says that point releases should get supported 1-2 weeks after the upstream release.

Considering 1.10 has been released on March 27, are there any plans to support it on AKS?

Alternatively, is there something akin to GKE's [Alpha clusters](https://cloud.google.com/kubernetes-engine/docs/concepts/alpha-clusters)?

**Comment by derekperkins** [comment] 2018-05-07 15:16
He's referring to 1.9.x as point releases and 1.10 as minor releases, so the long-term goal would be 1 month for 1.10. The fact that GKE still hasn't made 1.10 GA yet leads me to believe that this is a more difficult integration than previous minor releases.

**Comment by seanmck** [comment] 2018-06-09 05:29
Duplicate of #288

**Closed by seanmck** 2018-06-09 05:29 UTC
