### ISSUE TITLE
AKS k8s version 1.13.5 Calico pods in CrashLoopBackOff state

### ISSUE THREAD

**Issue by neumanndaniel** [Azure/AKS#933] opened 2019-04-29 06:44 UTC
**What happened**:
The Calico pods are in CrashLoopBackOff state after deploying an AKS cluster with Kubernetes version 1.13.5 in Azure region North Europe via Terraform.

The AKS cluster has RBAC with AAD integration enabled.

**What you expected to happen**:
That the Calico pods are in running state.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy an AKS cluster with Kubernetes version 1.13.5 in Azure region North Europe with Azure CNI plugin and Calico Network Policy plugin enabled. Also RBAC with AAD integration is enabled.

**Anything else we need to know?**:
Here is the log output of one of the Calico pods. Seems to be an RBAC permission issue.
```
2019-04-29 06:37:05.718 [INFO][9] startup.go 256: Early log level set to info
2019-04-29 06:37:05.718 [INFO][9] startup.go 272: Using NODENAME environment for node name
2019-04-29 06:37:05.718 [INFO][9] startup.go 284: Determined node name: aks-agentpool-20563840-1
2019-04-29 06:37:05.720 [INFO][9] startup.go 316: Checking datastore connection
2019-04-29 06:37:05.744 [INFO][9] startup.go 340: Datastore connection verified
2019-04-29 06:37:05.744 [INFO][9] startup.go 95: Datastore is ready
2019-04-29 06:37:05.751 [INFO][9] customresource.go 100: Error getting resource Key=GlobalFelixConfig(name=CalicoVersion) Name="calicoversion" Resource="GlobalFelixConfigs" error=the server could not find the requested resource (get GlobalFelixConfigs.crd.projectcalico.org calicoversion)
Calico node failed to start
2019-04-29 06:37:05.769 [INFO][9] node.go 79: Error updating Node resource error=nodes "aks-agentpool-20563840-1" is forbidden: User "system:serviceaccount:kube-system:calico-node" cannot update resource "nodes/status" in API group "" at the cluster scope
2019-04-29 06:37:05.769 [ERROR][9] startup.go 164: Unable to set node resource configuration error=connection is unauthorized: nodes "aks-agentpool-20563840-1" is forbidden: User "system:serviceaccount:kube-system:calico-node" cannot update resource "nodes/status" in API group "" at the cluster scope
2019-04-29 06:37:05.769 [WARNING][9] startup.go 1042: Terminating
```

**Environment**:
- Kubernetes version (use `kubectl version`): **1.13.5**
- Size of cluster (how many worker nodes are in the cluster?) **3**
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) **Fresh cluster after deployment. No workloads on it.**
- Others:

**Comment by feiskyer** [comment] 2019-04-29 07:50
@neumanndaniel This is a known issue because of this week's rollout. We're fixing the rollout now. Meanwhile, you can still try calico feature in Australia or Canada regions.

**Comment by neumanndaniel** [comment] 2019-04-29 07:51
Thanks @feiskyer

**Comment by feiskyer** [comment] 2019-04-30 08:03
The issue has been fixed now. @neumanndaniel Could you try to upgrade the cluster, or create a new one?

After upgrading, remember to do a cleanup first (this is required, see discussion on aks-engine [here](https://github.com/Azure/aks-engine/pull/454)):

    kubectl delete -f https://github.com/Azure/aks-engine/raw/master/docs/topics/calico-3.3.1-cleanup-after-upgrade.yaml

If there're other Pods (e.g. dashboard) in crashing state, delete the pod and let Kubernetes creating new ones could bring it back.

**Comment by neumanndaniel** [comment] 2019-04-30 08:20
I had not to do any upgrade. I just restarted the agent nodes and the Calico pods are now up and running. **I did not the cleanup yet.**

**Comment by feiskyer** [comment] 2019-04-30 08:22
@neumanndaniel OK, when you do the upgrade, remember the cleanup. or else, network policy would be broken.

**Comment by ams0** [comment] 2019-04-30 10:14
I deployed a new cluster and it works.

**Comment by feiskyer** [comment] 2019-04-30 13:48
@ams0 thanks for the information.

**Comment by sNathan13** [comment] 2019-05-03 14:23
This happens with AKS deployed with k8s v 1.14 . I deployed a new cluster with v1.14 and seeing the same issue with calico pods.

**Comment by feiskyer** [comment] 2019-05-04 11:03
@sNathan13 How did you deploy a v1.14 cluster? And could you share the logs of calico-node pod (note that there're two containers in that pod)

**Comment by sNathan13** [comment] 2019-05-04 15:46
@feiskyer I created the cluster using cli. Here's the command I used,

az aks create --resource-group <RESOURCE_GP> --name <CLUSTER_NAME> --node-count 2 --generate-ssh-keys  --vnet-subnet-id <SUBNET_ID>  --dns-name-prefix <DNS_PREFIX>  --aad-server-app-id <AAD_SERVER_ID> --aad-server-app-secret <ADD_SECRET>  --aad-client-app-id <AAD_CLIENT_ID> --aad-tenant-id <TENANT_ID> --network-plugin azure --network-policy calico --kubernetes-version 1.14.0 

And when I try to print the logs, I get an error,
Error from server: Get https://aks-nodepool1-11422562-0:10250/containerLogs/kube-system/calico-node-fdhhs/calico-node: dial tcp 10.x.x.x:10250: i/o timeout

**Comment by feiskyer** [comment] 2019-05-05 01:23
@sNathan13 Seems tunnelfront pod is not working as expected. Could you delete the pod, wait a while for new Pod running by controller, and try again with logs?

**Comment by sNathan13** [comment] 2019-05-06 15:14
@feiskyer No luck. I deleted tunnelfront pod and waited for a new one to come up. It still gives me a timeout error, when I try to display logs of Calico pod.

**Comment by feiskyer** [comment] 2019-05-07 05:29
@sNathan13 thanks for the information. Just confirmed there's a version issue of calico-node, the image version should be v3.5.0. We would fix it in AKS's next rollout.

Since Kubernetes v1.14 on AKS is still not production ready yet, and AKS doesn't allow users to change calico manifests, could you try with v1.12 or v1.13 instead?

**Comment by sNathan13** [comment] 2019-05-07 12:13
@feiskyer AKS v1.13.5 works great. I just wanted to test 1.14 and report any issues that I encountered. Thanks for the response :)

**Comment by feiskyer** [comment] 2019-05-07 14:11
@sNathan13 thanks. Let's close the issue since v1.13 is back to normal now.

**Closed by feiskyer** 2019-05-07 14:11 UTC
