### ISSUE TITLE
High CPU usage for "other processes" in our AKS Windows node

### ISSUE THREAD

**Issue by hallgeirl** [Azure/AKS#1277] opened 2019-10-17 08:04 UTC
**What happened**:
We have an AKS cluster with a single Windows node (using it only for development at the moment). In Azure Monitor we see that the item "Other processes" uses almost a full CPU core (about 850m). Currently we only have 9 pods deployed on this node, which isn't a lot. Each of thse pods are mostly idle, so they consume less than 50m CPU each. It does seem like the "Other processes" sometimes are high, sometimes low. I assume the "Other processes" means mainly Kubernetes services that runs on the node, but I can't understand how the CPU usage can be that high when having so few pods.

**What you expected to happen**:
I would expect the "Other processes" CPU usage to be quite low when having few pods deployed.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a cluster with Windows nodes. Deploy a few pods.

**Anything else we need to know?**:
Our container images are fairly big. They're full Windows ASP.NET images, with about 2 GB of application data on top. Could there be some anti-malware service running on the nodes that causes this?

**Environment**:
- Kubernetes version (use `kubectl version`):
1.15.3
- Size of cluster (how many worker nodes are in the cluster?)
1 Windows node, 1 Linux node
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
ASP.NET web applications (fairly large monolithic ones)
- Others:

**Comment by hallgeirl** [comment] 2019-10-17 08:43
Seems the CPU usage is actually increasing even more. Now it's on 1,5 core. In other words, it's consuming almost the whole node.

![image](https://user-images.githubusercontent.com/428446/66992901-f40c0800-f0ca-11e9-9068-f365f83931f0.png)

**Comment by MikkelHegn** [comment] 2019-10-28 14:00
Hi @hallgeirl - to further diagnose the issue, please open a support case through the Azure Portal. Thanks - We can keep this issue open to post the result of the investigation back here.

**Comment by hallgeirl** [comment] 2019-10-29 08:05
@MikkelHegn - Thanks, I have done that now. Ticket number: 119102921000300

**Comment by MikkelHegn** [comment] 2020-01-10 12:41
Closing as support case has been closed. The node in question with excessive CPU usage dropped the usage. No conclusion to the root cause was made.

**Closed by MikkelHegn** 2020-01-10 12:41 UTC
Labels: triage

**Comment by 0x53A** [comment] 2020-02-27 17:12
> Could there be some anti-malware service running on the nodes that causes this?

@hallgeirl Yes, there is Windows Defender running on the node: https://github.com/Azure/AKS/issues/1462

That would also explain why the usage stopped: it probably finished scanning
