### ISSUE TITLE
Cluster upgrade through Azure Portal does not upgrade node pool

### ISSUE THREAD

**Issue by NatGra** [Azure/AKS#1860] opened 2020-09-16 14:24 UTC
Hi AKS team,

I tried updating my cluster and the node pool, however, only the cluster got updated. It would be great if you could provide support, and thank you in advance.

**What happened**: 
After a cluster upgrade from v1.14.8 to v1.15.12 via the Azure Portal, the control pane upgraded to version v1.15.12 but the node pool stayed at v1.14.8 

<img width="341" alt="cluster-node-version" src="https://user-images.githubusercontent.com/10546494/93350114-916e3f80-f838-11ea-96ea-ab250f82edc6.png">

I verified my portal findings via CLI:
```
➜  ~ az aks show --resource-group myResourceGroup --name myCluster --output table
Name                  Location    ResourceGroup            KubernetesVersion    ProvisioningState    Fqdn
--------------------  ----------  -----------------------  -------------------  -------------------  ----
myCluster             westeurope  myResourceGroup          1.15.12              Succeeded            ...

➜  ~ az aks nodepool show --resource-group myResourceGroup --cluster-name myClusters --name default --output table 
Name     OsType    KubernetesVersion    VmSize           Count    MaxPods    ProvisioningState    Mode
-------  --------  -------------------  ---------------  -------  ---------  -------------------  ------
default  Linux     1.14.8               Standard_D4s_v3  3        40         Succeeded            User
```

An upgrade of the node pool through the Portal is not possible (the respective drop-down-menu is greyed out)
<img width="425" alt="upgrade-node-pool" src="https://user-images.githubusercontent.com/10546494/93350183-a519a600-f838-11ea-9dec-e2d74f5f0024.png">

I tried to upgrade the node pool via CLI:
```
➜  ~ az aks nodepool upgrade --resource-group myResourceGroup --cluster-name myCluster --name default --kubernetes-version 1.15.12 --no-wait
Operation failed with status: 'Bad Request'. Details: Upgrade agent pool version from 1.14.8 to 1.15.12 is not allowed, you can only upgrade one minor version at a time. Please use [az aks get-upgrades] command to get the supported upgrade paths. For more information, please check https://aka.ms/version-skew-policy
```

**What you expected to happen**:
An upgrade of both, the control pane and the node pool.

**How to reproduce it (as minimally and precisely as possible)**:
Needed: a cluster & node pool with version 1.14.8

Upgrade triggered vial Azure Portal drop-down-menu
<img width="1200" alt="azure-portal-drop-down-menu" src="https://user-images.githubusercontent.com/10546494/93350023-7ac7e880-f838-11ea-8de4-132473c56559.png">

**Anything else we need to know?**:
Same behavior was reported in #1718 and closed without proper explanation.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: v1.18.3
Server Version: v1.15.12

- Size of cluster (how many worker nodes are in the cluster?)
3 nodes

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
HTTP microservices

**Comment by jluk** [comment] 2020-09-16 16:34
Hi @natgra I believe you're hitting a few issues at the moment. One is the expected behavior of the portal upgrade pane, which targets the control plane of your cluster only. We're working through UI improvements to make it more clear what aspect of your cluster is upgrading.

The other issue is the failing upgrade via CLI and inability to make the nodepool upgrade via portal. It looks like you are targeting the 1.15 K8s version which has been deprecated this week with the GA of 1.18.

Could you retry to CLI upgrade of your cluster (control plane and nodepool) to a 1.16 supported version? In the CLI the default behavior of `az aks upgrade` is to upgrade the control plane and all node pools together. If you wish to upgrade them separately you can use the below flag.

```
Arguments
    --control-plane-only           : Upgrade the cluster control plane only. If not specified,
```

**Comment by NatGra** [comment] 2020-09-17 11:40
Hi @jluk thank you for your answer.

Yes, the initial information was a little misleading here, but nevertheless I figured out how to upgrade the node pool.

Your assumption is true, I targeted a node pool version 1.15 as my cluster is also running with the version 1.15. 
I did not want to straight away upgrade my cluster to 1.16 as the error message said to only `upgrade one minor version at a time`, and this would mean that I have to upgrade my node pool from 1.14 to 1.16.

Should I anyways try to upgrade my cluster & node pool to 1.16 even though the node pool is still at 1.14?

**Comment by NatGra** [comment] 2020-09-17 14:12
When I run the upgrade command for the whole cluster including node pools, I get the error shown above:
```
➜  ~ az aks upgrade --resource-group myResourceGroup --name myCluster --kubernetes-version 1.15.12
Kubernetes may be unavailable during cluster upgrades.
 Are you sure you want to perform this operation? (y/N): y
The cluster is already on version 1.15.12 and is not in a failed state. No operations will occur when upgrading to the same version if the cluster is not in a failed state.
Since control-plane-only argument is not specified, this will upgrade the control plane AND all nodepools to version 1.15.12. Continue? (y/N): y
Operation failed with status: 'Bad Request'. Details: Upgrade agent pool version from 1.14.8 to 1.15.12 is not allowed, you can only upgrade one minor version at a time. Please use [az aks get-upgrades] command to get the supported upgrade paths. For more information, please check https://aka.ms/version-skew-policy

```

**Comment by jluk** [comment] 2020-09-17 15:18
@natgra Yes, please try an upgrade to 1.16 versions as 1.15 is no longer available. The command you ran should work with a 1.16 target version and bring all pools in sync with the control plane.

We found the misleading error message and will have a fix out in a few weeks that specifies when you're targeting an expired version correctly.

**Comment by NatGra** [comment] 2020-09-17 16:06
Hi @jluk an upgrade with `az aks upgrade --resource-group myResourceGroup --name myCluster --kubernetes-version 1.16.13` worked. Both control plane and node pool are now at v1.16.

Thank you very much for your help!

**Comment by jluk** [comment] 2020-09-17 23:58
Great news! Thanks for confirm, closing this issue and we are rolling fixes to the error message to be better!

**Closed by jluk** 2020-09-17 23:58 UTC
Labels: Upgrade, azure/portal
