### ISSUE TITLE
Error creating cluster in East US with Standard_B1ms machine size

### ISSUE THREAD

**Issue by tomasherceg** [Azure/AKS#284] opened 2018-04-02 10:32 UTC
I have tried to deploy AKS using the following command: 
``` 
az aks create --resource-group wugdays --name openevents --node-count 1 --node-vm-size Standard_B1ms --node-osdisk-size 32 --generate-ssh-keys --location eastus
```

I got the following error:
```
Deployment failed. Correlation ID: 24175893-d092-4b3c-88c1-7be7a214793f. PutControlPlane error
```

When I added `--kubernetes-version 1.8.7`, it worked.

**Comment by mboersma** [comment] 2018-08-07 20:13
@tomasherceg I can't reproduce this. I also can't think of a reason adding the `--kubernetes-version` argument would change the behavior. This seems more likely to be a transient error. If there were a problem with the node type, that results in a fairly specific error, which we didn't see.

I'm going to close this since it's over four months old, but please re-open if you still see this behavior.

**Closed by mboersma** 2018-08-07 20:13 UTC
Labels: bug, cli bug
