### ISSUE TITLE
DNS failures during Windows pod startup

### ISSUE THREAD

**Issue by brobichaud** [Azure/AKS#1029] opened 2019-05-31 23:37 UTC
**What happened**:
In an AKS cluster with Windows nodes I am seeing pod startup failures because the pod is unable to resolve DNS names. The problem is very unpredictable. Often pods will go into a continual restart cycle. When this happens I can sometimes (maybe 1/3 of the time) manually delete the pod and the new one that spins up will succeed. Often it requires that I manually delete the pod many times before it succeeds. When a pod is in this state RARELY will it ever start successfully. The pods in question have fairly robust fallback retry logic with long delays.

**What you expected to happen**:
I expect pods to have full access to DNS resolution on startup.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an AKS cluster with Windows nodes
2. Deploy Windows pods that access resources external to the cluster during startup
3. Some percentage of the time they will be unable to resolve DNS names

**Anything else we need to know?**:
Rebooting the Windows node does not seem to fix this.
I'd be happy to try and gather logs or other details you might need. This is a super critical issue for me as it makes my cluster utterly unreliable any time I deploy new code. Once a pod is running it is fine, though k8s scheduling operations can disrupt this at any time.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.0
- Size of cluster (how many worker nodes are in the cluster?): 2 Windows Standard_F8s_v2 nodes, 1 linux Standard_D1_v2 node
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): A mix of HTTP AspNetCore services and .NET Framework worker services (console apps). 19 Pods running on the Windows nodes, none of the linux node.
- Others:

**Comment by brobichaud** [comment] 2019-06-06 00:47
I am now seeing a very high percentage of failures of pod startups to resolve DNS. Rebooting the cluster nodes does help, but does not solve the problem. And over time the problem definitely gets much worse. All of my deployments have readiness and liveness probes disabled. I'd appreciate any advice you might have on how I can deal with this.

**Comment by artisticcheese** [comment] 2019-06-09 01:18
This seems to be issue with Windows 1809 servercore image itself running in AKS. ACI also runs in AKS and hence issue is showing up here as well https://github.com/MicrosoftDocs/azure-docs/issues/32209
Currently DNS is completely broken as far as I can see in windows containers. I have to add below to YAML config before actual runtime to make it work

```
          command: ["powershell"]
          args: ["-command", " Set-DnsClientServerAddress -InterfaceIndex (Get-NetAdapter).IfIndex -ServerAddresses ('8.8.8.8'); iex <whatever your EXEC is>"]

```

**Comment by brobichaud** [comment] 2019-06-10 17:13
> This seems to be issue with Windows 1809 servercore image itself running in AKS. ACI also runs in AKS and hence issue is showing up here as well [MicrosoftDocs/azure-docs#32209](https://github.com/MicrosoftDocs/azure-docs/issues/32209)
> Currently DNS is completely broken as far as I can see in windows containers. I have to add below to YAML config before actual runtime to make it work
> 
> ```
>           command: ["powershell"]
>           args: ["-command", " Set-DnsClientServerAddress -InterfaceIndex (Get-NetAdapter).IfIndex -ServerAddresses ('8.8.8.8'); iex <whatever your EXEC is>"]
> ```

Hmm, this is a pretty interesting hack to work around this rather huge hole in AKS. Do you have a working example of your full dockerfile I could see and use as a template?

**Comment by artisticcheese** [comment] 2019-06-10 17:15
I work with customers image (not dockerfile) and inspecting an imaged showed that /run.ps1 was used as entrypoint, so I just prepended it with setting up DNS.

**Comment by hiroshi1000** [comment] 2019-06-11 11:32
I have been facing the same problem and put the setting below in k8s YAML file for "first aid". This is working properly.

```
      containers:
      - name: <your container name>
        image: <your favorite image>
        lifecycle:
          postStart:
            exec:
              command: 
                - powershell
                - -command
                - Set-DnsClientServerAddress -InterfaceIndex (Get-NetAdapter).IfIndex -ServerAddresses ('168.63.129.16')
```

The IP address is the static address of Azure DNS server for vNet written in a MS document.

**Comment by artisticcheese** [comment] 2019-06-11 12:51
This seems to be better solution in the interim instead of overriding entry point

**Comment by brobichaud** [comment] 2019-06-11 16:24
Indeed this seems to work well with servercore images, thanks so much @hiroshi1000! It's a mitigation for a significant problem and not a solution, but it does allow me to move forward. 👍

However nanoserver does not support powershell so it fails there. Does anyone know of an equivalent version of this that works from a simple command shell?

**Comment by mjhilton** [comment] 2019-06-21 10:55
Have been seeing the same deploying images based off windows/servercore:ltsc2019, especially when deploying multiple pods simultaneously or in rapid succession.

30-60% of the pods deployed in bulk operations (eg Deployment with many replicas, or many Deployments with a single replica each) seem to end up with an irreparable failure on DNS resolution. The pod needs to be torn down and redeployed for things to come up.

I have 17 containers I want to deploy together, right now the only way I'm able to do it reliably is to put a 3 minute sleep in between each `kubectl apply`, which obviously takes an unacceptably long time when multiplied out by 17 deployments. Also means that Deployments with multiple replicas are completely unreliable and basically unusable :(

**Comment by artisticcheese** [comment] 2019-06-21 12:56
@mjhilton do you mean workaround above does not work for you? Or you mean your DNS works without any workarounds unless you deploy fast?

**Comment by mjhilton** [comment] 2019-06-24 01:09
I meant the [above workaround ](https://github.com/Azure/AKS/issues/1029#issuecomment-500801909) didn't work for me. Will give it another go today to confirm I didn't do anything silly.

**Comment by artisticcheese** [comment] 2019-06-24 01:11
It worked for me 100% of the time. I did not deploy hundreds of pods but about 10 may be and it was working fine.

**Comment by mjhilton** [comment] 2019-06-24 03:12
Sorry @artisticcheese, I was wrong. The workaround does work. 

Take [my comment above ](https://github.com/Azure/AKS/issues/1029#issuecomment-504384707) to be a big +1 to needing to find a fix on the root cause :)

**Comment by jnoller** [comment] 2019-06-27 16:24
@MikkelHegn  @craiglpeters ^

**Comment by PatrickLang** [comment] 2019-06-27 18:02
one issue with that workaround - that's setting an external DNS only. If you want to rely on DNS to resolve Kubernetes services, it will fail.

**Comment by artisticcheese** [comment] 2019-06-27 18:08
Workaround is calling to use Azure provided DNS service instead. If image would have worked properly would it point to AKS hosted DNS?

`Set-DnsClientServerAddress -InterfaceIndex (Get-NetAdapter).IfIndex -ServerAddresses ('168.63.129.16')`

**Comment by brobichaud** [comment] 2019-06-27 19:04
It would be great to hear from the AKS team as to where they think this problem resides. Is this a Windows v1809 issue, a K8s networking stack issue, an AKS-Engine issues, an AKS service issue?

That is if the problem is understood?

**Comment by MikkelHegn** [comment] 2019-07-03 11:50
Ref: https://github.com/Azure/aks-windows-private-preview/issues/31 with an update.

There are two scenarios, one will result in dns / networking never coming up, the other in delayed dns configuration (a few seconds). The first can hit if a container reuses an ip address of a previously deployed container, the latter is a design impact.

The first issue is resolved in the update mentioned in the link above, the latter has dependencies on container runtime updates, which is further out to get resolved. To work around the latter scenario you'll have to retry dns queries after a few seconds.

**Comment by zhiweiv** [comment] 2019-07-03 13:55
I can’t open https://github.com/Azure/aks-windows-private-preview/issues/31, could you please text here what is the update in https://github.com/Azure/aks-windows-private-preview/issues/31.

**Comment by MikkelHegn** [comment] 2019-07-03 15:40
Sorry - that was a blunder on my side... Here's the text :-)

> The updated Windows image is rolling out this week - look out for the release notes we publish here: https://github.com/Azure/AKS/blob/master/CHANGELOG.md

Initial testing looks to have improved startup issues with DNS. If you still encounter issue after having updated the nodepools, please open a support case, so we can get access to debug the issues.

**Comment by artisticcheese** [comment] 2019-07-03 16:20
How do you update node pools if version of kubernetes did not change?

**Comment by zhiweiv** [comment] 2019-07-03 17:34
Create a new pool, drain and delete the existing one, will this work?

**Comment by artisticcheese** [comment] 2019-07-03 17:40
I expected process to be automated per Microsoft docs they do it for you during cluster upgrade

**Comment by artisticcheese** [comment] 2019-07-05 13:43
How one verifies if new node pool is using updated engine? I just created a new node pool with Windows nodes but have no understanding how to verify version of AKS/base image on it as per notes for AKS release

**Comment by MikkelHegn** [comment] 2019-07-05 14:21
`kubectl describe nodes | grep -E "Name:|Kernel"`

**Comment by artisticcheese** [comment] 2019-07-05 14:27
Here is return of that statement. Does it mean it's latest I'm not sure how to tell

```
PS C:\em> kubectl describe nodes | select-string  "Name:|Kernel"  

Name:               aks-nodepool1-14015912-vmss000000
  Hostname:    aks-nodepool1-14015912-vmss000000     
 Kernel Version:             4.15.0-1045-azure       
Name:               akswinpl3000000
  Hostname:    akswinpl3000000
 Kernel Version:             10.0.17763.379
Name:               akswinpl3000001
  Hostname:    akswinpl3000001
 Kernel Version:             10.0.17763.379
Name:               akswinpl3000002
  Hostname:    akswinpl3000002
 Kernel Version:             10.0.17763.379
Name:               akswinpl3000003
  Hostname:    akswinpl3000003
 Kernel Version:             10.0.17763.379
```

**Comment by MikkelHegn** [comment] 2019-07-05 14:34
No, that is the March version of Windows, updated version would be: 10.0.17763.557. We're trying to figure out if we have a bug in the upgrade code, as right now it looks like only new clusters will get the new version. I'll keep you posted here when we know more.

**Comment by artisticcheese** [comment] 2019-07-05 17:09
When you add a new node pool, is not AKS supposed to create a new backend pool as well? I see in managed resource group single nodepool with Linux node. And all services I have running on windows nodes as result are inaccessible since there is no mapping to underlying VMSS.
![image](https://user-images.githubusercontent.com/13176884/60736676-617d9980-9f1d-11e9-8579-3bd161e8f540.png)

**Comment by zhiweiv** [comment] 2019-07-07 01:22
I created a new cluster, Windows version is stil the old one, **Version: 1809.0.20190314** from Azure Portal(vmss -> Operating system).

**Comment by MikkelHegn** [comment] 2019-07-08 08:06
The roll-out is still in progress. It was paused during US holiday end of last week.

**Comment by MikkelHegn** [comment] 2019-07-09 07:40
Roll-out completed to all regions...

**Comment by zhiweiv** [comment] 2019-07-09 08:14
It is 17763.557.20190604 now.

**Comment by MikkelHegn** [comment] 2019-07-09 08:20
Let us know how the DNS is looking. Please note there is still a know issue with DNS configuration being delayed in the containers: https://github.com/kubernetes/kubernetes/issues/78479

**Comment by zhiweiv** [comment] 2019-07-09 08:27
The first issue never occurred in my cluster. For dns delay issue, I have some codes at each application's start to ensure dns.

**Comment by artisticcheese** [comment] 2019-07-20 19:03
Am I supposed to deploy a new cluster or a new nodepool to get updated version of Windows? I just added a new nodepool and it's still old version.

**Comment by zhiweiv** [comment] 2019-07-21 00:33
It is maybe caused by https://github.com/Azure/aks-engine/issues/1638, I think AKS will update to fix this soon. 

You can create a new cluster to verify dns problrm.

**Comment by artisticcheese** [comment] 2019-07-21 18:05
Yes, the only way to get new windows nodes is to start from scratch unfortunately. I tried upgrading nodes, upgrading master nodes to 1.14.3 but nothing worked. Only complete cluster recreation gave access to updated windows nodes.

**Comment by brobichaud** [comment] 2019-08-08 19:03
@MikkelHegn we've now had a cluster with the 10.0.17763.557 Windows release running for about a week and it does seem to have cleared up the pod startup DNS issues we were seeing. Thank you!

We do still see the port exhaustion issue when liveness probes are enabled, as referenced here: https://github.com/Azure/AKS/issues/1014

**Comment by MikkelHegn** [comment] 2019-08-09 10:19
Thx for the feedback.

For upgrading node pools, existing node pools are non-upgradeable due to a change in the Azure image offering we use. The path to get new Windows OS for existing clusters are:

1. Upgrade cluster (control plane) to latest K8 version (1.14.5 is rolling out with a CVE fix).
2. Create a new node pool
3. Migrate workloads
4. Decommission old node pool

I will close this issue.

**Closed by MikkelHegn** 2019-08-09 10:19 UTC
Labels: windows
