### ISSUE TITLE
[ACNS] Historical Network Flow Logging

### ISSUE THREAD

**Issue by chasewilson** [Azure/AKS#4589] opened 2024-10-14 20:58 UTC
As a part of Advanced Container Networking Services, AKS will support historical network flow logging with multiple options to filter and query historical logs to identify and mitigation intermittent issues.

**Comment by rahulrai-in** [comment] 2024-10-31 22:18
Closed as duplicate of https://github.com/Azure/AKS/issues/4590

**Closed by rahulrai-in** 2024-10-31 22:18 UTC
Labels: networking, feature-request, advanced-container-networking-services, Cilium
