### ISSUE TITLE
[Feature] Nodepool labels

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#1496] opened 2020-03-11 10:23 UTC
Allow for user-specified k8s labels to be passed at nodepool creation time (or cluster creation time) and these will be propagated and persist across every node of the nodepool, including new scaled nodes

**Comment by jluk** [comment] 2020-03-11 15:23
Duplicate of https://github.com/Azure/AKS/issues/1088

**Closed by jluk** 2020-03-11 15:23 UTC
Labels: feature
