### ISSUE TITLE
AKS VMSS scale with many disks fails with status 429 - TooManyRequests HighCostGetVMScaleSet30Min

### ISSUE THREAD

**Issue by juerup** [Azure/AKS#1187] opened 2019-09-03 22:43 UTC
**What happened**:
We are running an AKS cluster with 27 nodes in 2 node pools with approx. 50 StatefulSets with Azure Disks attached and 300 stateless pods. We scaled one pool manually down from 25 to 20 nodes. After that most pods were crashing and not able to start again, because no disks could be attached. The pods showed errors similar to this:

Original Error: autorest/azure: Service returned an error. Status=429 Code='OperationNotAllowed' 
Message='The server rejected the request because too many requests have been received for this subscription.' 
Details=[{'code':'TooManyRequests','message':'{\\'operationGroup\\':\\'HighCostGetVMScaleSet30Min\\',\\'startTime\\':\\'2019-09-03T14:35:47.3211489+00:00\\',\\'endTime\\':
\\'2019-09-03T14:50:47.3211489+00:00\\',\\'allowedRequestCount\\':900,\\'measuredRequestCount\\':1535}','target':'HighCostGetVMScaleSet30Min'}] InnerError={'internalErrorCode':'TooManyRequestsReceived'})

The only way to stop this was to unauthorize Service Principal and wait 30 Minutes. After that the scaling was successful. We retried operation on the same cluster and on a different one with the same effect. It seems that a vmss handels disk attach/detach differently

**What you expected to happen**:
Scaling of node pools should happen in a way where throtteling is honored.

**How to reproduce it (as minimally and precisely as possible)**:
setup AKS cluster with VMSS enabled, deploy many pods with Azure Disks as PV and scale cluster down so rescheduling is happening

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.6
- Size of cluster (how many worker nodes are in the cluster?) 27
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) very diverse, mostly Java, 300 stateless services and 50 stateful sets
- Others:

**Comment by andyzhangx** [comment] 2019-09-06 12:09
cc @feiskyer

**Comment by feiskyer** [comment] 2019-09-06 13:59
@juerup we need some cluster information for checking why so many requests are sent. Could you open a support ticket for it?

**Comment by juerup** [comment] 2019-09-06 14:46
We already opened a Support Ticket 119090322002632 with Azure Support, but with no result. Does this help you identifying root cause?

**Comment by sundipnair** [comment] 2019-09-09 12:46
We are facing similar issues since last week. We worked around this by standing up clusters without VMSS.
Have raised a support ticket (119090422002737). The engineer on the other side has confirmed this as a Azure issues and that it is being resolved.

**Comment by sundipnair** [comment] 2019-09-16 06:06
Any further update on this issue?

**Comment by feiskyer** [comment] 2019-09-16 12:47
@sundipnair @juerup Sorry for the late response. This is a known issue that the requests count may exceed the ARM throttling threshold. We're fixing the issue and it would probably be fixed with Kubernetes v1.17.

**Comment by juerup** [comment] 2019-09-16 18:00
Can you please clarify about the known issue: 
Is there anything to avoid throttling which can be done be us?
Can this even happen while downscaling by one node?

**Comment by feiskyer** [comment] 2019-09-17 02:58
@juerup The issue is because Azure ARM API has [request limits and would throttle](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-request-limits) the client if there're too many requests are sent. When 429 happens, all the read requests are throttled, though there're already caches in Kubernetes codes, 429 blocks the cache refresh requests, which makes things worse.

Before the issue fixed, a few things could reduce the API requests number:

* Reduce number of nodes and frequency of node scaling
* Reduce frequency of AzureDisk detaching or attaching
* Reduce frequency of LoadBalancer typed service creating or deleting

**Comment by juerup** [comment] 2019-09-17 08:39
is there already a ticket for the development of this fix?

**Comment by jluk** [comment] 2019-09-26 17:42
Yes we've got these improvements logged, FYI @palma21 to reduce the API requests being made and the relation to cluster autoscaler.

@juerup would you mind if I updated this issue to refer to improving that and we can use this issue to track the api request reduction improvements?

**Comment by juerup** [comment] 2019-09-27 10:48
Thanks for keeping me updated.
@jluk feel free to use this issue in any way you consider helpful

**Comment by jluk** [comment] 2019-09-27 15:29
@feiskyer it sounds like you've got planned changes to reduce the overall requests to avoid the chances of a 429. Assigning to you, but correct me if otherwise. As mentioned by @juerup please update this ticket title as needed and we can use this issue to track the upstream changes needed to reduce those request totals.

**Comment by immunochomik** [comment] 2019-11-19 15:24
@jluk Could you tell us if that issue would affect a 'normal' workload when our cluster needs to scale up and down ~20 ~ 30 times a day  ? Can we monitor what is our usage of this limit ?

**Comment by jluk** [comment] 2019-11-19 22:30
I think previously it would be possible - but what version of k8s are you on now? @palma21 can correct me but the latest patch versions should have significant improvements on VMSS throttling.

**Comment by immunochomik** [comment] 2019-11-20 10:13
We are on 1.14.8

**Comment by palma21** [comment] 2019-11-20 16:36
Are you using the latest versions of cluster autoscaler? Do you have other clusters in this subscription with earlier versions of k8s?

**Comment by md2k** [comment] 2019-11-27 13:56
We have similar issues during rolling AKS with multiple pools (k8s version 1.15.5), Terraform 0.12.16, azurerm provider version 1.37.0

**Comment by andyzhangx** [comment] 2019-12-05 11:50
besides the azure cloud provider fix on throttling, we also found issue in AKS service side, if you have VMSS clsuter on different regions, there could be 12K list VMSS calls, AKS team are fixing this issue.

**Comment by Shenderchuk** [comment] 2020-01-03 13:39
Is there a way how to check which exactly VMSS generating traffic of these requests? 
We have more than 10 AKS clusters in subscription and faced with this yesterday, can not find the "problematic" one.

**Comment by andyzhangx** [comment] 2020-01-04 09:48
> Is there a way how to check which exactly VMSS generating traffic of these requests?
> We have more than 10 AKS clusters in subscription and faced with this yesterday, can not find the "problematic" one.

there is an internal way to query those traffic by providing your subs id, time, k8s version. @Shenderchuk

**Comment by kobyepistema** [comment] 2020-01-05 12:21
@andyzhangx - Is this "Internal way" can be used on my account? (We are facing the same issue)

**Comment by andyzhangx** [comment] 2020-01-05 12:24
> @andyzhangx - Is this "Internal way" can be used on my account? (We are facing the same issue)

@kobyepistema pls file support ticket, provide:
subs id, time, k8s version, how may vmss clusters in one subs, what's the workload you are running(e.g. disk volume attach/detach)

**Comment by palma21** [comment] 2020-01-06 20:31
Also, @Shenderchuk there doesn't need to be a problematic one necessarily, the limits are cumulative, so it might be that the overall number of calls from the 10 clusters concurrently are hitting these limits.

What k8s versions are you using?

**Comment by zloeber** [comment] 2020-01-07 14:06
So what I've read here is that for perfectly legitimate use cases, you know, standing up a cluster and deployment of resources on the new cluster, you can DDOS yourself. I've spent the better part of a few days now looking into why a cluster that worked without issues prior to a rebuild suddenly fails. I think that the answer is that I built and deployed it too quickly?

**Comment by palma21** [comment] 2020-01-08 06:47
Depending on how many clusters you have in one subscription, their respective kubernetes versions, the number of calls they are making (scale, upgrade), Cluster Autoscaling, and disk attach/detach calls, yes, that can happen when the Azure API quota thresholds are exceeded.

Without this you would be fine

The case from OP had 50 StatefulSets with Azure Disks attached and 300 stateless pods + a scale operation, all in a k8s patch version that is currently no longer supported (later versions also included call optimizations, but the Azure limits are the same).

The case from Shenderchuk had 10 clusters in the same sub, making calls concurrently which can accumulate to the limit. 

So I can only answer your specific question with details on the above. Also feel free to open a ticket if you want detailed investigation on your cluster.


I'm closing this ticket based on the above but will create a new pinned thread with details on throttling and to allow broader discussion that includes kubernetes upstream.

**Closed by palma21** 2020-01-08 06:47 UTC
Labels: VMSS, known-issue, nodepools, storage

**Comment by kalyan123i** [comment] 2020-01-30 07:54
I have raised a support ticket to microsoft and got the below recommendation which worked for now. microsoft is working to fix in later version of aks.

remove autoscaling feature for aks clusters in subscription and wait for 2 hours to api to lower the throtlle.
keep resource limits for all deployments and make sure its not more than 80% of total available resources.

**Comment by jluk** [comment] 2020-01-30 17:08
Please reference this ticket as well capturing the latest for 429 VMSS throttling.
https://github.com/Azure/AKS/issues/1413
