### ISSUE TITLE
Use Network Policy to whitelist external IP addresses

### ISSUE THREAD

**Issue by PeterRockstars** [Azure/AKS#974] opened 2019-05-14 12:15 UTC
**What happened**:
I attempted to use a NetworkPolicy on an Ingress Controller to whitelist external IP addresses, but the result is that I cannot connect from any IP address.

**What you expected to happen**:
I expected to be able to connect to a service from my own whitelisted IP but not from another IP.

**How to reproduce it (as minimally and precisely as possible)**:

Run this in powershell:
```
# Create a namespace for your ingress resources
kubectl create namespace ingress-basic

kubectl config set-context <myCluster> --namespace=ingress-basic

# Use Helm to deploy an NGINX ingress controller
helm install stable/nginx-ingress `
    --namespace ingress-basic `
    --set controller.replicaCount=1  `
    --set controller.service.externalTrafficPolicy=Local

kubectl get service -l app=nginx-ingress --namespace ingress-basic

helm repo add azure-samples https://azure-samples.github.io/helm-charts/

helm install azure-samples/aks-helloworld --namespace ingress-basic

'apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: ingress-basic
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: aks-helloworld
          servicePort: 80' > hello-world-ingress.yaml

kubectl apply -f hello-world-ingress.yaml

# expect to get html
Invoke-WebRequest -Uri http://<ingress-controller-service-external-ip> -TimeoutSec 2

'apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: ingress-basic
spec:
  podSelector:
    matchLabels:
      app: nginx-ingress
      component: controller
  ingress:
  - from:
    - ipBlock:
        cidr: <my-ip>/32' > networkpolicy.yaml

kubectl apply -f networkpolicy.yaml

sleep 10

# expect to still get html
Invoke-WebRequest -Uri http://<ingress-controller-service-external-ip>
```
My results from the web requests: 
Before applying policy, from any ip: 
```
StatusCode        : 200
StatusDescription : OK
Content           : <!DOCTYPE html>
                    <html xmlns="http://www.w3.org/1999/xhtml">
                    <head>
                        <link rel="stylesheet" type="text/css" href="/static/default.css">
                        <title>Welcome to Azure Kubernetes Service (AKS)</title>

                    ...
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    Vary: Accept-Encoding
                    Content-Length: 629
                    Content-Type: text/html; charset=utf-8
                    Date: Tue, 14 May 2019 12:03:12 GMT
                    Server: nginx/1.15.10
```
After applying policy, from \<my-ip\>:
```
Invoke-WebRequest : 504 Gateway Time-out
nginx/1.15.10
```
After applying policy, form \<another ip\>:
```
Invoke-WebRequest : Unable to connect to the remote server
```

**Anything else we need to know?**:
I roughly followed this tutorial: https://docs.microsoft.com/bs-cyrl-ba/azure/aks/ingress-basic combined with information found on https://kubernetes.io/docs/concepts/services-networking/network-policies/.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
1 node
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Demo application from Microsoft docs (to try this out before using it on our cluster which runs mainly HTTP microservices in asp.net core)
- Others:
I used this script to create the cluster:
```
$SP_PASSWORD="mypassword"
$RESOURCE_GROUP_NAME="myresourcegroup"
$CLUSTER_NAME="myclustername"
$LOCATION="westeurope"

# Create a resource group
az group create --name $RESOURCE_GROUP_NAME --location $LOCATION

# Create a virtual network and subnet
az network vnet create `
    --resource-group $RESOURCE_GROUP_NAME `
    --name myVnet `
    --address-prefixes 10.0.0.0/8 `
    --subnet-name myAKSSubnet `
    --subnet-prefix 10.240.0.0/16

# Create a service principal and read in the application ID
$SP_ID=$(az ad sp create-for-rbac --password $SP_PASSWORD --skip-assignment --query [appId] -o tsv)

# Wait 15 seconds to make sure that service principal has propagated
echo "Waiting for service principal to propagate..."
sleep 15

# Get the virtual network resource ID
$VNET_ID=$(az network vnet show --resource-group $RESOURCE_GROUP_NAME --name myVnet --query id -o tsv)

# Assign the service principal Contributor permissions to the virtual network resource
az role assignment create --assignee $SP_ID --scope $VNET_ID --role Contributor

# Get the virtual network subnet resource ID
$SUBNET_ID=$(az network vnet subnet show --resource-group $RESOURCE_GROUP_NAME --vnet-name myVnet --name myAKSSubnet --query id -o tsv)

# Create the AKS cluster and specify the virtual network and service principal information
# Enable network policy by using the `--network-policy` parameter
az aks create `
    --resource-group $RESOURCE_GROUP_NAME `
    --name $CLUSTER_NAME `
    --node-count 1 `
    --generate-ssh-keys `
    --network-plugin azure `
    --service-cidr 10.0.0.0/16 `
    --dns-service-ip 10.0.0.10 `
    --docker-bridge-address 172.17.0.1/16 `
    --vnet-subnet-id $SUBNET_ID `
    --service-principal $SP_ID `
    --client-secret $SP_PASSWORD `
    --network-policy azure
```

**Comment by sauryadas** [comment] 2019-05-14 18:00
@aanandr @nisheethsrivastava Folks can you please take a look at this? Using Azure Native network policy

**Comment by aanandr** [comment] 2019-05-14 20:49
Adding @sharmasushant
This will need deeper investigation. @PeterRockstars - can you share details of your cluster

**Comment by PeterRockstars** [comment] 2019-05-15 08:08
@aanandr Sure, here is the output from `az aks show`:
```
{
  "aadProfile": null,
  "addonProfiles": null,
  "agentPoolProfiles": [
    {
      "availabilityZones": null,
      "count": 1,
      "enableAutoScaling": null,
      "maxCount": null,
      "maxPods": 30,
      "minCount": null,
      "name": "nodepool1",
      "orchestratorVersion": "1.12.7",
      "osDiskSizeGb": 100,
      "osType": "Linux",
      "provisioningState": "Succeeded",
      "type": "AvailabilitySet",
      "vmSize": "Standard_DS2_v2",
      "vnetSubnetId": "/subscriptions/d090826d-21e1-44d7-9696-04e33887d08e/resourceGroups/testResourceGroup-NP/providers/Microsoft.Network/virtualNetworks/myVnet/subnets/myAKSSubnet"
    }
  ],
  "apiServerAuthorizedIpRanges": null,
  "dnsPrefix": "npTestClus-testResourceGrou-d09082",
  "enablePodSecurityPolicy": null,
  "enableRbac": true,
  "fqdn": "nptestclus-testresourcegrou-d09082-4f709e4c.hcp.westeurope.azmk8s.io",
  "id": "/subscriptions/d090826d-21e1-44d7-9696-04e33887d08e/resourcegroups/testResourceGroup-NP/providers/Microsoft.ContainerService/managedClusters/npTestCluster",
  "kubernetesVersion": "1.12.7",
  "linuxProfile": {
    "adminUsername": "azureuser",
    "ssh": {
      "publicKeys": [
        {
          "keyData": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEG/qQ3wys/2eZe8ZnVjjb9FFKjJdke5NxXVFiZynk0Owutsh/myLiqPRhE3LjB5XX3lIOa54RQG3tTKE5dintiLXmkQYiXEF+nSr0VsvQJ+2zB5Ozjyr0g/LgAAk89ek/J43bHcUX3XAM1EtTeHyk8PaeSNgUUoU/jlCzvXXY+ZSnfQw5e3EK9yFEeFz1pjmLT2aKvM7Fk2vG0IKTTfdrMjSQvsgwzzdJdg+X3EK8obOQ9hxsL4medRWW5eFQUKiPSfer+6GLjwYauSVBHOkHxj7SZVPRFGguVQbFjDVXjEgFBEz9IWjep0rB81Ayf+12STCx+xnKxPCEnAsBJPpl"
        }
      ]
    }
  },
  "location": "westeurope",
  "name": "npTestCluster",
  "networkProfile": {
    "dnsServiceIp": "10.0.0.10",
    "dockerBridgeCidr": "172.17.0.1/16",
    "networkPlugin": "azure",
    "networkPolicy": "azure",
    "podCidr": null,
    "serviceCidr": "10.0.0.0/16"
  },
  "nodeResourceGroup": "MC_testResourceGroup-NP_npTestCluster_westeurope",
  "provisioningState": "Succeeded",
  "resourceGroup": "testResourceGroup-NP",
  "servicePrincipalProfile": {
    "clientId": "f413092a-ec97-4356-bea9-327d3487f5e2"
  },
  "type": "Microsoft.ContainerService/ManagedClusters"
}
```

Do you need anything else?

**Comment by PeterRockstars** [comment] 2019-05-15 08:13
And, if it helps, if I run `Invoke-WebRequest -Uri http://<ingress-controller-service-external-ip>` from another IP than the one I whitelisted I get a different result: 
```
Invoke-WebRequest : Unable to connect to the remote server
At line:1 char:1
+ Invoke-WebRequest -Uri http://52.157.177.115
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by aanandr** [comment] 2019-05-15 20:56
Also adding @saiyan86 
@PeterRockstars - this error is similar to the error you reported earlier. If this IP is not in the allowed range then this is expected

**Comment by PeterRockstars** [comment] 2019-05-15 21:06
The reason I mention it is that, from an allowed IP I get a 504 that is served by my own nginx pod and, from an unallowed IP I can't access at all. So it would seem that the policy is working to some degree, but not entirely. Is that assumption correct?
The reason I'm asking is that I'm not sure if this is even an intended use case (blocking traffic from external IP's) or if NetworkPolicies are only meant for internal traffic.
________________________________

**Comment by PeterRockstars** [comment] 2019-05-20 11:20
@aanandr Any news on this?

**Comment by saiyan86** [comment] 2019-05-20 19:22
@PeterRockstars I'm going to take a look today.

**Comment by saiyan86** [comment] 2019-05-21 00:36
@PeterRockstars The problem is that the external source ip(client's source ip) isn't preserved. Even with ```externalTrafficPolicy=Local``` set, the nginx ingress controller still SNAT the external source ip to its own pod ip. There are two work-arounds:
1. Get rid of ingress controller
2. Add one iptables rule to actually whitelist the ip of the ingress controller.

**Comment by aanandr** [comment] 2019-05-22 23:16
@PeterRockstars - we brainstormed the behavior. externalTrafficPolicy will ensure that source IP is preserved in the traffic hitting the IC. However, IC will always SNAT after that. So the source that the backend service Pods will see will never be the actual source. Hence policy wont apply. I think the right way to apply the policy is to apply it for the Ingress pods. Let me know if this makes sense to you and if you can try this out. 
I dont know why the error codes you see are different.

**Comment by aanandr** [comment] 2019-05-23 21:07
Hi @PeterRockstars  - let me know if this suggestion works for you

**Comment by PeterRockstars** [comment] 2019-05-24 07:34
> @PeterRockstars - we brainstormed the behavior. externalTrafficPolicy will ensure that source IP is preserved in the traffic hitting the IC. However, IC will always SNAT after that. So the source that the backend service Pods will see will never be the actual source. Hence policy wont apply. I think the right way to apply the policy is to apply it for the Ingress pods. Let me know if this makes sense to you and if you can try this out.
> I dont know why the error codes you see are different.

Thanks for the suggestion. However, I don't understand what I'm supposed to change. The policy is already set to apply to the IC pods.

**Comment by PeterRockstars** [comment] 2019-05-24 07:57
> @PeterRockstars The problem is that the external source ip(client's source ip) isn't preserved. 

That doesn't exactly match the behaviour I'm seeing. 
- A request from the whitelisted IP reaches the IC. I know because I get served a 504 by NGINX
- A request from a different IP cannot connect at all. Probably because the NetworkPolicy blocks the request.

Whether the source ip is preserved on the request that is passed on to the pod, while necessary, isn't the problem right now. The pods don't do anything with the IP, they just serve a simple page. So, for the moment, I don't mind if they see the wrong source IP (well actually I do mind but this is problem 2, the first is actually getting a response)

**Comment by PeterRockstars** [comment] 2019-05-24 08:18
Maybe this helps, this is what NGINX logs when I do a request from the authorized IP:
Maybe this helps, this is what NGINX logs when I do a request from the authorized IP:
2019/05/24 08:15:41 [error] 189#189: *5438544 upstream timed out (110: Connection timed out) while connecting to upstream, client: 123.456.7.890, server: _, request: "GET / HTTP/1.1", upstream: "http://10.240.0.29:80/", host: "52.157.177.115"
2019/05/24 08:15:46 [error] 189#189: *5438544 upstream timed out (110: Connection timed out) while connecting to upstream, client: 123.456.7.890, server: _, request: "GET / HTTP/1.1", upstream: "http://10.240.0.29:80/", host: "52.157.177.115"
2019/05/24 08:15:51 [error] 189#189: *5438544 upstream timed out (110: Connection timed out) while connecting to upstream, client: 123.456.7.890, server: _, request: "GET / HTTP/1.1", upstream: "http://10.240.0.29:80/", host: "52.157.177.115"
123.456.7.890 - [123.456.7.890] - - [24/May/2019:08:15:51 +0000] "GET / HTTP/1.1" 504 168 "-" "Mozilla/5.0 (Windows NT; Windows NT 10.0; en-GB) WindowsPowerShell/5.1.17763.134" 134 15.006 [ingress-basic-aks-helloworld-80] 10.240.0.29:80, 10.240.0.29:80, 10.240.0.29:80 0, 0, 0 5.004, 5.000, 5.004 504, 504, 504 76e8f7a2dbbf2dad4c5c51ef23eeacbb

Note: 123.456.7.890 is my IP, which is whitelisted

**Comment by PeterRockstars** [comment] 2019-05-24 09:06
Sorry guys, I think the error was mine. I had only included an "ingress" section and no "egress" section, thinking that this would mean all egress traffic is allowed.  
Then I read this in the [docs](https://kubernetes.io/docs/concepts/services-networking/network-policies/): 

> Pods become isolated by having a NetworkPolicy that selects them. Once there is any NetworkPolicy in a namespace selecting a particular pod, that pod will reject any connections that are not allowed by any NetworkPolicy. (Other pods in the namespace that are not selected by any NetworkPolicy will continue to accept all traffic.) 

So my request was getting to NGINX but it was not allowed to contact the pods because no egress traffic was allowed.

Simply adding this fixed it:
```
  egress:
  - {}
```

**Comment by saiyan86** [comment] 2019-05-24 22:39
We can close this now. @sauryadas

**Comment by jnoller** [comment] 2019-05-24 22:40
Closed

**Closed by jnoller** 2019-05-24 22:40 UTC
Labels: triage
